### ISSUE TITLE
sed command getting mangled

### ISSUE THREAD

**Issue by huggsboson** [kubernetes/kubernetes.github.io#100]
sed command getting mangled by build pipeline, I can't figure out why or how.  But the sed command on this page, http://kubernetes.io/docs/getting-started-guides/docker-multinode/deployDNS/ has:
sed -e "s//${DNS_REPLICAS}/g;s//${DNS_DOMAIN}/g;s//${DNS_SERVER_IP}/g" skydns.yaml.in > ./skydns.yaml

should be like https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/getting-started-guides/docker-multinode/deployDNS.md:
sed -e "s/{{ pillar\['dns_replicas'\] }}/${DNS_REPLICAS}/g;s/{{ pillar\['dns_domain'\] }}/${DNS_DOMAIN}/g;s/{{ pillar\['dns_server'\] }}/${DNS_SERVER_IP}/g" skydns.yaml.in > ./skydns.yaml

**Comment by johndmulhausen** [comment]
Fixed by adding {% raw %} and {% endraw %}
