### ISSUE TITLE
Page fedora_ansible_config page does not mention building kubernetes

### ISSUE THREAD

**Issue by wfhartford** [kubernetes/kubernetes.github.io#101]
The page at http://kubernetes.io/docs/getting-started-guides/fedora/fedora_ansible_config/ seems to assume that kubernetes has already been built. This issue was brought up in kubernetes/kubernetes#12392 , but that was closed without fixing the documentation.

**Comment by johndmulhausen** [comment]
@wfhartford Any reason why you couldn't send a PR that adds this info? It's super easy to do so. Just click the blue pencil at the top-right of http://kubernetes.io/docs/getting-started-guides/fedora/fedora_ansible_config/

**Comment by jaredbhatti** [comment]
Already fixed.
