### ISSUE TITLE
missing images in getting-started-guides/logging

### ISSUE THREAD

**Issue by thkoch2001** [kubernetes/kubernetes.github.io#1010]
The images were removed in https://github.com/kubernetes/kubernetes/commit/3521a66dcec0347883e655594d264ba4c33f87c4 but the article was not updated. So there are broken images now in http://kubernetes.io/docs/getting-started-guides/logging/

I filed this issue originally here: https://github.com/kubernetes/kubernetes/issues/29545

**Comment by jaredbhatti** [comment]
Logging page has been moved and revised.
