### ISSUE TITLE
I wish /docs/user-guide/deployments/ Had an example of a fully customized deployment so I could see what all the options are

### ISSUE THREAD

**Issue by sgryschuk-va** [kubernetes/kubernetes.github.io#1015]
I wish /docs/user-guide/deployments/ Had an example of a fully customized deployment so I could see what all the options are

**Comment by jaredbhatti** [comment]
nginx-deployment.yaml is an example that's fairly fleshed out.  We also have an interactive deployment here: https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-intro/
