### ISSUE TITLE
I wish /docs/user-guide/horizontal-pod-autoscaling/walkthrough/ actually contained the information, or at least a link to autoscaling by custom application logic

### ISSUE THREAD

**Issue by analytik** [kubernetes/kubernetes.github.io#1018]
I wish /docs/user-guide/horizontal-pod-autoscaling/walkthrough/ actually contained the information, or at least a link to autoscaling by custom application logic (as referred to by the first sentence in the article - `(or, with alpha support, on some other, application-provided metrics)`.

The second half of this article seems like the correct target link - http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/

**Comment by jaredbhatti** [comment]
Fixed.  Thanks.
