### ISSUE TITLE
Run k8s.io mungers on docs

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes.github.io#102]
Goal - continue to run k8s.io/kubernetes/cmd/mungedocs on kubernetes/kubernetes.github.io docs.
- [ ] move k8s.io/kubernetes/cmd/mungedocs to kubernetes/contrib
  - fix tests to work outside kubernetes/kubernetes repo
- [ ] change kubernetes/kubernetes scripts to use k8s.io/contrib/cmd/mungedocs
- [ ] fix mungedocs so it doesn't fail when `git ls-tree` cannot find a release tag
- [ ] add travis config to kubernetes/kubernetes.github.io to run mungedocs
  - disable all mungers that do not already pass (virtually all of them)
- [ ] fix mungers to accept kubernetes/kubernetes.github.io stylings that differ where appropriate
- [ ] update docs in kubernetes/kubernetes.github.io with changes made by mungers
- [ ] resolve `kube-dash-f` munger issues
  - update munger to resolve `https://` links
  - update munger to resolve docs under kubernetes/kubernetes repo
  - update munger to accept `<filename>` placeholders that should not be resolved
  - update docs missing `./`prefix to reference files created as part of the exercise
- [ ] resolve `md-links` munger issues
  - don't escape urls
  - expect relative doc paths to start with `/`
  - remove trail `/` from urls in docs
  - fix hardcoded paths to kubernetes/kubernetes to be repo-configurable
- [ ] update munger with more friendly output describing what needs to be fixed

**Comment by pwittrock** [comment]
After further evaluation, the effort isn't warranted by the amount of effort required.  Reopen if we find noteworthy issues with docs that could have been detected by a script.

**Comment by jaredbhatti** [comment]
Is this issue still valid?

**Comment by pwittrock** [comment]
Yeah it is still valid, but no time.

**Comment by jaredbhatti** [comment]
Ping.  This is over a year old at this point.  Please reopen if there will be work on this.
