### ISSUE TITLE
I wish /docs/user-guide/kubectl/kubectl_create_secret/kubectl_create_secret_docker-registry/ existed

### ISSUE THREAD

**Issue by erstaples** [kubernetes/kubernetes.github.io#1028]
I wish /docs/user-guide/kubectl/kubectl_create_secret/kubectl_create_secret_docker-registry/ existed

**Comment by chenopis** [comment]
@erstaples there is now https://kubernetes.io/docs/user-guide/kubectl/kubectl_create_secret_docker-registry/
