### ISSUE TITLE
Custom search doesn't find volumes page

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes.github.io#103]
Use the site search bar to search for "volume" or "volumes". I would expect http://kubernetes.io/docs/user-guide/volumes/ to be the top result, but it doesn't seem to appear anywhere in the first 6 pages of results!

**Comment by johndmulhausen** [comment]
Finds it now. Indexing probably just took awhile: http://kubernetes.io/docs/search/?q=volumes
