### ISSUE TITLE
Seems /third_party/swagger-ui/ is missing

### ISSUE THREAD

**Issue by onorua** [kubernetes/kubernetes.github.io#105]
I've used it all the time for an API reference, and now it seems the only available option is local API server :(

**Comment by nikhiljindal** [comment]
Dup of https://github.com/kubernetes/kubernetes.github.io/issues/105.

fwiw, swagger-ui will be disabled by default on local api server: https://github.com/kubernetes/kubernetes/pull/23025. You will be able to turn it on by setting a flag.

Please reply to https://github.com/kubernetes/kubernetes.github.io/issues/112#issuecomment-196527345 if you prefer swagger UI.

**Comment by johndmulhausen** [comment]
Added 404.md forwarding
