### ISSUE TITLE
I wish /docs/api-reference/v1/definitions/ pointed to some big picture explanation of ComponentStatus

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes.github.io#1053]
I wish /docs/api-reference/v1/definitions/ pointed to some big picture explanation of `ComponentStatus`.  Where do these things come from?  As a cluster operator with a partly broken cluster, I need to distinguish between a bad definition and a bad result, and that's just the first step of my problem determination.

**Comment by jaredbhatti** [comment]
Can you give me some more context on what you mean by "big picture" beyond what's listed here? http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_componentstatus

**Comment by jeffmendoza** [comment]
Closing for now, please re-open with more information.
