### ISSUE TITLE
is the 'not yet implemented' note for '.spec.strategy.type==Recreate' obsolete?

### ISSUE THREAD

**Issue by amygdala** [kubernetes/kubernetes.github.io#106]
Given this PR: https://github.com/kubernetes/kubernetes/pull/16713 ,
is the "Note: This is not implemented yet" comment in https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/deployments.md
for `.spec.strategy.type==Recreate`, under 'Recreate Deployment' now obsolete?

(this is not a rhetorical question... I'm not sure :)

**Comment by bgrant0607** [comment]
@amygdala Yes, it is obsolete. Deployment docs have not been updated.

cc @janetkuo @kargakis @pwittrock

**Comment by janetkuo** [comment]
Filed #127
