### ISSUE TITLE
I wish /docs/getting-started-guides/logging/ Need change in command.Syntactical error

### ISSUE THREAD

**Issue by unixbhaskar** [kubernetes/kubernetes.github.io#1069]
I wish /docs/getting-started-guides/logging/ Need change in command.Syntactical error

for instance 

Getting into container shows like this 

kubectl exec **-i** counter bash

Should be changed to like this 

kubectl exec -**it** counter bash

Then only you get the shell inside the containter ,that "-t" flag signifies terminal .

**Comment by jeffmendoza** [comment]
Looks like this page does not exist any more.
