### ISSUE TITLE
I wish /docs/api-reference/v1/operations/definitions/ existed.  Linked to from http://kubernetes.io/docs/api-reference/v1/operations/

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kubernetes.github.io#1083]
I wish /docs/api-reference/v1/operations/definitions/ existed.  Linked to from http://kubernetes.io/docs/api-reference/v1/operations/

**Comment by jaredbhatti** [comment]
bad generated API content. Fixed in 1.4 push.
