### ISSUE TITLE
I wish /docs/design/architecture/ existed

### ISSUE THREAD

**Issue by rasputnik** [kubernetes/kubernetes.github.io#109]
I wish /docs/design/architecture/ existed

**Comment by bgrant0607** [comment]
That diagram is out of date, so I'm glad it doesn't. :-)

Sorry about the broken link, though.

We should create a new diagram sourced from one of our presentations.

cc @johndmulhausen

**Comment by rasputnik** [comment]
No worries, was quite an old page linking to you anyway.

**Comment by johndmulhausen** [comment]
Added 404 link forwarding that sends users over to kubernetes/kubernetes/docs/design, which is the best we can do.
