### ISSUE TITLE
Document kubectl explain and new commands in kubectl overview

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes.github.io#1094]
Even some long-time Kubernetes users didn't know kubectl explain existed, and we've had it for a year. It isn't in the overview:
https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/kubectl-overview.md
nor in the cheatsheet:
https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/kubectl-cheatsheet.md

It is in the autogenerated pages, but that requires expanding 2 collapsed lists to find.

**Comment by chrislovecnm** [comment]
@bgrant0607 going to be working on cheat sheet a bunch

**Comment by chrislovecnm** [comment]
PR https://github.com/kubernetes/kubernetes.github.io/pull/1486 updates the cheat sheet.
PR https://github.com/kubernetes/kubernetes.github.io/pull/1479 updates kubectl overview.

**Comment by jeffmendoza** [comment]
Looks like those PRs are merged and both of those pages cover 'explain'
