### ISSUE TITLE
API schema definition URL not valid from the operation page

### ISSUE THREAD

**Issue by Dabz** [kubernetes/kubernetes.github.io#1095]
On the page http://kubernetes.io/docs/api-reference/v1/operations/, links to schema definitions are invalid. While clicking on a link, I am redirected to http://kubernetes.io/docs/api-reference/v1/operations/definitions/#_v1_componentstatuslist, the correct redirection should be: http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_componentstatuslist

**Comment by jeffmendoza** [comment]
Schema links seem to be working now
