### ISSUE TITLE
Edit button is pixelated

### ISSUE THREAD

**Issue by agonzalezro** [kubernetes/kubernetes.github.io#110]
The edit button is a small 50x50 png file and it doesn't look great on retina displays.

I didn't want to a PR because I suspect that you want to keep this exact button, but if you provide me the original icon in SVG I could do the change.

**Comment by johndmulhausen** [comment]
@CreaturesInUnitards I agree, it seems like a low-quality asset. PTAL when you get a chance.

**Comment by CreaturesInUnitards** [comment]
yup fixed
