### ISSUE TITLE
I wish /docs/user-guide/ui/ to show how to retireve dashboard password

### ISSUE THREAD

**Issue by rutulpatel** [kubernetes/kubernetes.github.io#1100]
I wish /docs/user-guide/ui/ to show how to retireve dashboard password

**Comment by javiercr** [comment]
This page nows states:

>In case you have to provide a password, use the following command to find it out:
>```
>kubectl config view
>```

However it seems that after kubernetes >v1.3 the config view command does not display the user and password, nor the file `~/.kube/config`. As I'm using Google Container Engine I was able to find the user and password from the GKE Dashboard (under Container Cluster, select your container > Show credentials). 

I think this should be clarified in the user guide, especially for those not using GKE.

**Comment by jeffmendoza** [comment]
This has been updated since:
http://kubernetes.io/docs/user-guide/ui/#master-server
please re-open with new requests if still needed
