### ISSUE TITLE
I wish /docs/api-reference/ pointed to the latest version of the API

### ISSUE THREAD

**Issue by ljnelson** [kubernetes/kubernetes.github.io#1110]
I wish /docs/api-reference/ pointed to the latest version of the API, or at least didn't yield a `404`.

**Comment by jaredbhatti** [comment]
The right link should be: http://kubernetes.io/docs/reference/
or: http://kubernetes.io/docs/api-reference/v1/definitions/
Unfortunately, the "I wish" feature doesn't include the origin URL :(
