### ISSUE TITLE
I wish /docs/user-guide/kubectl/kubectl_config/kubectl_config_current-context/ contained information about kubectl config current-context, since it's linked to by the parent page

### ISSUE THREAD

**Issue by msteffen** [kubernetes/kubernetes.github.io#1113]
I wish /docs/user-guide/kubectl/kubectl_config/kubectl_config_current-context/ contained information about kubectl config current-context, since it's linked to by the parent page (kubectl config)

**Comment by jaredbhatti** [comment]
Fixed: http://kubernetes.io/docs/user-guide/kubectl/kubectl_config_current-context/
