### ISSUE TITLE
I wish /docs/getting-started-guides/docker/ existed (linked from https://github.com/kubernetes/kubernetes/tree/master/cluster/images/hyperkube)

### ISSUE THREAD

**Issue by chaosaffe** [kubernetes/kubernetes.github.io#1118]
I wish /docs/getting-started-guides/docker/ existed (linked from https://github.com/kubernetes/kubernetes/tree/master/cluster/images/hyperkube)

**Comment by jaredbhatti** [comment]
Known issue, fixed: 
/docs/getting-started-guides/ proposes possible options for hosting k8s
