### ISSUE TITLE
Travis CI: Authentication failed for `git push` to release-1.4

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes.github.io#1124]
``` console
$ git config --global user.email ${GIT_EMAIL}
The command "git config --global user.email ${GIT_EMAIL}" exited with 1.
...
The command "git merge -s recursive -X theirs homebase/release-1.4 -m "Sync from homebase"" exited with 0.
$ git push
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:
  git config --global push.default matching
To squelch this message and adopt the new behavior now, use:
  git config --global push.default simple
See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)
remote: Anonymous access to kubernetes-v1-4/kubernetes-v1-4.github.io.git denied.
fatal: Authentication failed for 'https://:@github.com/kubernetes-v1-4/kubernetes-v1-4.github.io.git/'
The command "git push" exited with 128.
```

**Comment by janetkuo** [comment]
cc @pwittrock

**Comment by janetkuo** [comment]
log: https://travis-ci.org/kubernetes/kubernetes.github.io/builds/156069148

**Comment by janetkuo** [comment]
I believe I've fixed it. Travis will now pass in newer PRs merged into release-1.4, see https://github.com/kubernetes/kubernetes.github.io/pull/1128

But old PRs are still using old travis configs...

**Comment by janetkuo** [comment]
@jaredbhatti maybe know the answer?

**Comment by janetkuo** [comment]
It seems that it passed just because I commited #1128 with GitHub :/

**Comment by janetkuo** [comment]
@jaredbhatti it seems that people submitting PRs to release-1.4 need to send their git credential to travis env.global.secure to make travis pass?

**Comment by janetkuo** [comment]
In the failed travis build log, the following steps are missing 

```
environment variables from repository settings
$ export encrypted_b7b6a058a6f4_key=[secure]
$ export encrypted_b7b6a058a6f4_iv=[secure]
Setting environment variables from .travis.yml
$ export GIT_EMAIL=[secure]
$ export GIT_NAME=[secure]
$ export GIT_USERNAME=[secure]
$ export GH_TOKEN=[secure]
```

**Comment by janetkuo** [comment]
I found the root cause https://github.com/travis-ci/travis-ci/issues/1500#issuecomment-26122631: 
> Secure environment variables are not included in pull request builds for security reasons. If they were, then anyone could submit a pull request and simply print out all the environment variables.

@jaredbhatti @pwittrock can we remove the travis script in release-1.4?

**Comment by janetkuo** [comment]
I removed .travis.yml in release-1.4 branch

**Comment by jeffmendoza** [comment]
looks like we are not using this any more
