### ISSUE TITLE
K8s Best Practices Documents Requested

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes.github.io#1160]
Based on many conversations - the following best practices documents are requested:
- [ ] How to increase your utilization
- [ ] How to measure your utilization
- [ ] How to test increased utilization
- [ ] How to rightsize your cluster
- [ ] How to run K8s in two datacenters
- [ ] How to run a CI/CD pipeline on K8s
- [ ] How to run two workloads (public diurnal workload (website) + big data to fill in the slack)
- [ ] How to run a database without petset
- [ ] How to run a database with petset
- [ ] How to run a bastion server and lock down firewall rules (to make up for the fact that we don’t offer non-external IPs)
- [ ] How to drain connections for the purposes of upgrading
- [ ] How to upgrade a master
- [ ] How to upgrade nodes
- [ ] How to upgrade an app
- [ ] How to do a gradual rolling upgrade with canary stages and/or blue/green
- [ ] How to hard cap a workload at # of CPUs
- [ ] How does capping work: memory and CPU (kill the container, limit the usage of CPU, etc)
- [ ] How to run a untrusted multi-tenant workload
- [ ] How to run a trusted/internal multi-tenant workload

Each one would have an SEO friendly headline, and would (hopefully) be around a page or two (no more) no included graphics.

**Comment by jaredbhatti** [comment]
I've seen a few efforts made on this, but this particular issue is over 6 months old.  I'm going to close this issue for issue hygiene reasons.

Related issue: https://github.com/kubernetes/kubernetes.github.io/issues/1108
