### ISSUE TITLE
I wish / linked to a Hello World that didn't require an account.

### ISSUE THREAD

**Issue by k0s** [kubernetes/kubernetes.github.io#1173]
I wish / linked to a Hello World that didn't require an account.

**Comment by k0s** [comment]
Kubernetes looks great. when step one is create an account on any specific provider, I care a lot less about software. How about let me play with the basics locally without getting lost in footnotes to appendixes?

**Comment by jaredbhatti** [comment]
Kubernetes basics tutorial lets you do this: http://kubernetes.io/docs/tutorials/kubernetes-basics/

Thanks for the bug!
