### ISSUE TITLE
Issue with /docs/user-guide/pods/single-container/

### ISSUE THREAD

**Issue by LiginGeorge** [kubernetes/kubernetes.github.io#1176]
Issue with /docs/user-guide/pods/single-container/

Hi Team,

I was following following link http://kubernetes.io/docs/user-guide/pods/single-container/
to create pod , its showing container creating status for long time. 
root@indmyskuberm01:~# kubectl get pod
NAME            READY     REASON                                         RESTARTS   AGE
example-pao7a   0/1       Image: nginx is ready, container is creating   0          1h

root@indmyskuberm01:~# kubectl get pods -l run=example-pao7a
NAME      READY     REASON    RESTARTS   AGE

Please find the describe output , please help me to resolve this issue

root@indmyskuberm01:~# kubectl describe pod example-pao7a | more
W0907 16:16:15.474241   55278 request.go:302] field selector: v1 - events - involvedObject.name - example-pao7a: need to check if this is versioned correctly.
W0907 16:16:15.474328   55278 request.go:302] field selector: v1 - events - involvedObject.namespace - default: need to check if this is versioned correctly.
W0907 16:16:15.474347   55278 request.go:302] field selector: v1 - events - involvedObject.uid - 393dd76c-74d8-11e6-8321-0017a477c82c: need to check if this is versioned correctly.
Name:                           example-pao7a
Image(s):                       nginx
Node:                           127.0.0.1/127.0.0.1
Labels:                         run=example
Status:                         Pending
Replication Controllers:        example (1/1 replicas created)
Containers:
  example:
    Image:              nginx
    State:              Waiting
      Reason:           Image: nginx is ready, container is creating
    Ready:              False
    Restart Count:      0
Conditions:
  Type          Status
  Ready         False
Events:
  FirstSeen                             LastSeen                        Count   From                    SubobjectPath                           Reason  Message
  Wed, 07 Sep 2016 15:16:21 +0530       Wed, 07 Sep 2016 15:16:21 +0530 1       {kubelet 127.0.0.1}     implicitly required container POD       created Created with doc
ker id bca05ac32ed6fd0e40322d9188ae645c9a6e6d69d4239a3585bd5045a1181311
  Wed, 07 Sep 2016 15:16:21 +0530       Wed, 07 Sep 2016 15:16:21 +0530 1       {kubelet 127.0.0.1}     implicitly required container POD       failed  Failed to start
with docker id bca05ac32ed6fd0e40322d9188ae645c9a6e6d69d4239a3585bd5045a1181311 with error: API error (400): {"message":"starting container with HostConfig was deprecat
ed since v1.10 and removed in v1.12"}

**Comment by jeffmendoza** [comment]
doesn't look like a doc issue
