### ISSUE TITLE
Need a fairly complete, searchable glossary

### ISSUE THREAD

**Issue by derekmahar** [kubernetes/kubernetes.github.io#1191]
I think ConfigMap deserves a place in the glossary in /docs/reference/.

**Comment by bgrant0607** [comment]
Lots of things are missing in the glossary, both in the navigation menu and in the body. 

We've had requests for short summaries. They used to be in kubernetes/README.md. We're in the process of removing the text there.

A glossary search mechanism would be useful, also.

It should include at least all system components, CLIs, addons, dependencies (e.g., docker, etcd), and APIs.

Other terms: SELinux, AppArmor, cAdvisor, controller, federation, kubeconfig, master, UID.

**Comment by chenopis** [comment]
This is being addressed by https://github.com/kubernetes/kubernetes.github.io/issues/4629.
