### ISSUE TITLE
/docs/user-guide/kubectl-cheatsheet/ improvments

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes.github.io#1204]
- [x] exporting kubeconfig and using multiple profiles with `export KUBECONFIG=<path>`
- [x] `kubectl explain` and other new commands 
- [ ] more jq commands and describe info on how to install
- [x] `kubeclt completion`
- [x] notes on abbreviations
- [ ] if a command is referenced, link the full docs
- [ ] how to use logging to debug commands
- [x] break up the sections to make it more readable, and wrap the line numbers
- [x] kubectl edit, patch, delete, replace, scale, update, and rolling-update commands
- https://github.com/kubernetes/kubernetes.github.io/issues/1200
- https://github.com/kubernetes/kubernetes.github.io/issues/1094

cc: @bgrant0607 you want to assign me?

**Comment by chrislovecnm** [comment]
http://kubernetes.io/docs/user-guide/kubectl-cheatsheet/ for ease of use.

**Comment by chrislovecnm** [comment]
PR https://github.com/kubernetes/kubernetes.github.io/pull/1486 is a good start.

**Comment by chrislovecnm** [comment]
`kubectl get po --all-namespaces  -o jsonpath='{range .items[?(@.spec.nodeName =="nodename")]}{.metadata.name}{"\n"}{end}'`

**Comment by chrislovecnm** [comment]
List masters vs minion nodes.  Get all nodes that are down, get all nodes that are up.  exec with an interactive session

**Comment by chrislovecnm** [comment]
@kubernetes/docs can someone assign this to me?

**Comment by chrislovecnm** [comment]
| Great. I see that in my 1.4.3 cluster, the master is "tainted" as described above.

| it will be good to either (i) make output of "get nodes" mention that node will run user pods or not or (ii) filter the output to not include non-schedulable nodes (with a "-a" option to show all)

**Comment by jeffmendoza** [comment]
Old issue, please re-open if you are going to continue with this.
