### ISSUE TITLE
I wish /examples/flocker/ i wish this page hadn't been removed so suddently!  It worked last week!

### ISSUE THREAD

**Issue by jsilberm** [kubernetes/kubernetes.github.io#122]
I wish /examples/flocker/ i wish this page hadn't been removed so suddently!  It worked last week!

**Comment by bgrant0607** [comment]
Sorry for the trouble.

You can still find this in the main github repo.

https://github.com/kubernetes/kubernetes/tree/master/examples/flocker

**Comment by bgrant0607** [comment]
cc @johndmulhausen

**Comment by johndmulhausen** [comment]
Added link forwarding to 404.md. Should work!
