### ISSUE TITLE
Clarify image pull policy 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes.github.io#1221]
In http://kubernetes.io/docs/user-guide/config-best-practices/#container-images, we tell the users that specifying image pull policy to Always or set image tag as :latest will always force a pull:

> The default container image pull policy is IfNotPresent, which causes the Kubelet to not pull an image if it already exists. If you would like to always force a pull, you must specify a pull image policy of Always in your .yaml file (imagePullPolicy: Always) or specify a :latest tag on your image.

Then the user is confused why specifying the deployment image tag to :latest doesn't make it pull the latest version of image upon image updates. 

I don't find more kubelet documents that show the users when an image pull will happen. We should make it more clear.

**Comment by jeffmendoza** [comment]
Looks like we have some docs here (first hit on searching for pull policy):
http://kubernetes.io/docs/user-guide/images/#updating-images
