### ISSUE TITLE
Issue with /docs/getting-started-guides/openstack-heat/

### ISSUE THREAD

**Issue by natejoebott** [kubernetes/kubernetes.github.io#1227]
Issue with /docs/getting-started-guides/openstack-heat/

Greetings, I'm looking for some guidance on which logs I need to review to troubleshoot issues using this deployment procedure.  I have my openstack environment set-up with an SSL cert defined in my profile file (openrc) and can execute client commands securely without issue, but received the following issue:

[centos@kube2-build ~]$ ./kubernetes/cluster/kube-up.sh
... Starting cluster using provider: openstack-heat
... calling verify-prereqs
swift client installed
glance client installed
nova client installed
heat client installed
openstack client installed
... calling kube-up
kube-up for provider openstack-heat
[INFO] Execute commands to create Kubernetes cluster
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)

I want to trace to which script file this issue manifested.  Thanks much!

**Comment by natejoebott** [comment]
I inserted 'set-x' in a number of the shell scripts to get a verbose output while executing

**Comment by xsgordon** [comment]
@natejoebott did you end up working this one out or is it still an issue?

**Comment by jeffmendoza** [comment]
This issue tracker for the site is probably not a good place to find answers. I'd suggest connecting with the openstack k8s community over slack / mailing list / stackoverflow. https://github.com/kubernetes/community
