### ISSUE TITLE
Issue with etcd credentials in kube api-server

### ISSUE THREAD

**Issue by johnbazan** [kubernetes/kubernetes.github.io#1237]
I'm facing this issue since some days ago, and is the following:

I'm trying to start my kubernetes master using hypercube,
but the documentation is missing how to pass the etcd credentials to kubernetes in order to use a given user.

In the api-server configuration I have something like this:

```
- --etcd-servers=http://root:toor@etcd2-0.server:2379,http://root:toor@etcd2-1.server:2379,http://root:toor@etcd2-2.server:
```

Which is the only possible way to set the basic auth parameters of etcd.
(This works great for both etcdctl and etcd REST API.)

But I'm getting the following error:
- F0915 17:25:35.579278       1 controller.go:86] Unable to perform initial IP allocation check: unable to persist the updated service IP allocations: 110: The request requires user authentication (Insufficient credentials) [0]

My etcd is refusing to write into /registry (which is the default folder), but root:toor are the right credentials. 

I couldn't find any other configuration parameters for this, and I REALLY, REALLY need to secure my etcd with roles/users.

Please, I need some ideas / solutions if possible.

Thanks a lot !

**Comment by jeffmendoza** [comment]
We're going to need more details on what documentation is needed. Closing now as this is an old issue. Please re-open if needed with more info on the documentation that you would like to see.
