### ISSUE TITLE
Duplicate labels and milestones from kubernetes repo

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes.github.io#124]
To facilitate management of action items owned by the engineering team.

**Comment by johndmulhausen** [comment]
@bgrant0607 right now the engineering team should know everything that requires their review here:
https://github.com/kubernetes/kubernetes.github.io/labels/Needs%20Tech%20Review

Is this not sufficient?

**Comment by bgrant0607** [comment]
@johndmulhausen Not if we want docs for any new features, no.

**Comment by bgrant0607** [comment]
Ok, Needs Tech Review, really, really, really needs to be split by team.

**Comment by bgrant0607** [comment]
https://medium.com/@dtinth/how-to-copy-github-labels-from-one-project-to-another-1857adc73e0f#.kg001k1bd

**Comment by bgrant0607** [comment]
@foxish Is already working on duplicating labels to all repos.

**Comment by foxish** [comment]
Labels have been created. @bgrant0607 PTAL.

**Comment by bgrant0607** [comment]
@foxish Yeah! Thanks! 

As we discussed in person, there are few enough milestones, needed in few enough repos, that we can call this done for now.
