### ISSUE TITLE
Broken link: any reference to {{page.docsbranch}} is broken

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes.github.io#1249]
@jaredbhatti @devin-donnelly we recently deleted release-1.3 and it breaks all the links to {{page.docsbranch}}

For example, http://kubernetes.io/docs/user-guide/node-selection/ links to https://github.com/kubernetes/kubernetes.github.io/tree/release-1.3/docs/user-guide/node-selection 

(See the exact line here https://github.com/kubernetes/kubernetes.github.io/blame/master/docs/user-guide/node-selection/index.md#L12)

@kubernetes/docs

**Comment by gustamora** [comment]
https://play.golang.org/p/Y-k0h7Ln3G

**Comment by chenopis** [comment]
This has been addressed
