### ISSUE TITLE
Issue with /docs/getting-started-guides/ubuntu-calico/

### ISSUE THREAD

**Issue by ted-jung** [kubernetes/kubernetes.github.io#1255]
Issue with /docs/getting-started-guides/ubuntu-calico/

I met a few errors while installation with this document. (ubuntu 16.04 xenial)

**On the Master**
#1) docker version 1.12 does not work properly with this steps
- Error logs  from /var/log/syslog
  Sep 19 00:53:15 kmaster kernel: [14875.205756] aufs au_opts_verify:1597:docker[11748]: dirperm1 breaks the protection by the permission bits on the lower branch
  Sep 19 00:53:15 kmaster docker[11734]: time="2016-09-19T00:53:15.886419531+09:00" level=error msg="Handler for GET /images/gcr.io/google_containers/etcd:2.2.1/json returned error: No such image: gcr.io/google_containers/etcd:2.2.1"
  Sep 19 00:53:17 kmaster docker[11734]: time="2016-09-19T00:53:17.386159980+09:00" level=error msg="Attempting next endpoint for pull after error: manifest unknown: Failed to fetch \"2.2.1\" from request \"/v2/google_containers/etcd/manifests/2.2.1\"."
  Sep 19 00:53:28 kmaster kernel: [14888.320583] aufs au_opts_verify:1597:docker[12288]: dirperm1 breaks the protection by the permission bits on the lower branch
  Sep 19 00:53:28 kmaster kernel: [14888.328948] aufs au_opts_verify:1597:docker[12288]: dirperm1 breaks the protection by the permission bits on the lower branch
  Sep 19 00:53:28 kmaster docker[11734]: time="2016-09-19T00:53:28.973408454+09:00" level=warning msg="DEPRECATED: Setting host configuration options when the container starts is deprecated and will be removed in Docker 1.12"
  Sep 19 00:53:28 kmaster kernel: [14888.342168] aufs au_opts_verify:1597:docker[12288]: dirperm1 breaks the protection by the permission bits on the lower branch
  Sep 19 00:53:29 kmaster kernel: [14888.422017] aufs au_opts_verify:1597:docker[12196]: dirperm1 breaks the protection by the permission bits on the lower branch
  Sep 19 00:53:29 kmaster kernel: [14888.440531] aufs au_opts_verify:1597:docker[12196]: dirperm1 breaks the protection by the permission bits on the lower branch
  - solution
    => changed docker version from 1.12.0(it is a default version of docker in ubuntu 16.04) to 1.11.0
         1.  sudo apt-get purge docker-engine
         2.  sudo apt-get autoremove
         3.  sudo rm -rf /var/lib/docker
         4.  sudo apt-get install -y -q docker-engine=1.11.2-0~xenial
#2) the images described in manifest under /etc/kubernetes/manifests does not downloaded properly

```
* Error logs from /var/log/syslog
```

Sep 19 00:53:01 kmaster docker[11734]: time="2016-09-19T00:53:01.151037299+09:00" level=error msg="Handler for GET /images/gcr.io/google_containers/hyperkube:v1.1.3/json returned error: No such image: gcr.io/google_containers/hyperkube:v1.1.3"
Sep 19 00:53:15 kmaster kernel: [14875.182254] aufs au_opts_verify:1597:docker[11748]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 19 00:53:15 kmaster kernel: [14875.192025] aufs au_opts_verify:1597:docker[11748]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 19 00:53:15 kmaster docker[11734]: time="2016-09-19T00:53:15.837988653+09:00" level=warning msg="DEPRECATED: Setting host configuration options when the container starts is deprecated and will be removed in Docker 1.12"
Sep 19 00:53:15 kmaster kernel: [14875.205756] aufs au_opts_verify:1597:docker[11748]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 19 00:53:15 kmaster docker[11734]: time="2016-09-19T00:53:15.886419531+09:00" level=error msg="Handler for GET /images/gcr.io/google_containers/etcd:2.2.1/json returned error: No such image: gcr.io/google_containers/etcd:2.2.1"
- solution
   => manually pulled those images (e.g. docker pull gcr.io/google_containers/etcd:2.2.1)

**on worker nodes**
#1) the same with master (docker version 1.11.0 on ubuntu 16.04)

```
 it looks does not work with docker 1.12.0
```
#2) the name of NIC on Ubuntu 16.04

```
  enp0S~ not like eth0...
 Error logs from /var/log/syslog
Sep 19 01:57:52 kslave2 kubelet[12600]: E0919 01:57:52.588337   12600 manager.go:377] NetworkPlugin cni failed on the status hook for pod 'kube-proxy-192.168.56.222' - invalid CIDR address: Device "eth0" does not exist.
```
- solution
   => resolved after rename it with old house (enp0S3 -> eth0)
        1.  goto /etc/default/grub
        2. fill up value GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"
        3. update-grub with sudo 
        4. change NIC name /etc/network/interface
        5. reboot

There are few things slightly need to be updated.
Will update that i found lately.

**Comment by jeffmendoza** [comment]
Need a Ubuntu/Calico SME to review, closing now as this is an old issue.
Updated link to guide: http://kubernetes.io/docs/getting-started-guides/ubuntu/calico/
