### ISSUE TITLE
Issue with /docs/user-guide/persistent-volumes/walkthrough/

### ISSUE THREAD

**Issue by surajssd** [kubernetes/kubernetes.github.io#1256]
On docs page: http://kubernetes.io/docs/user-guide/persistent-volumes/walkthrough/

When clicked on the link in doc saying:

> You can view all the files for this example in the docs repo here.

When clicked on "here", it takes to https://github.com/kubernetes/kubernetes.github.io/tree/release-1.3/docs/user-guide/persistent-volumes which does not exist!

**Comment by jeffmendoza** [comment]
looks fixed
