### ISSUE TITLE
Port clashing when creating new multi-container pods

### ISSUE THREAD

**Issue by vLia** [kubernetes/kubernetes.github.io#1278]
**Workspace:**
I am using Kubernetes based on this tutorial: https://blog.jetstack.io/blog/k8s-getting-started-part2/

**Environment:**
OS: NAME="Ubuntu" VERSION="16.04 LTS (Xenial Xerus)"
Docker version: 1.11.2

**What happened:**
I tried running a multicontainer pod based on a similar configuration file:

`apiVersion: v1`
`kind: Pod`
`metadata:`
`name: database-app`
`spec:`
`containers:`
`-`
`name: database`
`image: database_image:latest`
`ports:`
`- containerPort: 8080`
`hostPort: 8083`
`-`
`name: app`
`image: app_image:latest`
`ports:`
`- containerPort: 8080`
`hostPort: 8082`

I checked the logs for the second container and it said that the port 8080 was already in use. How could I run these two containers on the same pod?

**Comment by jeffmendoza** [comment]
not a kubernetes.io issue
