### ISSUE TITLE
in hellonode, 'docker push' --> 'gcloud docker push'

### ISSUE THREAD

**Issue by amygdala** [kubernetes/kubernetes.github.io#128]
In this example: https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/hellonode.md ,
the line:

    docker push gcr.io/PROJECT_ID/hello-node:v1
should be:

    gcloud docker push gcr.io/PROJECT_ID/hello-node:v1

I caught this on twitter.  I think the guy wanted to submit a PR, so I won't spoil his fun.  If he does not, I can fix it.

**Comment by johndmulhausen** [comment]
It indeed got a PR. :) Thanks, Amy!
