### ISSUE TITLE
Issue with /docs/user-guide/jsonpath/

### ISSUE THREAD

**Issue by bmeck** [kubernetes/kubernetes.github.io#1284]
Issue with /docs/user-guide/jsonpath/

what syntax does filter consume???

**Comment by bmeck** [comment]
?

**Comment by bmeck** [comment]
was this clarified / documented somewhere? I don't see it on a quick search

**Comment by jeffmendoza** [comment]
sorry about that, it is the jsonpath syntax

**Comment by bmeck** [comment]
Jsonpath doesnt have equality operators though. It is some superset?
