### ISSUE TITLE
Issue with /docs/user-guide/deployments/

### ISSUE THREAD

**Issue by danielromlein** [kubernetes/kubernetes.github.io#1296]
`nginx-deployment.yaml` 404s.

**Comment by rnaveiras** [comment]
Related https://github.com/kubernetes/kubernetes.github.io/issues/1269

**Comment by romlein** [comment]
Ah, cool. Thanks @rnaveiras!

**Comment by rnaveiras** [comment]
@devin-donnelly this is fixed in #1331 as well.
