### ISSUE TITLE
Issue with /docs/getting-started-guides/openstack-heat/

### ISSUE THREAD

**Issue by natejoebott** [kubernetes/kubernetes.github.io#1297]
Issue with /docs/getting-started-guides/openstack-heat/

Hello, I've encountered an issue with deploying the minion nodes using this procedure.  The stack deployment fails after completing the master node creation - from the stack events log:

master_wait_condition
OS::Heat::WaitCondition
Create Failed: CREATE aborted

Any idea why this is occuring?

**Comment by xsgordon** [comment]
Hi @natejoebott - typically a WaitCondition failing indicates that a timeout occurred on some other action, we would need more information on the state of other concurrent actions being undertaken by the stack to debug the cause.

**Comment by steveperry-53** [comment]
@natejoebott, Please reopen if you want to provide more information.
