### ISSUE TITLE
/docs/user-guide/managing-deployments/

### ISSUE THREAD

**Issue by ReSearchITEng** [kubernetes/kubernetes.github.io#130]
fix typo: **decscription**

**Comment by johndmulhausen** [comment]
Fixed. Next time, try hitting the blue pencil on the top-right and making the fix yourself! It takes just as much time as filing a bug. :)

**Comment by ReSearchITEng** [comment]
Afaik any contributions to the project are allowed only after signing an agreement. If that's no longer the case, we'll fork & request merge next time :)
