### ISSUE TITLE
Issue with /docs/getting-started-guides/minikube/

### ISSUE THREAD

**Issue by budhi003** [kubernetes/kubernetes.github.io#1301]
Issue with /docs/getting-started-guides/minikube/

minikube dashboard
xdg-open: no method available for opening

**Comment by yissachar** [comment]
Hi @budhi003,

It looks like this is a bug report and not a docs issue. You might have better luck posting your issue to the [Minikube repository](https://github.com/kubernetes/minikube/issues), with more details.
