### ISSUE TITLE
RBAC validation changes

### ISSUE THREAD

**Issue by jimmycuadra** [kubernetes/kubernetes.github.io#1313]
An update to the authorization docs are needed for the RBAC validation changes in kubernetes/kubernetes#29930.

/cc @ericchiang

**Comment by jaredbhatti** [comment]
I haven't seen any movement on this issue for 4 months.  I'm going to close for issue hygiene reasons.

**Comment by jimmycuadra** [comment]
Hygiene reasons? Shouldn't we try to get in touch with folks who could resolve the issue rather than closing something that isn't resolved?
