### ISSUE TITLE
Issue with /docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/kubernetes.github.io#1315]
Issue with /docs/getting-started-guides/kubeadm/

The yum repo to use `files.rm-rf.ca` does not seem to use gpg keys.

I would be nice to get a more legitimate sounding repo to get the packages, as well as a proper gpgkey.

maybe something like `k8s.io`

**Comment by errordeveloper** [comment]
@sebgoa this is very old, let's close 👍
