### ISSUE TITLE
Issue with /docs/admin/limitrange/

### ISSUE THREAD

**Issue by mikejk8s** [kubernetes/kubernetes.github.io#1318]
Issue with /docs/admin/limitrange/

Unless I've completely missed it after reading over this a few times, there's no link to the limit-example.yml file anywhere on the main page. When I attempted to grab it directly from the repo (https://github.com/kubernetes/kubernetes/tree/master/docs/admin/limitrange) I was redirected back to the kubernetes.io page. 

I tracked it down in the gh/kubernetes.io repo eventually https://github.com/kubernetes/kubernetes.github.io/tree/master/docs/admin/limitrange

I worry issues like this will frustrate users who like me didn't know the kubernetes.io repo existed until months into using Kubernetes. I've encountered this many times and haven't submitted reports because I'm not sure what state the documentation is in (is it still being migrated? is it considered done and I should report issues like this?)

In this case it would probably be very helpful to add a link directly to the files to the readme.

Thanks!

**Comment by steveperry-53** [comment]
Thanks for mentioning this. We are in the process of reorganizing the docs and are fixing this issue as we go along. Example: http://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-ram-container/
