### ISSUE TITLE
Make binaries available: issue with https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kubernetes.github.io#1319]
Issue with /docs/getting-started-guides/kubeadm/

Where's are the binary(s)?

I'm forced to either use 1.5.0 alpha version of it (not 1.4.0) or the Ubuntu Xenial build.

ping @errordeveloper

**Comment by ekozan** [comment]
all version are tagged 1.5.0 
-> https://github.com/kubernetes/release/commit/9decc00523f522f476b9f0c3011eafc25c8ea3b8

**Comment by errordeveloper** [comment]
Only kubeadm is 1.5, the rest of components will be 1.4.

**Comment by errordeveloper** [comment]
See the [repo manifest](https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-arm64/Packages). I believe this issue can be closed.

**Comment by cdrage** [comment]
Ahhhhh makes sense. Thought it would be included in 1.4 as it was on the 1.4 release pages.

I'll close this.

**Comment by cdrage** [comment]
@errordeveloper 

I'm re-opening this issue as I'm experimenting with setting this up with Debian unstable.

Is there a particular place where I can retrieve the binaries? Searching online appears that only the RPM and DEB is available, it'd be ideal to have a release page / repo where I can simple curl the binary. Is that possible?

**Comment by zacharysarah** [comment]
@cdrage 👋 I'm taking three actions here:

1. Renaming this issue to reflect that the docs path is now `/docs/setup/independent/create-cluster-kubeadm/`

2. Tagging this issue with the _area/build-release_ and _Needs Tech Review_ labels

    /cc @justinsb 👋 for kubeadm visibility after today's (7/13/17) [k8s community meeting](https://docs.google.com/document/d/1VQDIAB0OqiSjIHI8AWMvSdceWhnz56jNpZrLs6o7NJY/).

3. Closing this issue

        Making kubeadm binaries available may be an awesome idea, but it needs buy-in and review from the teams responsible for building them. I'm closing this until it's actionable for docs.

**Comment by cdrage** [comment]
@zacharysarah Awesome! :+1: Glad there's going to be more visibility. I'd like to see `kubeadm` on other operating systems!
