### ISSUE TITLE
Wrong link in kubernetes admin docs

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes.github.io#1335]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Link on http://kubernetes.io/docs/admin to "Changing Cluster Size" points to FAQ (https://github.com/kubernetes/kubernetes/wiki/User-FAQ#how-do-i-change-the-size-of-my-cluster/)

**Proposed Solution:**
We should just delete this link. We already have a section about changing cluster size in "Cluster Management Guide".

**Page to Update:**
http://kubernetes.io/docs/admin/

**Comment by jaredbhatti** [comment]
Fixed.
