### ISSUE TITLE
Issue with /docs/hellonode/ - error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

### ISSUE THREAD

**Issue by neilsarkar** [kubernetes/kubernetes.github.io#1369]
The first command that uses `kubectl` results in this error:

```
error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

Possibly relevant for reproduction: I initially selected us-west-1 for the first run and then switched to us-central-1 for the run documenting repro steps. I am currently in Portugal. 

Full script copied below. Seems like it could be related to https://github.com/kubernetes/kubernetes/issues/28612

[session.log.txt](https://github.com/kubernetes/kubernetes.github.io/files/509044/session.log.txt)

**Comment by neilsarkar** [comment]
I was able to resolve this by doing the following before any `kubectl` commands:

```bash
$ gcloud auth application-default login
```

can this be added to the hello world documentation? or was there a step I missed that should have done this?

**Comment by steveperry-53** [comment]
The /docs/hello-node page has been replace with a page that doesn't use Google Cloud Platform:
https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/
