### ISSUE TITLE
Issue with /docs/user-guide/persistent-volumes/walkthrough/

### ISSUE THREAD

**Issue by AndreFelipeMachado** [kubernetes/kubernetes.github.io#1384]
Issue with /docs/user-guide/persistent-volumes/walkthrough/

Hello,
The files path have moved. For example
docs/user-guide/persistent-volumes/claims/claim-01.yaml
became
test/fixtures/doc-yaml/user-guide/persistent-volumes/claims/claim-01.yaml
Regards.

**Comment by steveperry-53** [comment]
Fixed
