### ISSUE TITLE
Issue with /docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by dannyman** [kubernetes/kubernetes.github.io#1390]
Issue with /docs/getting-started-guides/kubeadm/

Yesterday I was able to install https://github.com/microservices-demo/microservices-demo just fine but today the install fails consistently. I can not tell if I am making bad clusters or if this microservices demo has been broken overnight (14 new issues!?)

Suggest the documentation has users pull a "known stable" or "release" tag of the microservices demo which is widely understood to work.

**Comment by errordeveloper** [comment]
@dannyman it's been a while since you have opened this issue, have you managed to make it work?

**Comment by steveperry-53** [comment]
@dannyman, Please reopen if you want to continue this discussion.
