### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/

### ISSUE THREAD

**Issue by RichNBBarrett** [kubernetes/kubernetes.github.io#1422]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

Tutorial buttons 404's and then redirects me to github

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by talklittle** [comment]
The broken links are on http://kubernetes.io/docs/tutorials/kubernetes-basics/

Link that 404's and redirects to github: http://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster.html

Links that simply 404:

* http://kubernetes.io/docs/tutorials/kubernetes-basics/1-0.html
* http://kubernetes.io/docs/tutorials/kubernetes-basics/2-0.html
* http://kubernetes.io/docs/tutorials/kubernetes-basics/3-0.html
* http://kubernetes.io/docs/tutorials/kubernetes-basics/4-0.html
* http://kubernetes.io/docs/tutorials/kubernetes-basics/5-0.html
* http://kubernetes.io/docs/tutorials/kubernetes-basics/6-0.html
