### ISSUE TITLE
I wish the documentation on kubernetes.io was versioned according to kubernetes versions

### ISSUE THREAD

**Issue by swehner** [kubernetes/kubernetes.github.io#143]
I was trying to find out if our kurrent version 1.1  support some feature and.
Before the documentation for kubernetes 1.0 and 1.1 was available. Now I can't seem to find it...
Having the documentation for the latest beta on the site also seems a bit misleading IMO

**Comment by johndmulhausen** [comment]
To view the 1.1 docs, see https://github.com/kubernetes/kubernetes.github.io/tree/release-1.1

You can follow the README instructions to view the 1.1 version of the site locally or on github.io.

**Comment by swehner** [comment]
Thanks for the tip!
