### ISSUE TITLE
Issue with /docs/admin/authentication/

### ISSUE THREAD

**Issue by achernev** [kubernetes/kubernetes.github.io#1430]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Incorrect HTTP header is quoted in the "Putting a Bearer Token in a Request" section.

**Proposed Solution:**
Replace the word `Authentication` with `Authorization` so the line becomes:
`Authorization: Bearer 31ada4fd-adec-460c-809a-9e56ceb75269`

**Page to Update:**
http://kubernetes.io/docs/admin/authentication/

**Comment by steveperry-53** [comment]
Fixed
