### ISSUE TITLE
Help to add a page to user guide

### ISSUE THREAD

**Issue by megastef** [kubernetes/kubernetes.github.io#1435]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report
- [x] Question

**Problem:**

Page not generated in _site folder
**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/docs/getting-started-guides/

I've created a new file in docs/getting-started-guides/logging-monitoring-sematext.md and added entry in _data/guides.md 

```
- title: Logging and Monitoring with Sematext
   path: /docs/getting-started-guides/logging-monitoring-sematext/
```

but the page is not generated as folder in _site. 
See animated gif how the page is displayed (404 error). 

![](http://g.recordit.co/iUYzd9xpsm.gif)

**Comment by megastef** [comment]
Could somebody please advise, why the new .md file is not converted to HTML? 
I use the Docker version to view the page 
```docker run -ti --rm -v "$PWD":/k8sdocs -p 4000:4000 gcr.io/google-samples/k8sdocs:1.0``` 
Does it execute "jekyll clean"?

**Comment by steveperry-53** [comment]
@megastef, Make sure your logging-monitoring-sematext.md page has front matter at the top. The front matter is the YAML block between the triple-dashed lines.

Also, we have changed the way the left nav and page titles are done. The title goes in the front matter like this.
title: Logging and Monitoring with Sematext

In guides.yaml, don't include the title. Just include a path.

**Comment by steveperry-53** [comment]
@megastef, I'm closing this, because we're cleaning up a backlog of issues. Please reopen if you need more assistance.

**Comment by megastef** [comment]
Thank you @steveperry-53 - got it finally running, PR in preparation :)
