### ISSUE TITLE
"libvirt or KVM" in TOC leads to fedora/flannel_multi_node_cluster/

### ISSUE THREAD

**Issue by rutsky** [kubernetes/kubernetes.github.io#144]
Here: https://github.com/kubernetes/kubernetes.github.io/blame/997fdd164c871eefb4115fb7e54ee94f9be8a333/_data/guides.yml#L77

`fedora/flannel_multi_node_cluster/` already have it's place in TOC: https://github.com/kubernetes/kubernetes.github.io/blame/997fdd164c871eefb4115fb7e54ee94f9be8a333/_data/guides.yml#L101

**Comment by johndmulhausen** [comment]
Note: That's how it was on the old site and I just copied it. I agree it's not the best to have one topic show up in multiple places in the left-nav, though I did make sure that our left nav can support this scenario. 

@bgrant0607 Is it okay to have this topic in both places in the left-nav?

**Comment by bgrant0607** [comment]
The "libvirt or KVM" link is wrong. Please delete that entry and add "(using libvirt or KVM)" to the "oVirt" line.
