### ISSUE TITLE
Issue with /docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes.github.io#1453]
Since https://github.com/kubernetes/kubernetes/pull/33718 has been merged, we should release that fix and remove this line:

```
kubectl logs is broken with kubeadm clusters due to #22770.
```

**Comment by errordeveloper** [comment]
@resouer thank you, we surely should do that, however we will need to wait for 1.5.0.

**Comment by jaredbhatti** [comment]
Closing, now that 1.5 is released.
