### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by emanguy** [kubernetes/kubernetes.github.io#1456]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Trying to run `kubectl proxy` in part 3 of module 2 in kubernetes bootcamp doesn't drop back to terminal.

**Proposed Solution:**
I fixed the issue by running the command through nohup:
`nohup kubectl proxy &`

You should probably change the instructions to reflect that.

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/

Kubernetes version 1.4

**Comment by BenHall** [comment]
Thanks for the feedback. In the tutorial all future commands are run in a second terminal window to get around this issue.
