### ISSUE TITLE
Google searches for Kubernetes topics returns links to pages with 404 errors

### ISSUE THREAD

**Issue by allannaim** [kubernetes/kubernetes.github.io#146]
I've noticed that Google searches for Kubernetes topics such as:

=====
"Kubernetes security" 

returns: kubernetes.io/v1.1/docs/design/security_context.html

results in 404 error
=====

"Kubernetes API"

returns: http://kubernetes.io/api-ref/

results in 404 error
=====

I'm sure there's more... Some links automatically redirect to the K8s.io docs pages, such as:

"Kubernetes Networking"

returns: kubernetes.io/v1.0/docs/admin/networking.html

redirects to: http://kubernetes.io/docs/admin/networking/

**Comment by johndmulhausen** [comment]
Shouldn't be too many more. Added a special case for api-ref. Thanks!
