### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by nivasvanka** [kubernetes/kubernetes.github.io#1475]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
Start Scenario Button is not clickable

**Proposed Solution:**
Make it clickable

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment]
Thank you for the feedback. Which browser / OS are you using? Could you try again to see if it's still a problem?
