### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/update-intro/

### ISSUE THREAD

**Issue by kjones1876** [kubernetes/kubernetes.github.io#1476]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Slider doesnt work.

**Proposed Solution:**
Fix slider.

**Page to Update:**
http://kubernetes.io/...

**Comment by steveperry-53** [comment]
Thanks, we are aware of this and are planning to update the UX.
