### ISSUE TITLE
Issue with /docs/user-guide/production-pods/

### ISSUE THREAD

**Issue by marrrvin** [kubernetes/kubernetes.github.io#1481]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**

Link to Resource QoS: https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/resource-qos.md  leads to 404 error.

**Proposed Solution:**

Probably change broken link to this one:
https://github.com/kubernetes/kubernetes/blob/master/docs/design/resource-qos.md

Pull request: https://github.com/kubernetes/kubernetes.github.io/pull/1483

**Page to Update:**
http://kubernetes.io/docs/user-guide/production-pods/

**Comment by steveperry-53** [comment]
This page will soon be replaced by a collection of Task pages.
