### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/update-intro/

### ISSUE THREAD

**Issue by redpandatronicsuk** [kubernetes/kubernetes.github.io#1490]
**This is a...** 

- [ ] Feature Request
- [ X] Bug Report

**Problem:**
Carousel doesn't work. Clicking the right or left chevron doesn't show the next or previous slide as expected, but scrolls the carousel to the top of the page. (Chrome: Version 53.0.2785.143 (64-bit) MacOS Sierra)

**Proposed Solution:**
For the right chevron, change the href #my-carousel to onclick="function nextSlide() { var elem = document.querySelector('.item.active img'), currSlide = Number(elem.src.slice(-5, -4));  elem.src = elem.src.slice(0,-5) + (currSlide+1) + '.svg' }"
or something similar.

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/update-intro/

**Comment by cmpaul** [comment]
Also:
http://kubernetes.io/docs/tutorials/kubernetes-basics/scale-intro/#myCarousel

**Comment by steveperry-53** [comment]
Fixed
