### ISSUE TITLE
Update HPA doc

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes.github.io#1498]
Update HPA documentation, verify that:
- it is up-to-date,
- it gives user clear info how to use HPA,
- it gives user clear info how to debug HPA (eg.: describes events generated by HPA).

**Comment by jszczepkowski** [comment]
CC @fgrzadkowski

**Comment by jszczepkowski** [comment]
PR #1356 is a part of this.

**Comment by jaredbhatti** [comment]
Marking fixed.
