### ISSUE TITLE
Issue with /docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by randollr** [kubernetes/kubernetes.github.io#1502]
**This is a...**

- [ ] Feature Request
- [x] Bug Report

**Problem:**  
"apt-get install -y kubelet kubeadm kubectl kubernetes-cni" returns:

<pre>
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package kubelet
E: Unable to locate package kubeadm
E: Unable to locate package kubectl
E: Unable to locate package kubernetes-cni
</pre>

**Proposed Solution:**
Packages do not exist on http://packages.ubuntu.com/. Please create.

**Page to Update:**
http://kubernetes.io/docs/getting-started-guides/kubeadm/

**Comment by errordeveloper** [comment]
You need to use Kubernetes repository, it's in the docs.

**Comment by keatz55** [comment]
+1

**Comment by abhishekjawali** [comment]
Even after including the Kubernetes repo, I am facing the same issue.

**Comment by randollr** [comment]
@adhishekjawaii make sure you're using the right distro version -- that was my issue.  I was on was ubuntu 14.04 and I thought I was already on 16.04 on that system.
