### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/explore-interactive/

### ISSUE THREAD

**Issue by ashu-mehra** [kubernetes/kubernetes.github.io#1504]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Incorrect documentation on http://kubernetes.io/docs/tutorials/kubernetes-basics/explore-interactive/ Module 3 Step 3.
It says when running kubectl logs, "Note: We don’t need to specify the container name, because we only have one container inside the pod.".
However if container name is omitted, kubectl logs does not run even though there is only one pod running:

> > kubectl get pods  
> > NAME                                  READY     STATUS    RESTARTS   AGE  
> > kubernetes-bootcamp-390780338-hdiih   1/1       Running   0          3m
> > kubectl logs  
> > error: expected 'logs POD_NAME [CONTAINER_NAME]'.  
> > POD_NAME is a required argument for the logs command  
> > See 'kubectl logs -h' for help and examples

Step 4 in the module also mentions the same point:

"Again, worth mentioning that the name of the container itself can be omitted in this case because we have only one running in the Pod."

**Proposed Solution:**

Please update the documentation.
**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/explore-interactive/
Go to Module 3, Step 3 of 4

Kubernetes Version

> kubectl version  
> Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", Git
> Commit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", Bu
> ildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platfor
> m:"linux/amd64"}  
> Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", Git
> Commit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", Bu
> ildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platfor
> m:"linux/amd64"}

**Comment by steveperry-53** [comment]
It's OK to omit the container name, but you have to supply the pod name.
