### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/update-intro/

### ISSUE THREAD

**Issue by hlship** [kubernetes/kubernetes.github.io#1512]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**

Carousel images do not work. Clicking the next/last or the direct buttons (small blue circles) does nothing.

I'm on OS X. Tried both Chrome and Safari.

I did a quick check in developer tools, and looks like all the JS on the page loaded without error.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/update-intro/

... but affects all the tutorial pages I've yet visited.

**Comment by cmpaul** [comment]
Dupe of #1490

**Comment by steveperry-53** [comment]
Fixed
