### ISSUE TITLE
Need more documentation in /docs/user-guide/kubectl/kubectl_apply/

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes.github.io#1513]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
There are no examples or details on kubectl apply and its uses.

**Page to Update:**
http://kubernetes.io/docs/user-guide/kubectl/kubectl_apply/

cc @pwittrock @ymqytw

**Comment by pwittrock** [comment]
Yes please

**Comment by ymqytw** [comment]
>Page to Update:
http://kubernetes.io/docs/user-guide/kubectl/kubectl_apply/

This is generated by `spf13/cobra`, isn't it?

**Comment by pwittrock** [comment]
Yes, we would need to update the source.

**Comment by ymqytw** [comment]
We will need to update the doc when flags `--dry-run` and `-o` have been fixed. Ref: https://github.com/kubernetes/kubernetes/pull/34028#issuecomment-262392748

**Comment by ymqytw** [comment]
@foxish I think we can close this.

**Comment by foxish** [comment]
@ymqytw the docs on http://kubernetes.io/docs/user-guide/kubectl/kubectl_apply/ need to be regenerated first from the godoc?

**Comment by ymqytw** [comment]
According to https://github.com/kubernetes/kubernetes.github.io/issues/1768#issuecomment-262329671, we will regenerate all of them by script on release date.
