### ISSUE TITLE
Problem with pressing backspace (delete) while inside interactive tutorial shell

### ISSUE THREAD

**Issue by matekdk** [kubernetes/kubernetes.github.io#1515]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
While inside interactive tutorial, pressing backspace sends the whole browser window to previous page. This makes it impossible to correct a spelling error inside interactive shell. 

**Proposed Solution:**
Simple javascript re-mapping of backspace key.

**Page to Update:**
Any pages with interactive tutorial shell, starting here: http://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-intro/

Tried the system in Vivaldi browser, version 1.4.589.38.

**Comment by BenHall** [comment]
Thank you for the report. We hadn't tested Vivaldi, but can confirm it's a problem. Thank you for highlighting this.

We'll work on a fix for this. Sadly the only workaround at present is to use Chrome/Firefox/Safari

**Comment by BenHall** [comment]
This should now have been resolved. Vivaldi is fully supported.

**Comment by chenopis** [comment]
Thanks @BenHall

**Comment by matekdk** [comment]
Perfect (y) - looking forward to start the tutorial :)
