### ISSUE TITLE
Issue with /docs/getting-started-guides/ubuntu/

### ISSUE THREAD

**Issue by dikarel** [kubernetes/kubernetes.github.io#1517]
**This is a...**
- [ ] Feature Request
- [x] Bug Report

**Problem:**
It is unclear how you are supposed to "Configure and start the Kubernetes cluster"

**Proposed Solution:**
- A command-line snippet would provided clarification
- A screencast can provide additional details that a written guide might glance over

**Page to Update:**
http://kubernetes.io/docs/getting-started-guides/ubuntu/

**Comment by chenopis** [comment]
This was address by PR #1932
