### ISSUE TITLE
Visited links and regular text look too similar on kubernetes.io/docs/

### ISSUE THREAD

**Issue by kenden** [kubernetes/kubernetes.github.io#1519]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

Visited links in http://kubernetes.io/docs/ appear just like regular text.

On Chrome, Firefox and Safari, after visiting a page once, a link doesn't appear to be a link anymore. It looks too similar to regular text.

![kubernetes github io-links-issue](https://cloud.githubusercontent.com/assets/480586/19563755/75ee54e6-96e1-11e6-94ce-a02867a500c9.png)

**Proposed Solution:**

Change the color/text stylie of a visited link to be more different than the rest of the text.

**Page to Update:**

Pretty much all the pages under /docs seem to have the problem. Ex:
http://kubernetes.io/docs/
http://kubernetes.io/docs/getting-started-guides/aws/

Changing a css should fix this.

**Comment by jaredbhatti** [comment]
Yep. Fixed issue.

**Comment by jaredbhatti** [comment]
I pushed a fix for this already.  Closing.
