### ISSUE TITLE
Issue with /docs/getting-started-guides/logging/

### ISSUE THREAD

**Issue by josselin-c** [kubernetes/kubernetes.github.io#1523]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
In kubernetes.github.io/docs/getting-started-guides/logging.md, around line 132 we have:
`You can also follow this link to the [settings tab](https://pantheon.corp.google.com/project/_/logs/settings).`
This pantheon link seems to be an internal google-only link which shouldn't be there.

**Proposed Solution:**
Change the link. I don't know what the correct-one is.

**Page to Update:**
kubernetes.github.io/docs/getting-started-guides/logging.md
File on github: https://github.com/kubernetes/kubernetes.github.io/blame/master/docs/getting-started-guides/logging.md

**Comment by jaredbhatti** [comment]
Logging got a rewrite and now lives here: https://kubernetes.io/docs/user-guide/logging/overview/

If there's still issues, please feel free to open an new issue.
