### ISSUE TITLE
We need some page somewhere that tells users how to download and install kubectl, for when they are connecting to a new cluster they didn't set up

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes.github.io#153]
I wish /docs/getting-started-guides/aws/kubectl/ had a description of how to download kubectl

We need some page somewhere that tells users how to download and install kubectl, for when they are connecting to a new cluster they didn't set up :-)

**Comment by johndmulhausen** [comment]
Sorry, @justinsb what URL is this? I don't see it in master or release-1.1

**Comment by justinsb** [comment]
Yeah sorry... this was from the first page of the google search at the time, and it was a broken page.  I clicked on the "I wish this page..." link, and this is what came out.

I think "downloading kubectl" is a pretty common task, and I don't think we have a page that directly covers it;  I get dumped into the local docker instructions right now, which does cover it, but is kind of a roundabout way to cover this...

**Comment by johndmulhausen** [comment]
Ah I see. Updated the issue title. :)

**Comment by sah** [comment]
The guide at http://kubernetes.io/docs/getting-started-guides/docker/ mentions how to download kubectl binaries, but gives an HTTP URL! HTTPS would be smarter, and already works.

Ideally, kubernetes would provide apt and yum repositories, etc, so that OS package managers could be used to install and manage (upgrade, remove...) kubectl.

**Comment by bgrant0607** [comment]
Saw a blog post that linked to this:
https://coreos.com/kubernetes/docs/latest/configure-kubectl.html

**Comment by techtonik** [comment]
@bgrant0607 should the URL be https://console.cloud.google.com/storage/browser/kubernetes-release/ instead of https://storage.googleapis.com/kubernetes-release/ ?

**Comment by techtonik** [comment]
Seems like canonical page describing `kubectl` installation is http://kubernetes.io/docs/user-guide/prereqs/

**Comment by jaredbhatti** [comment]
Documented here: http://kubernetes.io/docs/user-guide/sharing-clusters/

**Comment by techtonik** [comment]
It is now here: https://kubernetes.io/docs/tasks/kubectl/install/
