### ISSUE TITLE
HA Upgrades /admin/high-availability/upgrades.md

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes.github.io#1531]
Outline and layout document about HA Master upgrade process and best practices for upgrading virtual machine images for instance

Again @bgrant0607 happy to help.

I am coding this into kops, and will need to document. Documenting here will be work, but not crazy. Who can I lean on for tech edit? Doing this will make kops better.

**Comment by bgrant0607** [comment]
@chrislovecnm The other members of @kubernetes/kops-maintainers ?

**Comment by chrislovecnm** [comment]
@kubernetes/docs can I be assigned?

**Comment by chenopis** [comment]
Since this is covered by #1733, I'm closing this issue.
