### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by kevin-smets** [kubernetes/kubernetes.github.io#1535]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

Kubernetes Bootcamp Terminal                                                                        

Sorry, we hit a problem with the connection.  
Your internet may have dropped, or we hit capacity and are adding more.                             

Please refresh and try again.

**Proposed Solution:**

**Page to Update:**

http://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/

**Additional Information:**

Could this be related to the global DDoS?

**Comment by BenHall** [comment]
Hi Kevin,

Thank you for reporting this. I believe this was a one-off event that was the result of an upgrade we needed to perform to update our SSL certificates.  Sorry it caused an interrupted. It would be working now, could you please retry?

**Comment by kevin-smets** [comment]
I'm afraid it's still the same message:

> Kubernetes Bootcamp Terminal                                                                                                   
>                                                                                                     
> Sorry, we hit a problem with the connection.                                                        
> Your internet may have dropped, or we hit capacity and are adding more.                             
>                                                                                                     
> Please refresh and try again.

**Comment by BenHall** [comment]
Thanks, we're investigating now to check we haven't missed anything. Thank you.

**Comment by BenHall** [comment]
It looks like one of the servers in our cluster had a few hiccups. I've deployed a change to the application and architecture that should remove the problems. Please let me know if the situation improves. We'll continue monitoring to verify ourselves.

Thanks for your support

**Comment by chenopis** [comment]
This issue has been addressed. Please open a new one if you see this behavior again.
