### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by yfaykya** [kubernetes/kubernetes.github.io#1539]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**

"Sorry, we hit a problem with the connection.  
Your internet may have dropped, or we hit capacity and are adding more.                             

Please refresh and try again.                       "

I have been getting this now for 4 days. Once I briefly saw a 404 flash by.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/

**Comment by BenHall** [comment]
Sorry you've been having a problem connecting to Katacoda. Could you please let me know your OS / Browser version? Are you using a proxy that could block websockets?

**Comment by yfaykya** [comment]
Linux and windows - chrome / firefox and IE.
I see a few other reports of this also in the bug tracker. 
No proxy used.

**Comment by BenHall** [comment]
Is the problem still happening? We upgraded a few of our systems on the weekend which may have interrupted your connection. I'm very sorry about that

**Comment by yfaykya** [comment]
Yes - it is still happening. Interestingly I just copied the iframe URL to
another tab (
http://katacoda.com/embed/kubernetes-bootcamp/1/?ui=inline&amp;host=kubernetes.io&amp;target=inline-terminal-1&amp;prompt=Kubernetes%20Bootcamp%20Terminal&amp;color=326de6&amp;secondary=273d6d&amp;hideintro=false&amp;font=Roboto&amp;fontheader=Roboto%20Slab

and it works! But not from the main tutorial page.

**Comment by chenopis** [comment]
This issue has been addressed. Please open a new one if you see this behavior again.
