### ISSUE TITLE
I wish /img/warning.png existed

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes.github.io#154]
I wish /img/warning.png existed.

All docs in https://github.com/kubernetes/kubernetes refer to http://kubernetes.io/img/warning.png for release version warning

cc @johndmulhausen @bgrant0607

**Comment by johndmulhausen** [comment]
The correct action item is for the docs in kubernetes/kubernetes to get updated. We don't have a use for that image here and I don't want both an /img and /images directory on root. Feel free to file a bug against the kubernetes/kubernetes repo asking them to update their image link for warning.png to http://kubernetes.io/kubernetes/img/warning.png
