### ISSUE TITLE
Issue with /docs/getting-started-guides/aws/

### ISSUE THREAD

**Issue by mudrii** [kubernetes/kubernetes.github.io#1543]
Please can team create document step by step installation independent of Linux distribution.
Is very confusing how the installation process takes place and what and how is installed.

**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
Missing Steps documentation in installation process

**Proposed Solution:**
Document step by step kubernetes installation

**Page to Update:**
http://kubernetes.io/...

**Comment by chrislovecnm** [comment]
I have a PR in that will change this a ton.

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kubernetes.github.io/pull/1562

**Comment by chenopis** [comment]
#1562 has been merged.
