### ISSUE TITLE
batch/v2alpha1 needs swagger docs for ScheduledJob

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes.github.io#1544]
We have http://kubernetes.io/docs/api-reference/batch/v1/definitions/ but we do not have docs for batch/v2alpha1 so we do not have ScheduledJob docs.

**Comment by erictune** [comment]
@soltysh

**Comment by erictune** [comment]
fyi @janetkuo

**Comment by soltysh** [comment]
I'm gonna close this, since it's already being tracked in #1439. I have the prereq to have those generated in k8s 1.4, just need to update the docs. I'm hoping to have a PR opened later today.
