### ISSUE TITLE
Issue with font being hard to read

### ISSUE THREAD

**Issue by dikarel** [kubernetes/kubernetes.github.io#1550]
**This is a...**
- [ ] Feature Request
- [x] Bug Report

**Problem:**

It is difficult to read the body text on Google Chrome (Windows) using a 24" 1080p LCD monitor

Some issues:
- The text is small and thin, making it hard to read. It's almost not there
- Paragraph width is excessively long. After reaching the end of a line, it takes noticeable effort to backtrack to where the start of the next line is

For comparison, I find GitHub readmes/wikis a lot more readable.

**Proposed Solution:**

Any of the following changes will improve readability:
- A paragraph width that is based on [UX best practices](http://ux.stackexchange.com/questions/3618/ideal-column-width-for-paragraphs-online)
- Increasing font size/weight

For example, the following settings improved readability for me:

```
p {
  font-weight: normal;
  letter-spacing: 0.2px;
  line-height: 1.5;
  font-size: 16px;
  max-width: 50em;
  color: rgba(0, 0, 0, 0.8);
}
```

**Modified typography**

![image](https://cloud.githubusercontent.com/assets/15131271/19675049/52a9558e-9ab6-11e6-9e2e-d4ca21890ebe.png)

**Original**

![image](https://cloud.githubusercontent.com/assets/15131271/19675050/554a478a-9ab6-11e6-9fd3-66462bc6aeb9.png)

**Page to Update:**
http://kubernetes.io/docs/*

---

**Comment by chenopis** [comment]
Being addressed in PR #2094
