### ISSUE TITLE
dead link on /docs/admin/dns/ to kube-dns/README.md

### ISSUE THREAD

**Issue by thkoch2001** [kubernetes/kubernetes.github.io#1552]
This is a Bug Report

**Problem:**
http://kubernetes.io/docs/admin/dns/ includes dead link to http://releases.k8s.io/master/build/kube-dns/README.md at the bottom of the page

**Comment by techtonik** [comment]
I guess it is here - https://github.com/kubernetes/kubernetes/tree/master/build-tools/kube-dns
