### ISSUE TITLE
Issue with /docs/getting-started-guides/centos/centos_manual_config/

### ISSUE THREAD

**Issue by xavinux** [kubernetes/kubernetes.github.io#1563]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
In the CentOS guide for Kubernetes installation for etcd to be configure it says this:
- Configure ETCD to hold the network overlay configuration on master: Warning This network must be unused in your network infrastructure! 172.30.0.0/16 is free in our network.

$ etcdctl mkdir /kube-centos/network

But running the above command will show:

$ etcdctl mkdir /kube-centos/network
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused
error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused

**Proposed Solution:**
First etcd should be start to avoid the error by excuting:

 $ systemctl start etcd

**Page to Update:**
http://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/

version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0"

**Comment by a-mccarthy** [comment]
fixed by #1641 to include instructions to start etcd before configuring
