### ISSUE TITLE
I wish /swagger.json existed

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes.github.io#1569]
The same as old /swagger-spec, I wish OpenAPI spec also available in kubernetes.io/kubernetes/swagger.json

**Comment by techtonik** [comment]
Why in `kubernetes.io/kubernetes/swagger.json` specifically?

**Comment by mbohlool** [comment]
old swagger spec is in kubernetes.io/kubernetes/swagger-spec, I just followed that pattern, feel free to find an appropriate location for it, if this does not make sense. We should put swagger.spec somewhere in our website.

**Comment by jaredbhatti** [comment]
We're working on a new method of documenting APIs: https://kubernetes.io/docs/api-reference/1_5/

**Comment by mbohlool** [comment]
This is not about documentation, swagger spec (OpenAPI) is the source of documentation and many clients. I still think we should have it somewhere in kubernetes.io. we are serving an old version of this spec in "kubernetes.io/kubernetes/swagger-spec". We should serve the new one that is here now: https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json

**Comment by ahmetb** [comment]
@mbohlool is there a specific reason why you want it on the kubernetes.io domain rather than github.com? We're deprecating everything under kubernetes.io/kubernetes/*

**Comment by mbohlool** [comment]
Well as long as there is no old swagger (ui or spec) hosted anywhere in kubernetes.io, I am fine with not having this. My initial reason was around having an old spec is bad and we should update to the new spec.

**Comment by mbohlool** [comment]
btw, I still see https://kubernetes.io/kubernetes/third_party/swagger-ui/ though it is not loading and also I think there is another issue about removing it somewhere.

These are related issues that need to be resolved (and by removing all old swagger things, they should be): #1908 #515

**Comment by ahmetb** [comment]
@mbohlool we actually removed it from the source repo and yet it's still showing up. We're currently suspecting there's a script somewhere that gets kicked off during the build causing some URLs like that to be added to the website. I'm actively investigating.

@chenopis can we take care of the issues linked above now that we link out to the Swagger spec?

**Comment by chenopis** [comment]
I'm still working on this. I'll see what I can do.

**Comment by chenopis** [comment]
I left links to the spec and swagger.json in the ToC of the [Reference](https://kubernetes.io/docs/reference/) section.
