### ISSUE TITLE
Show autoscaling and batch api reference docs as well

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes.github.io#157]
We only show the v1 and extensions/v1beta1 api ref docs at k8s.io: http://kubernetes.io/docs/reference/.

We need to show the autoscaling/v1 and batch/v1 api-ref docs as well.
Feel free to close this if we are just waiting to release 1.2  before updating the docs.

@kubernetes/sig-api-machinery @bgrant0607 @caesarxuchao @kubernetes/docs

**Comment by bgrant0607** [comment]
@johndmulhausen copied them from master somehow

**Comment by johndmulhausen** [comment]
Done in 634654a96b82c3247c9f5a190a30a531ffa27dab

**Comment by nikhiljindal** [comment]
Thanks @johndmulhausen 

Sorry I should have mentioned it earlier but realized it now, that we also need to update the swagger spec to include those 2 new groups. We had a script (https://github.com/kubernetes/kubernetes/blob/gh-pages/swagger-spec/update.sh) for that, but not sure if that will work with the new website?

Once, we have updated the spec, the new groups should become visible at http://kubernetes.io/kubernetes/third_party/swagger-ui/

**Comment by caesarxuchao** [comment]
I guess the update.sh is not being used now, since most file names in the script is out-of-date.

**Comment by nikhiljindal** [comment]
Yes, we used it while we were releasing v1.1.
Havent used it after that.

**Comment by bgrant0607** [comment]
@nikhiljindal @caesarxuchao I don't think swagger json needs to be on the website if we're not going to host the swagger UI there. The swagger json should be in the kubernetes repo, though.

**Comment by nikhiljindal** [comment]
I was thinking that we will let swagger UI be there on kubernetes.io, but not point to it in our docs. So that new users wont know about it, but existing users who want to use it (like the ones in https://github.com/kubernetes/kubernetes.github.io/issues/112) can still use it.
I agree that it is very slow, but looks like some users still find it useful.
