### ISSUE TITLE
Overall Improvements to the site using netlify

### ISSUE THREAD

**Issue by jessfraz** [kubernetes/kubernetes.github.io#1575]
- [x] **All pages need a unique title**: right now a lot of the generated docs have no title (ex. kubectl pages)
- [x] **Replace javascript redirects with something better or not at all**: everything in https://github.com/kubernetes/kubernetes.github.io/blob/master/js/redirects.js is a 302 redirect which throws a 404 then gets redirected and is pretty bad for SEO either we should replace them with 301 redirects via a web server or not have them at all, it also hurts page load time
- [x] **SSL**: we can get SSL pretty easily by hosting via netlify instead of github pages, it would not require any changes to jekyll etc, it would just be a flip on a DNS record and a setting inside the netlify UI (I am willing to help, I just dont have the right permissions but I have a lot of other sites I've set up doing this)

**Comment by chrislovecnm** [comment]
All great comments, will help search ability of the site with page titles.

SGTM - Google project need SEO help

**Comment by calavera** [comment]
> Replace javascript redirects with something better or not at all

Netlify can handle those redirects too out of the box :smile: 
https://www.netlify.com/docs/redirects/

This is a rough translation of what's in that JS to a `_redirects` file:

```
# 301 redirects
/third_party/swagger-ui http://kubernetes.io/kubernetes/third_party/swagger-ui/
/resource-quota http://kubernetes.io/docs/admin/resourcequota/
/horizontal-pod-autoscaler http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/
/docs/roadmap https://github.com/kubernetes/kubernetes/milestones/
/api-ref https://github.com/kubernetes/kubernetes/milestones/
/docs/user-guide/overview http://kubernetes.io/docs/whatisk8s/
```

The forwardning rules to the repo branch might be more involved, but still doable. That `_redirects` file can also be generated based on a template, it's always processed after Netlify builds the site.

**Comment by jaredbhatti** [comment]
Tagged this with P1 and Needs tech review. I think we should figure this out soon.  Netlify seems to be the right way forward.

**Comment by chenopis** [comment]
I'm targeting 2017Q3 to move k8s.io prod over to Netlify.

**Comment by calavera** [comment]
@chenopis happy to jump in a Hangout or meet somewhere else to prepare this.

**Comment by chenopis** [comment]
@calavera Awesome. Thanks for volunteering to jump in. Once k8s 1.7 is out the door, hopefully next week, I will setup some meetings to work on a plan for the cutover.

**Comment by chenopis** [comment]
OMG, all three of these are done!
