### ISSUE TITLE
Issue with /docs/user-guide/kubectl/kubectl_create_secret_docker-registry/

### ISSUE THREAD

**Issue by mecampbellsoup** [kubernetes/kubernetes.github.io#1577]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
This page should have an example usage of `kubectl create secret docker-registry`.

**Proposed Solution:**
Here is an example command that references `quay.io` as a private Docker registry:

```
kubectl create secret docker-registry quayregistrykey --docker-server=your-docker-registry-eg-quay.io --docker-username=docker-registry-username --docker-password=some-password --docker-email=someone@foo.com
```

**Page to Update:**
http://kubernetes.io/docs/user-guide/kubectl/kubectl_create_secret_docker-registry/

**Comment by chenopis** [comment]
http://kubernetes.io/docs/user-guide/kubectl/kubectl_create_secret_docker-registry/ now has an example of kubectl create secret docker-registry.
