### ISSUE TITLE
Docker local cluster setup guide doesn't work on mac

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes.github.io#159]
1.2 issues:
- suggested image tag for hyperkube image does not exist
- running the command with the image tag in the Makefile on HEAD does not bring up a working cluster

non-1.2 issues:
- master only listens on 127.0.0.1, so curl <master ip>:8080 doesn't work, nor does kubectl

**Comment by ericandrewlewis** [comment]
I can confirm, `kubectl` can't communicate with the API.

**Comment by ericandrewlewis** [comment]
I would offer a bounty of $10 to whoever fixes this ;)

**Comment by pwittrock** [comment]
I think for now adding the ssh tunnel to the doc is the best way to address the issue.  Bounty would be great to improve community engagement, otherwise I plan to send a doc fix this afternoon given how frustrating it is.
