### ISSUE TITLE
etcdctl mkdir /kube-centos/network Error:  client: etcd cluster is unavailable or misconfigured error #0: dial tcp 127.0.0.1:4001: getsockopt: connection refused error #1: dial tcp 127.0.0.1:2379: getsockopt: connection refused

### ISSUE THREAD

**Issue by rajeshwer** [kubernetes/kubernetes.github.io#1590]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by AlexMioMio** [comment]
I met this error too.etcd is not started

**Comment by rajeshwer** [comment]
I tried https://coreos.com/etcd/docs/latest/clustering.html

static seems working

**Comment by AlexMioMio** [comment]
yeah,seems helpful
