### ISSUE TITLE
guide doesnt include how to create etcd cluster 

### ISSUE THREAD

**Issue by rajeshwer** [kubernetes/kubernetes.github.io#1591]

**Comment by chrislovecnm** [comment]
Not sure what u mean. You expect docs to setup k8s or etcd?

**Comment by rajeshwer** [comment]
I keep getting this error 

Unable to listen for secure (open /var/run/kubernetes/apiserver.crt: no such file or directory); will try again.


how do i fox this issue

**Comment by rajeshwer** [comment]
I was unable to deploy kubernetes dashboard

kubectl get pods --namespace=kube-system
NAME                                    READY     STATUS             RESTARTS   AGE
kubernetes-dashboard-4260454762-89zmr   0/1       CrashLoopBackOff   10         29m
kubernetes-dashboard-v1.4.1-kj5kv       0/1       CrashLoopBackOff   10         28m
