### ISSUE TITLE
Issue with /docs/ - broken link to http://kubernetes.io/docs/admin/networking/

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes.github.io#1592]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The left hand column has a link, under the text "Networking in Kubernetes", to http://kubernetes.io/docs/admin/networking/ --- which does not seem to exist now.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/docs/

**Comment by chrismarino** [comment]
This page still exists, but a recent change introduced invalid characters. Fixed with PR #1605

**Comment by chrismarino** [comment]
Fixed. http://kubernetes.io/docs/admin/networking/
