### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by janesch** [kubernetes/kubernetes.github.io#1597]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
When trying to run the interactive tutorial, where I expect a video we get 
'The webpage cannot be found '

**Proposed Solution:**
correct the link?

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/

**Comment by BenHall** [comment]
Thanks for your feedback. I believe this issue has now been resolved as I'm not seeing a 'The webpage cannot be found ' error. If you could check that would be great! Thanks

**Comment by a-mccarthy** [comment]
marking closed
