### ISSUE TITLE
Re: The Community page: 

### ISSUE THREAD

**Issue by CreaturesInUnitards** [kubernetes/kubernetes.github.io#16]
I'm guessing the best we can do for content here is porting the old HTML from the current k8s.io, so please do.

Waiting for Sara(h?) for now.

**Comment by johndmulhausen** [comment]
I believe you have the copy for this now.

**Comment by CreaturesInUnitards** [comment]
I just stubbed this out — you can just pour in your content, then Peter will work some magic on it.

**Comment by CreaturesInUnitards** [comment]
yup done.

**Comment by johndmulhausen** [comment]
The Media section is not there.

**Comment by johndmulhausen** [comment]
@CreaturesInUnitards Just pinging your alias so you're aware

**Comment by CreaturesInUnitards** [comment]
@johndmulhausen Media section is dropped for now per Bob: https://docs.google.com/document/d/1_y-g6lTTtv6kU7J8TOjLD8BMDWCIwVaxaqodz2zKKWA/edit#

I'm labeling this "Website Feature Request" and un-assigning

**Comment by johndmulhausen** [comment]
Ah, no need for that; we'll start a new bug if needed.
