### ISSUE TITLE
I wish /docs/user-guide/liveness/ had a working link to the guide on healthchecks

### ISSUE THREAD

**Issue by malexovi** [kubernetes/kubernetes.github.io#160]
I wish /docs/user-guide/liveness/ had a working link to the guide on healthchecks

**Comment by malexovi** [comment]
"This [guide](http://kubernetes.io/docs/user-guide/k8s201/#health-checking) has more information on health checks." currently links to a 404

**Comment by johndmulhausen** [comment]
Fixed in e90b574aa23226c05b36fc2051ced55e44693344

In the future, you should fix links like this by clicking the blue pencil in the top-right! It takes exactly as much time as filing a bug :)
