### ISSUE TITLE
Issue with /docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes.github.io#1602]
- [ ] Feature Request
- [x] Bug Report

**Problem:**
- The section on kubeadm being multi-platform needs to be rewritten and go through docs review.
- It is also in the wrong part of the page IMO.
- There needs to be a TOC. 

**Page to Update:**
http://kubernetes.io/docs/getting-started-guides/kubeadm/

cc @mikedanese

**Comment by foxish** [comment]
I'm surprised how https://github.com/kubernetes/kubernetes.github.io/pull/1420 got through without an LGTM from the docs team, given that some of the wording doesn't quite seem like documentation.
The community needs to be informed of the process with docs, and if they should self-apply docs-lgtm that way. @bgrant0607, what is the consensus on the two stage LGTM?

**Comment by bgrant0607** [comment]
@foxish Everyone in kubernetes-maintainers currently has write access to kubernetes.github.io, and people with write access can merge currently. That was done initially in order to increase velocity in the doc repo.
