### ISSUE TITLE
Issue with /docs/getting-started-guides/centos/centos_manual_config/

### ISSUE THREAD

**Issue by rtoma** [kubernetes/kubernetes.github.io#1613]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Page contains
```
[virt7-docker-common-release]
name=virt7-docker-common-release
baseurl=http://cbs.centos.org/repos/virt7-docker-common-release/x86_64/os/
gpgcheck=0
```
This repo has kubernetes 1.1.0 as only and latest version.

**Proposed Solution:**
Change docs to point to https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64 (sourced from http://kubernetes.io/docs/getting-started-guides/kubeadm/)

**Page to Update:**
http://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/

**Comment by chenopis** [comment]
http://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/ has been deprecated.
