### ISSUE TITLE
failed to create network

### ISSUE THREAD

**Issue by rajeshwer** [kubernetes/kubernetes.github.io#1616]
etcdctl mkdir /kube-centos/network
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused
error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused

**Comment by johnsmith0209** [comment]
same problem here
I just follow the steps here[http://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/].

**Comment by chenopis** [comment]
http://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/ has been deprecated.
