### ISSUE TITLE
dead link in docs

### ISSUE THREAD

**Issue by thkoch2001** [kubernetes/kubernetes.github.io#1621]
containing page: Issue with /docs/admin/dns/
link text: Docs for the DNS cluster addon
bad link: http://releases.k8s.io/master/build/kube-dns/README.md

I know this link was dead already last week but I had no time to report it then. Could you please employ an automated system that checks all links in the docs? Google might have something like this. :-)

**Comment by a-mccarthy** [comment]
thanks for reporting! this appears to have been fixed by #2170
