### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by astoklas** [kubernetes/kubernetes.github.io#1622]
**This is a...** 

- [ ] Feature Request
- [ X] Bug Report

**Problem:**
Terminal did not connect, refresh does not work using Safari 10.0.1 on MacOSX 10.12.1

**Proposed Solution:**
Use Chrome works fine

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment]
Sorry you've encountered an error. Could you please check and try again. This should have been resolved.

**Comment by a-mccarthy** [comment]
marking closed
