### ISSUE TITLE
Issue with /docs/admin/

### ISSUE THREAD

**Issue by alexanderdrozd** [kubernetes/kubernetes.github.io#1629]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
there is a problem with one of the link http://kubernetes.io/docs/admin/networking
it shows 404 error Sorry, this page was not found. :(

**Proposed Solution:**
change link or create http://kubernetes.io/docs/admin/networking

**Page to Update:**
http://kubernetes.io/...

**Comment by chrismarino** [comment]
Their is a fix for this in the queue. PR #1605

**Comment by a-mccarthy** [comment]
marking as closed
