### ISSUE TITLE
dashboard crash

### ISSUE THREAD

**Issue by rajeshwer** [kubernetes/kubernetes.github.io#1645]
912 <autogenerated>:1] Error getting ResourceLocation: no endpoints available for service "kubernetes-dashboard"
635052     912 <autogenerated>:1] Error getting ResourceLocation: no endpoints available for service "kubernetes-dashboard"
262084     912 <autogenerated>:1] Error getting ResourceLocation: endpoints "kubernetes-dashboard" not found
241774     912 <autogenerated>:1] Error getting ResourceLocation: endpoints "kubernetes-dashboard" not found
982787     912 <autogenerated>:1] Error getting ResourceLocation: endpoints "kubernetes-dashboard" not found
623413     912 <autogenerated>:1] Error getting ResourceLocation: endpoints "kubernetes-dashboard" not found
497379     912 <autogenerated>:1] Error getting ResourceLocation: endpoints "kubernetes-dashboard" not found

**Comment by nVitius** [comment]
The issues tracker on this repository is for problems directly related to the Kubernetes documentation website [kubernetes.io](kubernetes.io/docs). For general support regarding Kubernetes, please read through [this doc](http://kubernetes.io/docs/troubleshooting/) or visit the official Kubernetes [Slack channel](https://kubernetes.slack.com/)

**Comment by rajeshwer** [comment]
I was getting this errors after following the steps in documentation 
kubernetes on centos
http://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/
I think there are lot of misleading steps in this doc

**Comment by rajeshwer** [comment]
Like for example 
/etc/kubernetes/config doesnt have any KUBE_ETCD_SERVERS
Its in /etc/kubernetes/apiserver

**Comment by a-mccarthy** [comment]
a duplicate of #1618, marking as closed
