### ISSUE TITLE
kubelet logs shows errors

### ISSUE THREAD

**Issue by rajeshwer** [kubernetes/kubernetes.github.io#1646]
9045 docker.go:327] Start docker client with request timeout=2m0s
    9045 server.go:487] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file
    9045 server.go:448] Could not load kubernetes auth path /var/lib/kubelet/kubernetes_auth: stat /var/lib/kubelet/kubernetes_aut
    9045 manager.go:138] cAdvisor running in container: "/system.slice/kubelet.service"
    9045 manager.go:146] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsock
    9045 fs.go:139] Filesystem partitions: map[/dev/mapper/centos-root:{mountpoint:/ major:253 minor:0 fsType:xfs blockSize:0} /de
    9045 manager.go:192] Machine: {NumCores:12 CpuFrequency:2700000 MemoryCapacity:67282030592 MachineID:2f281170da08447facacf42ef
:eno2 MacAddress:54:ab:3a:0a:01:8f Speed:10000 Mtu:1500} {Name:flannel.1 MacAddress:76:30:7c:f6:42:31 Speed:0 Mtu:1450}] Topology:
    9045 manager.go:198] Version: {KernelVersion:3.10.0-327.el7.x86_64 ContainerOsVersion:CentOS Linux 7 (Core) DockerVersion:1.10
    9045 server.go:768] Watching apiserver
    9045 kubelet.go:561] Hairpin mode set to "promiscuous-bridge" but configureCBR0 is false, falling back to "hairpin-veth"
    9045 kubelet.go:384] Hairpin mode set to "hairpin-veth"
    9045 docker_manager.go:235] Setting dockerRoot to /var/lib/docker
    9045 server.go:730] Started kubelet v1.3.4
    9045 kubelet.go:933] Image garbage collection failed: unable to find data for container /
    9045 server.go:117] Starting to listen on 0.0.0.0:10250
    9045 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
    9045 status_manager.go:123] Starting to sync pod status with apiserver
    9045 kubelet.go:2470] Starting kubelet main sync loop.
    9045 kubelet.go:2479] skipping pod synchronization - [network state unknown container runtime is down]
    9045 volume_manager.go:216] Starting Kubelet Volume Manager
    9045 kubelet.go:2366] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable 
    9045 kubelet.go:2374] Failed to check if disk space is available on the root partition: failed to get fs info for "root": unab
    9045 kubelet.go:1187] Node kubernetes-2 was previously registered
    9045 factory.go:224] devicemapper filesystem stats will not be reported: unable to find thin_ls binary
    9045 factory.go:228] Registering Docker factory
    9045 manager.go:240] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot
    9045 factory.go:54] Registering systemd factory
    9045 factory.go:86] Registering Raw factory
    9045 manager.go:1072] Started watching for new ooms in manager
    9045 oomparser.go:185] oomparser using systemd
    9045 manager.go:281] Starting recovery of all containers
    9045 manager.go:286] Recovery completed
    9045 container.go:352] Failed to create summary reader for "/system.slice/docker-8f939ca0be05d52f81d75eef62b18c33f2c6a8bb406d3

**Comment by karthikeayan** [comment]
why is this closed?
am seeing the same error logs, is there any fix for this?

**Comment by pwittrock** [comment]
Sorry I thought I left a comment.  Is this about documentation?  You probably don't want to create this issue for the documentation repo.  I suspect you want the github.com/kubernetes/kubernetes repo.

**Comment by karthikeayan** [comment]
am looking for a approach how this has been solved. am getting this log in kubectl "Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable"
