### ISSUE TITLE
Download Docs issues in prep for bankruptcy

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes.github.io#1660]
Per developer discussion, this is a note to myself to use the GitHub API to download all issues and do some analytics on them, such as number of issues with a specific page.

**Comment by techtonik** [comment]
Bankrupcy?

**Comment by jberkus** [comment]
Wiping out all accumulated docs issues so that we can do a big reset and actually start paying attention to issues.

**Comment by jberkus** [comment]
@pwittrock all issues have been downloaded into a Postgres database, for later searching if we want to retrieve any.  You're clear to proceed to bankruptcy.  Give me an appropriate non-public location and I'll share the database with you.

If bankruptcy gets delayed and you need be to re-do the download, that's pretty simple now.

**Comment by pwittrock** [comment]
@jaredbhatti Should we go ahead and do this?

**Comment by pwittrock** [comment]
@devin-donnelly

**Comment by jberkus** [comment]
Lemme know if you want me to update the download.  Oh, and also where I should put it.
