### ISSUE TITLE
Issue with /docs/admin/

### ISSUE THREAD

**Issue by gerardo8a** [kubernetes/kubernetes.github.io#1661]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
link "networking model" is broken
http://kubernetes.io/docs/admin/networking

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by chrismarino** [comment]
There is a fix for this page (PR #1605) but it has not been merged yet.

**Comment by chrismarino** [comment]
Fixed. http://kubernetes.io/docs/admin/networking/

**Comment by a-mccarthy** [comment]
looks to be fixed :) marking as closed
