### ISSUE TITLE
Update NodeController docs after logic changes.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes.github.io#1664]
NodeController does not force delete Pods anymore. We need to update docs to reflect that (/docs/admin/node.md).

cc @saad-ali @foxish @smarterclayton

**Comment by foxish** [comment]
Since it is a behavioral change, I think it would make sense to call it out somewhere on top of the doc also. The details could still live in the section specific to the Node Controller.
WDYT?

cc @devin-donnelly @erictune

**Comment by gmarek** [comment]
SGTM.

**Comment by foxish** [comment]
Tracking here, the change required to http://kubernetes.io/docs/user-guide/pods/#termination-of-pods as mentioned in https://github.com/kubernetes/kubernetes.github.io/pull/1757#discussion_r89532055
