### ISSUE TITLE
/docs/admin/networking (404 not found)

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes.github.io#1669]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:** http://kubernetes.io/docs/admin/networking returns 404 not found 

**Proposed Solution:** Although `docs/admin/networking.md` exists in the repo, the link is broken. I suspect the problem is generic and may happen to other docs too. @kubernetes/docs 

**Page to Update:**
http://kubernetes.io/docs/admin/networking

**Comment by chrismarino** [comment]
There is a PR for this (PR #1605) in review.

**Comment by chrismarino** [comment]
Fixed.
http://kubernetes.io/docs/admin/networking/

**Comment by janetkuo** [comment]
Thanks!
