### ISSUE TITLE
No docs on QoS except design doc

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes.github.io#1670]
There should be a doc written with users as a target (not a design doc) about QoS that describes the term QoS, and the levels Burstable, Guaranteed, and Best Effort.

Currently there is just https://github.com/kubernetes/kubernetes/blob/master/docs/design/resource-qos.md which is written as a design doc not user documentation.

**Comment by steveperry-53** [comment]
@erictune @heckj Vish and I recently added several docs along thises lines. Example: https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/
