### ISSUE TITLE
Issue with /docs/user-guide/

### ISSUE THREAD

**Issue by applequist** [kubernetes/kubernetes.github.io#1671]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
The link to Docker Volumes is broken: it does not exist anymore.

**Proposed Solution:**
Fix the link to point to https://docs.docker.com/engine/tutorials/dockervolumes/

**Page to Update:**
http://kubernetes.io/...

**Comment by a-mccarthy** [comment]
looks like there's a redirect to the correct page on Docker so this link isn't broken anymore. It's probably still worth updating to point users to the right page to begin with

**Comment by chenopis** [comment]
Updated w/ PR #2531
