### ISSUE TITLE
Page not found Issue with hyperlink on /docs/user-guide/connecting-applications/

### ISSUE THREAD

**Issue by akerstens** [kubernetes/kubernetes.github.io#1674]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
The hyperlink http://kubernetes.io/docs/admin/networking/#how-to-achieve-this in the section "Exposing pods to the cluster" doesn't link to a valid page and generates a 404 error.

**Proposed Solution:**
Either fix the hyperlink or create a page for the existing one.

**Page to Update:**
http://kubernetes.io/docs/user-guide/connecting-applications/
Section: "Exposing pods to the cluster"
Sentence: "You can read more about how we achieve this if you’re curious."

**Comment by chrismarino** [comment]
There is a PR to fix this in the queue. PR #1605

**Comment by chrismarino** [comment]
Fixed. 

http://kubernetes.io/docs/admin/networking/

**Comment by a-mccarthy** [comment]
looks like this was fixed by #1605, closing
