### ISSUE TITLE
Issue with /docs/getting-started-guides/ubuntu/

### ISSUE THREAD

**Issue by bitsoko-services** [kubernetes/kubernetes.github.io#1676]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
When adding the flannel version at 
`...
 export FLANNEL_VERSION=0.5.0
$ export ETCD_VE...`
the build process is failing because of a spell check! when running the script master.sh, the flannel build fails to pull from **https://quay.io/coreos/flannel:v0.5.0-amd64** because the url is missing a 'v'

**Proposed Solution:**
just add v to the pull url

**Page to Update:**
http://kubernetes.io/...

**Comment by castrojo** [comment]
I think this bug is referring to an older version of the page that did flannel installation by hand, this is now automated so the user shouldn't have to do anything manually.

**Comment by a-mccarthy** [comment]
marking as closed, as these pages have just been updated
