### ISSUE TITLE
I wish /docs/ had a way to switch versions of documentation. There are many breaking changes and different features from v1.0 to v1.1 to v1.2

### ISSUE THREAD

**Issue by four43** [kubernetes/kubernetes.github.io#168]
I wish /docs/ had a way to switch versions of documentation. There are many breaking changes and different features from v1.0 to v1.1 to v1.2

(I just used the footer submit thing and it was pretty cool, nice feature there!)

**Comment by johndmulhausen** [comment]
See the docs for 1.1 by visiting/cloning/forking https://github.com/kubernetes/kubernetes.github.io/tree/release-1.1

You can follow the README.md instructions to serve up the old docs on github.io or your local machine.

For v1.0, see the docs/ directory at https://github.com/kubernetes/kubernetes/tree/release-1.0

**Comment by johndmulhausen** [comment]
P.S. glad you liked the footer submit thing! :)

**Comment by four43** [comment]
Thanks for the response! I'll just use the GitHub docs.
