### ISSUE TITLE
Issue with /docs/troubleshooting/

### ISSUE THREAD

**Issue by jonalv** [kubernetes/kubernetes.github.io#1687]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
http://kubernetes.io/docs/user-guide/jobs/work-queue-2/ has a link to https://github.com/kubernetes/kubernetes/tree/master/examples/redis/README.md which gives 404

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/docs/user-guide/jobs/work-queue-2/

**Comment by chenopis** [comment]
Being addressed in PR #2208
