### ISSUE TITLE
Remove unmaintained docs/getting-started-guides/coreos/coreos_multinode_cluster/

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes.github.io#1688]
A user linked to this guide from an issue: http://kubernetes.io/docs/getting-started-guides/coreos/coreos_multinode_cluster/

I believe that guide is unmaintained.  It still specifies k8s 1.1.2.

@philips can we delete?

**Comment by philips** [comment]
Thank you. Yes, this guide was unmaintained and community contributed. I am
OK with this change.
