### ISSUE TITLE
Wanted Doc: Changing the Retention Policy of a PV

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes.github.io#1692]
Given a PV (Which might have been auto-provisioned), a common user Task will be to change the retention Policy from `Delete` to `Retain`.

There should be a doc on how to do this.

Steps are something like:

1. Prereq: I have a PVC whose data I care about
1. How to find the PV from the PVC (preferably in scriptable form)
1. How to update the retention policy, e.g. `kubectl patch pv $PVNAME -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'`

**Comment by erictune** [comment]
I'd like to be able to refer to this from the StatefulSets docs by the 1.5 release data.
Adding 1.5 milestone.

**Comment by erictune** [comment]
This can use the Task template: https://github.com/kubernetes/kubernetes.github.io/blob/master/_includes/templates/task.md

**Comment by erictune** [comment]
@matchstick Do you if there is someone in storage area who could write this doc for 1.5? I'd like to reference it from StatefulSet docs.

**Comment by saad-ali** [comment]
@kubernetes/sig-storage @childsb @jsafrane Can someone help write this ASAP to unblock @erictune?

**Comment by childsb** [comment]
This is possible, but its bad practice in the world of admin/developer roles since the developer shouldn't modify the PV.

i'd argue that if the developer cared about the data s/he would retain the PVC.

**Comment by erictune** [comment]
Is is possible for a user to rename a PVC without risk of loss of the backing PV, if the PV policy is `Delete` and the user cannot delete the PV?

**Comment by jsafrane** [comment]
> Is is possible for a user to rename a PVC without risk of loss of the backing PV, if the PV policy is Delete and the user cannot delete the PV?

No, pv.spec.claimRef would not be valid if PVC is renamed and the PV would be deleted.

**Comment by jsafrane** [comment]
> Can someone help write this ASAP

Done, please review carefully and fix my English
