### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/update-interactive/

### ISSUE THREAD

**Issue by pdqsoftware** [kubernetes/kubernetes.github.io#1697]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The last line of the 'Updating your app' screen reads:

"We see that the deployment is using a stable version of the app (v1). The Rollback was successful."

**Proposed Solution:**
It should read:
"We see that the deployment is using a stable version of the app (**v2**). The Rollback was successful."

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/update-interactive/

**Comment by chenopis** [comment]
Last paragraph of Module 6, step 3 of 3, "(v1)" should be updated to "(v2)".

**Comment by BenHall** [comment]
Thanks for the feedback. This has been resolved.

**Comment by chenopis** [comment]
Thanks @BenHall
