### ISSUE TITLE
Support HTTPS on kubernetes.io

### ISSUE THREAD

**Issue by sthadka** [kubernetes/kubernetes.github.io#1698]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The website kubernetes.io is currently available only under HTTP. My employer is currently blacklisting all HTTP websites.
Would it be possible to provide kubernetes.io via HTTPS as well?

**Proposed Solution:**
Have the kubernetes.io website support both HTTP and HTTPS

**Page to Update:**
http://kubernetes.io/

**Comment by idvoretskyi** [comment]
cc @pwittrock @kubernetes/docs

**Comment by pwittrock** [comment]
cc @devin-donnelly

**Comment by sthadka** [comment]
Turns out the issue was blocking of Github pages IP due to the presence of a malicious website on the same IP. Having HTTPS would not fix this issue, but it would be definitely nice to have.

Please feel free to take this forward or close this issue as you see fit.

Thanks!

**Comment by chenopis** [comment]
@sthadka thanks for the update and info.
