### ISSUE TITLE
volume `subPath` behavior is not documented

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes.github.io#1710]
There's effectively no documentation on this field.

@MikaelCluseau if you have time :)

**Comment by MikaelCluseau** [comment]
I'll have a look when I come back (end of this month) ;)
Le 17 nov. 2016 12:05 PM, Tim Hockin <notifications@github.com> a écrit :There's effectively no documentation on this field.
@MikaelCluseau if you have time :)

**Comment by thockin** [comment]
Merci!

**Comment by MikaelCluseau** [comment]
Ummm it seems like there is actually documentation on this: https://github.com/MikaelCluseau/kubernetes.github.io/blob/master/docs/api-reference/v1/definitions.html#L458

**Comment by thockin** [comment]
Generated API docs != user docs :)

**Comment by MikaelCluseau** [comment]
oh, this kind of doc where I need to have ideas ;)

**Comment by thockin** [comment]
This feature should take a couple paragraphs MAX, in a doc that already
exists..

**Comment by MikaelCluseau** [comment]
On 12/29/2016 05:44 PM, Tim Hockin wrote:
> This feature should take a couple paragraphs MAX, in a doc that already
> exists..

yes yes no problem, no worries :)
