### ISSUE TITLE
Issue with /docs/user-guide/federation/

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/kubernetes.github.io#1712]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The API reference docs link at the end returns a 404.

It links to http://kubernetes.io/federation/docs/api-reference/readme/

**Proposed Solution:**

Fix the link. ( I don't know yet where the actual api-reference for federation is)

**Page to Update:**
http://kubernetes.io/...

**Comment by chenopis** [comment]
This will be fixed by PR #2192
