### ISSUE TITLE
Issue with /docs/user-guide/images/

### ISSUE THREAD

**Issue by kapekost** [kubernetes/kubernetes.github.io#1740]
**This is a broken link** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
top of the page http://kubernetes.io/docs/user-guide/images/ the `docker images` link is now broken

**Proposed Solution:**
maybe needs to point here : https://docs.docker.com/engine/getstarted/step_two/
or here: https://docs.docker.com/engine/reference/commandline/images/

**Page to Update:**
http://kubernetes.io/docs/user-guide/images/

**Comment by chenopis** [comment]
This issue has been resolved.
