### ISSUE TITLE
Many 404's

### ISSUE THREAD

**Issue by gtirloni** [kubernetes/kubernetes.github.io#1749]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

404's spread throughout the docs website (as of 2016-11-21 13:00 UTC)

http://kubernetes.io/doc/admin/authentication/
http://kubernetes.io/docs/admin/api.md
http://kubernetes.io/docs/admin/federation-apiserver.md
http://kubernetes.io/docs/admin/federation-controller-manager.md
http://kubernetes.io/docs/admin/networking
http://kubernetes.io/docs/admin/networking/
http://kubernetes.io/docs/admin/node-problem/cluster-large.md/
http://kubernetes.io/docs/admin/resource-quota/
http://kubernetes.io/docs/admin/sysctls.md
http://kubernetes.io/docs/create-pull-request/
http://kubernetes.io/docs/federation/api-reference/extensions/v1beta1/definitions.html
http://kubernetes.io/docs/federation/api-reference/extensions/v1beta1/operations.html
http://kubernetes.io/docs/federation/api-reference/federation/v1beta1/definitions.html
http://kubernetes.io/docs/federation/api-reference/federation/v1beta1/operations.html
http://kubernetes.io/docs/federation/api-reference/v1/definitions.html
http://kubernetes.io/docs/federation/api-reference/v1/operations.html
http://kubernetes.io/docs/getting-started-guides/docker
http://kubernetes.io/docs/getting-started-guides/kops/kubeadm
http://kubernetes.io/docs/getting-started-guides/photon-controller/docs/user-guide/ingress
http://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app.html
http://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-intro/5-0.html
http://kubernetes.io/docs/tutorials/kubernetes-basics/explore-intro/2-0.html
http://kubernetes.io/docs/user-guide/federation/federated-ingress/docs/user-guide/federation/federated-replicaset.md
http://kubernetes.io/docs/user-guide/federation/federated-ingress/federated-replicasets.md
http://kubernetes.io/docs/user-guide/federation/federated-ingress/federated-services.md
http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaler/
http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/configmap/
http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/image/
http://kubernetes.io/docs/user-guide/jobs/expansions/docs/user-guide/labels/
http://kubernetes.io/docs/user-guide/kubectl/kubectl
http://kubernetes.io/docs/user-guide/kubectl/kubectl_annotate.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_api-versions.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_apply.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_attach.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_autoscale.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_cluster-info.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_completion.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_config.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_convert.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_cordon.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_create.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_delete.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_describe.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_drain.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_edit.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_exec.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_explain.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_expose.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_get.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_label.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_logs.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_namespace.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_options.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_patch.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_port-forward.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_proxy.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_replace.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_rolling-update.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_rollout.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_run.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_scale.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_set.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_taint.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_top.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_uncordon.md
http://kubernetes.io/docs/user-guide/kubectl/kubectl_version.md
http://kubernetes.io/docs/user-guide/load-balancer/Runtime%20feature%20flags%20proposal
http://kubernetes.io/docs/user-guide/network-policy
http://kubernetes.io/docs/user-guide/production-pods/secrets.md
http://kubernetes.io/examples/simple-nginx
http://kubernetes.io/federation/docs/api-reference/readme/

**Comment by chenopis** [comment]
Due to ongoing site restructuring. We will look into adding redirects for the appropriate ones.

**Comment by chenopis** [comment]
@gtirloni Do you have a list of the original docs that linked to these? We need to know where these links originated from to make sure that they get fixed properly. Thx

**Comment by steveperry-53** [comment]
@gtirloni @chenopis I've done some recent work fixing 404s. I'm using Screaming Frog SEO Spider and the [linkchecker](https://linux.die.net/man/1/linkchecker). At this point, both tools indicate that there are no more 404s in the 1.8 doc set.

There are still some some 404s in older versions of the reference docs. I'm planning to either fix or redirect those soon.

I'm going to go ahead and close this, but please reopen if it turns out I haven't caught them all.

**Comment by gtirloni** [comment]
That's great, thank you!

**Comment by chenopis** [comment]
Thanks, @steveperry-53 !
