### ISSUE TITLE
Wanted Doc: Task: Safely Draining a Machine while Respecting Application SLOs 

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes.github.io#1758]
A common admin task will be to drain a machine.  Therefore, we should have task-centric documentation on how to do this.  It can use the Task template: https://github.com/kubernetes/kubernetes.github.io/blob/master/_includes/templates/task.md

Suggested points to cover in the doc:

- use`kubectl drain` on the node you want to remove.
- don't power-down the machine until `kubectl drain` returns.  This ensure that graceful termination is respected and PDB respected.
- overview of what is happening when kubectl drain is run (codoning, eviction)
- link to PDB/eviction docs.
- Bonus: how to drain multiple in parallel.

**Comment by erictune** [comment]
@davidopp

**Comment by davidopp** [comment]
A sample Task PR like
https://github.com/kubernetes/kubernetes.github.io/pull/1774/files
looks somewhat different from the template, so I'm just going to copy that PR and modify it rathern than start with the template.

**Comment by chenopis** [comment]
Resolved by PR #1789
