### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/update-intro/

### ISSUE THREAD

**Issue by folago** [kubernetes/kubernetes.github.io#1766]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The carousel does not work.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/update-intro/#myCarousel

Mac os sierra 10.12.1
Chrome Version 54.0.2840.98 (64-bit)

**Comment by jaredbhatti** [comment]
@steveperry-53 Can you take a look at this?

**Comment by steveperry-53** [comment]
I'm working on this in
[PR 1773](https://github.com/kubernetes/kubernetes.github.io/pull/1773).

**Comment by steveperry-53** [comment]
Fixed.
http://kubernetes.io/docs/tutorials/kubernetes-basics/scale-intro/
http://kubernetes.io/docs/tutorials/kubernetes-basics/update-intro/
