### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-intro/

### ISSUE THREAD

**Issue by jpeterson88** [kubernetes/kubernetes.github.io#1767]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Kubernetes is spelled wrong on the Cluster Diagram image on the cluster-intro tutorial page: 
'Kuberneters Cluster'

**Proposed Solution:**
fix spelling

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-intro/

**Comment by chenopis** [comment]
Has been corrected
