### ISSUE TITLE
Update kubectl drain docs

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes.github.io#1768]
1. change `docs/user-guide/kubectl/kubectl_drain.md` and `docs/man/man1/kubectl-drain.1` text so that they mention that eviction is used when the apiserver supports it.  
2. Link to [http://kubernetes.io/docs/admin/disruptions/]
3. Say that it waits for graceful termination 
4. Say that you should not operate on the machine until the command completes (duh?)
5. push the updated docs to kubernetes/kubernetes.io

**Comment by erictune** [comment]
@pwittrock @ymqytw

**Comment by erictune** [comment]
This is documenting https://github.com/kubernetes/kubernetes/pull/35483

**Comment by janetkuo** [comment]
We run this script to update imported docs, including kubectl docs https://github.com/kubernetes/kubernetes.github.io/blob/master/update-imported-docs.sh

So @ymqytw only needs to update kubectl drain code, and running this script will automatically sync those updates

**Comment by ymqytw** [comment]
Thanks @janetkuo 
Created kubernetes/kubernetes#37321

**Comment by ymqytw** [comment]
@janetkuo I think we can close this, since #37321 has been merged.
