### ISSUE TITLE
I wish / would show the current stable version of kubernetes

### ISSUE THREAD

**Issue by matesito** [kubernetes/kubernetes.github.io#177]
I wish / would show the current stable version of kubernetes

**Comment by johndmulhausen** [comment]
@CreaturesInUnitards What do you think?

**Comment by CreaturesInUnitards** [comment]
Hi John! Sorry for the delay.

I think it’s a good idea to show the current stable version up front — let me throw it to Peter & see what he comes up with. We’re only talking about the home page, yes?

Cheers!

[United Creations]<http://www.unitedcreations.com>

        Scott Simpson
Interactive Services

        p: 206.523.9010 x325

        www.unitedcreations.com<http://www.unitedcreations.com/>

        Passion         [valYou-Passion]


        What's your ValYou? Find out.<http://www.unitedcreations.com/beyoumore>



On Mar 18, 2016, at 10:56 AM, johndmulhausen <notifications@github.com<mailto:notifications@github.com>> wrote:

—

**Comment by johndmulhausen** [comment]
@CreaturesInUnitards my turn to apologize for the delay. Actually; we might want to dovetail this into a greater discussion about doc version selection. We're going to have 1.1, 1.2, and 1.3 docs up live soon.

**Comment by ghodss** [comment]
@johndmulhausen Any update on being able to see latest (preferably "master" branch) docs on the public rendered site?

**Comment by johndmulhausen** [comment]
Sam, we always are showing the master branch on the public/rendered site! :)

Scott, any word here?

**Comment by ghodss** [comment]
Ah - in that case, it makes it really hard to continuously update the site with the latest new features only available in kubernetes master. :) It would be much preferred to freeze the docs and have a dropdown to be able to access latest/master, which could then always reflect the current development version of kube.

**Comment by CreaturesInUnitards** [comment]
@johndmulhausen are we still just talking about a static "current stable version: x.x" somewhere (like, say, in the header)?

**Comment by johndmulhausen** [comment]
It can literally just say: "Version: X.X"

Also, could you mock up a drop down that lets you select versions and
forwards the user to a URL defined in the drop-down? We are going to need
to surface alternate versions of the documentation after all.

**Comment by ghodss** [comment]
Is there a reason this was closed? I don't see a version dropdown on the docs page.

**Comment by ghodss** [comment]
@jaredbhatti

**Comment by DavidTPate** [comment]
@johndmulhausen has there been any progress on this? I don't see a version on the page or any way to view older docs.
