### ISSUE TITLE
from scratch doc: What is $CONTEXT_NAME

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kubernetes.github.io#178]
In the preparing credentials section, a variable called $CONTEXT_NAME is referenced, but there's no explanation of what it means, or what it should be set to, or indeed any other reference to the variable in the document at all.

**Comment by jaredbhatti** [comment]
This is the URL: http://kubernetes.io/docs/getting-started-guides/scratch/#preparing-credentials

**Comment by jaredbhatti** [comment]
There's been a number of fixes to contexts to make it far more understandable: https://github.com/kubernetes/kubernetes/issues/20605
