### ISSUE TITLE
I wish OpenAPI mentioned in docs instead of swagger 1.2

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes.github.io#1780]
In http://kubernetes.io/docs/api/ we mentioned swagger 1.2 however as of 1.5 we will support OpenAPI (swagger 2.0) spec. We should update docs to reflect that.

**Comment by jaredbhatti** [comment]
I believe this is pending with the 1.5 changes that are coming out.

**Comment by mbohlool** [comment]
Excellent, is there any staging area with that change I can look at?

**Comment by mbohlool** [comment]
I don't see any doc changes for OpenAPI. Please link to the change if I am wrong, otherwise we should at lets mention OpenAPI in the docs and later on (1.6 maybe) remove swagger 1.2 references completely.
