### ISSUE TITLE
from scratch doc: Preparing Certs needs to be re-written

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kubernetes.github.io#179]
It is currently wildly unclear what you're attempting to do, and why its important.

A reference to the easyrsa stuff might be prudent, or even better a "This is a complex topic, but this procedure will create a new CA for you, and you put the resulting files HERE and you set these variables to reference those files." as a starting point would be a vast improvement.

This way, those who have more detailed requirements can extend an existing procedure rather than handwaving at 'go figure it out'.

**Comment by jaredbhatti** [comment]
Seems like this has been addressed in a number of improvements to this doc.  If there are still open issues please reopen this issue: https://github.com/kubernetes/kubernetes.github.io/commits/master/docs/getting-started-guides/scratch.md
