### ISSUE TITLE
Issue with /docs/troubleshooting/

### ISSUE THREAD

**Issue by mahavirteraiya** [kubernetes/kubernetes.github.io#1797]
**This is a...** 

- [x] Feature Request
- [x] Bug Report

**Problem:**

How to create kubernetes service with docker image step wise ???? 

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-beta.11", GitCommit:"4b28af1232cc52da453eb4ebe3dc001314a1f99b", GitTreeState:"clean", BuildDate:"2016-09-23T22:53:01Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by chenopis** [comment]
@mahavirteraiya you might find these links helpful:
https://kubernetes.io/docs/user-guide/images/
https://github.com/kubernetes/minikube
https://kubernetes.io/docs/user-guide/docker-cli-to-kubectl/
