### ISSUE TITLE
From scratch doc: Expound on networking in cloud providers

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kubernetes.github.io#180]
The biggest thing needed here is a discussion of the various network paths needed.  Topics to expound on would be the SERVICE_CLUSTER_IP_RANGE and what the differences between docker0 and cbr0 and when and how they relate would be appreciated.

GCE is 'home' for kubernetes, but some more love for the AWS side would be appreciated... If someone wanted to tweak the route tables for the VPC, how would that need to happen?  Or some better discussion of Flannel to build an overlay network, etc.

**Comment by jaredbhatti** [comment]
Added a lot more networking content: http://kubernetes.io/docs/getting-started-guides/scratch/#network
