### ISSUE TITLE
/docs/user-guide/containers/ misses info on how to add/drop capabilities

### ISSUE THREAD

**Issue by vonneudeck** [kubernetes/kubernetes.github.io#1805]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The user-guide about containers does list Linux and Docker capabilities in a nice table. But it does not mention how to actually add/drop the capabilities of containers in Kubernetes. 

**Proposed Solution:**
Add a sentence mentioning the place to declare the capabilities and a short example example to /docs/user-guide/containers/. 
I made PR https://github.com/kubernetes/kubernetes.github.io/pull/1804 for this.

**Page to Update:**
http://kubernetes.io/docs/user-guide/containers/

**Comment by chenopis** [comment]
Being resolve by PR #1804
