### ISSUE TITLE
Generate list of high trafficked pages

### ISSUE THREAD

**Issue by a-mccarthy** [kubernetes/kubernetes.github.io#1813]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

Generate list of high trafficked pages (from Google Analytics) to help prioritization and place list somewhere contributors can access it. We'll need to update it after the site is completely revamped. 

@jaredbhatti

**Comment by jaredbhatti** [comment]
Top 100 pages from the site: https://docs.google.com/spreadsheets/d/1pXfrCs2YlYjoFK5Z0mUmgSx_stMryhI-OmtGU8GXGN4/edit#gid=2130667426&vpid=A1

**Comment by chenopis** [comment]
Thanks @jaredbhatti
