### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by marcote** [kubernetes/kubernetes.github.io#1815]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Sorry, we hit a problem with the connection.                                                        
Your internet connection may have dropped.                                                          
                                                                                                    
Please refresh and try again.                                                                       

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

Tried Chrome latest and Safari.

**Comment by BenHall** [comment]
Sorry you've encountered the error. This should now have been resolved. Please retry.

**Comment by chenopis** [comment]
Seems to be working for me. @marcote if this still a problem w/ you, let me know, I can reopen the issue.
