### ISSUE TITLE
Example for HPA is not easily accessible

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes.github.io#182]
Main HPA documentation is avaiable via Reference > Glossary > Horizontal Pod Autoscaling. That's ok. However, AFAIU it's impossible to find example usage other than through Glossary and once I click it in the "Further reading section" I see no menu on the left. See [here](http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/).

@piosz @mwielgus

**Comment by yissachar** [comment]
I don't think this is the case any more. There is a user guide for HPA available at http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/walkthrough/.

Guides > Workload Deployment and Management > Horizontal Pod Autoscaling
