### ISSUE TITLE
Doc missing for finalizername

### ISSUE THREAD

**Issue by ymqytw** [kubernetes/kubernetes.github.io#1829]
**Problem:**
Doc missing for finalizername

**Page to Update:**
http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_finalizername

cc: @caesarxuchao

**Comment by caesarxuchao** [comment]
@derekwaynecarr can we remove the [FinalizerName type](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L3106)? It's only used by the NamespaceSpec. [ObjectMeta.Finalizers](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L205) are defined as `[]string`. I think removing `FianlizerName` is backward compatible.

**Comment by derekwaynecarr** [comment]
@caesarxuchao what was the reason that you used `[]string` for `ObjectMeta`?  Originally, I had thought this was consistent with what was done for `api.ResourceName`?

**Comment by caesarxuchao** [comment]
@derekwaynecarr I don't remember why we did []string. I can't see any disadvantage of using `FinalizerName`, so probably I'll just change them to use `FinalizerName`/

**Comment by caesarxuchao** [comment]
Looks like our doc generator has problems. k8s.io doc doesn't show comments even if the type is properly commented. As another example, the `Capability` type is [commented](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L1335-L1336), but [k8s.io](http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_capability) doesn't show the comments either.
