### ISSUE TITLE
HPA should be linked from user-guides for Deployment and RC

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes.github.io#184]
I think it'll help users find out about this feature.

User guides:
http://kubernetes.io/docs/user-guide/managing-deployments/
http://kubernetes.io/docs/user-guide/deploying-applications/

@mwielgus @bgrant0607

**Comment by johndmulhausen** [comment]
@fgrzadkowski  Any reason why you can't make this change in a PR? It would probably take as long as it did to file this bug? :)

**Comment by bgrant0607** [comment]
cc @janetkuo @pwittrock

**Comment by bgrant0607** [comment]
We're adding content about Deployment to the thorough walkthrough now.

**Comment by janetkuo** [comment]
Managing deployments doc already links to hpa --> http://kubernetes.io/docs/user-guide/managing-deployments/#scaling-your-application

Do you think it's observable enough for the users?
