### ISSUE TITLE
Issue with /docs/user-guide/ingress/

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes.github.io#1843]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

Links in the Terminology section point to (obsolete?) `release-1.0` documents.

**Proposed Solution:**

Point them at master.

**Page to Update:**
http://kubernetes.io/docs/user-guide/ingress/

**Comment by chenopis** [comment]
@porridge thanks!

Addressed in PR #2207
