### ISSUE TITLE
Add Trademark footer

### ISSUE THREAD

**Issue by caniszczyk** [kubernetes/kubernetes.github.io#1846]
Add trademark footer to properly indicate trademark guidelines around kubernetes.

Something like: 

> Copyright © 2016 The Linux Foundation®. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our Trademark Usage page: https://www.linuxfoundation.org/trademark-usage

**Comment by jeffmendoza** [comment]
Do we want to remove "© 2016 The Kubernetes Authors | Distributed under CC BY 4.0" or add to it?

**Comment by caniszczyk** [comment]
I'd add to it. I'd also specify that "Documentation Distributed under CC BY 4.0"

Other than that, LGTM!
