### ISSUE TITLE
Rolling update user-guide should mention the problem updating RC with HPA

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes.github.io#185]
Rolling update for RC doesn't work (see http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaler/ section "Autoscaling during rolling update"). It might make sense to mention this in the (user guide for rolling update)[http://kubernetes.io/docs/user-guide/rolling-updates/]

@mwielgus

**Comment by bgrant0607** [comment]
cc @janetkuo @pwittrock

**Comment by jaredbhatti** [comment]
Fixed.  Added a link. https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/horizontal-pod-autoscaling/index.md
