### ISSUE TITLE
Issue with /docs/getting-started-guides/scratch/

### ISSUE THREAD

**Issue by githubwithme** [kubernetes/kubernetes.github.io#1850]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
All kubernetes components can be container?

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by githubwithme** [comment]
All kubernetes components can be container?

**Comment by chenopis** [comment]
This area is only for submitting problems w/ the documentation site. For general questions, you might want to use the #kubernetes-users Slack channel: https://kubernetes.slack.com/messages/kubernetes-users/
