### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/update-interactive/

### ISSUE THREAD

**Issue by adrrrrrrrian** [kubernetes/kubernetes.github.io#1859]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
After rolling update to V10 and then rolling back, should the deployment be running on version 2 instead of version 3? 

**Proposed Solution:**
Just the last paragraph, change the "v2" to "v1".

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/update-interactive/

**Comment by BenHall** [comment]
Thanks for the feedback. This has been fixed.

**Comment by chenopis** [comment]
This is a duplicate issue and has been resolved.
