### ISSUE TITLE
Links to some user guides redirects to github

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes.github.io#186]
Link to "Guides > Testing & Monitoring > Simulating Large Test Workload" redirects to github page with examples in 1.2 branch. Is this intentional?

**Comment by fgrzadkowski** [comment]
Another example:
"Guides > Testing & Monitoring > Using Explorer to Examine the Runtime Environment"

**Comment by johndmulhausen** [comment]
Yes; examples/ stays in the main repo (for now).
