### ISSUE TITLE
Add additional information for Helm / Kompose / Third-party tools

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kubernetes.github.io#1868]
**This is a...** 
- [X] Feature Request
- [ ] Bug Report

**Problem:**

Add additional documentation for Helm + other Kubernetes third-party tools in order to merge https://github.com/kubernetes/kubernetes.github.io/pull/1607

**Proposed Solution:**

Create additional documentation for projects such as Helm to be added to the tools page in a major update.

**Page to Update:**
http://kubernetes.io/docs/tools/

**Pings:**
@devin-donnelly

**Comment by cdrage** [comment]
ping @kubernetes/docs @devin-donnelly @pwittrock

**Comment by cdrage** [comment]
@kubernetes/sig-docs-misc

**Comment by chenopis** [comment]
#1607 has been merged
