### ISSUE TITLE
I wish /docs/user-guide/managing-deployments/ touched on deployment-manager/helm, the Deployment kind, and how (if at all) they're related

### ISSUE THREAD

**Issue by crimeminister** [kubernetes/kubernetes.github.io#188]
I wish /docs/user-guide/managing-deployments/ discussed [helm](https://github.com/kubernetes/helm), especially if it's liable to become the preferred way to manage deployments in the future.

**Comment by bgrant0607** [comment]
I agree it's worth mentioning Helm, though it's not the only solution in that space.
cc @janetkuo @pwittrock @jackgr

**Comment by jaredbhatti** [comment]
I could use some tech help on actually creating the content necessary.  This issues isn't actionable until I get that.
