### ISSUE TITLE
Issue with /docs/getting-started-guides/vsphere/

### ISSUE THREAD

**Issue by gwl7810** [kubernetes/kubernetes.github.io#1886]
**thank for the great work! it work like a charm ,but how to add a node to the existed cluster?** 

- [ x] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by chenopis** [comment]
@gwl7810 thank you for your feedback. Please see https://kubernetes.io/docs/admin/cluster-management/#resizing-a-cluster
