### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/update-interactive/

### ISSUE THREAD

**Issue by araj7** [kubernetes/kubernetes.github.io#1898]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The last paragraph says:
We see that the deployment is using a stable version of the app (v1). The Rollback was successful.
I think there is a typo. Shouldn't it be saying v2.
**Proposed Solution:**
We see that the deployment is using a stable version of the app (v2). The Rollback was successful.

**Page to Update:**
![screen shot 2016-12-08 at 4 33 02 pm](https://cloud.githubusercontent.com/assets/17076113/21030485/5f25f27e-bd64-11e6-932c-532d621c76ca.png)

http://kubernetes.io/docs/tutorials/kubernetes-basics/update-interactive/
Step 3 of 3

**Comment by BenHall** [comment]
Thanks for the feedback. This has been fixed.

**Comment by chenopis** [comment]
This was a duplicate issue and has been resolved. Thx @BenHall
