### ISSUE TITLE
I wish /docs/user-guide/services/ would have better images because they seem to be cut in half

### ISSUE THREAD

**Issue by aanm** [kubernetes/kubernetes.github.io#190]
I wish /docs/user-guide/services/ would have better images because they seem to be cut in half

**Comment by johndmulhausen** [comment]
Fixed in https://github.com/kubernetes/kubernetes.github.io/commit/55020cc414e356a310bee6e71c009e1ab5d9e07d

**Comment by aanm** [comment]
Awesome, thanks!
