### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/update-interactive/

### ISSUE THREAD

**Issue by CianciuStyles** [kubernetes/kubernetes.github.io#1906]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
In the last paragraph of the Step 3, it says that "We see that the deployment is using a stable version of the app (v1). The Rollback was successful.", while the stable version currently running is v2

**Proposed Solution:**
Change v1 into v2 in the last paragraph of the Step 3

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/update-interactive/

**Comment by chenopis** [comment]
Duplicate issue; same as #1697, https://github.com/kubernetes/kubernetes.github.io/issues/1697#event-918036436
