### ISSUE TITLE
Wrong HTML title tag and first header

### ISSUE THREAD

**Issue by seeekr** [kubernetes/kubernetes.github.io#1923]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Searched for "kubernetes readiness probe" on google, noticed title of first result was "Kubernetes - Persistent Storage", but clicked on it anyway since there was a fitting subheading with relevant-seeming info, as well as a potentially-matching URL: http://kubernetes.io/docs/user-guide/production-pods/

**Proposed Solution:**
Title that particular page something like "Production Pods" or "Working with containers in production" (its link name in the menu on the left).

**Page to Update:**
http://kubernetes.io/docs/user-guide/production-pods/ (as well as many others)

---
I would gladly send a PR to fix the issue, if someone kindly pointed me towards where such a change may be done. I'm assuming there's some kind of config file or text file from which the menu item titles are drawn, which could be used to fix this. Not sure if there's a more appropriate way than to use those titles as both page title and for auto-generating an initial heading.

**Comment by enisoc** [comment]
I don't know where this went wrong, but in case it helps you find the problem: The titles are supposed to come from the YAML files in [_data](https://github.com/kubernetes/kubernetes.github.io/tree/master/_data). All I know is that they were working properly in the rendered previews for individual PRs before the release-1.5 branch was merged.

**Comment by enisoc** [comment]
It looks like this should be fixed by https://github.com/kubernetes/kubernetes.github.io/pull/1942. It sounds like the problem was version skew in the Jekyll plugins we use for our previews vs. what GitHub Pages actually uses to render the final site.

**Comment by seeekr** [comment]
Thanks, I'll follow the referenced PR and see if that fixes it! Would be lovely!

**Comment by jaredbhatti** [comment]
Should be updated.  Github pages/jekyll issue that's not been resolved.
