### ISSUE TITLE
Swagger UI 404 page is thrashing

### ISSUE THREAD

**Issue by stillinbeta** [kubernetes/kubernetes.github.io#1924]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The 404 page for Swagger UI is constantly flashing, reloading itself. It also does it's best to peg the CPU. I mentioned this to several of my colleagues and we can reproduce it on multiple internet connections, browsers, locations, and operating sytems, including:

![screenshot 2016-12-12 11 43 45](https://cloud.githubusercontent.com/assets/523632/21108044/af5f576c-c061-11e6-80b7-b2dd32692e42.png)

* Firefox 50.0.2 on OSX 10.11.6
* Chrome  55.0.2883.75 on OS X 10.11.6
* Chrome 55.0.2883.75 on Arch Linux
* Chrome 54.0.2840.98 on OSX 10.01
* Chrome 44.0.2403.633 on Android 6.01
* Safari 9.1.2 on OSX 10.11.6

**Proposed Solution:**

Front-end development isn't really my forte, but this is clearly an issue specific to this page. Not all 404 pages reproduce this issue. Probably the short-term solution is to remove the links to the Swagger API page from the sidebar in the documentation.

**Page to Update:**
http://kubernetes.io/kubernetes/third_party/swagger-ui/

**Comment by pwittrock** [comment]
Can we kill this page and use the new api docs instead?
