### ISSUE TITLE
Need to document implications of changing a selector for a Deployment

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes.github.io#1938]
Especially for non-overlapping changes (new selectors cannot match old replica sets)

@kubernetes/sig-apps

**Comment by krmayankk** [comment]
@kargakis Is this just documentation or there are other bugs which plan to handle this situation ? What about when selector is changing, deleting the old pods/rs optionally ? We ran into this accidentally in our deployment, and we saw all rs and pods were orphaned.

**Comment by kargakis** [comment]
@krmayankk this is just about documenting the effects of changing the selector (yes, you may end up orphaning your replica sets if the new selector doesn't overlap with the old). Please open an issue in the main kubernetes repo if you wish to discuss new functionality.

**Comment by kargakis** [comment]
@chenopis any plans on working on this one? I can take it over since I am planning on doing some docs this week.

**Comment by chenopis** [comment]
@kargakis Yeah, if you have time to work on this, that would be great. Thanks!
