### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes.github.io#194]
For example, http://kubernetes.io/docs/user-guide/managing-deployments/ contains a number of broken links, mostly referenced to kubectl. 

Is there a way to detect all broken links?

@kubernetes/docs @pwittrock

**Comment by pwittrock** [comment]
Yup. I'll reopen #102 and pick this up again.

**Comment by johndmulhausen** [comment]
Fixed, thanks!
