### ISSUE TITLE
Issue with /docs/getting-started-guides/minikube/ - 404 on multiple links

### ISSUE THREAD

**Issue by msterin** [kubernetes/kubernetes.github.io#1944]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Multiple links on the page generate 404 Not Found
Examples: 
http://kubernetes.io/docs/getting-started-guides/minikube/CONTRIBUTING/ (redirected from http://kubernetes.io/docs/getting-started-guides/minikube/CONTRIBUTING.md) 
http://kubernetes.io/docs/getting-started-guides/minikube/ROADMAP/  (redirected from 
http://kubernetes.io/docs/getting-started-guides/minikube/ROADMAP.md) 

**Proposed Solution:**
fix the links

**Page to Update:**
http://kubernetes.io/docs/getting-started-guides/minikube/#quickstart

**Comment by chenopis** [comment]
Here is the full list of broken links on https://kubernetes.io/docs/getting-started-guides/minikube/#quickstart

xhyve driver
https://kubernetes.io/docs/getting-started-guides/minikube/DRIVERS.md#xhyve-driver

kvm (driver installation)
https://kubernetes.io/docs/getting-started-guides/minikube/DRIVERS.md#kvm-driver

xhyve (driver installation)
https://kubernetes.io/docs/getting-started-guides/minikube/DRIVERS.md#xhyve-driver

See DRIVERS
https://kubernetes.io/docs/getting-started-guides/minikube/DRIVERS.md

docker-env command
https://kubernetes.io/docs/getting-started-guides/minikube/docs/minikube_docker-env.md

minikube start
https://kubernetes.io/docs/getting-started-guides/minikube/docs/minikube_start.md

minikube stop
https://kubernetes.io/docs/getting-started-guides/minikube/docs/minikube_stop.md

minikube delete
https://kubernetes.io/docs/getting-started-guides/minikube/docs/minikube_delete.md

full CLI docs
https://kubernetes.io/docs/getting-started-guides/minikube/docs/minikube.md
