### ISSUE TITLE
Issue with /docs/admin/federation/kubefed/

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes.github.io#1948]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:** http://kubernetes.io/docs/admin/federation/kubefed/#choosing-a-host-cluster the output seems to be too long and I can't scroll to see the full output. This doc also needs a home.

**Proposed Solution:** Make the output shorter. Add left nav for it, and link it in tools page  http://kubernetes.io/docs/tools/

**Page to Update:**
http://kubernetes.io/docs/admin/federation/kubefed/

**Comment by jaredbhatti** [comment]
Fixed.
