### ISSUE TITLE
Issue with /docs/user-guide/kubectl/: "See Also" returns 404 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes.github.io#1949]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
1. All `see also` links under http://kubernetes.io/docs/user-guide/kubectl/ are broken (they link to kubectl_xxx.md and should be redirected to /docs/... but is redirected to docs/...)
2. Many new commands (such as `kubectl cp`) aren't included in the left nav; some obsolete commands (such as `kubectl namespaces`) are removed, but not their left nav  

cc @kubernetes/sig-docs 

**Proposed Solution:**
Fix left nav and those links 

**Page to Update:**
http://kubernetes.io/docs/user-guide/kubectl/

**Comment by steveperry-53** [comment]
The links are working now.
