### ISSUE TITLE
Ubuntu installation document not available

### ISSUE THREAD

**Issue by cdz620** [kubernetes/kubernetes.github.io#1952]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Ubuntu installation is not available.
http://kubernetes.io/docs/getting-started-guides/ubuntu/.

response:
```
Edit This Page
404 Error!

Sorry, this page was not found. :(
```

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by castrojo** [comment]
I've fixed this, it's in this PR: https://github.com/kubernetes/kubernetes.github.io/pull/1932

**Comment by a-mccarthy** [comment]
looks like this page was just fixed :)
