### ISSUE TITLE
Issue with /docs/troubleshooting/

### ISSUE THREAD

**Issue by mkheck** [kubernetes/kubernetes.github.io#1988]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Documentation bug: _http://kubernetes.io/docs/getting-started-guides/minikube/DRIVERS/#xhyve-driver_ page returns a 404. This is linked to from **xhyve-driver** link in Requirements section under OS X on _http://kubernetes.io/docs/getting-started-guides/minikube/_ page. Just wanted to let someone know.

**Proposed Solution:**
Point to correct destination page. Searching the site doesn't produce the correct page or I would have submitted a PR, sorry. 😞 

**Page to Update:**
http://kubernetes.io/docs/getting-started-guides/minikube/

**Comment by mkheck** [comment]
Found another similar-but-slightly-different dead link: In section **Quickstart**, for link _driver installation_ next to **xhyve**. Destination URL is _http://kubernetes.io/docs/getting-started-guides/minikube/DRIVERS.md#xhyve-driver_.

**Comment by bentleycook** [comment]
+1

**Comment by a-mccarthy** [comment]
hey! it looks like you should have been pointed to https://github.com/kubernetes/minikube/blob/master/DRIVERS.md. Thanks for reporting the dead links, #2182 has a few more links to update on that page, so i'm going to close this to make sure all the links are updated
