### ISSUE TITLE
CSS: Styles are huge, generally

### ISSUE THREAD

**Issue by johndmulhausen** [kubernetes/kubernetes.github.io#2]
The non-doc CSS styles (header/footer stuff) seems very large and looks best zoomed out to about 75% in the browser.

The docs CSS styles are also big but not quite as dire, IMO; that said, they look good at 75% too.

**Comment by johndmulhausen** [comment]
CC @CreaturesInUnitards

**Comment by CreaturesInUnitards** [comment]
ok, trimmed back quite a bit on header/footer

**Comment by CreaturesInUnitards** [comment]
@johndmulhausen  LGTM, but I'm re-assigning to you because:

1. You still might have specific areas that you want ensmallened; and
2. I can tell that you're not busy. At all.
