### ISSUE TITLE
Guides work with rcs rather than deployments

### ISSUE THREAD

**Issue by sah** [kubernetes/kubernetes.github.io#200]
Guides including http://kubernetes.io/docs/hellonode/ and http://kubernetes.io/docs/getting-started-guides/docker/ show commands for working with replication controllers. These no longer work as expected, because `kubectl run` creates a deployment. Docs need to be updated to describe the new stable 1.2.0 release.

**Comment by bgrant0607** [comment]
cc @janetkuo @pwittrock

**Comment by janetkuo** [comment]
Merged #262; all docs referencing `kubectl run` are talking about deployments (instead of rc) now.
