### ISSUE TITLE
Issue (typos) with /docs/user-guide/thirdpartyresources/

### ISSUE THREAD

**Issue by akanso** [kubernetes/kubernetes.github.io#2013]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The page for the user guide on third party resources has a few typos:
- When you user create a new...
- For example, if a save the following...

**Proposed Solution:**
Proof reading for the documentation

**Page to Update:**
http://kubernetes.io/docs/user-guide/thirdpartyresources/

**Comment by a-mccarthy** [comment]
looks like this was fixed as part of #2020, closing :)
