### ISSUE TITLE
404 page is a weirdly incomplete "Report a Security Vulnerability" page

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes.github.io#2018]
If you go to a path on kubernetes.io that doesn't exist (e.g. http://kubernetes.io/docs/foo/bar/), you get this weird page with the title "Report a Security Vulnerability", but that isn't actually the proper page for that. It only offers options to create the missing page or to edit the missing page. It's a fairly weird mishmash of things to have on a 404 page.

<img width="1347" alt="screen shot 2016-12-21 at 3 21 08 pm" src="https://cloud.githubusercontent.com/assets/7085343/21404860/21b10280-c791-11e6-9d02-71a8b1d573d3.png">

**Comment by elouanKeryell-Even** [comment]
Seems to be fixed, I'd be interested in knowing how

**Comment by jaredbhatti** [comment]
Marking Closed.
