### ISSUE TITLE
I wish /docs/user-guide/kubectl/kubectl_create/kubectl_create_secret/ existed...there's a link to it

### ISSUE THREAD

**Issue by joltup** [kubernetes/kubernetes.github.io#202]
I wish /docs/user-guide/kubectl/kubectl_create/kubectl_create_secret/ this page existed...there's a link to it

**Comment by johndmulhausen** [comment]
Can't repro: https://github.com/kubernetes/kubernetes.github.io/search?utf8=%E2%9C%93&q=kubectl_create_secret
