### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/update-interactive/

### ISSUE THREAD

**Issue by andrewpai** [kubernetes/kubernetes.github.io#2028]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Typo names v1 instead of v2.

**Proposed Solution:**
On step 3 of http://kubernetes.io/docs/tutorials/kubernetes-basics/update-interactive/, the result of the rollback is v2 not v1.

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/update-interactive/

**Comment by a-mccarthy** [comment]
hi! it looks like this has been fixed #1898
