### ISSUE TITLE
Issue with /docs/user-guide/horizontal-pod-autoscaling/image/

### ISSUE THREAD

**Issue by tengqm** [kubernetes/kubernetes.github.io#2034]
**This is a Bug Report

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The image link to hpa_example is broken.

**Proposed Solution:**
Rework the page so that people know how to create their own image, or remove the link from the walkthrough page: http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/walkthrough/

**Page to Update:**
http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/walkthrough/
http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/walkthrough/image

**Comment by chenopis** [comment]
Fixed in PR #2532
