### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by dpaks** [kubernetes/kubernetes.github.io#2037]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
The _START SCENARIO_  button is overlapped by the Intel footer rendering the button unusable.

**Proposed Solution:**
Adjust the button relative to the other content of the page.

**Page to Update:**
http://kubernetes.io/...

**Comment by a-mccarthy** [comment]
duplicate of #2101 and #2050. closing this issue. Please follow issue under #2050
