### ISSUE TITLE
Issue with /docs/getting-started-guides/ubuntu/

### ISSUE THREAD

**Issue by liuyanfu** [kubernetes/kubernetes.github.io#2041]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
I opend the doc of getting-started-guides for ubuntu, but the web showed a 404 error.

Following this: http://kubernetes.io/docs/getting-started-guides/ubuntu/

**Proposed Solution:**
pls chk the url and web link is alright.

**Page to Update:**
http://kubernetes.io/...
NA

all

NA

**Comment by a-mccarthy** [comment]
thanks for reporting, looks like this page was just fixed :)
