### ISSUE TITLE
Issue with /docs/tutorials/stateful-application/basic-stateful-set/

### ISSUE THREAD

**Issue by weidagang** [kubernetes/kubernetes.github.io#2044]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The title of this page is wrong, should be "StatefulSet Basics" instead of "Running ZooKeeper, A CP Distributed System". But when I click "Edit this page", it links to .../zookeeper.md. I couldn't figure out how to fix.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/

**Comment by elouanKeryell-Even** [comment]
Seems to be fixed, I'd be interested in knowing how

**Comment by enisoc** [comment]
The title issue was affecting many pages, not just this one. For reference, see https://github.com/kubernetes/kubernetes.github.io/issues/1959 and https://github.com/kubernetes/kubernetes.github.io/issues/1923.

**Comment by a-mccarthy** [comment]
it looks like this was fixed by #1994 and #1942 when changes were made to how pages were titled
