### ISSUE TITLE
Remove known-issues page

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes.github.io#205]
This page is woefully out of date:
docs/user-guide/known-issues/

We should move the content to the 1.0 release notes and delete the page.

cc @david-mcmahon

**Comment by david-mcmahon** [comment]
https://github.com/kubernetes/kubernetes/releases/tag/v1.0.1 already contains this info.  I'll delete the file.

**Comment by david-mcmahon** [comment]
cc @johndmulhausen,  I can't see how to delete a file using this new edit-in-place interface. Maybe it's a permission issue?

**Comment by david-mcmahon** [comment]
These items are all in flight - https://github.com/kubernetes/kubernetes.github.io/pull/220.
But I have no power to assign or merge anything.

**Comment by johndmulhausen** [comment]
Nice work, David. :)
