### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by voyalab** [kubernetes/kubernetes.github.io#2050]
Browser: Google Chrome with 100% zoom. 
OS: Ubuntu 16.04

**Problem:**
Unable to start scenario for Module 2[/docs/tutorials/kubernetes-basics/deploy-interactive/]. Some texts are overlapping with start scenario button. 

**Proposed Solution:**
Please check why the text is overlapping with start scenario button. 

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/

**Comment by BenHall** [comment]
Sorry, I had missed these. I'll look at this tomorrow.

**Comment by BenHall** [comment]
This has been resolved. The start scenario button should always clickable. Thank you for your feedback and help.
