### ISSUE TITLE
Fix time "Issue with /docs/user-guide/pods/init-container/"

### ISSUE THREAD

**Issue by bondareko** [kubernetes/kubernetes.github.io#2061]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by a-mccarthy** [comment]
@bondareko, can you provide a litte more information on what you'd like to see changed on http://kubernetes.io/docs/user-guide/pods/init-container/?
