### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by gokul2993** [kubernetes/kubernetes.github.io#2065]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
Unable to view Minicube CLI. It just displaying black screen

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment]
Thanks for reporting the issue. I've been unable to reproduce the issue. It would be great if you could let me know your browser / OS, or retry and see if it's still a problem.

**Comment by BenHall** [comment]
Thanks for reporting the bug. @zacharysarah I believe this can be closed.
