### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by werowe** [kubernetes/kubernetes.github.io#2084]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**

On this page http://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/
Clicking on Start Scenario does not start MiniKube in the browser.  Instead it does to this Intel page with just articles http://www.intel.com/content/www/us/en/cloud-for-all/cloud-for-all.html?linkId=18217494

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment]
Sorry about that. Duplicate of #2050

**Comment by a-mccarthy** [comment]
Closing this because it is a duplicate. Please follow this issue in #2050
