### ISSUE TITLE
Issue with /docs/getting-started-guides/minikube/DRIVERS/

### ISSUE THREAD

**Issue by werowe** [kubernetes/kubernetes.github.io#2085]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

from http://kubernetes.io/docs/getting-started-guides/minikube/#installation
Broken link to http://kubernetes.io/docs/getting-started-guides/minikube/DRIVERS/

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by a-mccarthy** [comment]
duplicate of #2182. closing
