### ISSUE TITLE
Issue with /docs/getting-started-guides/centos/centos_manual_config/

### ISSUE THREAD

**Issue by bostone** [kubernetes/kubernetes.github.io#2086]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
After replicating all steps using 2 CentOS 7 VM there are 2 errors:

1. Executing "etcdctl mkdir /kube-centos/network" issues the following error: "etcd cluster has no published client endpoints. Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:2379,http://127.0.0.1:4001). Error:  client: no endpoints available"
2. Unable to start flanneld service. It fails with this error: Unable to start service flanneld: Job for flanneld.service failed because a timeout was exceeded. See "systemctl status flanneld.service" and "journalctl -xe" for details. Checking specified files shows the same error: "Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured"

**Proposed Solution:**

1. Adding "--no-sync" to command removed the message. The key is created
2. I am not able to come up with any solutions 

**Page to Update:**
http://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/

Kubernetes v1.3.0

I run all the steps outlined in the manual except I don't add IPs into /etc/hosts but use fully qualified (pingable) hostnames instead. I did try to use IPs instead of hostnames to the same effect

**Comment by bostone** [comment]
Ok, I think I have a solution to my \#2:
There is a mismatch between flanneld.service and /etc/sysconfig/flanneld configuration (which wasn't there before). You need to change keys in the flanneld configuration file to match these in flanneld.service. Namely - change FLANNEL_ETCD to FLANNEL_ETCD_ENDPOINTS and FLANNEL_ETCD_KEY to FLANNEL_ETCD_PREFIX in /etc/sysconfig/flanneld. After that flanneld.service starts with no problem on both master and minion(s) nodes

**Comment by a-mccarthy** [comment]
It looks like this was completed by #2133, closing
