### ISSUE TITLE
Issue with /docs/getting-started-guides/minikube/

### ISSUE THREAD

**Issue by riturajtiwari** [kubernetes/kubernetes.github.io#2093]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Minikube quickstart documentation has an issue. The URL for echo server container is incorrect. The suggested commandline:
`$ kubectl run hello-minikube --image=gcr.io/google_containers/echoserver:1.4 --port=8080`

leads to error:
`Error from server: the server could not find the requested resource`

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by ipedrazas** [comment]
This command line seems to work fine. There was an [issue](https://github.com/kubernetes/contrib/issues/1097) but it seems it's fixed now.

**Comment by riturajtiwari** [comment]
Agreed. This is no longer an issue.
