### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by keuller** [kubernetes/kubernetes.github.io#2101]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
We can't click START button and start the module

**Proposed Solution:**
Corret advertise on footer page.

**Page to Update:**
http://kubernetes.io/...

**Comment by a-mccarthy** [comment]
duplicate of #2037 and #2050. closing this issue. Please follow issue under #2050
