### ISSUE TITLE
Minikube seems to have issue with emptyDir directory rights

### ISSUE THREAD

**Issue by nvnobelen** [kubernetes/kubernetes.github.io#2107]
**This is a bug report** 

**Problem:**

Minikube 0.14.0 seems to have a problem writing to disk with emptyDir, which disappears when the **proposed solution** is applied.

**Proposed Solution:**

Update the image with:

- chmod o+x /var/lib/kubelet/pods 
- cd pods ; chmod -R 0755 .

**Comment by a-mccarthy** [comment]
hi @nvnobelen, is there a page or example this should be added to?

**Comment by nvnobelen** [comment]
No page, it should just be verified in the minikube code and possibly added in the initialization scripts so that this emptyDir rights issue disappears.

**Comment by a-mccarthy** [comment]
This sounds like it is an issue with minikube not documentation. @nvnobelen, the best place for this issue is probably in the minikube repo https://github.com/kubernetes/minikube. Closing the issue because there isn't any documentation changes needed.

**Comment by nvnobelen** [comment]
Ah, sorry, I see what I have done: incorrect click when creating the issue.
