### ISSUE TITLE
Issue with /docs/ (Installation & upgrade) for 1.6 and etcd3. 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes.github.io#2172]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
Outline the upgrade and data migration process for etcd3 in 1.6. 

**Proposed Solution:**
Write + review the docs. 

**Page to Update:**
Installation and upgrades.
http://kubernetes.io/...

/cc @kubernetes/sig-scalability-misc @justinsb 

xref: https://github.com/kubernetes/kubernetes/pull/36229

**Comment by lavalamp** [comment]
@mml @wojtek-t

**Comment by hongchaodeng** [comment]
@timothysc 
We can own and update https://kubernetes.io/docs/admin/etcd/ together.
Sorry I missed the sig scale this morning. We probably need to also discuss deprecation of etcd2.

@xiang90 @calebamiles

**Comment by wojtek-t** [comment]
This should have 1.6 milestone (though there doesn't seem to be 1.6 milestone in this repo).

**Comment by timothysc** [comment]
@xiang90 Could you paste a link to your documentation here?

**Comment by xiang90** [comment]
We are working on the generic etcdv3 specific doc here: 

https://docs.google.com/document/d/16ES7N51Xj8r1P5ITan3gPRvwMzoavvX9TqoN8IpEOU8/edit?usp=sharing

Any feedback is welcomed. We hope to get this doc finalized early Feb.

Thanks.

**Comment by grodrigues3** [comment]
ping @kubernetes/sig-docs-maintainers etcdv3 docs is waiting for feedback.

**Comment by timothysc** [comment]
@wojtek-t @mml So I'm flummoxed on where to update docs here... 

A bunch of docs need to be cleaned up, either they are owned by distros or are not directly relevant.

Then the main docs on cluster upgrade only really pertains towards the salt/GCE setup and don't even reference the details under the hood.  

Any advise on where we should update?   New upgrade page?  
/cc @hongchaodeng @justinsb

**Comment by wojtek-t** [comment]
I think we need a separate/new page for the process of upgrade itself.
But if you are aware of any docs that might no longer be valid, can you post the links to them here?
