### ISSUE TITLE
Link on GUI installation is incorrect on getting-started-guides/scratch

### ISSUE THREAD

**Issue by rutsky** [kubernetes/kubernetes.github.io#218]
This link is 404 now: https://github.com/kubernetes/kubernetes.github.io/blame/master/docs/getting-started-guides/scratch.md#L809 (http://releases.k8s.io/release-1.2/cluster/addons/kube-ui/)

Looks like kube-ui was deprecated and removed from the repository. What should be used instead? Dashboard?

**Comment by johndmulhausen** [comment]
I'm not sure, honestly :( Marking for tech review.

**Comment by jaredbhatti** [comment]
Dashboard is the new Kube-ui.  Sorry for the lack of communication.
