### ISSUE TITLE
Issue with /docs/tutorials/stateless-application/hello-minikube/

### ISSUE THREAD

**Issue by clarenceb** [kubernetes/kubernetes.github.io#2181]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

In the **Create your Node.js application** section:

1. Clicking `server.js` link results in a HTTP 404 (not found)
2. `server.js` snippet is missing module import: `var http = require('http');` so it's invalid code

**Proposed Solution:**

* Fix broken link to server.js
* Add `var http = require('http');` to top of server.js snippet.

**Page to Update:**

http://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/

**Comment by steveperry-53** [comment]
I'll fix this.
