### ISSUE TITLE
I wish /docs/hellonode/ was up to date with deployments and ReplicaSets

### ISSUE THREAD

**Issue by cmpis** [kubernetes/kubernetes.github.io#219]
I wish /docs/hellonode/ This page was up to date with deployments and ReplicaSets

I had to look up this issue on StackOverflow([issue]) to discover why I wasn't creating any ReplicationControllers or Services after using `kubectl run ...`

Still not quite sure how to finish. 

[issue]: https://stackoverflow.com/questions/36138636/how-do-i-delete-orphan-kubernetes-pods

**Comment by johndmulhausen** [comment]
@jeffmendoza Can you offer any advice on this? It's based on your GCP Next codelab. :)

http://kubernetes.io/docs/hellonode/

**Comment by jeffmendoza** [comment]
I really like `kubectl (run, expose, scale)` for a 5-min quickstart. We should have an explination at the end that you should move to a declarative "Deployment" after the quickstart. Taking out `rolling-update` might be a good idea, it is a client-side hack, and is now outclassed by a deployment.

BTW the codelab is not mine =), don't want to take credit, but I guess we own it now.

**Comment by bgrant0607** [comment]
cc @janetkuo @pwittrock

**Comment by bgrant0607** [comment]
As a quick fix, we could specify the old generator. We should put instructions about that somewhere (e.g., kubectl run --help), since there are likely lots of external docs also.

https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/kubectl/kubectl_run.md

```
kubectl run --generator=run/v1 ...
```

**Comment by bgrant0607** [comment]
See also #200

**Comment by pwittrock** [comment]
I have a fix for this in Pull #231 if we can wait that long.

**Comment by bgrant0607** [comment]
@pwittrock Can this be closed now?

**Comment by pwittrock** [comment]
Yup.  Sorry I didn't close this.
