### ISSUE TITLE
Document Federation CoreDNS support.

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes.github.io#2197]
It is not entirely clear how to use CoreDNS as a DNS provider for federation. We need a doc walking through the setup.

cc @kubernetes/sig-federation-misc

**Comment by jaredbhatti** [comment]
Do you have further ideas of how this would fit into existing content? Need any guidance from the docs team?

**Comment by shashidharatd** [comment]
I would give it a try and come up with a draft in couple of days. any pointers that would help me in this task would be great and thanks for help offer.

**Comment by jaredbhatti** [comment]
Sure,

I'd suggest starting with the page template for tasks: https://kubernetes.io/docs/contribute/page-templates/

Do you know where you're going to put the page on the site?

**Comment by shashidharatd** [comment]
the federation deployment using CoreDNS would mostly be associated with this page https://kubernetes.io/docs/admin/federation/kubefed/

**Comment by madhusudancs** [comment]
@jaredbhatti this doc will probably be one of the user guides.

**Comment by marun** [comment]
https://github.com/kubernetes/kubernetes/issues/40536 is the umbrella issue for tracking this and others targeting improvements in non-cloud deployment of the federation control plane.

**Comment by anuribs** [comment]
I am currently facing the issue mentioned in http://stackoverflow.com/questions/43759332/coredns-in-k8s-federation-in-on-prem-clusters-doesnt-work. I would appreciate if someone could tell me the reason of this behavior or possible fixes of this problem. I have followed all the steps mentioned in the documentation.

**Comment by chenopis** [comment]
Have you asked the kubernetes-dev group (https://groups.google.com/forum/#!forum/kubernetes-dev)?
