### ISSUE TITLE
Issue with /docs/tutorials/stateless-application/hello-minikube/

### ISSUE THREAD

**Issue by ensonic** [kubernetes/kubernetes.github.io#2201]
**This is a...** 
- [ ] Feature Request
- [X] Bug Report

**Problem:**
link "Minikube installation guide" points to https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/docs/getting-started-guides/minikube/ which is 404

**Proposed Solution:**
fix the link by making it absolute:
https://kubernetes.io/docs/getting-started-guides/minikube/

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/

**Comment by jaredbhatti** [comment]
Fixed.
