### ISSUE TITLE
Issue with /docs/user-guide/images/

### ISSUE THREAD

**Issue by naisanza** [kubernetes/kubernetes.github.io#2219]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Where is Google's Public Docker registry for searching and pulling images for use in K8s?

**Page to Update:**
https://kubernetes.io/docs/user-guide/images/

**Comment by jaredbhatti** [comment]
Google Container Registry is (I think) what you're looking for. 
https://kubernetes.io/docs/user-guide/images/#using-google-container-registry

**Comment by naisanza** [comment]
@jaredbhatti I'm looking for Google's version of https://hub.docker.com/ specifically for K8s
