### ISSUE TITLE
Swagger UI isn't loading

### ISSUE THREAD

**Issue by maisem** [kubernetes/kubernetes.github.io#2220]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
The swagger UI page shows "Can't read from server. It may not have the appropriate access-control-origin settings."

**Proposed Solution:**
Verify and correct the access-control-origin settings.

**Page to Update:**
https://kubernetes.io/kubernetes/third_party/swagger-ui/

cc: @mikedanese

**Comment by mikedanese** [comment]
@devin-donnelly

**Comment by pwittrock** [comment]
Lets kill this and the other reference docs and have them redirect to the new docs.

**Comment by bpulito** [comment]
Running into this also. Is there some other link from where I can access the Kubernetes Swagger API definition?

**Comment by andrewhowdencom** [comment]
The swagger page is requesting resources over HTTP; doesn't look like CORS headers

**Comment by treilly1969** [comment]
Hi, Is there any update on this thread? Is there a link to later swagger docs if this has been addressed?

**Comment by ahmetb** [comment]
Hi folks, sorry for the slow response here. I think the best course of action is to kill the Swagger UI and create docs (or just links) for the Swagger Specs. We will be presenting a plan to redesign the https://kubernetes.io/docs/reference/ section in the SIG-Docs meeting on April 4th 10:30am PST. You’re welcome to join there (or comment here) to discuss this further.

**Comment by treilly1969** [comment]
Thanks for the update Ahmet

**Comment by nikhiljindal** [comment]
Latest kubernetes API ref docs can be viewed at https://kubernetes.io/docs/api-reference/v1.6.
Federation API ref docs can be viewed at https://kubernetes.io/docs/federation/api-reference/
