### ISSUE TITLE
API docs: 'pretty' is a query parameter not a path parameter

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes.github.io#2222]
`pretty	If 'true', then the output is pretty printed.`

This appears in multiple places under path parameters. But it is actually a query parameter.

@pwittrock

**Comment by pwittrock** [comment]
Thanks @lavalamp.  Will try to fix this in the next couple weeks.  Need to figure out if this is something in the swagger, or how I am displaying the swagger.

**Comment by pwittrock** [comment]
I figured out the problem.  It is how I am parsing the open-api spec.  Will update.
