### ISSUE TITLE
Workload controllers have wrong api group

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes.github.io#2229]
All of the workload controllers in the following doc are claimed under the Core (api) group which is not true. 

https://kubernetes.io/docs/resources-reference/1_5/#cronjob-v2alpha1

@pwittrock @kubernetes/sig-docs-misc

**Comment by jaredbhatti** [comment]
The link doesn't appear to work.  Can you verify?  Can you also submit additional information on what the specific docs fix is?

**Comment by kargakis** [comment]
Seems like it was changed to https://kubernetes.io/docs/resources-reference/v1.5/#cronjob-v2alpha1 in the meantime. It seems that all (and not only workloads) resources that don't belong to the Core api group are not updated to their own api groups.

For example, [daemon sets](https://kubernetes.io/docs/resources-reference/v1.5/#daemonset-v1beta1) belong to the Extensions api group.

**Comment by jaredbhatti** [comment]
@pwittrock  Philip, can you track this issue down?

**Comment by kargakis** [comment]
This seems fixed, closing.
