### ISSUE TITLE
revisionHistoryLimit suggestion for Deployments

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes.github.io#2230]
The following doc suggests using 10 as a revisionHistoryLimit. Since this is one of the first examples for a Deployment that users will come across and it may be used as is I would suggest a saner value of 2 or 3.

https://kubernetes.io/docs/resources-reference/1_5/#deployment-v1beta1

@pwittrock

**Comment by pwittrock** [comment]
2 < 10 <<<<<<<< infinity

But sure I can update it :)

**Comment by pwittrock** [comment]
@kargakis Didn't mean to be snarky, thanks for the feedback.  Really glad to see you are looking at them and finding ways to improve them.

**Comment by pwittrock** [comment]
Fixed in #2237
