### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by ussmith** [kubernetes/kubernetes.github.io#2239]
**This is a...** 

- [ ] Feature Request
- [X ] Bug Report

**Problem:**
I don't think it's really a bug, just an observation.  The build date for the server showed up as Linux epoch (BuildDate:"1970-01-01T00:00:00Z").  Thought I would pass it along.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by jaredbhatti** [comment]
Thanks!
