### ISSUE TITLE
Hard to find Job, Ingress, Deployment from top-down

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes.github.io#224]
If I heard that 1.2 has Job, Ingress, or Deployment, and then I went to the top-level docs page, it is sort of hard to find the pages for these types.  They are there and linked, but finding them is not easy.  A user on slack mentioned this, and I also separately noticed it.

**Comment by bgrant0607** [comment]
In general, we need to look thoroughly at the navigation organization.

cc @janetkuo @pwittrock @johndmulhausen

**Comment by wernight** [comment]
I agree that I'd advise any new project to use those (as I did in my article). We should promote best practices in the getting started guides.

**Comment by bgrant0607** [comment]
Proposal for new doc organization:
https://docs.google.com/document/d/12Nfj2E8tZL-CMnnpkSH9m5k_oqd4qJh4qDwYDxPGJJI/edit?ts=5705b1fc#

**Comment by wernight** [comment]
For reference my article which hobbyiste seem to appreciate: http://beroux.com/english/articles/kubernetes/

**Comment by janetkuo** [comment]
@wernight I like the overview graph!
