### ISSUE TITLE
Issue with /docs/user-guide/pods/init-container/

### ISSUE THREAD

**Issue by cdz620** [kubernetes/kubernetes.github.io#2240]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Page url:  https://kubernetes.io/docs/user-guide/pods/init-container/
kubernetes.github.io/docs/user-guide/pods/init-container.md in line 83, click [PetSets
guide](https://kubernetes.io/docs/user-guide/pods/init-container/docs/user-guide/petset/bootstrapping/index/) occur 404 error.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by jaredbhatti** [comment]
Fixed.
