### ISSUE TITLE
Issue with /docs/getting-started-guides/ubuntu/calico/

### ISSUE THREAD

**Issue by quidome** [kubernetes/kubernetes.github.io#2243]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Installing on ubuntu 16.04: the chapter "Install Calico’s etcd on the master" states: "This will not have any effect until we later run the kubelet, but Calico seems to tolerate the lack of its etcd in the interim."

I'm sure what you mean here but in my installation calico won't start due to the absence of etcd. I got this from journalctl:
calicoctl[7221]: ERROR: Could not connect to etcd at 10.0.0.201:6666

And calico-node.service will shut down after this

**Proposed Solution:**
I don't know the solution, kubernetes newbie here.

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/ubuntu/calico/#install-calicos-etcd-on-the-master

1.1.4

ubuntu 16.04
docker 1.12.6

**Comment by caseydavenport** [comment]
@quidome I think the intention is that Calico will recover when etcd is eventually recover when etcd is started later in the process.

However, as I said here, this is a really old guide as mentioned here: https://github.com/kubernetes/kubernetes.github.io/issues/3007#issuecomment-290709647 

I'd recommend checking out
- The Calico docs: http://docs.projectcalico.org/v2.1/getting-started/kubernetes/ 
- Or the kubeadm guide: https://kubernetes.io/docs/getting-started-guides/kubeadm/

**Comment by zacharysarah** [comment]
Closing this issue because docs support for Calico was removed; see #4167 for more info.
