### ISSUE TITLE
Issue with /docs/user-guide/kubectl-overview/

### ISSUE THREAD

**Issue by kKronstainBrown** [kubernetes/kubernetes.github.io#2254]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
I can't link to individual commands that are described in this page.

**Proposed Solution:**
Add anchors to each command.

**Page to Update:**
https://kubernetes.io/docs/user-guide/kubectl-overview/

**Comment by jaredbhatti** [comment]
Thanks for filing the issue.  We'll look into it.
