### ISSUE TITLE
Issue with /docs/getting-started-guides/minikube/

### ISSUE THREAD

**Issue by grahamwhaley** [kubernetes/kubernetes.github.io#2272]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Broken links to kvm and xyhve installation pages from here:
https://kubernetes.io/docs/getting-started-guides/minikube/#quickstart
to
https://kubernetes.io/docs/getting-started-guides/minikube/DRIVERS/#kvm-driver
for instance - gives a 404.

**Proposed Solution:**
Find the correct links and update appropriately

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/minikube/#quickstart

**Comment by r2d4** [comment]
fixed w/ this PR https://github.com/kubernetes/kubernetes.github.io/pull/2184

**Comment by jaredbhatti** [comment]
Fixed.  Thanks!
