### ISSUE TITLE
How do I create a new .md file and link to it in other docs? How do I modify the link/title of a .md file?

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes.github.io#228]
Forked from https://github.com/kubernetes/kubernetes.github.io/pull/197#issuecomment-198585268. I wanted to (but don't know how to):

1. Change the title of "managing deployments" doc from "Managing Deployments" to "Managing Resources"
2. Create the link to the new doc how-to-kubectl-rolling-update.md and link to it in the "managing deployments" doc

@kubernetes/docs

**Comment by johndmulhausen** [comment]
Create a new file in GitHub by clicking "new file" on the repo's homepage. Or, if you clone the repo to your laptop, just create the file and [use the command line to generate the pull request](https://git-scm.com/docs/git-request-pull).

If you create a file at /docs/user-guide/foo.md, then the file's URL to link to will be /docs/user-guide/foo

To change the title of a topic, or change where it appears in the left nav tree, edit /_data/*.yml (whichever file contains the topic in the left nav).

**Comment by bgrant0607** [comment]
What about redirects?
