### ISSUE TITLE
Tools Index page formatting

### ISSUE THREAD

**Issue by devin-donnelly** [kubernetes/kubernetes.github.io#2294]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The formatting on the [Tools page](http://kubernetes.io/docs/tools) has a great deal of dead whitespace and basic plain text and links.

**Proposed Solution:**
I'd like to come up with a newer, better layout for the tools page that's more navigable and makes it easier on the eyes.

**Page to Update:**
http://kubernetes.io/docs/tools/index.md

**Comment by steveperry-53** [comment]
Fixed in #3880.
@devin-donnelly Please reopen if this isn't what you had in mind.

Note: /docs/tools/index.md is orphaned. I'll address that elsewhere.
