### ISSUE TITLE
Images are being cut off on the right side

### ISSUE THREAD

**Issue by johndmulhausen** [kubernetes/kubernetes.github.io#23]
http://kubernetes.github.io/docs/getting-started-guides/coreos/azure/

**Comment by johndmulhausen** [comment]
@CreaturesInUnitards why am I assigned?

**Comment by CreaturesInUnitards** [comment]
...because I got pulled away in the middle of handling this sorry :)

**Comment by CreaturesInUnitards** [comment]
do you want me to force fit, or scroll X?

**Comment by johndmulhausen** [comment]
Force fit plz!

**Comment by CreaturesInUnitards** [comment]
ok done
