### ISSUE TITLE
Need a way to preview a doc without making changes in master branch of a fork

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes.github.io#232]
Normal developer workflow is to create a branch for every PR. Requiring changes to be done in master in order to preview formatting is contrary to standard operating procedure.

**Comment by johndmulhausen** [comment]
Hmm. Stop me when I'm wrong, but: we currently have two ways to preview, locally or in a fork on the user's account (yes, in the master branch of said fork). GitHub doesn't build previews out of any branch except gh-pages, so I think this is infeasible barring some kind of cloud solution that constantly monitors for branches and spins up subdomains at a totally external URL. Seems like an expensive thing to spend time on just to avoid using forks, or am I missing something?

**Comment by bgrant0607** [comment]
Since the fork needs to have the same name as the user's account (plus .github.io), that implies we need to create multiple github accounts to have multiple PRs open at a time?

**Comment by johndmulhausen** [comment]
No, you can fork as many times as you want and make PRs, but you would need multiple github accounts to _stage_ each of those PRs live on github.io's space. Not much we can do about that but roll our own cloud solution. Is that officially what we're looking to do?

**Comment by bgrant0607** [comment]
We either need a way to easily view the content as it will eventually appear on the site or mechanical verification that the formatting is compliant with conventions. Previously we did the latter.

**Comment by techtonik** [comment]
Looks like with Netlify this issue is resolved https://github.com/kubernetes/kubernetes.github.io/pull/1402/files

**Comment by jaredbhatti** [comment]
Yep.
