### ISSUE TITLE
Link to meetups on community page

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes.github.io#2323]
https://www.meetup.com/topics/kubernetes/
https://www.meetup.com/Kubernetes-Cloud-Native-Online-Meetup/
cc @sarahnovotny

**Comment by jaredbhatti** [comment]
Sarah, can you review and update?

**Comment by sarahnovotny** [comment]
sounds great.  They can be their own horizontal section after SIGs before the Events calendar.  Something like...

"Join Kubernauts all around the world in our Kubernetes Meetup Community [link] and the Cloud Native Meetup Community [link]"

**Comment by jaredbhatti** [comment]
https://github.com/kubernetes/kubernetes.github.io/pull/2366
