### ISSUE TITLE
v1.List reference docs missing

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes.github.io#2324]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
I've used `v1.List` before and there are many references online, but I don't see it here: https://kubernetes.io/docs/api-reference/v1/definitions/

**Proposed Solution:**
Not sure, I would've assumed the definitions/reference api docs were auto-generated.

**Page to Update:**
https://kubernetes.io/docs/api-reference/v1/definitions/

**Comment by pwittrock** [comment]
@mbohlool I didn't see this in the swagger.  Do you know if it is there?

**Comment by colemickens** [comment]
Per Slack yesterday, I was told that there is not an actual endpoint that supports a POST/PUT body of `v1.List`.

It looks like it's just something that `kubectl` has special support for. It, client-side, parses the List and makes individual API calls.

Unless you feel otherwise, I'll close this out shortly.

**Comment by mbohlool** [comment]
@colemickens If there is no endpoint using it, it won't show up in our spec and any generated content from it. I am fine with closing this out.
