### ISSUE TITLE
Broken link to GUI "Setup Instructions"

### ISSUE THREAD

**Issue by miabbott** [kubernetes/kubernetes.github.io#236]
From http://kubernetes.io/docs/getting-started-guides/scratch/#starting-cluster-services, there is a link to the GUI "Setup Instructions" that points to https://github.com/kubernetes/kubernetes/tree/release-1.2/cluster/addons/kube-ui/, which returns 404

**Comment by johndmulhausen** [comment]
Fixed in https://github.com/kubernetes/kubernetes.github.io/commit/e0ff6f51a04456961fe9a796bd11581aa8a9ce69
