### ISSUE TITLE
Developer guide not reachable from http://kubernetes.io/docs/reference/

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes.github.io#238]
I found no path from http://kubernetes.io/docs/reference/ to the developer guide.

**Comment by johndmulhausen** [comment]
Click "Guides" in the horizontal nav

**Comment by MikeSpreitzer** [comment]
You mean like this: <img width="1236" alt="screen shot 2016-03-27 at 11 59 34 pm" src="https://cloud.githubusercontent.com/assets/14296719/14070709/06a29950-f478-11e5-86c7-3766b5d5b007.png">
?  What is the path from there to https://github.com/kubernetes/kubernetes/blob/master/docs/devel/README.md ?
