### ISSUE TITLE
Issue with /docs/getting-started-guides/binary_release/

### ISSUE THREAD

**Issue by alexlist** [kubernetes/kubernetes.github.io#2384]
**This is a...** 
- [ ] Feature Request
- [X] Bug Report

**Problem:**

```For more details on the release process see the build-tools/ directory```
The link "build-tools/" doesn't work anymore and returns 404.

**Proposed Solution:**
Fix the link

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/binary_release/

**Comment by jaredbhatti** [comment]
Fixed.  Thanks!
