### ISSUE TITLE
No doc for how to build kubernetes

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes.github.io#239]
I found no path from http://kubernetes.io/docs/reference/ nor the developer guide (https://github.com/kubernetes/kubernetes/blob/master/docs/devel/README.md --- BTW, is that still right?  I thought the docs had moved) to instructions on how to build Kubernetes.

**Comment by johndmulhausen** [comment]
@MikeSpreitzer see http://kubernetes.io/docs/getting-started-guides/binary_release/#building-from-source

**Comment by MikeSpreitzer** [comment]
OK, that's good, but you must forgive readers who fail to look under "downloading" for instructions on how to build.  This needs to be more findable.
