### ISSUE TITLE
I wish /docs/api-reference/v1/operations/definitions/ existed

### ISSUE THREAD

**Issue by aaronLariat** [kubernetes/kubernetes.github.io#240]
I wish /docs/api-reference/v1/operations/definitions/ existed

**Comment by johndmulhausen** [comment]
That has never existed. there is .../operations/ and .../definitions/ but never /operations/definitions. 

See: https://github.com/kubernetes/kubernetes/tree/gh-pages/_v1.1/docs/api-reference/v1

**Comment by johndmulhausen** [comment]
Closing as there's no way to tell where to redirect such a request and it doesn't look to be valid
