### ISSUE TITLE
Kube init returns a failed to parse kernel config: error

### ISSUE THREAD

**Issue by abuehrle** [kubernetes/kubernetes.github.io#2435]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Setting up Kubernetes on bare metal servers (Ubuntu 16.04 kernel version: 4.4.0-47-generic #68-Ubuntu SMP Wed), and when I initialize the master with  ```kube init```  the following error is returned: 

```
failed to parse kernel config: unable to load kernel module "configs": output - "modprobe: FATAL: Module configs not found in directory /lib/modules/4.4.0-47-generic\n", err - exit status 1
```

kubeadm version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2074+a092d8e0f95f52", GitCommit:"a092d8e0f95f5200f7ae2cba45c75ab42da36537", GitTreeState:"clean", BuildDate:"2016-12-13T17:03:18Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Proposed Solution:**
This is fixed by running: 

```apt-get install linux-image-$(uname -r)```

But maybe the missing mods should be added?  @lukemarsden 

**Page to Update:**
http://kubernetes.io/...

**Comment by lukemarsden** [comment]
@luxas PTAL?

**Comment by abuehrle** [comment]
logged over in other repo here:  https://github.com/kubernetes/kubernetes/issues/41025
