### ISSUE TITLE
Issue with SSL in Kops Kubernetes cluster setup

### ISSUE THREAD

**Issue by ksr1** [kubernetes/kubernetes.github.io#2442]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
SSL connection to RabbitMQ pod from another pod fails with a timeout error. No further errors are seen. While connecting from outside the cluster via AWS Loadbalancer URL the same SSL port works. Cluster was setup with:
kops version
Version 1.5.0-beta2 (git-a27d355)

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:43:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

SSL Client is run from OpenJDK. The same setup works fine in a cluster setup with kube-up.sh script.

**Comment by chrislovecnm** [comment]
This may be the wrong repo to file this issue.  I would try slack or stackoverflow

**Comment by ksr1** [comment]
Ok thanks will do that.
