### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by Nyefan** [kubernetes/kubernetes.github.io#2448]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Using safari version 10.0.3 (12602.4.8) on MacOS Sierra version 10.12.3 (16D32), the interactive console says: 
    - Problem accessing cookies. Are cookies enabled?
follow about a minute later by:
    - Sorry, we hit a problem with the connection.
    - Your internet connection may have dropped.
    - Please refresh and try again.

Enabling all cookies and enabling cookies just for the site don't solve the problem.  

Trying the same on chromium version 58.0.3006.0 (64-bit) results in a different error message with the same result:
    - Oops! Sorry, we had a problem. Please refresh and try again.
Again, changing the cookie settings doesn't affect the outcome.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment]
I'm sorry you encountered an issue. We had a problem with our main load balancer that was causing websocket connections to drop. This happened intermittently for around 30mins before we (Katacoda) corrected the issue. You should be able to complete the tutorials without a problem now.

**Comment by jeffmendoza** [comment]
Looks like this is addressed, please reopen if you encounter again.

**Comment by jsco2t** [comment]
I'm having this same exact issue today - using Safari on a Mac (tried on two machines). Same error - has been repro'ing for me for the last 6 hours or so. 

If you need any additional details please let me know. Thanks!
