### ISSUE TITLE
Getting started docs recommend adding whatever directory you're in to your PATH

### ISSUE THREAD

**Issue by ericandrewlewis** [kubernetes/kubernetes.github.io#245]
e.g. [here](https://github.com/kubernetes/kubernetes.github.io/blame/1c27f43b7b405c5fc9c74d366854d49d4ef6f11a/docs/getting-started-guides/docker.md#L64-L67)

``` shell
$ wget http://storage.googleapis.com/kubernetes-release/release/v${K8S_VERSION}/bin/darwin/amd64/kubectl
$ chmod 755 kubectl
$ PATH=$PATH:`pwd`
```

Could we consider suggesting installation via brew, which would place `kubectl` somewhere by design, or suggest to the user to move the file to somewhere already on the user's PATH, e.g. `/usr/local/bin` ?

**Comment by jaredbhatti** [comment]
Replaced by Minikube. 
http://kubernetes.io/docs/getting-started-guides/minikube/
