### ISSUE TITLE
Issue with /docs/admin/addons/

### ISSUE THREAD

**Issue by rhim** [kubernetes/kubernetes.github.io#2454]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
We would like to list contiv as addon under "Networking and Network Policy"

**Proposed Solution:**
[Contiv](http://contiv.github.io) provides configurable networking (native l3 using BGP, overlay using vxlan, classic l2, or Cisco-SDN/ACI) for various use cases and a rich policy framework. Contiv project is fully [open sourced](http://github.com/contiv).

**Page to Update:**
http://kubernetes.io/docs/admin/addons/

**Comment by chenopis** [comment]
The PR for this issue has been merged.
