### ISSUE TITLE
Google is indexing personal repos

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes.github.io#246]
Searching for "download kubectl" ... the top link that is from our docs is on thockin's personal fork of the docs.

https://www.google.com/search?q=download+kubectl

I think we need a canonical reference link or similar, so that all those links push people to kubernetes.io

**Comment by johndmulhausen** [comment]
Added canonical URLs per https://support.google.com/webmasters/answer/139066?hl=en

See https://github.com/kubernetes/kubernetes.github.io/commit/9c731b6bba982fcfcf73120a02fdc56d8c13327c

Not sure what else we can do. Both sitemap.xml and the canonical links refer to the kubernetes.io domain now.

**Comment by justinsb** [comment]
Sounds great!  We can probably ping the primary people that have forks of the repo that don't have this commit (e.g @thockin ) to get them to update!

**Comment by johndmulhausen** [comment]
Looks like all @thockin has is the old v1.0 docs anyway. Closing out. Thanks!
