### ISSUE TITLE
Issue with /docs/user-guide/ingress/

### ISSUE THREAD

**Issue by cristifalcas** [kubernetes/kubernetes.github.io#2460]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
On #prerequisites, the second [link](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/BETA_LIMITATIONS.md#disabling-glbc) goes to a 404 page

**Proposed Solution:**
Fix the url or remove the link

**Page to Update:**
https://kubernetes.io/docs/user-guide/ingress/

**Comment by chenopis** [comment]
taken care of by PR #2530
