### ISSUE TITLE
Issue with /docs/user-guide/ingress/ - Links to GCE and NGINX ingress controllers are broken

### ISSUE THREAD

**Issue by j-mueller** [kubernetes/kubernetes.github.io#2474]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
The links to GCE and NGINX ingress controllers in "Before you begin" are broken. They point to

https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/README.md and
https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/README.md respectively neither of those pages exist.

**Proposed Solution:**
Fix the links.

**Page to Update:**
https://kubernetes.io/docs/user-guide/ingress/

**Comment by chenopis** [comment]
Addressed by PR #2530
