### ISSUE TITLE
Can't download the latest version of kubectl from a step in hello-minikube

### ISSUE THREAD

**Issue by AjkP** [kubernetes/kubernetes.github.io#2478]
**This is a Bug Report** 

**Problem:**
Cannot download the latest version of kubectl from a step in the `hello-minikube` tutorial.

**Proposed Solution:**
Review the download link and make sure it works.

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/

When following the above page, the step:
`curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/kubectl
`

does not succeed and outputs the following error:
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>%
```

**Comment by steveperry-53** [comment]
@waprin

**Comment by waprin** [comment]
The links works fine for me but @ahmetb is pointing out this zsh (not uncommon) is escaping the $ sign when copy/pasting. @steveperry-53 any guidance on how we address that?

**Comment by ahmetb** [comment]
so @AjkP if you're using zsh like I do, just because the command starts with `curl`, it does URL escaping like `$\(` and I get the same error.

An easy fix would be to fix the tutorial as:

    KUBE_VERSION=$(curl -sfL https://storage.googleapis.com/kubernetes-release/release/stable.txt)
    curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBE_VERSION/bin/darwin
