### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by pramodsetlur** [kubernetes/kubernetes.github.io#2493]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
The last line in the terminal is cut out. i can see just the top half of the words. Seen in all the pages of the interactive tutorial.

**Proposed Solution:**
I am not sure.

**Page to Update:**
http://kubernetes.io/...

- [ ]

**Comment by jeffmendoza** [comment]
Can you post a screenshot and your browser info? This is what I'm seeing:

![katakoda terminal](https://cloud.githubusercontent.com/assets/771387/23180137/351ff474-f825-11e6-8e9b-e8a8744c5651.png)

cc @BenHall

**Comment by jeffmendoza** [comment]
which browser / version / platform ?

**Comment by pramodsetlur** [comment]
MacOS Sierra v 10.12.3
Google Chrome : Version 56.0.2924.87 (64-bit)

**Comment by BenHall** [comment]
Thank you for the additional info. I've added a note and we'll look into this.

**Comment by zacharysarah** [comment]
@pramodsetlur Are you still experiencing this bug?

**Comment by pramodsetlur** [comment]
@zacharysarah I don't see the issue anymore. Thanks for the fix.
