### ISSUE TITLE
Issue with /docs/user-guide/ui/

### ISSUE THREAD

**Issue by githubvick** [kubernetes/kubernetes.github.io#2502]
**This is a...**  Feature Request

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
Trying to setup Kubernetes Dashboard without authentication with the help of documentation provided. The kube cluster is setup in virtual box vm's with Flannel. 

```
kubectl get svc --all-namespaces
NAMESPACE     NAME                   CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
default       kubernetes             10.254.0.1       <none>        443/TCP         22h
default       mongoservice           10.254.109.200   <none>        27017/TCP       21h
default       webappservice          10.254.52.137    <none>        8080/TCP        21h
kube-system   kube-dns               10.254.0.2       <none>        53/UDP,53/TCP   21h
kube-system   kubernetes-dashboard   10.254.24.203    <nodes>       80/TCP          6m

```
When we follow the steps as per the documentation, it doesn't work.

**Proposed Solution:**

Please improve documentation on Kubernetes to setup Dashboards. Since it involves networking,it is difficult for programmers. From my current understanding, kubectl proxy command starts a proxy for the api-server. It runs on port 8001. By proxy, any api calls coming to the api server has to come through this, so internally it is mapped to the api server.

Kindly update the troubleshooting steps to be taken when facing issues like this since this is the most basic env setup for Kube dashborad

**Page to Update:**
https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md

Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"87d9d8d7bc5aa35041a8ddfe3d4b367381112f89", GitTreeState:"clean", BuildDate:"2017-01-23T14:15:25Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"87d9d8d7bc5aa35041a8ddfe3d4b367381112f89", GitTreeState:"clean", BuildDate:"2017-01-23T14:15:25Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

Steps done:

I'm running the kubectl proxy command on the kubernetes master whose IP is 192.168.6.101.

Downloaded from this location and kubectl create -f 
https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml

On first iteration, it failed with 

`Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get http://192.168.6.101/version: dial tcp 192.168.6.101:80: getsockopt: connection refused`

Then figured in the yaml file that I need to change the api server value if it doesn't work by default. 

Tried changing the api server value to --apiserver-host=http://192.168.6.101 which is the node ip, but it failed with the same error as above. 

The closest I had come to hopes that I could get it working is when I had changed the --apiserver-host=http://10.254.0.1 which is the Kubernetes Cluster IP. Then when I try to access via the browser http://localhost:8001/, it gives unauthorized. When I try this http://localhost:8001/ui, it displays after redirecting to 

`{
  "kind": "Service",
  "apiVersion": "v1",
  "metadata": {
    "name": "kubernetes-dashboard",
    "namespace": "kube-system",
    "selfLink": "/api/v1/namespaces/kube-system/services/kubernetes-dashboard",
    "uid": "ee715496-f152-11e6-92cf-08002700df07",
    "resourceVersion": "172129",
    "creationTimestamp": "2017-02-12T18:41:57Z",
    "labels": {
      "app": "kubernetes-dashboard"
    }
  },
  "spec": {
    "ports": [
      {
        "protocol": "TCP",
        "port": 80,
        "targetPort": 9090,
        "nodePort": 30474
      }
    ],
    "selector": {
      "app": "kubernetes-dashboard"
    },
    "clusterIP": "10.254.151.97",
    "type": "NodePort",
    "sessionAffinity": "None"
  },
  "status": {
    "loadBalancer": {}
  }
}`

and then crashes again with the same error above.

```
 kubectl describe pods kubernetes-dashboard-1964089633-n5g21 --namespace=kube-system
Name:		kubernetes-dashboard-1964089633-n5g21
Namespace:	kube-system
Node:		192.168.6.103/192.168.6.103
Start Time:	Sun, 12 Feb 2017 23:11:14 -0500
Labels:		app=kubernetes-dashboard
		pod-template-hash=1964089633
Status:		Running
IP:		172.17.93.4
Controllers:	ReplicaSet/kubernetes-dashboard-1964089633
Containers:
  kubernetes-dashboard:
    Container ID:	docker://0921a82317ec3167509bdba9c410000f41cd9adcc8371b5b8c05e58cdf6f113a
    Image:		gcr.io/google_containers/kubernetes-dashboard-amd64:v1.5.1
    Image ID:		docker-pullable://gcr.io/google_containers/kubernetes-dashboard-amd64@sha256:46a09eb9c611e625e7de3fcf325cf78e629d002e57dc80348e9b0638338206b5
    Port:		9090/TCP
    Args:
      --apiserver-host=http://10.254.0.1
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Sun, 12 Feb 2017 23:20:21 -0500
      Finished:		Sun, 12 Feb 2017 23:20:51 -0500
    Ready:		False
    Restart Count:	6
    Liveness:		http-get http://:9090/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-f5ate (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  default-token-f5ate:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-f5ate
QoS Class:	BestEffort
Tolerations:	dedicated=master:Equal:NoSchedule
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath				Type		Reason		Message
  ---------	--------	-----	----			-------------				--------	------		-------
  9m		9m		1	{default-scheduler }						Normal		Scheduled	Successfully assigned kubernetes-dashboard-1964089633-n5g21 to 192.168.6.103
  9m		9m		1	{kubelet 192.168.6.103}	spec.containers{kubernetes-dashboard}	Normal		Created		Created container with docker id f0359469a8a6; Security:[seccomp=unconfined]
  9m		9m		1	{kubelet 192.168.6.103}	spec.containers{kubernetes-dashboard}	Normal		Started		Started container with docker id f0359469a8a6
  9m		9m		1	{kubelet 192.168.6.103}	spec.containers{kubernetes-dashboard}	Normal		Started		Started container with docker id d42635fc7e63
  9m		9m		1	{kubelet 192.168.6.103}	spec.containers{kubernetes-dashboard}	Normal		Created		Created container with docker id d42635fc7e63; Security:[seccomp=unconfined]
  8m		8m		2	{kubelet 192.168.6.103}						Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 10s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-1964089633-n5g21_kube-system(75c623a9-f1a2-11e6-a404-08002700df07)"

  8m	8m	1	{kubelet 192.168.6.103}	spec.containers{kubernetes-dashboard}	Normal	Started		Started container with docker id 3f470e49f5e0
  8m	8m	1	{kubelet 192.168.6.103}	spec.containers{kubernetes-dashboard}	Normal	Created		Created container with docker id 3f470e49f5e0; Security:[seccomp=unconfined]
  7m	7m	3	{kubelet 192.168.6.103}						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 20s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-1964089633-n5g21_kube-system(75c623a9-f1a2-11e6-a404-08002700df07)"

  7m	7m	1	{kubelet 192.168.6.103}	spec.containers{kubernetes-dashboard}	Normal	Started		Started container with docker id 2082b8ae798b
  7m	7m	1	{kubelet 192.168.6.103}	spec.containers{kubernetes-dashboard}	Normal	Created		Created container with docker id 2082b8ae798b; Security:[seccomp=unconfined]
  6m	6m	4	{kubelet 192.168.6.103}						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 40s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-1964089633-n5g21_kube-system(75c623a9-f1a2-11e6-a404-08002700df07)"

  6m	6m	1	{kubelet 192.168.6.103}	spec.containers{kubernetes-dashboard}	Normal	Created		Created container with docker id c2fa77ca7a64; Security:[seccomp=unconfined]
  6m	6m	1	{kubelet 192.168.6.103}	spec.containers{kubernetes-dashboard}	Normal	Started		Started container with docker id c2fa77ca7a64
  5m	4m	7	{kubelet 192.168.6.103}						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-1964089633-n5g21_kube-system(75c623a9-f1a2-11e6-a404-08002700df07)"

  4m	4m	1	{kubelet 192.168.6.103}	spec.containers{kubernetes-dashboard}	Normal	Created		Created container with docker id 5853a643908d; Security:[seccomp=unconfined]
  4m	4m	1	{kubelet 192.168.6.103}	spec.containers{kubernetes-dashboard}	Normal	Started		Started container with docker id 5853a643908d
  3m	1m	13	{kubelet 192.168.6.103}						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-1964089633-n5g21_kube-system(75c623a9-f1a2-11e6-a404-08002700df07)"

  9m	49s	7	{kubelet 192.168.6.103}	spec.containers{kubernetes-dashboard}	Normal	Pulling		pulling image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.5.1"
  9m	47s	7	{kubelet 192.168.6.103}	spec.containers{kubernetes-dashboard}	Normal	Pulled		Successfully pulled image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.5.1"
  46s	46s	1	{kubelet 192.168.6.103}	spec.containers{kubernetes-dashboard}	Normal	Started		Started container with docker id 0921a82317ec
  46s	46s	1	{kubelet 192.168.6.103}	spec.containers{kubernetes-dashboard}	Normal	Created		Created container with docker id 0921a82317ec; Security:[seccomp=unconfined]
  8m	0s	32	{kubelet 192.168.6.103}	spec.containers{kubernetes-dashboard}	Warning	BackOff		Back-off restarting failed docker container
  15s	0s	3	{kubelet 192.168.6.103}						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-1964089633-n5g21_kube-system(75c623a9-f1a2-11e6-a404-08002700df07)"

```

**Comment by githubvick** [comment]
The error was because I had not added the port :8080 to the api-server flag in addition to the external ip. Hope you can add in the yml file that port also can be added (for networking beginners like me).I was able to get it up and running. Thanks,

**Comment by nitinja08** [comment]
I get the same problem

root@demo4 Builds]# kubectl --namespace="kube-system" logs kubernetes-dashboard-3203962772-x33rd
Using HTTP port: 9090
Creating API server client for https://10.254.0.1:443
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.254.0.1:443/version: dial tcp 10.254.0.1:443: i/o timeout
Refer to the troubleshooting guide for more information: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md
[root@demo4 Builds]# kubectl --namespace="kube-system" logs kubernetes-dashboard-3203962772-x33rd
Using HTTP port: 9090
Creating API server client for https://10.254.0.1:443
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.254.0.1:443/version: dial tcp 10.254.0.1:443: i/o timeout
Refer to the troubleshooting guide for more information: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md

**Comment by nitinja08** [comment]
[root@demo4 Builds]# kubectl describe pods kubernetes-dashboard-3203962772-x33rd --namespace=kube-system
Name:           kubernetes-dashboard-3203962772-x33rd
Namespace:      kube-system
Node:           192.168.56.12/192.168.56.12
Start Time:     Sun, 30 Apr 2017 00:01:27 +0200
Labels:         app=kubernetes-dashboard
                pod-template-hash=3203962772
Status:         Running
IP:             172.30.75.3
Controllers:    ReplicaSet/kubernetes-dashboard-3203962772
Containers:
  kubernetes-dashboard:
    Container ID:       docker://578b159da7a0ff3bb5421acf65210516721ff249e670477d95596b1c262dd762
    Image:              gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0
    Image ID:           docker-pullable://gcr.io/google_containers/kubernetes-dashboard-amd64@sha256:4ad64dfa7159ff4a99a65a4f96432f2fdb6542857cf230858b3159017833a882
    Port:               9090/TCP
    State:              Waiting
      Reason:           CrashLoopBackOff
    Last State:         Terminated
      Reason:           Error
      Exit Code:        1
      Started:          Sun, 30 Apr 2017 00:15:58 +0200
      Finished:         Sun, 30 Apr 2017 00:16:29 +0200
    Ready:              False
    Restart Count:      7
    Liveness:           http-get http://:9090/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-827vq (ro)
    Environment Variables:      <none>
Conditions:
  Type          Status
  Initialized   True 
  Ready         False 
  PodScheduled  True 
Volumes:
  default-token-827vq:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-827vq
QoS Class:      BestEffort
Tolerations:    dedicated=master:Equal:NoSchedule
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath                           Type            Reason          Message
  ---------     --------        -----   ----                    -------------                           --------        ------          -------
  15m           15m             1       {default-scheduler }                                            Normal          Scheduled       Successfully assigned kubernetes-dashboard-3203962772-x33rd to 192.168.56.12
  15m           15m             1       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal          Created         Created container with docker id 86a47d73080c; Security:[seccomp=unconfined]
  15m           15m             1       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal          Started         Started container with docker id 86a47d73080c
  15m           15m             1       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal          Started         Started container with docker id 5d8cdef59daf
  15m           15m             1       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal          Created         Created container with docker id 5d8cdef59daf; Security:[seccomp=unconfined]
  14m           14m             2       {kubelet 192.168.56.12}                                         Warning         FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 10s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-3203962772-x33rd_kube-system(64fcf473-2d27-11e7-b17e-94de80fae89e)"

  14m   14m     1       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal  Started         Started container with docker id cf3264bb8535
  14m   14m     1       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal  Created         Created container with docker id cf3264bb8535; Security:[seccomp=unconfined]
  13m   13m     2       {kubelet 192.168.56.12}                                         Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 20s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-3203962772-x33rd_kube-system(64fcf473-2d27-11e7-b17e-94de80fae89e)"

  13m   13m     1       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal  Created         Created container with docker id 011fe3b024e6; Security:[seccomp=unconfined]
  13m   13m     1       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal  Started         Started container with docker id 011fe3b024e6
  12m   12m     4       {kubelet 192.168.56.12}                                         Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 40s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-3203962772-x33rd_kube-system(64fcf473-2d27-11e7-b17e-94de80fae89e)"

  12m   12m     1       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal  Created         Created container with docker id 8d21676c0bf9; Security:[seccomp=unconfined]
  12m   12m     1       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal  Started         Started container with docker id 8d21676c0bf9
  11m   11m     1       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Warning Unhealthy       Liveness probe failed: Get http://172.30.75.3:9090/: dial tcp 172.30.75.3:9090: getsockopt: connection refused
  11m   10m     7       {kubelet 192.168.56.12}                                         Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-3203962772-x33rd_kube-system(64fcf473-2d27-11e7-b17e-94de80fae89e)"

  10m   10m     1       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal  Created         Created container with docker id 60baa5fc3387; Security:[seccomp=unconfined]
  10m   10m     1       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal  Started         Started container with docker id 60baa5fc3387
  9m    7m      13      {kubelet 192.168.56.12}                                         Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-3203962772-x33rd_kube-system(64fcf473-2d27-11e7-b17e-94de80fae89e)"

  6m    6m      1       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal  Created         Created container with docker id e36e2ca793e7; Security:[seccomp=unconfined]
  6m    6m      1       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal  Started         Started container with docker id e36e2ca793e7
  15m   1m      8       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal  Pulling         pulling image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0"
  1m    1m      1       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal  Started         Started container with docker id 578b159da7a0
  15m   1m      8       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal  Pulled          Successfully pulled image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0"
  1m    1m      1       {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Normal  Created         Created container with docker id 578b159da7a0; Security:[seccomp=unconfined]
  6m    10s     28      {kubelet 192.168.56.12}                                         Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-3203962772-x33rd_kube-system(64fcf473-2d27-11e7-b17e-94de80fae89e)"

  14m   10s     56      {kubelet 192.168.56.12} spec.containers{kubernetes-dashboard}   Warning BackOff Back-off restarting failed docker container
