### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by fulltopic** [kubernetes/kubernetes.github.io#2547]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
"kubectl proxy" hung
After "+" a new terminal to try POD_NAME, the size of display < that of the terminal that bottom lines could not be seen
**Proposed Solution:**
Don't know
**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/

**Comment by zacharysarah** [comment]
@fulltopic Thanks for opening this issue.

@BenHall 👋 Possibly related to #2493?

**Comment by BenHall** [comment]
@zacharysarah It does look like it, however I thought I had resolved this.

@fulltopic Could you please tell me your browser, os and screen resolution please?

**Comment by heckj** [comment]
Thanks @fulltopic 

This bug matches closely other bugs reported against the use of `kubectl proxy` in the tutorial's hosted at Katacoda. I have a PR pending to resolve, and am closing this bug to focus conversation on the earliest report of this issue: https://github.com/kubernetes/kubernetes.github.io/issues/1561

Please comment at https://github.com/kubernetes/kubernetes.github.io/issues/1561, or subscribe to that bug, to get updates as we work on resolving this.
