### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by razghe** [kubernetes/kubernetes.github.io#2555]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

After executing :
export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
echo Name of the Pod: $POD_NAME
 
I try to tun the curl command and receive the following error message : "curl: (7) Failed to connect to localhost port 8001: Connection refused "

The issue is at Interactive Tutorial - Deploying an App -> Module2

**Comment by jaredbhatti** [comment]
Seems like there was an outage with the interactive tutorial, but it's fixed now.  Please reopen this issue if you see it again. Thanks!

**Comment by pete0emerson** [comment]
I'm seeing this issue now.

**Comment by zacharysarah** [comment]
Closing this issue. It looks like the interactive tutorial is fixed:

![image](https://user-images.githubusercontent.com/3210446/28185607-96224470-67dd-11e7-8c73-f418341e954f.png)

**Comment by sabarnwa** [comment]
I am seeing this issue now. Can someone help me with it please.
