### ISSUE TITLE
"hellonode" docs for create cluster need to reference explicit cluster name

### ISSUE THREAD

**Issue by ALRubinger** [kubernetes/kubernetes.github.io#256]
When creating your cluster:

"Leave all the options default, and you should get a Kubernetes cluster with three nodes, ready to receive your container image."

..should read:

"Set the name to 'hello-world', leaving all other options default.  You should get a Kubernetes cluster with three nodes, ready to receive your container image."

**Comment by ALRubinger** [comment]
PR submitted: https://github.com/kubernetes/kubernetes.github.io/pull/257

**Comment by bgrant0607** [comment]
cc @pwittrock @janetkuo

**Comment by runseb** [comment]
should be closed now
