### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by Spirit328** [kubernetes/kubernetes.github.io#2560]
**This is a...** 

- [ ] Feature Request
- [ X  ] Bug Report

**Problem:**
Kubernetes Bootcamp Terminal                                                                                                                                                          Sorry, we hit a problem with the connection.
Your internet connection may have dropped
Please refresh and try again.

**Proposed Solution:**
NONE

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/

This problem persists no matter what Connection I tried or which browser I used.
Quite disappointing.

**Comment by jaredbhatti** [comment]
Huh, it seems to work for me. Maybe it was a transient error?

**Comment by jaredbhatti** [comment]
Seems like there was an outage with the interactive tutorial, but it's fixed now.  Please reopen this issue if you see it again. Thanks!
