### ISSUE TITLE
"hellonode" docs missing "gcloud" in rolling update section

### ISSUE THREAD

**Issue by ALRubinger** [kubernetes/kubernetes.github.io#258]
In issuing the push to gcr.io in the "Rolling Updates" section:

  docker push gcr.io/PROJECT_ID/hello-node:v2

...should read:

  gcloud docker push gcr.io/PROJECT_ID/hello-node:v2

**Comment by ALRubinger** [comment]
PR submitted: https://github.com/kubernetes/kubernetes.github.io/pull/259

**Comment by bgrant0607** [comment]
cc @pwittrock @janetkuo

**Comment by johndmulhausen** [comment]
Thanks, Al; confirmed that is the command by talking to the GCR team today.
