### ISSUE TITLE
kubectl/API reference links broken during transition

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes.github.io#2631]
```
$ kubectl explain deploy.spec.template.spec.containers
...

   initialDelaySeconds	<integer>
     Number of seconds after the container has started before liveness probes
     are initiated. More info:
     http://kubernetes.io/docs/user-guide/pod-states#container-probes
```

we have links like that which seem to be broken now. They're very specific (e.g. they point to specific sections in pages, like `#id`). Is there a plan to update these links in API reference etc?

**Comment by zacharysarah** [comment]
@ahmetb Thanks for opening this. The API docs in general need serious updates, both to content and how they're created and updated. It may be a while (6+ months?) before we can address API docs effectively, but this kind of detail helps scope the work that needs to be done.

**Comment by ahmetb** [comment]
I actually fixed most of these a while ago after the big docs shuffle happened prior to 1.7 release. We can close these.
