### ISSUE TITLE
k8s.io blocked be F-Secure Freedome VPN

### ISSUE THREAD

**Issue by snichme** [kubernetes/kubernetes.github.io#2632]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
The domain k8s.io is blocked by F-Secure VPN Freedome which means that follow in guides form the documentation doesn't work, for example running: 

```
kubectl create -f http://k8s.io/docs/tasks/configure-pod-container/task-pv-volume.yaml
```

**Proposed Solution:**
Contact F-Secure and have them dropped the block and ask them why it was blocked in the first place. I think that the request should come from the domain owner thus I haven't contact F-Secure my self.

**Comment by jaredbhatti** [comment]
Is kubernetes.io blocked or just k8s.io?

**Comment by snichme** [comment]
Not an issue anymore. Can now access both domains via Freedome.
