### ISSUE TITLE
I wish /docs/admin/admission-controllers/ documented the recommended set of admission controller plug-ins to use for Kubernetes 1.2

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes.github.io#265]
I wish /docs/admin/admission-controllers/ documented the recommended set of admission controller plug-ins to use for Kubernetes 1.2
That page currently documents the set for version 1.0

**Comment by jaredbhatti** [comment]
http://kubernetes.io/docs/admin/admission-controllers/#is-there-a-recommended-set-of-plug-ins-to-use 

Done and Done :)
