### ISSUE TITLE
Create doc roadmap

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes.github.io#266]
We need a plan for improving the docs, with individual issues filed.
- General issues
  - We need to simplify the way we describe the system. Our documentation presents more components and concepts than are necessary for users to understand.
  - Improve doc quality: progressive disclosure, diagrams, screenshots, etc.
  - Address documentation debt (out-of-date, incorrect, incomplete, duplicated, …)
  - Fix organization and navigation
  - SEO
- User docs (e.g., https://github.com/kubernetes/kubernetes/issues/15244)
  - Reference
  - [Cheatsheets / cookbooks](https://github.com/kubernetes/kubernetes/issues/15032)
  - How-to
  - Concepts, with diagrams
  - API docs with multi-language examples
- [Transition/migration guides](https://github.com/kubernetes/kubernetes/issues/22651)
- Decision-maker guides
- Troubleshooting guides
- [Planning guides](https://github.com/kubernetes/kubernetes/issues/10100)
- Admin docs
- Porting guides
- Developer docs (e.g., https://github.com/kubernetes/kubernetes/issues/19680)
- Doc infrastructure (generation, formatters, checkers, etc.)
- Examples and demos
  - Real apps
  - Out-of-the-box, recommended non-cloud storage solutions
  - Tutorials demonstrating how to run different types of workloads
  - Tutorials demonstrating core and latest K8s features
  - Tutorials demonstrating production-worthy deployments
  - Canned demos, with visualization

cc @kubernetes/docs @kubernetes/examples

**Comment by bgrant0607** [comment]
The overhaul proposal doesn't cover all these topics, but is here:
https://docs.google.com/document/d/12Nfj2E8tZL-CMnnpkSH9m5k_oqd4qJh4qDwYDxPGJJI/edit?ts=5705b1fc#

**Comment by bgrant0607** [comment]
Mocks:
https://docs.google.com/presentation/d/14mJwJGlwBJHIpMRGR-nYMSyyNk-kRpabyz74-YYXeTo/edit#slide=id.g12d21f53ed_2_11

**Comment by jaredbhatti** [comment]
I think with Q1 2017 here, we should write up a new plan with our milestones.  We've deviated a bit from what's listed in this issue. I also think we should make that plan public through the SIG-Docs group.

**Comment by jaredbhatti** [comment]
Steve Perry is owning this going forward, and he's giving regular updates in the SIG-Docs meeting for k8s.   

Tracking sheet here: https://docs.google.com/spreadsheets/d/1DGnDEUo2Y9lxJkKmQmGfno-4qpTE8WIDgOi3QDI-MJM/edit#gid=0
