### ISSUE TITLE
Input something directly to search on https://kubernetes.io/docs/

### ISSUE THREAD

**Issue by YuPengZTE** [kubernetes/kubernetes.github.io#2668]
**This is a...** 

- [ x] Feature Request
- [ ] Bug Report

**Problem:**
When I open https://kubernetes.io/docs/, I want to input something directly to search, and do not need to move the mouse to the search input text, like https://www.google.com.

**Proposed Solution:**
Add autofocus="autofocus" on _layouts/docwithnav.html

**Page to Update:**
http://kubernetes.io/...

**Comment by avdd** [comment]
You assume **everyone** wants to immediately search for **another page** as soon as they visit **every page**.  That's a very faulty assumption.
