### ISSUE TITLE
Update "node selection" documentation to reflect Beta affinity syntax

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes.github.io#2671]
https://kubernetes.io/docs/user-guide/node-selection/
uses the alpha annotation, but in 1.6 node and pod affinity/anti-affinity use the Affinity field of PodSpec.

cc/ @kevin-wangzefeng 
ref/ kubernetes/features#106
ref/ kubernetes/features#60

**Comment by kevin-wangzefeng** [comment]
Close this as #2699 merged.
