### ISSUE TITLE
I wish /docs/services/operations/#service-configuration-file existed

### ISSUE THREAD

**Issue by nehasinha** [kubernetes/kubernetes.github.io#268]
I wish /docs/services/operations/#service-configuration-file existed
http://kubernetes.io/docs/services/operations/#service-configuration-file

**Comment by johndmulhausen** [comment]
Fixed in https://github.com/kubernetes/kubernetes.github.io/commit/34c2002a1c8c4e73a17e11c302ca1cf11f13ac94
