### ISSUE TITLE
Deleting a deployment fails

### ISSUE THREAD

**Issue by b43646** [kubernetes/kubernetes.github.io#2685]
[Env]
Kubernetest V1.4.9

[Descriptions]
on my test env,  etcd/apiserver/control-manage/scheduler pods are deployed on different machines.
i met error information when deleting a deployment.  The deployment will be deleted when repeating the operation twice or three times.

[Log]

```
[root@localhost tt]# kubectl -s 15.114.100.73:80 delete -f webapp-deployment.yaml --timeout=600s
error: error when stopping "webapp-deployment.yaml": timed out waiting for the condition
```

[Question]
how to config apiserver or other components to make it pass?  Thanks

**Comment by henriquetruta** [comment]
@b43646 this issue should've been registered in kubernetes/kubernetes repo

**Comment by zacharysarah** [comment]
@b43646 Thanks for opening this issue. It looks like you're asking for specific help with your environment, rather than making a feature request for the docs. I encourage you to bring your question to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/).
