### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by Al-WaySlate** [kubernetes/kubernetes.github.io#2701]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**

Sorry, we hit a problem with the connection.
Your internet connection may have dropped.

Please refresh and try again.

Can’t use the interactive tutorial on iMac with latest Safari, aka tutorial is non-responsive

**Proposed Solution:**

No idea, if I was a programmer I probably didn’t need the tutorial anyway :)

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment]
Thank you for the feedback. We're looking into addressing this now.

**Comment by zacharysarah** [comment]
@Al-WaySlate It looks like the tutorial is working. Please re-open this issue if you encounter any difficulties.

<img width="950" alt="screen shot 2017-07-14 at 1 28 32 pm" src="https://user-images.githubusercontent.com/3210446/28225466-695ec862-6898-11e7-986a-d95a9bb89f8f.png">
