### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/explore-interactive/

### ISSUE THREAD

**Issue by fuho** [kubernetes/kubernetes.github.io#2702]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Kubernetes basics - Chapter 3 mentions :
```
Again, worth mentioning that the name of the container itself can be omitted in this case because we have only one running in the Pod.```

But it seems that omitting the container name is not supported:
```
 > kubectl exec env
error: expected 'exec POD_NAME COMMAND [ARG1] [ARG2] ... [ARGN]'.
POD_NAME and COMMAND are required arguments for the exec command
See 'kubectl exec -h' for help and examples.
```
**Proposed Solution:**
Remove that piece of advice?

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/explore-interactive/

<!--Optional Information (remove the comment tags around information you would like to include)-->
<!--Kubernetes Version:-->

<!--Additional Information:-->

**Comment by ahmetb** [comment]
@fuho `kubectl exec` defaults to the single/first container by default given the argument followed by `kubectl exec` is a valid pod name. You will get the error you pasted if the pod name is invalid, (in your case `env`).

You will not get this error if you specified a valid pod name followed by `kubectl exec`.

Here's an example:


```
$ kubectl run web --image nginx --port 80
deployment "web" created

$ kubectl get pod
NAME                   READY     STATUS    RESTARTS   AGE
web-4291803130-472lw   1/1       Running   0          5s

$ kubectl exec web-4291803130-472lw env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=web-4291803130-472lw
KUBERNETES_SERVICE_PORT=443
...

$ kubectl exec invalid
error: expected 'exec POD_NAME COMMAND [ARG1] [ARG2] ... [ARGN]'.
POD_NAME and COMMAND are required arguments for the exec command
See 'kubectl exec -h' for help and examples.
```

In the interactive tutorial, in step 2 of 4 you need to execute this:

    export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
echo Name of the Pod: $POD_NAME

and in Step 4 of 4, it makes you execute `kubectl exec $POD_NAME env` so this is valid advice.


If this makes sense, let's close the issue. The advice given in the tutorial  If not, please feel free to ask your question if it is still confusing.

**Comment by zacharysarah** [comment]
@fuho Thanks for opening this issue. Given @ahmetb's response, I'm closing this issue. 

Help is also available in the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/).
