### ISSUE TITLE
Issue with /docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by skytalemcc** [kubernetes/kubernetes.github.io#2706]
Dear Kubernets
Today I install the k8s .firstly ,I run the yum update to update all the rpm  in the centos 7 .
Then  i find my docker version is updated and  now released at 17.03.0-ce (2017-03-01) .but i dont notice it .
Then I install the kuberntes .
When i install the master ,everything is fine .
but when i run  the( yum install kubernetes-node  ) in the mirror,i find one issue 
---> Package yajl.x86_64 0:2.0.4-4.el7 will be installed
--> Processing Conflict: docker-engine-17.03.0.ce-1.el7.centos.x86_64 conflicts docker
--> Processing Conflict: docker-engine-17.03.0.ce-1.el7.centos.x86_64 conflicts docker-io
--> Processing Conflict: docker-engine-selinux-17.03.0.ce-1.el7.centos.noarch conflicts docker-selinux
--> Finished Dependency Resolution
Error: docker-engine conflicts with 2:docker-1.12.5-14.el7.centos.x86_64
Error: docker-engine-selinux conflicts with 2:container-selinux-1.12.5-14.el7.centos.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@minion1 7]# 
--------------------------------------------
I use the docker.yum resource to install it .I can not install the node now ,can anyway solve it ,thanks.

**Comment by zacharysarah** [comment]
@skytalemcc Thanks for opening this issue. It looks like you're seeking technical support rather than reporting an issue with the docs. I encourage you to bring your question to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/).
