### ISSUE TITLE
index.md missing in the website

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes.github.io#271]
For example, https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/admin/namespaces/index.md and https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/admin/namespaces.md both link to http://kubernetes.io/docs/admin/namespaces/, and the former doc was lost in the website. 

I can imagine this happening elsewhere. 

@kubernetes/docs @pwittrock

**Comment by johndmulhausen** [comment]
Fixed in https://github.com/kubernetes/kubernetes.github.io/commit/0d31281f270634040f19d5b427471ed0c636389a
