### ISSUE TITLE
taints/tolerations documentation for 1.6

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes.github.io#2737]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
Please refer to https://groups.google.com/forum/#!search/taints$2Ftolerations$20documentation$20effort$20for$201.6/kubernetes-sig-scheduling/MFt4zjtaRuI/NrOOaSULEgAJ for detail.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by ravisantoshgudimetla** [comment]
@gyliu513 I'd recommend to add milestone 1.6 to these PR's. It seems 03/17 is last date for documentation changes.

**Comment by gyliu513** [comment]
Seems I donot have permission to add labels for those PRs, can you please help @ravisantoshgudimetla

**Comment by ravisantoshgudimetla** [comment]
@gyliu513 I don't have either.   

/cc @aveshagarwal @timothysc @davidopp

**Comment by gyliu513** [comment]
cc @kubernetes/sig-docs-maintainers I think that this needs to catch 1.6 release, can anyone help? Thanks!

**Comment by davidopp** [comment]
I found out that it is possible to change the branch after the PR is created (go to "edit" in the PR on Github, and change the base branch). So, I have modified your PRs to now point to the release-1.6 branch.

**Comment by gyliu513** [comment]
@aveshagarwal @davidopp shall we close this issue?

**Comment by gyliu513** [comment]
@davidopp @aveshagarwal do you know when we need to merge this to master branch or it will be merged automatically?

**Comment by davidopp** [comment]
Yes the docs team will take care of that.
