### ISSUE TITLE
Issue with /docs/admin/resourcequota/walkthrough/

### ISSUE THREAD

**Issue by ttripp** [kubernetes/kubernetes.github.io#2740]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**

All the examples are opaque because it does -f with a specified file without showing the file contents

**Proposed Solution:**

Can you include a link to the file that was used in the examples?

**Page to Update:**
http://kubernetes.io/docs/admin/resourcequota/walkthrough/

**Comment by zacharysarah** [comment]
@ttripp Thanks for opening this issue. If you look at the reference for [`kubectl create`](https://kubernetes.io/docs/user-guide/kubectl/v1.7/#create), the `-f` flag specifies:

> Filename, directory, or URL to files to use to create the resource

The code samples here for `kubectl create -f` all point to URLs for YAML files. For example:
```shell
kubectl create -f https://k8s.io/docs/tasks/configure-pod-container/rq-best-effort.yaml
``` 
Visiting [the URL](https://k8s.io/docs/tasks/configure-pod-container/rq-best-effort.yaml) returns:
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: best-effort
spec:
  hard:
    pods: "10"
  scopes:
  - BestEffort
```

Does that make sense? 

I'm going to close this issue; if you have any further questions, feel free to re-open it. You can also bring questions to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/).

Also, I'm updating the title of this issue to reflect that the content you reported has a different pathway now: `/docs/tasks/administer-cluster/apply-resource-quota-limit/`.
