### ISSUE TITLE
Issue with /docs/user-guide/persistent-volumes/

### ISSUE THREAD

**Issue by oxygenpresident** [kubernetes/kubernetes.github.io#2757]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
why StorageClasses doesn't have a provisioner for nfs?
**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

1.4.0

**Comment by zacharysarah** [comment]
@oxygenpresident Thanks for opening this issue. This looks like a feature request for Kubernetes itself, rather than for the docs. I recommend opening this issue in [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/issues).
