### ISSUE TITLE
Issue with /docs/user-guide/pods/multi-container/

### ISSUE THREAD

**Issue by thisisdavidbell** [kubernetes/kubernetes.github.io#2759]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
I came to this page clearly looking for doc on how to add multiple containers to a single pod, given the basic tutorials I have found specify a single container image. 

**Proposed Solution:**
Please provide a link directly to this information, rather than state there are a few general places doc may now be.

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
@thisisdavidbell is this still applicable? Looks like the page now redirects to https://kubernetes.io/docs/tasks/configure-pod-container/communicate-containers-same-pod/ which shows how to run multiple containers in a pod.

**Comment by zacharysarah** [comment]
Verified that the [docs](https://kubernetes.io/docs/tasks/configure-pod-container/communicate-containers-same-pod/) do contain a walkthrough for running multiple containers in a pod. Closing this issue.
