### ISSUE TITLE
I wish /docs/user-guide/services/ had a link to old versions of the documentation

### ISSUE THREAD

**Issue by rwillmer** [kubernetes/kubernetes.github.io#276]
I wish /docs/user-guide/services/ had a link to old versions of the documentation.

I'm trying to write a config yaml to create a service; I'm following the example on this page, but am getting an invalid error.

I suspect this is because the version of the K8S code I am using is older than this documentation; it would be good to be able to see the version of the documentation which matched my running system (v1.1.7)

**Comment by johndmulhausen** [comment]
You can see that version! Check out the release-1.1 branch: https://github.com/kubernetes/kubernetes.github.io/tree/release-1.1

There's a greater discussion around old doc versions and presenting them that we don't really wanna track here, but I hope that helps. :)
