### ISSUE TITLE
I wish /docs/user-guide/services/ had an example in the "External IPs" section that worked

### ISSUE THREAD

**Issue by rwillmer** [kubernetes/kubernetes.github.io#277]
I wish /docs/user-guide/services/ had an example in the "External IPs" section that worked

I've tried taking that example JSON and using it with a 'kubectl create -f' command; it fails with an invalid field error on "externalIPs"

**Comment by jaredbhatti** [comment]
Created a tutorial for this: http://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/

The page that you reference in this issue is more of a reference doc.
