### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/expose-interactive/: how to get exposed IP of service?

### ISSUE THREAD

**Issue by mappedinn** [kubernetes/kubernetes.github.io#2772]
**This is a request for extra details on the documentation regarding how to expose an application** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
This is a request for extra details on the documentation regarding how to expose an application.
The creation of the service `kubernetes-bootcamp` was successful on the **website** and **my machine**.

```sh
$ kubectl expose deployment/kubernetes-bootcamp --type="NodePort" --port 8080
service "kubernetes-bootcamp" exposed

$ kubectl get services
NAME                  CLUSTER-IP   EXTERNAL-IP   PORT(S)          AGE
kubernetes            10.0.0.1     <none>        443/TCP          1d
kubernetes-bootcamp   10.0.0.176   <nodes>       8080:31715/TCP   41s
```

Below a desc of the service:

```sh
$ kubectl describe services/kubernetes-bootcamp
Name:           kubernetes-bootcamp
Namespace:      default
Labels:         run=kubernetes-bootcamp
Selector:       run=kubernetes-bootcamp
Type:           NodePort
IP:         10.0.0.176
Port:           <unset> 8080/TCP
NodePort:       <unset> 31715/TCP
Endpoints:      172.17.0.3:8080
Session Affinity:   None
No events.
```

Now, I am trying to check if the application is exposed or not!

**PS:** these checks below are done on my machine! The checks on the website are all successful but the host `host01` is not known for my machine minikube.

```sh
$ export NODE_PORT=$(kubectl get services/kubernetes-bootcamp -o go-template='{{(index .spec.ports 0).nodePort}}')
$ echo $NODE_PORT
31715

## Checking as mentionned on the website
$ curl host01:$NODE_PORT
## return nothing... Exited from it by Ctrl+C

# Checking based on the IP address of the service 'kubernetes-bootcamp' that I obtained from
$ curl 172.17.0.3:$NODE_PORT
curl: (7) Failed to connect to 172.17.0.3 port 31715: No route to host
```

So, how to get the exposed IP address of the service 'kubernetes-bootcamp'???

**Proposed Solution:**

Add in the documentation how to get the exposed IP address of the service 'kubernetes-bootcamp'.

**Page to Update:**
[http://kubernetes.io/docs/tutorials/kubernetes-basics/expose-interactive/](http://kubernetes.io/docs/tutorials/kubernetes-basics/expose-interactive/)

**Comment by ahmetb** [comment]
@mappedinn in this example `10.0.0.176` is actually the IP address that's exposed for this service. 
 `kubectl get services` output has ClusterIP or ExternalIP columns. This example uses ClusterIP and that's the IP address that would work on your Kubernetes cluster.

**Comment by mappedinn** [comment]
Since I am using minikube, the IP address was obtained though `$ minikuber ip`.

Obtaining the port was done as you mentionned through `kubectl get services`

Thanks,
