### ISSUE TITLE
I wish /docs/user-guide/secrets/ Was more clear regarding the need to rename ssh keys and known_hosts files once they are mounted.  Extra points if yaml format for secrets was also covered.

### ISSUE THREAD

**Issue by icorbett** [kubernetes/kubernetes.github.io#278]
I wish /docs/user-guide/secrets/ Was more clear regarding the need to rename ssh keys and known_hosts files once they are mounted as kubernetes does not support underscores in key names.  Extra points if yaml format for secrets was also covered.

**Comment by jaredbhatti** [comment]
http://kubernetes.io/docs/user-guide/secrets/#creating-a-secret-manually
