### ISSUE TITLE
Issue with /docs/user-guide/node-selection/: "If selected node are all NotReady"

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/kubernetes.github.io#2795]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
If I use node affinity  to make pod schedule onto selected nodes, while these selected nodes are all "NotReady". Will the pod be terminated at once ?  Or it waits until some of these selected nodes turn to be "Ready", if so what's waiting period?

**Proposed Solution:**
I want to know whether it will be terminated.
If not, what is the wait period, and could it be modified?  

**Page to Update:**
https://kubernetes.io/docs/user-guide/node-selection/

**Comment by zacharysarah** [comment]
@zhangxiaoyu-zidif Thanks for opening this issue. I've tagged it for technical review.

**Comment by zhangxiaoyu-zidif** [comment]
I know the result, in this case, it would not be scheduled...
So I can close it now. =)
