### ISSUE TITLE
Natural getting started flow implies GCP is required

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes.github.io#282]
If I go to http://kubernetes.io/ and click Try Kubernetes, it takes me to http://kubernetes.io/docs/hellonode/, which says "If you don’t already have a Google Account (Gmail or Google Apps), you must create one.".  If a person did not know otherwise, they could get the impression that Kubernetes only runs on GCP.  There should at least be a sentence about "Kubernetes works on many types of virtual and real hardware.  This example uses GCP".  Maybe also link to cluster-creation guides.

**Comment by MHBauer** [comment]
Similarly, the intro shouldn't require a cloud environment that you have to pay to use.

**Comment by jaredbhatti** [comment]
Fixed with the new tutorial.  Closing.
