### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by carschno** [kubernetes/kubernetes.github.io#2833]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
In step 3 of Module 2, the proxy URL in the `curl` call is not really readable. It also seems to be wrong, my impression is that it should be `http://127.0.0.1:8001/api/v1/namespaces/default/pods/$POD_NAME`

**Proposed Solution:**
Find a way to display long lines in a more readable way and check/fix the URL.

**Page to Update:**
http://kubernetes.io/...

**Comment by zacharysarah** [comment]
@carschno Thanks for opening this issue. The wrapping for that line is pretty awkward.

I'm tagging this for technical review of the URL.

/cc @BenHall for input on line-wrapping URLs in the tutorial

**Comment by BenHall** [comment]
We're investigating how to improve this. Let me loop back in and see where we're at. 

Thanks for the prompt/suggestion.

**Comment by BenHall** [comment]
This has now been fixed and lines wrap as expected.
