### ISSUE TITLE
Issue with /docs/getting-started-guides/kops/

### ISSUE THREAD

**Issue by tomweston** [kubernetes/kubernetes.github.io#2861]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
The eu-west-2 (london az) is not yet known to kops.

Running:
`kops create cluster --zones=eu-west-2 eu-west-2.dev.mydomain.com`

Fails with the following result:
`unable to infer CloudProvider from Zones (is there a typo in --zones?)`

**Proposed Solution:**
Add the eu-west-2 az to kops.

**Comment by chrislovecnm** [comment]
This is a bug that is filed upstream and in the kops repo.  Thanks for the error report!

**Comment by zacharysarah** [comment]
@tomweston Thanks for opening this issue.

@chrislovecnm Do the docs need to be updated, or can we close this issue?

**Comment by chrislovecnm** [comment]
@zacharysarah this should be fixed!  Please close, and @tomweston please re-open if you need to!

**Comment by zacharysarah** [comment]
@chrislovecnm Thanks!
