### ISSUE TITLE
Update docs/tutorials/stateful-application/zookeeper.{md,yaml} to use PodSpec affinity field instead of annotation

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes.github.io#2904]
@enisoc @foxish @kow3ns could one of you do this?

**Comment by kow3ns** [comment]
\assign kow3ns

**Comment by davidopp** [comment]
This is pretty urgent, as the example will not work with 1.6.

**Comment by foxish** [comment]
/unassign
Thanks @davidopp 
@kow3ns is taking this one.

**Comment by kow3ns** [comment]
#3013

**Comment by kow3ns** [comment]
@davidopp So we need to update all helm charts as well?

**Comment by davidopp** [comment]
Yes, any controller definitions that used the alpha (annotation) version of node or pod affinity need to change to use fields.

**Comment by davidopp** [comment]
(Concretely, move the contents of the affinity annotation into the affinity field of the PodSpec)

**Comment by kow3ns** [comment]
@davidopp so v1.6 scheduler will not respect the anti-affinity annotation at all? That is, do users need to update their Pods and Pod containers to use the field post upgrade?

**Comment by davidopp** [comment]
Correct.

I did send emails to kubernetes-users and kubernetes-dev about it.

https://groups.google.com/d/msg/kubernetes-users/8jmQVipeRMs/G51ZbNVzDQAJ
https://groups.google.com/d/msg/kubernetes-users/xf-VlRlAm2A/Th76aF-lAwAJ

(and corresponding emails to kubenetes-dev)

**Comment by davidopp** [comment]
They don't need to update the already-running pods, just the PodSpec / pod template in their controllers.

**Comment by foxish** [comment]
On a less related note: with helm charts, it seems to me like we need some notion of versioning of charts to ensure that there are different working versions of each chart for 2-3 latest K8s versions.

**Comment by kow3ns** [comment]
\close

**Comment by kow3ns** [comment]
fixed in #3013
