### ISSUE TITLE
Issue with /docs/tutorials/federation/set-up-cluster-federation-kubefed/

### ISSUE THREAD

**Issue by allannaim** [kubernetes/kubernetes.github.io#2909]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
Getting kubefed section should cover OSX, Linux and Windows. Today, it's only Linux. 

**Proposed Solution:**
Follow the same guidelines as how we get Kubectl

Download the latest release with the command:
# OS X
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/kubectl

# Linux
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl

# Windows
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/windows/amd64/kubectl.exe

**Page to Update:**
http://kubernetes.io/...

@madhusudancs @csbell

**Comment by madhusudancs** [comment]
@allannaim addressed in PR #2899.
