### ISSUE TITLE
Document which network providers work with kubeadm 1.6

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubernetes.github.io#2942]
This is a "Feature Request" for 1.6

**Problem:**

kubeadm/kubernetes 1.6 has new requirements for CNI based network providers.  We need to make it clear which network plugins work.

**Proposed Solution:**

Update the list of network addons to call out which ones have been updated for 1.6 (and kubeadm).

**Page to Update:**
https://kubernetes.io/docs/admin/addons/

**Other Details:**
We need to make sure that plugins:
1. Support RBAC
2. Support new taints for kubeadm
3. don't suffer from start up issues when pods are started before CNI

See also:
https://github.com/kubernetes/kubernetes/issues/43014
https://github.com/kubernetes/kubeadm/issues/143

**Comment by jbeda** [comment]
**Calico:** @tomdee You say you have a fix for Calico but http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/ still points to the old stuff.  What should I point docs at?

**Flannel:** What do we need to do to get Flannel working?  https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml looks like it won't work at all.

**Weave:** It looks like https://www.weave.works/docs/net/latest/kube-addon/ still points to an old manifest.  What should I point 1.6 docs at.

**Canal:** It looks like https://github.com/projectcalico/canal/blob/master/k8s-install/kubeadm/canal.yaml isn't ready.  @netroby @heschlie?

**Contiv:** Not sure what is going on here but I've never used it.  @rhim -- can you confirm that Contiv works with kubeadm 1.6.

**Romana:** Doesn't look ready for 1.6.  @chrismarino -- can you confirm?

**Comment by monadic** [comment]
probably https://github.com/weaveworks/weave/releases/tag/v1.9.4 for weave net but I shall check with @bboreham

**Comment by jbeda** [comment]
@bowei created this spreadsheet to start figuring what the current support is: https://docs.google.com/spreadsheets/d/1Nqa6y4J3kEE2wW_wNFSwuAuADAl74vdN6jYGmwXRBv8/edit#gid=0.  

But we need to lock down what we point users at.  Most of the landing pages haven't been updated yet.

**Comment by djosborne** [comment]
It doesn't fit in the spreadsheet well, but figured I'd mention - we're working on a Calico v2.1.1 release which includes the updated Calico CNI plugin and manifests for deploying with Kubernetes v1.6. Aiming to complete by EOD.

**Comment by andrewrynhard** [comment]
For flannel there is:
1) https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel-rbac.yml for RBAC
2) https://github.com/coreos/flannel/pull/618 for master taint
3) my experience with flannel is that pods are started before CNI

**Comment by cmluciano** [comment]
Looks like I need to first run https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel-rbac.yml and then I can run https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml . 

@tomdee can you confirm?

**Comment by tomdee** [comment]
@cmluciano Yes, that's right. I just merged https://github.com/coreos/flannel/pull/614 which should mean there's one less command to run.

**Comment by cmluciano** [comment]
👍🏽 testing now

**Comment by cmluciano** [comment]
I'm having issues with that Flannel deploy, will open issue on flannel

**Comment by rhim** [comment]
will try out and update the thread

**Comment by bowei** [comment]
@djosborne -- you are free to add columns, edit the spreadsheet as you see fit ...

 can the others (canal, contiv, romana) update the spreadsheet as well. I'm having trouble trying to correlate the conversation thread across different github issues.

https://docs.google.com/spreadsheets/d/1Nqa6y4J3kEE2wW_wNFSwuAuADAl74vdN6jYGmwXRBv8/edit#gid=0.

I am going to write a release note with a list of verified compatible CNI plugins from the data in the spreadsheet

**Comment by unclejack** [comment]
Issue #44041 is causing some issues when plugins are deployed with kubeadm. Perhaps this could be investigated to sort out those issues?

**Comment by errordeveloper** [comment]
@jbeda if you check Weave docs page now there instructions for 1.6; however we are all subject to kubernetes#44041 now.

**Comment by pritesh** [comment]
@jbeda Romana supports 1.6 (PR: https://github.com/romana/romana/commit/42a64bf8654d7aeb67d7b43cd27c9f35800033bd) and it can be installed using: kubectl apply -f https://raw.githubusercontent.com/romana/romana/master/containerize/specs/romana-kubeadm.yml

**Comment by jbeda** [comment]
There are other updates in progress and most of the network plugins have been updated at this point.  Closing this.
