### ISSUE TITLE
Documentation: 404 Error when selecting "Annotations" under the Object Metadata heading towards the bottom of the Concepts page

### ISSUE THREAD

**Issue by tedops** [kubernetes/kubernetes.github.io#2960]
**This is a...** 

- [x] Bug Report

**Problem:**
Documentation: 404 Error (dead link) when selecting "Annotations" under the Object Metadata heading towards the bottom of the Concepts page

**Proposed Solution:**
Update the link target to https://kubernetes.io/docs/user-guide/annotations/ from the existing https://kubernetes.io/docs/concepts/object-metadata/annotations/.

**Page to Update:**
https://kubernetes.io/docs/concepts/

**Comment by zacharysarah** [comment]
@tedops Thanks for opening this issue. 

Noting that the correct path for updating is now `/docs/concepts/overview/working-with-objects/annotations/`.
