### ISSUE TITLE
MEAN Stack getting started page should list newer version of nodejs

### ISSUE THREAD

**Issue by SomeoneWeird** [kubernetes/kubernetes.github.io#297]
NodeJS 0.10 is going into security-only release mode very soon. The first version of 0.10 was released in March 2013, so it's over 3 years old. It would be great if we could update the tutorial/dockerfile to list the latest (or at least a newer) nodejs version.

**Comment by bgrant0607** [comment]
Resolved by#485, thanks to @rosskukulinski
