### ISSUE TITLE
Issue with /docs/reference/ "Kubernetes API" doesn't link to the reference

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes.github.io#2974]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:** "Kubernetes API" link is not going to the reference doc. It goes to a page, which redirects to article in "Concepts" area.

> ![image](https://cloud.githubusercontent.com/assets/159209/24259407/09e9eddc-0fae-11e7-8138-38d0989a9d38.png)

This makes it harder to reach the API reference by googling "kubernetes api".

**Proposed Solution:**  should link to https://kubernetes.io/docs/api-reference/v1/operations/ maybe? or https://kubernetes.io/docs/api-reference/v1.5/ ? I'm not sure what the difference is but will learn that soon.

**Page to Update:**
http://kubernetes.iodocs/reference/

**Comment by zacharysarah** [comment]
This appears to be linking correctly now. Feel free to re-open this if there's any concern. 👍
