### ISSUE TITLE
There is no doc page for API extensions and/or ThirdParty Resource...

### ISSUE THREAD

**Issue by chrismarino** [kubernetes/kubernetes.github.io#298]
Extensions to the API as a Third Party Resource does not seem to be included in the docs. 

They are explained here:

https://github.com/kubernetes/kubernetes/blob/release-1.2/docs/design/extending-api.md

But this page does not show up anywhere?

Network policy is applied via ThirdParty resource API. There may be others as well.

**Comment by jaredbhatti** [comment]
http://kubernetes.io/docs/user-guide/thirdpartyresources/

Also, the doc that you're pointing to is specifically for developers contributing to k8s.  Let me know if this doesn't solve it (and feel free to reopen the issue)
