### ISSUE TITLE
Issue with /docs/getting-started-guides/docker-multinode/

### ISSUE THREAD

**Issue by thanhpk** [kubernetes/kubernetes.github.io#2983]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

I have gone through the whole page but still don't know how to access the dashboard and how to point kubectl to this cluster setup. Can you guys give me some newbie instructions.

**Comment by zacharysarah** [comment]
@thanhpk 👋 Thanks for opening this issue. I wanted to let you know that the [page](https://kubernetes.io/docs/getting-started-guides/docker-multinode/) you opened an issue for was replaced with [docs for kubeadm](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/). 

If you still need individual help, I encourage you to bring your question to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/).
