### ISSUE TITLE
Search Results page is quite ugly

### ISSUE THREAD

**Issue by johndmulhausen** [kubernetes/kubernetes.github.io#3]
http://kubernetes.github.io/docs/search/?q=nodes

Too much whitespace, results not aligned with header. 

@CreaturesInUnitards

**Comment by CreaturesInUnitards** [comment]
Did a first pass at fixing this — let me know what you think.

**Comment by johndmulhausen** [comment]
Needs more work.

**Comment by johndmulhausen** [comment]
Example: http://kubernetes.github.io/docs/search/?q=nodes
cc @CreaturesInUnitards

**Comment by johndmulhausen** [comment]
Fixed with commit af265623af5c9e2382b417bd4c8499f29a632624
