### ISSUE TITLE
Issue with /docs/getting-started-guides/ubuntu/calico/

### ISSUE THREAD

**Issue by TheFausap** [kubernetes/kubernetes.github.io#3007]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The instructions are not compatible with latest calicoctl and docker (1.12).

**Proposed Solution:**
Is it possible to update the instructions (and the versions) to be used with docker 1.12 ?

**Page to Update:**
http://kubernetes.io/...

**Comment by caseydavenport** [comment]
Yikes, this is a really old guide.  I thought this was removed long ago - we should remove it now.

The latest Calico installation documentation [can be found on the Calico website](http://docs.projectcalico.org/v2.1/getting-started/kubernetes/installation/).

You can also follow the [kubeadm guide](https://kubernetes.io/docs/getting-started-guides/kubeadm/).

**Comment by TheFausap** [comment]
Thanks a lot!
