### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by akaRem** [kubernetes/kubernetes.github.io#3046]
I'm trying interactive tutorials on https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/

When I push "Start scenario" button, it shows me raccoon in the mask that asks for cookies.
Does it mean that service is down? Or .. what does it all mean!?
<img width="864" alt="2017-03-28 20 42 34" src="https://cloud.githubusercontent.com/assets/1472728/24419232/2627f532-13f7-11e7-95ba-0206d1d39602.png">

**Comment by jaredbhatti** [comment]
Cookies have to be enabled for you to use the interactive tutorial :(
