### ISSUE TITLE
Issue with /docs/user-guide/kubectl/

### ISSUE THREAD

**Issue by someword** [kubernetes/kubernetes.github.io#3053]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**

Links to kubectl subcommands are broken.   For example from this page https://kubernetes.io/docs/user-guide/kubectl/ if i select the kubectl_delete link which points to https://kubernetes.io/docs/user-guide/kubectl/kubectl_delete.md I get a 404.   Tried a few others and they all return 404
**Proposed Solution:**
Not clear from looking at the kubernetes/docs/user-guide where the problem is.  It looks like in the source repo files like kubectl_delete.md exist.

**Page to Update:**

https://kubernetes.io/docs/user-guide/kubectl

**Comment by someword** [comment]
FWIW - checking out git@github.com:kubernetes/kubernetes.git tag v1.6.0 and building the docs with hack/generate-docs.sh.  I am able to open docs/user-guide/kubectl/kubectl.md in a markdown editor (MacDown in this case) and the links to all of the kubectl subcommands (eg: kubectl_delete) open the desired subcommand page.

**Comment by foxish** [comment]
Just noticed that a lot of kubectl docs links are broken such as:
https://kubernetes.io/docs/user-guide/kubectl/kubectl_rollout/

Is there an issue tracking these?
cc @chenopis @kubernetes/sig-docs-maintainers

**Comment by chenopis** [comment]
@foxish No, not that I know of, but feel free to create one and assign me. I'll work on cleaning up the links.

**Comment by chenopis** [comment]
The links on https://kubernetes.io/docs/user-guide/kubectl/ should now work properly, e.g. kubectl delete goes to https://kubernetes.io/docs/user-guide/kubectl/v1.6/#delete

Is the issue also inbound links? Do we need a redirect to fix cases where people are using the old links?

**Comment by foxish** [comment]
Also fixed by #3160
/cc @chenopis

**Comment by chenopis** [comment]
I'll close this then.
