### ISSUE TITLE
Issue with /docs/reference/

### ISSUE THREAD

**Issue by jboeuf** [kubernetes/kubernetes.github.io#3063]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
kube-scheduler link points to https://kubernetes.io/docs/admin/kube-scheduler/ which gives a 404.

**Proposed Solution:**
Have a page at the end of the link or remove the link.

**Page to Update:**
http://kubernetes.io/...

**Comment by surajnarwade** [comment]
page was there till release-1.5, if its needs to be add again, shall I proceed to send a PR ?

**Comment by surajnarwade** [comment]
@jboeuf , `kube-scheduler.md` was there till 1.5 branch, shall I create PR for the same ?

**Comment by jboeuf** [comment]
Thanks for having a look @surajnarwade. 
I'm not really sure. I was just surprised, as a user of the doc to have a link to a 404. If the kube-scheduler is a thing, then it should be documented and I think that #3320 addresses that. Thanks!
