### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by JensRantil** [kubernetes/kubernetes.github.io#3076]
https://kubernetes.io/docs/admin/multiple-schedulers/ states

> Kubernetes ships with a default scheduler that is described here.

"here" points to https://kubernetes.io/docs/admin/kube-scheduler/ which gives a 404.

**Comment by vbmade2000** [comment]
@JensRantil  Where should this link point to ? Any idea ? I can correct it.

**Comment by JensRantil** [comment]
@vbmade2000 Maybe https://github.com/kubernetes/community/blob/master/contributors/devel/scheduler.md?

**Comment by surajnarwade** [comment]
@JensRantil @vbmade2000 , this issue duplicates the issue #3063

**Comment by JensRantil** [comment]
@surajnarwade Nice find. Closing.
