### ISSUE TITLE
Issue with https://kubernetes.io/docs/user-guide/kubectl/kubectl_logs/

### ISSUE THREAD

**Issue by erikbgithub** [kubernetes/kubernetes.github.io#3077]
Link doesn't exist anymore and there's no redirect.

**Comment by erikbgithub** [comment]
works now, thanks!

**Comment by ahmetb** [comment]
@erikbgithub can you please close?

**Comment by erikbgithub** [comment]
Oh I confused the closed symbol for the other ticket with this one. Sorry. Of course I close it.
