### ISSUE TITLE
Issue with /docs/concepts/containers/container-lifecycle-hooks/

### ISSUE THREAD

**Issue by erikbgithub** [kubernetes/kubernetes.github.io#3094]
It's a nice description of what hooks are and options the user has. But where to configure it? How about an example?

**Comment by ahmetb** [comment]
@erikbgithub you can find examples of container lifecycle hooks here: https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/

I am afraid it is currently a bit hard to find. Thanks for reporting. We should add a link to this /task from the /concept.

**Comment by erikbgithub** [comment]
That's awesome, thanks a lot!
