### ISSUE TITLE
Automatable Docs tasks

### ISSUE THREAD

**Issue by johndmulhausen** [kubernetes/kubernetes.github.io#310]
We need a script that checks for the following on all open PRs and prevents submission until these tests come back clean: 

Sub issues:
- [ ] #732
- [ ] #731 
- [ ] #733
- [ ] #734
- [ ] #735
- [ ] #736
- [ ] #737
- [ ] #738
- [ ] #739

@bgrant0607 @pwittrock @janetkuo

**Comment by janetkuo** [comment]
and auto assign reviewers

**Comment by bgrant0607** [comment]
Thanks!

Auto assign reviewer

Submit queue

**Comment by bgrant0607** [comment]
K8s YAML validation

**Comment by bgrant0607** [comment]
Previous issue: #102

**Comment by bgrant0607** [comment]
Link checking

**Comment by bgrant0607** [comment]
We've also discussed adding date last reviewed (as well as owners) to every doc, so we could enforce periodic reviews.

**Comment by bgrant0607** [comment]
Regarding labels: It would help if they were identical to the corresponding labels in the main (kubernetes) repo.

**Comment by bgrant0607** [comment]
cc @kubernetes/contributor-experience

**Comment by bgrant0607** [comment]
Move mungedocs: https://github.com/kubernetes/kubernetes/issues/29314

**Comment by bgrant0607** [comment]
One idea @johndmulhausen had was to automatically generate a PR containing necessary reformatting against the PR author's fork.

**Comment by jaredbhatti** [comment]
We're taking a different path towards automation issues.  Also, we should break up any general automation bug into specific tasks that can be completed.
