### ISSUE TITLE
Issue with https://kubernetes.io/docs/user-guide/kubectl/kubectl_create/

### ISSUE THREAD

**Issue by jseldess** [kubernetes/kubernetes.github.io#3116]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The docs page for [`kubectl_create`](https://kubernetes.io/docs/user-guide/kubectl/kubectl_create/) is returning a 404 error. Same for many other `kubectl` docs

**Proposed Solution:**

If these pages moved, put redirects in place.

**Comment by jseldess** [comment]
Ah, I see this is a duplicate of at least https://github.com/kubernetes/kubernetes.github.io/issues/3053. Feel free to close.

**Comment by foxish** [comment]
Also fixed by #3160
/cc @chenopis

**Comment by chenopis** [comment]
Yup, this should be working now.
