### ISSUE TITLE
kubectl docs links need update

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes.github.io#3124]
All links to kubectl commands referenced in various parts of the documentation need to be updated to point to the new links such as https://kubernetes.io/docs/user-guide/kubectl/v1.6/#expose
We're starting to see issues because of this (https://github.com/kubernetes/kubernetes.github.io/issues/3116, https://github.com/kubernetes/kubernetes.github.io/issues/3053)

Top priority would be to update the user-facing docs for kubectl commands, such as:

- https://kubernetes.io/docs/user-guide/kubectl/kubectl_create/
- https://kubernetes.io/docs/user-guide/kubectl/kubectl_run/
- ...

cc @chenopis

**Comment by chenopis** [comment]
PR #3160 addresses this w/ a change to the js/redirects.js file.

**Comment by chenopis** [comment]
@foxish Do you have time to do a tech review of PR #3160? Thx

**Comment by chenopis** [comment]
The PR was merged, so these should be working now. Cheers
