### ISSUE TITLE
Need to document how to get previous versions of kubeadm

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubernetes.github.io#3127]
**This is a Feature Request**

We have old versions in the various repositories now.  The one exception is kubeadm due to the vagaries of how versions sorted.  Yet the 1.5.5 version of kubeadm is available as a direct download.  We should document this someplace.

See https://github.com/kubernetes/release/issues/234.

**Comment by overip** [comment]
any update on this issue? 
Thank you so much.

**Comment by jbeda** [comment]
@overip The details are in https://github.com/kubernetes/release/issues/234 but you'll have to dig.  I'm going to start pulling together some more consumable instructions now.

**Comment by jbeda** [comment]
I'm collecting notes that are going to go in to the docs here: https://gist.github.com/jbeda/5e8a4ce0a23711da146e51900859c037

**Comment by luxas** [comment]
@jbeda Note that v1.5.5 of kubeadm probably can't deploy v1.5 clusters ;)

v1.6.0-alpha.0-2074+(somesha) is the stable v1.5 version of kubeadm

**Comment by jbeda** [comment]
Yeah -- take a look a the gist and let me know what you think.

**Comment by luxas** [comment]
Ah, sorry commented without taking a look at the gist -- it looks good to me!

**Comment by overip** [comment]
@jbeda it is great! Thank you so much!!!

**Comment by fabiand** [comment]
Is there actually an issue with keeping older builds in the repository?

**Comment by rushabh268** [comment]
Why can't we have all the older versions in the repository along with the newer ones?

**Comment by fabiand** [comment]
Indeed - It would just be so convenient, and yum would take the latest, and older version would only be taken if the complete NVR is given.

**Comment by jbeda** [comment]
@fabiand @rushabh268 -- @mikedanese is the guy that is driving this stuff and so he has the real story.  But the nitty gritty details are in kubernetes/release#234.  

Old versions for most components are in the repos.  However, the version string for the previous kubeadm was, confusingly, 1.6.0-alpha.  My understanding is that this caused problems when sorting with/against 1.6.0.  Again, Mike has the details.  For now I just want to get *some* solution documented.
