### ISSUE TITLE
kubectl_rollout page is not accessible

### ISSUE THREAD

**Issue by rahmanusta** [kubernetes/kubernetes.github.io#3171]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**

kubectl_rollout page is not accessible

https://kubernetes.io/docs/user-guide/kubectl/kubectl_rollout/

**Comment by foxish** [comment]
To be fixed by https://github.com/kubernetes/kubernetes.github.io/pull/3160

**Comment by foxish** [comment]
/close 

Fixed by #3160

**Comment by foxish** [comment]
cc @chenopis, can you close this as well?

**Comment by chenopis** [comment]
Yup.
