### ISSUE TITLE
Issue with /docs/concepts/workloads/controllers/deployment/

### ISSUE THREAD

**Issue by styshoo** [kubernetes/kubernetes.github.io#3192]
**This is a Bug Report.** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
When I create a Deployment with the nginx-deployment.yaml, it returns an error: "error: error validating "dpl_nginx.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false". After some query, it turn out to be a clerical error or something.

**Proposed Solution:**
At the top of nginx-deployment.yaml, the apiVersion is "apiVersion: apps/v1beta1", when I change it to "apiVersion: extensions/v1beta1", it works fine.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ahmetb** [comment]
@styshoo  this is because your client is v1.6 and server is v1.5. [[changelog]](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#deployment-2) The client uses apps/v1beta1 generator for Deployment but this doesn't exist on the server. I recommend upgrading your server or downgrading your client. (or just changing the `apiVerison` in yaml file)

**Comment by ahmetb** [comment]
I believe we can close this issue.

**Comment by styshoo** [comment]
@ahmetb yeah, you are right. After I upgraded Kubernetes to v1.6， the yaml worked. But I also have two suggestions to improve Kubernetes doc.
1. Add a doc version on the Kubernetes doc website. We can see the version of current doc, and we can also switch doc version. What I expect Is quite similar with the [Docker doc](https://docs.docker.com/), which has its doc version in the top-right corner.  
2. Add a current doc TOC in the doc, maybe in the right pane, because the main doc TOC Is in the left pane. When reading a Kubernetes doc, I usually page up and down to search content, but it would be more convenient if there is a doc TOC in the right pane.

Maybe I should close this issue and open a new one.
