### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/explore-interactive/

### ISSUE THREAD

**Issue by g-wattz** [kubernetes/kubernetes.github.io#3196]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Terminal inside the page won't load - renders as a blank gray image:

![screen shot 2017-04-01 at 11 56 50 am](https://cloud.githubusercontent.com/assets/18709005/24581115/53586c02-16d2-11e7-9b19-35786574125b.png)

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/explore-interactive/

Chrome Version 57.0.2987.98 (64-bit)
MacBook Air (13-inch, Early 2015)

**Comment by mikehuston** [comment]
FWIW, this also wasn't working for me several minutes ago but is working again now.

**Comment by ahmetb** [comment]
Can’t repro either. @g-wattz can you please check if it works now, if so can you please close?

**Comment by g-wattz** [comment]
Looks like it works now, I'll close this out.
