### ISSUE TITLE
Tutorial set-up-cluster-federation-kubefed uses GKE tokens expire quickly

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes.github.io#3197]
**This is a:**  Bug report

**Page to Update:** https://kubernetes.io/docs/tutorials/federation/set-up-cluster-federation-kubefed/

The [Setting up Cluster Federation with Kubefed](https://kubernetes.io/docs/tutorials/federation/set-up-cluster-federation-kubefed/) uses Google Container Engine (GKE) to illustrate how to set up federation using Kubernetes.

The way tutorial joins the clusters to the federation uses the the short-lived Google Cloud tokens stored in the context are passed to the federation host.

This is causing clusters that joined federation to go offline (listed at `kubectl get cluster --context=federation`) shortly after when short-lived tokens expire.

Therefore the tutorial provides a Federation Control Plane the user gets at the end works only for a brief period of time. The tutorial should provide a way to set up a Federation Control Plane that works seamlessly out of the box.

**Comment by madhusudancs** [comment]
@ahmetb @perotinus has a PR to fix this problem - https://github.com/kubernetes/kubernetes/pull/42042. Once that's merged, the problem in question here should go away. In the meantime, @kelseyhightower has a workaround described in https://github.com/kelseyhightower/kubernetes-cluster-federation/blob/master/labs/06-adding-clusters.md#generate-kubeconfigs-and-cluster-objects that could be imported to the kubefed doc. I will get to it if no one does, but I don't have an ETA. However, contributions to update the documentation are welcome.

**Comment by zacharysarah** [comment]
@ahmetb @madhusudancs 👋 Pinging for updates--it looks like https://github.com/kubernetes/kubernetes/pull/42042 was merged. Is there still a docs impact here, or can we close the issue?
