### ISSUE TITLE
Issue with /docs/getting-started-guides/kops/

### ISSUE THREAD

**Issue by kastork** [kubernetes/kubernetes.github.io#3198]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
After making the cluster with kops, you enter ` kubectl cluster-info`. This provides you with the URL to access the Kubernetes master node.  When you visit the provided URL, it prompts you with an HTTP basic auth.

What are the credentials needed?

- The tutorial at (`https://kubernetes.io/docs/getting-started-guides/kops/`) does not suggest anything.
- The output of `kops update ...` does not suggest anything
- `https://github.com/kubernetes/kops/blob/master/docs/aws.md` does not suggest anything
- The contents of the generated file when you enter `kops edit cluster <cluster name>` don't suggest anything.

I'm at a loss...

**Proposed Solution:**

Provide the credentials somewhere.

**Page to Update:**
http://kubernetes.io/...

**Comment by gtirloni** [comment]
That's the URL to the API Server and the credentials to access it are in ~/.kube/config and are automatically used by kubectl.

Maybe you're thinking of the Dashboard instead? That's an [add-on](https://github.com/kubernetes/kops/blob/master/docs/addons.md) that you have to install separately.

**Comment by kastork** [comment]
Yes, I thought this would be some kind of web interface.  I'll research the dashboard.
