### ISSUE TITLE
Issue with /docs/tasks/tls/managing-tls-in-a-cluster/

### ISSUE THREAD

**Issue by haribole** [kubernetes/kubernetes.github.io#3202]
**This is a...** 

- [ ] Feature Request
- [*] Bug Report

**Problem:**

When I try the command:

cat <<EOF | cfssl genkey - | cfssljson -bare server

I get the following error:

flag provided but not defined: -bare

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
I just downloaded cfssl/cfssljson on my mac and launched it successfully, what is your setup @haribole ?

```
cat <<EOF | ./cfssl genkey - | ./cfssljson -bare server
{
  "hosts": [
    "my-svc.my-namespace.svc.cluster.local",
    "my-pod.my-namespace.pod.cluster.local",
    "172.168.0.24",
    "10.0.34.2"
  ],
  "CN": "my-pod.my-namespace.pod.cluster.local",
  "key": {
    "algo": "ecdsa",
    "size": 256
  }
}
EOF

<hit Return>
<output:>

2017/04/04 20:55:59 [INFO] generate received request
2017/04/04 20:55:59 [INFO] received CSR
2017/04/04 20:55:59 [INFO] generating key: ecdsa-256
2017/04/04 20:55:59 [INFO] encoded CSR
```

**Comment by ahmetb** [comment]
@haribole have you been able to get this to work?

**Comment by zacharysarah** [comment]
@haribole Feel free to re-open this issue if you're still encountering difficulty.
