### ISSUE TITLE
We should be able to switch between docs versions

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes.github.io#322]
We should be able to switch between docs versions, both for users of older released versions, and so users of the current version aren't confused as we push new docs during the next release.

It sounds like this is already being worked on (https://github.com/kubernetes/kubernetes.github.io/issues/177#issuecomment-204108507), but I wanted to make sure we had a tracking issue specifically for it.

**Comment by jaredbhatti** [comment]
Thanks.  this is a known issue, but the site requires some significant restructuring to maintain multiple versions of the same page.

**Comment by mikeln** [comment]
+100 for this to get implemented.
