### ISSUE TITLE
Issue with /docs/concepts/workloads/controllers/deployment/

### ISSUE THREAD

**Issue by GeoTob** [kubernetes/kubernetes.github.io#3222]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Running the official deployment example fails on current kubectl/minikube.

```
$ curl https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/master/docs/concepts/workloads/controllers/nginx-deployment.yaml > nginx.yaml
$ kubectl create -f nginx.yaml
error: error validating "nginx.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false
$ kubectl create -f nginx.yaml --validate=false
error: unable to recognize "nginx.yaml": no matches for apps/, Kind=Deployment
```

**Proposed Solution:**
No idea?

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

Kubernetes Version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ahmetb** [comment]
@GeoTob this is because your client is v1.6 and server is v1.5. [[changelog]](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#deployment-2) The client uses apps/v1beta1 generator for Deployment but this doesn't exist on the server. I recommend upgrading your server or downgrading your client.

**Comment by GeoTob** [comment]
@ahmetb thanks for the help, I figured that out yesterday:)

It might be nice though to somehow ensure that examples work against the latest minikube out of the box (or at least put a warning somewhere)?

**Comment by ahmetb** [comment]
@r2d4 What’s the timeline for minikube to have a new ISO released with 1.6? Users with latest kubectl can't use it to run `kubectl run` because the default generator uses apps/v1beta1 which only exists in apiserver v1.6 and minikube is still 1.5.

**Comment by r2d4** [comment]
Here is the open PR switching 1.6 to the default version, we'll probably merge it tomorrow and do a release.  Sorry for the delay.

https://github.com/kubernetes/minikube/pull/1314

You can use 1.6 right now with the current version of minikube with `minikube start --kubernetes-version v1.6.0`

**Comment by GeoTob** [comment]
Hey guys , thanks for getting onto this and fixing this quickly :+1: Will close the issue now
