### ISSUE TITLE
Docs need to be versioned

### ISSUE THREAD

**Issue by waprin** [kubernetes/kubernetes.github.io#3239]
The documentation for Kubernetes only documents the latest release and offers no way to select a different version. See #3229.

**This is a...** 

- [x ] Feature Request
- [ ] Bug Report

**Problem:**

Basic stuff is changed and then basics tutorials are broken on major Kubernetes distributions like GKE.

**Proposed Solution:**

The docs are supported for at least a few recent versions, and a version picker is used to select the version of the docs you want to look at. See [Django docs](https://docs.djangoproject.com/en/1.10/) as an example (may others).

**Page to Update:**
http://kubernetes.io/...

**Comment by chenopis** [comment]
I'm targeting 2017Q3 to move k8s.io prod over to Netlify, after which we should be able to version the docs.

**Comment by ahmetb** [comment]
This is discussed at #3239. Closing as duplicate.

**Comment by ahmetb** [comment]
Looks like #3992 has more details. Closing this one.
