### ISSUE TITLE
Issue with /docs/tutorials/object-management-kubectl/declarative-object-management-configuration/

### ISSUE THREAD

**Issue by robsonpeixoto** [kubernetes/kubernetes.github.io#3245]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The value `apiVersion: apps/v1beta1`

**Proposed Solution:**
Should be `apiVersion: extensions/v1beta1`

**Page to Update:**
https://kubernetes.io/docs/tutorials/object-management-kubectl/declarative-object-management-configuration/
https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/master/docs/concepts/tools/simple_deployment.yaml

**Comment by ahmetb** [comment]
@robsonpeixoto  Kubernetes v1.6 uses `apps/v1beta1` and the documentation is reflecting the latest stable release.

**Comment by robsonpeixoto** [comment]
Thanks
