### ISSUE TITLE
Issue with /docs/tutorials/stateful-application/basic-stateful-set/

### ISSUE THREAD

**Issue by tianshapjq** [kubernetes/kubernetes.github.io#3249]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
In the "Using Stable Network Identities" chapter, I try the nslookup web-0.tomcat but could not resolve the IP of the pod web-0, as my StatefulSet is set to "tomcat" in my test. Meanwhile I can resolve the web-0.tomcat.default.svc.cluster.local. Is that we do not support this anymore?

I deploy the DNS discover by kubedns 1.9 which includes images of kubedns-amd64:1.9, dnsmasq-metrics-amd64:1.0, kube-dnsmasq-amd64:1.4 and exechealthz-amd64:1.2.

**Proposed Solution:**
If we do not support anymore then these specifications should be deleted.

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#using-stable-network-identities

Kubernetes Version:
1.5

**Comment by ahmetb** [comment]
@kow3ns can you please take a look at this?

**Comment by kow3ns** [comment]
@ahmetb looking

**Comment by zacharysarah** [comment]
@kow3ns 👋 Any updates?

**Comment by kow3ns** [comment]
@tianshapjq this tutorial works for me, can you post the manifests you used and the command you used to resolve the address?

**Comment by tianshapjq** [comment]
@kow3ns sorry for taking so long, but I can not reproduce this environment. I will close this temporarily, and reopen if occurs again :)
