### ISSUE TITLE
Issue with /docs/concepts/overview/kubernetes-api/

### ISSUE THREAD

**Issue by Fuzzo** [kubernetes/kubernetes.github.io#3251]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The Swagger Codegen 2.2.2, used to create a Java/Jersey2 client, does not provide a String constructor for the class `V1FinalizerName`.

The execution of the following code snippet:
```
                // client object init
		Apiv1Api v1 = new Apiv1Api(client);
		V1NamespaceList nsList = v1.listNamespace("true", null, null, null, null, null);
		for (V1Namespace ns : nsList.getItems()) {
			System.out.println(ns.getMetadata().getName());
		}

```
cause at runtime the error: 
`com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class com.vts.k8s.swagger.client.model.V1FinalizerName] from String value ('kubernetes'); no single-String constructor/factory method`

**Workaround:**
Add this to the generated `V1FinalizerName` class:
```
  public V1FinalizerName(String s) {
  }

```
**Proposed Solution:**
Fix the API definitions to have the String constructor in class `V1FinalizerName `using Swagger Codegen.

Kubernetes Version: 1.6.1
Swagger Codegen Version: 2.2.2

**Comment by ahmetb** [comment]
@Fuzzo I'm afraid this issue is not for the documentation. Can you please open an issue against kubernetes/kubernetes repository instead?

**Comment by Fuzzo** [comment]
[Done](https://github.com/kubernetes/kubernetes/issues/44433)

**Comment by ahmetb** [comment]
I believe we can close this issue.
