### ISSUE TITLE
Issue with /docs/tutorials/stateless-application/run-stateless-application-deployment/

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/kubernetes.github.io#3260]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
`$ kubectl create -f http://k8s.io/docs/tutorials/stateless-application/deployment.yaml`

results in 

error: error validating "http://k8s.io/docs/tutorials/stateless-application/deployment.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by mixj93** [comment]
the apiVersion in deployment.yaml should be "extensions/v1beta1" not "apps/v1beta1"

**Comment by ahmetb** [comment]
@grodrigues3  Kubernetes v1.6 uses `apps/v1beta1` and the documentation is reflecting the latest stable release.

**Comment by grodrigues3** [comment]
Thanks, I'll try upgrading my master to 1.6.x
