### ISSUE TITLE
Issue with /docs/concepts/workloads/pods/init-containers/

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes.github.io#3261]
**This is a...** 

- [ ] Feature Request
- [ x ] Bug Report

**Problem:**

Init containers doc has not been updated for 1.6.  Examples still use 1.5 annotations and don't show the new syntax.

**Proposed Solution:**

Update examples for 1.6.

Filing this bug mostly so that I remember to submit a patch.

**Page to Update:**
http://kubernetes.io/...

**Comment by foxish** [comment]
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#init-containers-in-use

This section should explicitly have an example showing the 1.6 version (init container field) in addition to the existing example for pre-1.6
It should also call them out explicitly.

@crimsonfaith91, Can you send a PR updating docs here?

**Comment by crimsonfaith91** [comment]
@foxish sure! :)

**Comment by crimsonfaith91** [comment]
@jberkus I am working on this issue. Apart from changing to 1.6 syntax for YAML files, I am thinking about showing `services.yaml`, or give a link to it. Where should I find the YAML file?

Is the line `i11:32 $ kubectl describe -f examples/init-container.yaml` a typo?

**Comment by jberkus** [comment]
@crimsonfaith91 not sure what you mean with services.yml?  Why would you need to show that?

**Comment by crimsonfaith91** [comment]
@jberkus I apologize for getting back to you late.

I am working on updating: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#init-containers-in-use

In the tutorial, there are a code snippet:
`$ kubectl create -f services.yaml
  service "myservice" created
  service "mydb" created`

As it mentions about `services.yaml`, i am thinking whether we need to include it (or a link to it) for easy reference by readers. However, i am not sure where should i find one (or have to create my own).

Tell me if i should work on another section of the tutorial. Thanks!

**Comment by jberkus** [comment]
Oh, yeah, I think you're right, we really need an example service.yaml file there because that's just confusing.  We'd have to create one from scratch, though, since that's just a dummy example.

**Comment by crimsonfaith91** [comment]
I see. I will create `services.yaml` from scratch too.
I plan to include both 1.5 and 1.6 YAML files as there are clients using 1.5. Will it be fine?

**Comment by crimsonfaith91** [comment]
I am able to create `services.yaml` and update the syntax of `myapp.yaml` to 1.6.
I will make a PR tomorrow. :)

**Comment by jberkus** [comment]
Looks good to me.  Closing issue. Thanks so much!
