### ISSUE TITLE
All link https://kubernetes.io/docs/reference/ in API References are broken

### ISSUE THREAD

**Issue by rvrignaud** [kubernetes/kubernetes.github.io#3269]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
When navigating to https://kubernetes.io/docs/reference/ all links in `API References` are broken (404)

**Page to Update:**
https://kubernetes.io/docs/reference/

**Comment by jaredbhatti** [comment]
Evaluating.  

Seems like the following links are broken, and they're missing from the left-nav. 
Autoscaling API - Manages autoscaling resources such as HorizontalPodAutoscalers.
Batch API - Manages batch resources such as Jobs.
Apps API - Manages apps resources such as StatefulSets.
Extensions API - Manages extensions resources such as Ingress, Deployments, and ReplicaSets.

**Comment by chenopis** [comment]
There's no reasonable place to redirect those individual links, so I removed them and cleaned up the ToC nav.
