### ISSUE TITLE
I wish /docs/user-guide/overview/ existed - it's linked from Github: https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/overview.md

### ISSUE THREAD

**Issue by seamonstr** [kubernetes/kubernetes.github.io#328]
I wish /docs/user-guide/overview/ existed - it's linked from Github: https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/overview.md

**Comment by johndmulhausen** [comment]
Proposed fix in https://github.com/kubernetes/kubernetes/pull/24311

**Comment by runseb** [comment]
This should be closed
