### ISSUE TITLE
Issue with /docs/tutorials/stateful-application/run-stateful-application/

### ISSUE THREAD

**Issue by craigbilner** [kubernetes/kubernetes.github.io#3292]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The `mysql-deployment.yaml` is showing the deployment with an `apiVersion` of `apps/v1beta1` which @ahmetb pointed out is supported by v1.6 of Kubernetes.

If you follow the tutorial, it blows up with a validation warning, `v1beta1.Deployment` cannot be found, which led me on a bit of a wild goose chase, but was because I'm on the "wrong version" of kubernetes.

**Proposed Solution:**
Could the docs explicitly declare which version of kubernetes is required and possibly provide yaml files per version?

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
@craigbilner  Kubernetes v1.6 and up uses `apps/v1beta1`. If you look at the `master` version of the YAML file here, you can see it using the new apiVersion: https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/tutorials/stateful-application/mysql-deployment.yaml

**Comment by craigbilner** [comment]
thanks @ahmetb, I couldn't find any documentation on how the `apiVersion` is derived. I looked at the [docs](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md) but it didn't indicate a kubectl version maps to an `apiVersion`. Would you be able to point me to some docs explaining it?

I've edited my issue to reflect my actual confusion.

**Comment by ahmetb** [comment]
@craigbilner agreed, a bit hard to find out. If your cluster uses v1.6, you can take a look at the API Reference here: https://kubernetes.io/docs/api-reference/v1.6/ If you click `Deployment` here, it tells you that it's in `apps` group.

**Comment by craigbilner** [comment]
@ahmetb oh I see, awesome, thanks. I've upgraded my cluster to 1.6 and everything's working, ta

**Comment by ahmetb** [comment]
@craigbilner np. please consider closing the issue.

**Comment by craigbilner** [comment]
@ahmetb the problem's still there for other people? Either the kubernetes error messages themselves should be a bit more explicit (hint at an incorrect version?) and/or the docs should support multiple yaml files, or at the very least say at the top this is for version 1.6.0 etc. ?

**Comment by ahmetb** [comment]
@craigbilner the discussion for the docs versioning is at #3239. This came up specifically because of the Deployment apiVersion changed and started breaking people.

**Comment by craigbilner** [comment]
np, ta
