### ISSUE TITLE
Explain how to setup ELK stack on GCE. Issue with /docs/tasks/debug-application-cluster/logging-elasticsearch-kibana/

### ISSUE THREAD

**Issue by gajus** [kubernetes/kubernetes.github.io#3316]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

The documentation page about ES and Kibana states:

> Note that Elasticsearch and Kibana do not work with Kubernetes clusters hosted on Google Container Engine.

– https://kubernetes.io/docs/tasks/debug-application-cluster/logging-elasticsearch-kibana/

However, it does not explain/ link to resources that explain how to setup ELK logging on Google Cloud Container. If it is not possible, it should should explicitly say that the only option is  Stackdriver Logging.

**Proposed Solution:**

Expand the documentation.

**Page to Update:**

* https://kubernetes.io/docs/tasks/debug-application-cluster/logging-elasticsearch-kibana/

**Comment by ahmetb** [comment]
@gajus I am not sure, but I think the reason ELK stack doesn't work on Google Container Engine is because it's a solution pre-configured by Google and you cannot modify the low level details like the logging configuration.

**Comment by ahmetb** [comment]
@crassirostris @piosz can you please explain why is the following the case for GKE?

> Note that Elasticsearch and Kibana do not work with Kubernetes clusters hosted on Google Container Engine.

It sounds like if you set up a DaemonSet, you can make GKE upload the logs anywhere you like. Obviously the `kube-up.sh` cannot be used for GKE, but saying "ELK stack don’t work on Container Engine" is misleading.

**Comment by crassirostris** [comment]
@ahmetb TBH, it existed there for quite some time, I haven't paid much attention to it, my fault.

> Obviously the kube-up.sh cannot be used for GKE, but saying "ELK stack don’t work on Container Engine" is misleading

I think that's what's meant by this phrase. I will send a PR to fix it shortly.

**Comment by crassirostris** [comment]
@gajus Overall, to the original question: we're pushing the idea that Kubernetes is not about logging or monitoring, it should just expose some integration points and let other solutions to integrate with it. We don't plan to support existing installation in the future, I would suggest taking a look at e.g https://github.com/pires/kubernetes-elasticsearch-cluster, it's much more up to date and well-supported

**Comment by crassirostris** [comment]
Damn, forgot to include the fix into the PR description

@chenopis Could you please close this one?
