### ISSUE TITLE
Issue installing Kube-Proxy for windows

### ISSUE THREAD

**Issue by rvbsalgado** [kubernetes/kubernetes.github.io#3317]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
When i´m trying to install Kube-Proxy, executing the command "go build cmd/kube-proxy/proxy.go", i receive the error message: "cmd\kube-proxy\app\options\options.go:104: cannot use fs (type *"k8s.io/kubernetes/vendor/github.com/spf13/pflag".FlagSet) as type *"k8s.io/apiserver/vendor/github.com/spf13/pflag".FlagSet in argument to feature.DefaultFeatureGate.AddFlag" 

PS: After cloning all the git repositories needed(should be mentioned in the getting-started-guides), the installation of kubelet was successful.  

Regarding kube-proxy can some one help me???

Thanks

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
@rvbsalgado It looks like https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/getting-started-guides/windows/index.md led you to this page and this has not been included in the issue. 

I recommend asking about this first on SIG-Windows channels listed at https://github.com/kubernetes/community/blob/master/sig-windows/README.md for a faster response, perhaps the folks at the SIG can update the docs and point you in the right direction.

**Comment by zacharysarah** [comment]
@rvbsalgado It looks like you're looking for support rather than reporting an issue with the docs. I encourage you to bring your question to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/).
