### ISSUE TITLE
Issue with /docs/getting-started-guides/ubuntu/

### ISSUE THREAD

**Issue by waldauf** [kubernetes/kubernetes.github.io#3321]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
$ sudo snap install conjure-up --classic
error: cannot perform the following tasks:
- Download snap "core" (1577) from channel "stable" (read tcp 10.0.2.15:41966->69.88.149.138:443: read: connection reset by peer)

**Proposed Solution:**
Not sure.

**Page to Update:**
http://kubernetes.io/...

I'm trying to install Kubernetes on Ubuntu Server (host in VBox) and got this error.

**Comment by waldauf** [comment]
Before installation I proceeded update & upgrade.

**Comment by ahmetb** [comment]
@waldauf looks like a temporary error in network. can you please try again?

**Comment by waldauf** [comment]
Now it works. Thanks for checking.
