### ISSUE TITLE
Page 404 not found

### ISSUE THREAD

**Issue by netroby** [kubernetes/kubernetes.github.io#3366]
The official project link to page 

https://kubernetes.io/docs/troubleshooting

Which seems 404

**Comment by ixdy** [comment]
What page contained this link?

**Comment by xiangpengzhao** [comment]
The content of former troubleshooting has been moved to https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/tasks/debug-application-cluster/troubleshooting.md

FYI: https://github.com/kubernetes/kubernetes.github.io/pull/3337

**Comment by xiangpengzhao** [comment]
@ixdy [support-content-moved.md](https://github.com/kubernetes/kubernetes.github.io/blob/master/_includes/support-content-moved.md) contains this link. And `support-content-moved.md` is contained by [deprecation-policy.md](https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/deprecation-policy.md) i.e. https://kubernetes.io/docs/deprecation-policy/

**Comment by netroby** [comment]
Made a pr to adjust the link at kubernetes repository. please take a look

**Comment by jaredbhatti** [comment]
I've asked Steve Perry to take a look at this content as well.  I think general troubleshooting information should be in a different location than under "tasks"

**Comment by chenopis** [comment]
I've moved Troubleshooting into the Home ToC as well as adding a blurb about it on the Home landing page. I also added a redirect for `/docs/troubleshooting` to go to the correct page.
