### ISSUE TITLE
Secrets and ConfigMap should be siblings in the doc

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes.github.io#338]
Secrets and ConfigMap are logically siblings to one another and this should be reflected in the doc.  Currently, the ConfigMap docs are linked to from 'Configuring Kubernetes' and the Secrets docs are linked only from the 'Concept Guide'.

I suggest we do one of the following:
1.  Link from 'Concept Guide' to ConfigMap and remove the link to the ConfigMap docs from the 'Configuring Kubernetes' list
2.  Link from 'Configuring Kubernetes' to the Secrets docs and remove the link in the Concept Guide.

We also need to add a stanza in the Concept Guide for ConfigMap, whether we link to the existing docs from there or not.

Thoughs, @johndmulhausen ?

**Comment by jaredbhatti** [comment]
Added information on Secretes to ConfigMap, and they're both under the same header in guides.  Should fix this the rest of the way with the site reorg.
