### ISSUE TITLE
Issue with /docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

### ISSUE THREAD

**Issue by tonglil** [kubernetes/kubernetes.github.io#3381]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

**Problem:**
The probe documentation should provide an example with a probe that has every parameter completed. Many app devs look for an example spec for guidance, and don't know there is an [API reference](https://kubernetes.io/docs/api-reference/v1.6/#probe-v1-core) (they are not K8s developers).

**Proposed Solution:**
Expand the example yaml to include these probe parameter (vs listing them in the "discussion section"):

-     timeoutSeconds
-     successThreshold
-     failureThreshold

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

**Comment by ahmetb** [comment]
@tonglil does #3494 solve this?

**Comment by tonglil** [comment]
Yes, excellent. Thank you.
