### ISSUE TITLE
Issue with /docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by vamsijakkula** [kubernetes/kubernetes.github.io#3406]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:** 
After Exeucting this command 
kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address $MASTER_IP

it hangs at the following line 

[apiclient] Created API client, waiting for the control plane to become ready 

Below are the installed versions !! Is there any issue specific to kubeadm 1.6.1

Setting up kubernetes-cni (0.5.1-00) ...
Setting up socat (1.7.3.1-1) ...
Setting up kubelet (1.6.1-00) ...
Setting up kubectl (1.6.1-00) ...
Setting up kubeadm (1.6.1-00) ...
Setting up ubuntu-fan (0.9.2) 

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
@vamsijakkula I would recommend seeking help in Kubernetes-users mailing list, IRC or Slack channels. This repository is for documentation issues.

**Comment by jaredbhatti** [comment]
Closing.
