### ISSUE TITLE
Issue with /docs/getting-started-guides/cloudstack/

### ISSUE THREAD

**Issue by ltupin** [kubernetes/kubernetes.github.io#3407]
**This is a...** 

- [x ] Bug Report

**Problem:**
The documentation regarding k8s installation on CloudStack is not up to date. The Ansible playbook refer to a github repository now defined to deploy on AWS ([see here](https://github.com/runseb/ansible-kubernetes.git)). All previous job for CS has been deleted.

**Proposed Solution:**
We can retrieve from git history the original work for CS ([last related commit](https://github.com/skippbox/ansible-aws/tree/db59b26cb6c9deedc0c2932da9f55b12e0faaf0b)). So I havae forked this repo to an **kubernetes-cloudstack** repo and update it. In the meantime we should correct the k8s documentation related page. I begin to work on it [there](https://github.com/ltupin/kubernetes-cloudstack) and I can validate it works.

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/cloudstack/

**Additional Information.**
I would be happy to update the k8s website page too and created the following issue https://github.com/kubernetes/kubernetes.github.io/pull/3430.

**Comment by jaredbhatti** [comment]
Thanks for the update.  Closing this issue.
