### ISSUE TITLE
Multiple incorrect relative links to docs

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes.github.io#341]
I wish http://kubernetes.io/docs/user-guide/service-accounts/working-with-resources/#resources-are-automatically-modified existed. It is linked to from http://kubernetes.io/docs/user-guide/service-accounts/

cc @kubernetes/docs

**Comment by janetkuo** [comment]
The link should be http://kubernetes.io/docs/user-guide/working-with-resources/#resources-are-automatically-modified

**Comment by janetkuo** [comment]
The link in .md is `working-with-resources/#resources-are-automatically-modified`. The format isn't correct, is it a tooling issue when converting the docs? @johndmulhausen

**Comment by janetkuo** [comment]
In http://kubernetes.io/docs/getting-started-guides/docker-multinode/, the link to "single node" is broken too. It should link to "/docs/..../docker.md" instead of just "docker.md"

**Comment by janetkuo** [comment]
In http://kubernetes.io/docs/api-reference/extensions/v1beta1/operations/, this link to "schema" was like http://kubernetes.io/docs/api-reference/extensions/v1beta1/operations/definitions/#_v1beta1_daemonsetlist but should be like http://kubernetes.io/docs/api-reference/extensions/v1beta1/operations/#_v1beta1_daemonsetlist

**Comment by johndmulhausen** [comment]
Looks like all the reported links here are fixed. Thanks all.
