### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/

### ISSUE THREAD

**Issue by kdureidy** [kubernetes/kubernetes.github.io#3429]
Allow the interactive tutorial terminal to work on iphone. 

**This is a...** 

- [ ] Feature Request
- [ x ] Bug Report

**Problem:**
The terminal does not work on iphone. I tried on safari and chrome but it still does not work. I enabled the brower request desktop site as well.

**Proposed Solution:**
Similar to gmail solution. There is a link to enforce desktop version of the site

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
The "Request Desktop Site" feature on mobile browsers use User-Agent header to fake the device as a desktop device. However I think the Kubernetes website doesn't use User-Agent header. It simply relies on viewport size (which is small on mobile) and renders a responsive version of the website.

The interactive tutorial requires a wide viewport, as it's an iframe to katakoda.com and I'm not sure if they've got any plans to support mobile. That’s basically where the "terminal" is hosted. I don't think this is something we can fix on k8s website. Please also try asking http://twitter.com/teamKatacoda

**Comment by jaredbhatti** [comment]
Yeah, I don't think it works on mobile devices.  I'll follow up with Katacoda, but since this isn't specifically a docs issue, I'm going to close.

**Comment by BenHall** [comment]
Thank you for the feedback. We're still working on how we can deliver a mobile optimised site but haven't found a great solution.

But you're right, in the meantime we should respect The "Request Desktop Site" feature.
