### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/explore-intro/

### ISSUE THREAD

**Issue by donghl** [kubernetes/kubernetes.github.io#3431]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
@donghl what's the issue?

**Comment by ahmetb** [comment]
@chenopis please close
