### ISSUE TITLE
Issue with /docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

### ISSUE THREAD

**Issue by timstoop** [kubernetes/kubernetes.github.io#3435]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
There is no description nor example on how to set up a TCP Probe, even though the option is mentioned. Although it might be obvious to veteran users, for greener users it is helpful to have examples available. For example, by reading the text, there's no indication whether a TCP Probe would be set up with `tcp` in the config or `tcpGet` or even something else entirely.

**Proposed Solution:**
Add an example of a TCP Probe as well.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

**Comment by ahmetb** [comment]
Looks like this is fixed. @chenopis can we close please/
