### ISSUE TITLE
Issue with /docs/tutorials/stateless-application/run-stateless-application-deployment/

### ISSUE THREAD

**Issue by rchapple** [kubernetes/kubernetes.github.io#3439]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
I think the "apiVersion" value in the example yaml files is incorrect.

If I submit that to my Tectonic Kubernetes cluster, I get:
" error validating data: API version "apps/v1beta1" isn't supported, only supports API versions ["componentconfig/v1alpha1" "extensions/v1beta1" "rbac.authorization.k8s.io/v1alpha1" "storage.k8s.io/v1beta1" "v1" "authentication.k8s.io/v1beta1" "authorization.k8s.io/v1beta1" "autoscaling/v1" "batch/v1" "batch/v2alpha1" "certificates.k8s.io/v1alpha1" "policy/v1alpha1" "federation/v1beta1" "apps/v1alpha1"]; if you choose to ignore these errors, turn validation off with --validate=false"

**Kubernetes Client/Server Versions:**
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6+coreos.0", GitCommit:"afa80ed4c07c36b753e370fc090bb3c6fc42f0e4", GitTreeState:"clean", BuildDate:"2017-03-29T03:36:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Proposed Solution:**
Should they be "apiVersion: extensions/v1beta1" instead of "apiVersion: apps/v1beta1"?

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
@rchapple  Kubernetes v1.6 uses `apps/v1beta1` and the documentation is reflecting the latest stable release. Your version looks old.

**Comment by rchapple** [comment]
@ahmetb -- you are correct.  Thanks for pointing that out.
