### ISSUE TITLE
I wish /docs/user-guide/overview/ would match the link from your github account

### ISSUE THREAD

**Issue by Setomidor** [kubernetes/kubernetes.github.io#344]
I wish /docs/user-guide/overview/ would match the link from your github account

**Comment by johndmulhausen** [comment]
There is no such page and never has been?

**Comment by Setomidor** [comment]
Right here:
https://github.com/kubernetes/kubernetes/blob/release-1.2/docs/user-guide/overview.md

**Comment by johndmulhausen** [comment]
@Setomidor Moved to http://kubernetes.io/docs/user-guide/
