### ISSUE TITLE
Issue with /docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by bjornl** [kubernetes/kubernetes.github.io#3440]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

On Ubuntu in addition to installing Docker one need to install package "aufs-tools" as dockerd may call aufs tools like "auplink" up on need.

This may be relevant for Docker on CentOS 7 too, I do not know with certainty.

**Proposed Solution:**
Replace line

apt-get install -y docker.io

with the line

apt-get install -y docker.io aufs-tools

**Page to Update:**
http://kubernetes.io/docs/getting-started-guides/kubeadm/

Kubernetes Version:
Kubernetes 1.5.1

Additional Information:
Ubuntu 16.10

**Comment by bjornl** [comment]
The root problem may be a missing dependency in the docker package on Ubuntu and derivatives. But needs to be addressed for kubeadm until it is resolved up stream by OS vendor.

**Comment by ahmetb** [comment]
cc: @mikedanese
