### ISSUE TITLE
Issue with /docs/tutorials/stateless-application/expose-external-ip-address-service/

### ISSUE THREAD

**Issue by puttpotsawee** [kubernetes/kubernetes.github.io#3443]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
I practice this tutorial using Google Cloud Container and I struggle quite a while on creating firewall rules.
When creating a service and `curl` to it, it returns no response due to the firewall block. At first, I thought I did something wrong in the previous step. This might lead to some confusion for others too.

**Proposed Solution:**
Since GCE is out of the scope of this tutorial, maybe you could add a link to create a firewall rule for GCE. As for me, I googled and found this link

http://stackoverflow.com/questions/42040238/how-to-expose-nodeport-to-internet-on-gce

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address-service/

**Comment by ahmetb** [comment]
@puttpotsawee is there any reason why you want to use `type: NodePort` instead of using `type: LoadBalancer` on gCE?

**Comment by puttpotsawee** [comment]
@ahmetb step 4 in this tutorial use `type=NodePort` while exposing the deployment, so I just follow the step, this is the good example for me to understand the concept of NodePort though.

**Comment by ahmetb** [comment]
@puttpotsawee understood. Thanks for your proposed solution. We are trying to eliminate Google Cloud specific documentation from Kubernetes site over time and move it to the Google Container Engine website. I'll make a note that we explain "How to expose NodePort on Container Engine"
