### ISSUE TITLE
Unable to create ingress deny policy from kubectl. 

### ISSUE THREAD

**Issue by pradeeppandeyy** [kubernetes/kubernetes.github.io#3459]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Unable to create ingress deny policy from kubectl. 

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

1.5.3

We have two namepaces  one is for MZ pods and onther is  for DMZ pods , I want to enable ingress deny policy in MZ from DMZ pods . All pods within same namespce will able to communicate with each other but DMZ should not allowed to communicate with MZ (except which are allowed).

**Comment by ahmetb** [comment]
@pradeeppandeyy this issue tracker is for documentation problems. If you're seeking help, please ask your question on StackOverflow, Slack or [mailing list](https://groups.google.com/forum/#!forum/kubernetes-users) all of which are listed at the bottom of kubernetes.io page.

**Comment by jaredbhatti** [comment]
Closing.
