### ISSUE TITLE
Kubectl namsapce Annotation, so that all traffic from outside namespace will block but not within namespace

### ISSUE THREAD

**Issue by pradeeppandeyy** [kubernetes/kubernetes.github.io#3460]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

How can I add annotation, so that all traffic from outside namespace will block but not within namespace from kubectl network policies. 

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

We have two namepaces  one is for MZ pods and onther is  for DMZ pods ,
I want to enable ingress deny policy in MZ namespace . All pods within same namespce will able to communicate  with each other but DMZ namespace pods should not allowed to communicate with MZ (except which are allowed) pods.

**Comment by ahmetb** [comment]
@pradeeppandeyy this issue tracker is for documentation problems. If you're seeking help, please ask your question on StackOverflow, Slack or [mailing list](https://groups.google.com/forum/#!forum/kubernetes-users) all of which are listed at the bottom of kubernetes.io page.

**Comment by jaredbhatti** [comment]
Closing this issue for now.
