### ISSUE TITLE
Issue with /docs/tutorials/stateless-application/hello-minikube/

### ISSUE THREAD

**Issue by conradwt** [kubernetes/kubernetes.github.io#3461]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

When I execute

$ minikube start --vm-driver=xhyve
Starting local Kubernetes cluster...
Starting VM...
SSH-ing files into VM...
Setting up certs...
Starting cluster components...
Connecting to cluster...
Setting up kubeconfig...
Kubectl is now configured to use the cluster.

$ kubectl config use-context minikube
Switched to context "minikube".

$ kubectl cluster-info

I get the following message

The connection to the server 192.168.99.100:8443 was refused - did you specify the right host or port?

setup is as follows

macOS 10.12.4
minikube v0.18.0
Docker for Mac CE 17.05.0-ce-rc1-mac8 (16582)

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
@conradwt looks like a minikube bug. Can you please file an issue at https://github.com/kubernetes/minikube/issues/new instead and close this one?

**Comment by jaredbhatti** [comment]
I'm going to close this issue since it's not a doc issue.  Please follow up with minikube!  Thanks!
