### ISSUE TITLE
Issue with /docs/getting-started-guides/docker-multinode/

### ISSUE THREAD

**Issue by sudhagarc** [kubernetes/kubernetes.github.io#3466]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The instructions in this page is outdated. The git repo mentioned (kube-deploy) in this page has updated the scripts as the scripts no longer work as expected.

**Proposed Solution:**
Could you please take this page offline or update with correct information?

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
@chenopis it looks like the page is already moved. Can we close?
