### ISSUE TITLE
Issue with /docs/reference/

### ISSUE THREAD

**Issue by dtaner** [kubernetes/kubernetes.github.io#3505]
**This is a...** 

- [ ] Feature Request
- [ x ] Bug Report

**Problem:**
extensions/..  links are broken

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
@dtaner you mean the extensions/.. under the Federation API section? I see that one is broken on the main Reference docs page. Sent #3545 to fix this (to basically remove the link from that page). The Federation links on the left sidebar are working though.
