### ISSUE TITLE
Need documentation for "deploy a .jar to k8s"

### ISSUE THREAD

**Issue by goltermann** [kubernetes/kubernetes.github.io#352]
Searching the internet doesn't give a lot of docs.  A tutorial about going from a .jar file to a containerized Java app running in k8s would be a useful addition.

**Comment by bgrant0607** [comment]
This is not really k8s-specific. It's more a docker thing, and it really depends on what the Java app's dependencies are.

Here's an example of a simple Dockerfile:
http://stackoverflow.com/questions/32352143/deploying-java-app-to-docker-image

**Comment by bgrant0607** [comment]
Could be an example of a focused "how-to" document.

cc @pwittrock @janetkuo @johndmulhausen

**Comment by pwittrock** [comment]
Agreed.  Maybe 3 how to guides: java, node, ruby

**Comment by pwittrock** [comment]
Would also be a good use of templates.
