### ISSUE TITLE
Issue with /docs/reference/ - broken links to model documentation

### ISSUE THREAD

**Issue by feliperoos** [kubernetes/kubernetes.github.io#3525]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Model definition links is broken

**Proposed Solution:**
Fix model definition link with current model definitions for each version

**Page to Update:**
http://kubernetes.io/docs/reference/

**Comment by ahmetb** [comment]
@feliperoos you mean the Federation API model link? I see that one is broken. Sent #3545 to fix this (to basically remove the link from that page). The Federation links on the left sidebar are working though.
