### ISSUE TITLE
Issue with /docs/tutorials/stateless-application/run-stateless-application-deployment/

### ISSUE THREAD

**Issue by naseemkullah** [kubernetes/kubernetes.github.io#3527]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**

error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false

when using yaml file provided in "Running a Stateless Applciation" on a K8S cluster on Google Cloud

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateless-application/run-stateless-application-deployment/

**Comment by ahmetb** [comment]
@naseemkullah your kubernetes cluster is probably running an older version v1.5. The examples on the website are updated to reflect the v1.6 which has the Deployment resource in `v1beta1/apps` API category now.

**Comment by naseemkullah** [comment]
Thanks Ahmet, client version is 1.6 but I see that server version is indeed
1.5

**Comment by jaredbhatti** [comment]
Marking this issue closed. Thanks!
