### ISSUE TITLE
Issue with /docs/getting-started-guides/ubuntu/manual/

### ISSUE THREAD

**Issue by feborges** [kubernetes/kubernetes.github.io#3549]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
I'm using the git clone (the link below), when it finished I didn't find the folder ubuntu.

git clone --depth 1 https://github.com/kubernetes/kubernetes.git

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
@feborges what's your output. It works on my setup. Are you sure it did not fail?

**Comment by feborges** [comment]
When I executed the command KUBERNETES_PROVIDER=ubuntu ./kube-up.sh from the link https://kubernetes.io/docs/getting-started-guides/ubuntu/manual/

The error is:

... Starting cluster using provider: ubuntu
... calling verify-prereqs
Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
... calling verify-kube-binaries
./kube-up.sh: line 45: verify-kube-binaries: command not found

**Comment by ahmetb** [comment]
So your `kubernetes` folder is now there? That's your original issue. I'd love to know if that worked first.

It looks like the documentation is a bit out of date given the `kube-up.sh` failed for you. 

I see that doc says "Cloud team from Zhejiang University will maintain this work." Does anybody know how we can get a hold of them?
