### ISSUE TITLE
/docs/admin/authorization/rbac/#controller-roles should say `--use-service-account-credentials` is required

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes.github.io#3556]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The cited doc section says that the controllers manager _can_ be given the `--use-service-account-credentials` argument but does not mention that this argument is *required*.  As far as I can tell, it *is required*.  When I tested release 1.6.2 without giving this argument many controllers failed due to lack of permissions.  Here is an example of a couple of error messages from stderr of the controllers manager:

E0426 19:05:39.573907       1 reflector.go:201] k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go:192: Failed to list <nil>: User "controller-manager" cannot list endpoints at the cluster scope. (get endpoints)

E0426 19:05:39.575049       1 reflector.go:201] k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go:192: Failed to list <nil>: User "controller-manager" cannot list limitranges at the cluster scope. (get limitranges)

And here are the corresponding entries from the log of the apiserver:

I0426 19:05:39.573471       1 rbac.go:87] RBAC DENY: user "controller-manager" groups [system:authenticated] cannot "list" resource "endpoints" cluster-wide

I0426 19:05:39.573583       1 wrap.go:75] GET /api/v1/endpoints?resourceVersion=0: (545.21µs) 403 [[hyperkube/v1.6.2 (linux/amd64) kubernetes/477efc3/generic-garbage-collector] 192.168.10.2:54776]

I0426 19:05:39.574746       1 rbac.go:87] RBAC DENY: user "controller-manager" groups [system:authenticated] cannot "list" resource "limitranges" cluster-wide

I0426 19:05:39.574794       1 wrap.go:75] GET /api/v1/limitranges?resourceVersion=0: (548.611µs) 403 [[hyperkube/v1.6.2 (linux/amd64) kubernetes/477efc3/generic-garbage-collector] 192.168.10.2:54776]

Yes, I used a non-standard username for the controllers manager, but I bound it to the `system:kube-controller-manager` ClusterRole.  That ClusterRole does *not* grant the privileges in question.

**Proposed Solution:**

Update the doc to say that the controllers manager _must_ be given the `--use-service-account-credentials` argument.

**Page to Update:**
https://kubernetes.io/docs/admin/authorization/rbac/#controller-roles

Kubernetes Version: 1.6.2

**Comment by liggitt** [comment]
It's not required. If you want to run all the control loops with a single credential, grant all the roles to that credential

**Comment by liggitt** [comment]
Will clarify that the individual controller roles must be granted as well

**Comment by jaredbhatti** [comment]
Any updates?
