### ISSUE TITLE
/docs/admin/daemons/ redirect URL is serving application/octet-stream

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes.github.io#3577]
If you visit https://kubernetes.io/docs/admin/daemons/ the browser is trying to download the page because it is served as `Content-Type: application/octet-stream`. I can't understand why.

But it's actually trying to do a redirect:

```
$ curl https://kubernetes.io/docs/admin/daemons/
<!DOCTYPE html>
<html lang="en-US">
  <meta charset="utf-8">
  <title>Redirecting…</title>
  <link rel="canonical" href="/docs/concepts/workloads/controllers/daemonset/">
  <meta http-equiv="refresh" content="0; url=/docs/concepts/workloads/controllers/daemonset/">
  <h1>Redirecting…</h1>
  <a href="/docs/concepts/workloads/controllers/daemonset/">Click here if you are not redirected.</a>
  <script>location="/docs/concepts/workloads/controllers/daemonset/"</script>
</html>
```

Could something be hinting github pages or nginx to interpret this as a non-HTML content? 

@steveperry-53 have you seen this in other redirections before?

**Comment by ahmetb** [comment]
@kubernetes/sig-docs-maintainers any ideas?

**Comment by chenopis** [comment]
I think I know what it is. There is a typo in the `redirect_from` directive in `/docs/concepts/workloads/controllers/daemonset.md`.

**Comment by chenopis** [comment]
Yup, that did the trick.
