### ISSUE TITLE
I wish /docs/hellonode/ had the table of contents and left navigation links as sticky when the page is scrolled

### ISSUE THREAD

**Issue by rajeshvaya** [kubernetes/kubernetes.github.io#358]
I wish /docs/hellonode/ had the table of contents and left navigation links as sticky when the page is scrolled

**Comment by jaredbhatti** [comment]
Yeah, I do too.  We don't really have the UX skills to build this out at the moment, so we haven't done it.  We're reorganzing the rest of the site and fixing other UX issues to address readability.
