### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by moveax3** [kubernetes/kubernetes.github.io#3590]
**This is a...** 

- [ ] Feature Request
- [ *] Bug Report

**Problem:**
[Error] Failed to load resource: Не удалось подключиться к серверу. (embed.js, line 0)

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
Can you please send a screenshot of the error? Is your browser’s cookie settings enabled?

**Comment by moveax3** [comment]
![2017-05-02 11 14 35](https://cloud.githubusercontent.com/assets/5323081/25606036/95369522-2f28-11e7-93a1-c1415736b175.png)

all browser functions is enabled, default setting, in safary and chrome and firefox.

**Comment by BenHall** [comment]
This looks like Cloudflare is blocking the HTTP request.

**Comment by ahmetb** [comment]
That sounds likely. What happens when you click to one of those font URLs or something and open in a separate tab?

**Comment by zacharysarah** [comment]
This looks more like a request for individual support and less of an issue with the docs per se. @moveax3, I encourage you to bring your question to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/).
