### ISSUE TITLE
Downward API doc 404 flash

### ISSUE THREAD

**Issue by Ngo-The-Trung** [kubernetes/kubernetes.github.io#3595]
This URL: https://kubernetes.io/v1.1/docs/user-guide/downward-api.html is the top most result when googling "kubernetes downward api". It eventually redirects to https://kubernetes.io/docs/user-guide/downward-api/ , although briefly flashes a "404 error" page before redirecting. I don't think the 404 flash is intended.

**Comment by ahmetb** [comment]
@Ngo-The-Trung it's currently intended until we have server-side redirects.

**Comment by jaredbhatti** [comment]
Yeah.  :(
Working on fixing this at some point, but not until the next quarter or two.
