### ISSUE TITLE
Issue with /docs/tutorials/stateless-application/run-stateless-ap-replication-controller/

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes.github.io#3598]
**This is a...** 
- [x] Bug Report

**Problem:**

https://kubernetes.io/docs/tutorials/stateless-application/run-stateless-ap-replication-controller/

This page is titled `Run Stateless AP Replication Controller`. I have no idea what `AP` means and it is not explained anywhere.

My only theory is that it is the availability/partition-tolerance, AP, part of the CAP theorem. I hope it’s not this because there’s really no way to tell that from the tutorial. 

cc: author @bprashanth

**Proposed Solution:**

- Find a better name for this document
- Move this next to the [Deployment tutorial](https://kubernetes.io/docs/tutorials/stateless-application/run-stateless-application-deployment/)
- See how much overlap between this and the [Deployment tutorial](https://kubernetes.io/docs/tutorials/stateless-application/run-stateless-application-deployment/) and if there’s any good reason to eliminate this as this tutorial might be obsolete in the presence of Deployment tutorial.

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateless-application/run-stateless-ap-replication-controller/

**Comment by jaredbhatti** [comment]
Looks like this has been fixed. Please reopen if there's still an issue.
