### ISSUE TITLE
Issue with /docs/concepts/configuration/manage-compute-resources-container/

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes.github.io#3608]
## Problem

https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/

Multiple statements in this page claim you can set resource limits on Pods (not at container-level). Such as:

>  A Pod resource request/limit for a particular resource type is the sum of the resource requests/limits of that type for each Container in the Pod.

1. There's no examples of this in the document.
2. Section “_Resource requests and limits of Pod and Container_“ only has examples of `spec.containers[].*`
3. The title of this doc says "_Managing Compute Resources for Containers_" (not Pods)
4. I can't find any examples of Pod-level resource requirements on the web.
5. I can't find any fields on the API reference for Pod (`kubectl explain pod.spec`)  to specify resource requirements.

## Proposed Solution

Investigate if “pod-level resource requirements” is a thing at all? If yes, document properly. If not, remove statements implying this feature exists from the doc.

## Page to Update
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/

**Comment by zoidbergwill** [comment]
I don't see anything in explain or the docs online either for [`v1.PodSpec`](https://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1_podspec).

Maybe the docs mean Pods just in the way that it's an aggregate of the `requests` for the containers, definitely worth clearing up though.

`pod.alpha.kubernetes.io/opaque-int-resource-foo: 1`  is also done container-level which is quite confusing from those docs.

The "Planned Improvements" section mentions: 

> Kubernetes version 1.5 only allows resource quantities to be specified on a Container. It is planned to improve accounting for resources that are shared by all Containers in a Pod, such as emptyDir volumes.

Everything looks like aggregated container configuration [here (`pkg/api/v1/resource/helpers.go`)](https://github.com/kubernetes/kubernetes/blob/600ab29e522d03b09290163a15b4a8314a34569c/pkg/api/v1/resource/helpers.go#L30)

**Comment by jaredbhatti** [comment]
I think this has been somewhat clarified in the section: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#resource-requests-and-limits-of-pod-and-container

"Although requests and limits can only be specified on individual Containers, it is convenient to talk about Pod resource requests and limits. A Pod resource request/limit for a particular resource type is the sum of the resource requests/limits of that type for each Container in the Pod."
