### ISSUE TITLE
Issue with /docs/getting-started-guides/ubuntu/local/

### ISSUE THREAD

**Issue by techtonik** [kubernetes/kubernetes.github.io#3612]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
It is not clear if LXD nodes are running Docker containers.

https://kubernetes.io/docs/getting-started-guides/ubuntu/local/

**Comment by ahmetb** [comment]
cc: @castrojo

**Comment by marcoceppi** [comment]
Thanks for the report. Yes, the LXD nodes serve as "machines" for running kubelet, the docker processes are then run inside of LXD. I'll put up a pull request to include a diagram and description

**Comment by techtonik** [comment]
Yes. Took time to figure it out. https://github.com/lxc/lxd/issues/670#issuecomment-298731344

**Comment by ahmetb** [comment]
@techtonik if you have time, we really appreciate if you can send a patch to the documentation to make ease other people’s potential pains in the future.

**Comment by techtonik** [comment]
@ahmetb see PR above.

**Comment by ahmetb** [comment]
Thanks.
