### ISSUE TITLE
Issue with /docs/getting-started-guides/minikube/

### ISSUE THREAD

**Issue by MarkRebuck** [kubernetes/kubernetes.github.io#3624]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

"On kubectl See the kubectl installation instructions for more details." ... the link points to https://kubernetes.io/docs/getting-started-guides/kubectl/ .  But if you follow that link, there is a message that the documentation is now at...

**Proposed Solution:**

https://kubernetes.io/docs/tasks/kubectl/install/

**Page to Update:**

http://kubernetes.io/docs/getting-started-guides/minikube/

**Comment by jaredbhatti** [comment]
Appears to be fixed.
