### ISSUE TITLE
Issue with /docs/getting-started-guides/minikube/

### ISSUE THREAD

**Issue by VijayVijayaguru** [kubernetes/kubernetes.github.io#3632]
Hi All,

First, thanks for providing online support on Kubernets.
I have loaded ubuntu 14.04 and I am trying to install minikube to discover docker containers.
I have referred below links for installation.

1.Installing Cloud SDK
https://cloud.google.com/sdk/downloads#linux

2. Installing and Setting Up kubectl
https://kubernetes.io/docs/tasks/kubectl/install/

3.Using a Service to Access an Application in a Cluster
https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address-service/

4.Running Kubernetes Locally via Minikube
https://kubernetes.io/docs/getting-started-guides/minikube/

Version details
############
Linux version: ubuntu=14.04
root@HAX-PNPV-1:~/google-cloud-sdk# 
root@HAX-PNPV-1:~/google-cloud-sdk# kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Error from server (NotFound): the server could not find the requested resource
root@HAX-PNPV-1:~/google-cloud-sdk# 
root@HAX-PNPV-1:~/google-cloud-sdk# 
root@HAX-PNPV-1:~/google-cloud-sdk# uname
Linux
root@HAX-PNPV-1:~/google-cloud-sdk# uname -r
4.2.0-42-generic
root@HAX-PNPV-1:~/google-cloud-sdk# 
root@HAX-PNPV-1:~/google-cloud-sdk# 

I am getting below error when running kubectl run hello-world command, could any one please help on this.

root@HAX-PNPV-1:~/google-cloud-sdk# kubectl run hello-world --replicas=2 --labels="run=load-balancer-example" --image=gcr.io/google-samples/node-hello:1.0  --port=8080
Error from server (NotFound): the server could not find the requested resource (post replicationcontrollers)

Thanks,
Vijay

**Comment by jaredbhatti** [comment]
This issue queue is only for docs :(  Can you try the kubernetes slack channel or the main K8s repo instead?
