### ISSUE TITLE
Issue with /docs/tasks/web-ui-dashboard/

### ISSUE THREAD

**Issue by feborges** [kubernetes/kubernetes.github.io#3636]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
I'm using ubuntu 16.04.

I want to configure the kubectl proxy to run when the master kubernetes reboot. I wrote the command in the file /etc/rc.local, but it didn't work.

The command:
     **kubectl proxy --address='0.0.0.0' --port=8001 --accept-hosts='^*$' &**   (execute in background)

I executed the command to see the status of service (systemctl status rc-local.service).

rc-local.service - /etc/rc.local Compatibility
   Loaded: loaded (/lib/systemd/system/rc-local.service; static; vendor preset: enabled)
  Drop-In: /lib/systemd/system/rc-local.service.d
           ââdebian.conf
  **Active: active (exited) (Result: exit-code) since Thu 2017-05-04 14:44:44 BRT; 6min ago
  Process: 965 ExecStart=/etc/rc.local start (code=exited, status=0/SUCCESS)
 Main PID: 2022 (code=exited, status=1/FAILURE)**

May 04 14:44:14 kube1 systemd[1]: Starting /etc/rc.local Compatibility...
May 04 14:44:44 kube1 systemd[1]: Started /etc/rc.local Compatibility.
**May 04 14:44:47 kube1 rc.local[965]: The connection to the server localhost:8080 was refused - did you specify the right host or port?**
May 04 14:44:47 kube1 systemd[1]: rc-local.service: Main process exited, code=exited, status=1/FAILURE
May 04 14:50:50 kube1 systemd[1]: Started /etc/rc.local Compatibility.

If I execute the command above in the bash, it work.

Is there a way to configure a service to verify if the dashboard is up? If it down, the service check and start.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by feborges** [comment]
Is there a way to configure a service to verify if the dashboard is up? If it down, the service check and start.

**Comment by ychtch** [comment]
Hello!
I confirm that problem. How did you solve it?
