### ISSUE TITLE
Issue with /docs/concepts/workloads/controllers/deployment/

### ISSUE THREAD

**Issue by omarkj** [kubernetes/kubernetes.github.io#3641]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
The documentation for Min Ready Seconds seems to contradict itself. It states both that the default value is 600s and that it is 0, see below:

Min Ready Seconds
.spec.minReadySeconds is an optional field **(with default value of 600s)** that specifies the minimum number of seconds for which a newly created Pod should be ready without any of its containers crashing, for it to be considered available. **This defaults to 0** (the Pod will be considered available as soon as it is ready). To learn more about when a Pod is considered ready, see Container Probes.

**Proposed Solution:**
I do not know what the default is here, but I do believe from having used Kubernetes that it is 0s. The page should be updated to reflect that

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

**Comment by jaredbhatti** [comment]
Default should be zero.  Updated.
