### ISSUE TITLE
I wish /docs/getting-started-guides/azure/ I wish this page existed.

### ISSUE THREAD

**Issue by mmlt** [kubernetes/kubernetes.github.io#365]
I wish /docs/getting-started-guides/azure/ existed.

**Comment by johndmulhausen** [comment]
All this page ever did was forward users on to the CoreOS guide, which is still with us:
https://github.com/kubernetes/kubernetes/blob/2b2f2857771c748f0f0e261f3b8e2ad1627325ce/docs/getting-started-guides/azure.md
