### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by japkin** [kubernetes/kubernetes.github.io#3675]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Proxy command is stuck and never completes:

> kubectl proxy
Starting to serve on 127.0.0.1:8001

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by jaredbhatti** [comment]
Doesn't seem to be happening now, but I'm keeping an eye on the interactive tutorial since it's getting a lot of bugs.
