### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by rickbrauen** [kubernetes/kubernetes.github.io#3697]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Live interaction is not possible. Scenario kicks off but terminal screen says internet connection has dropped. 

**Proposed Solution:**
I believe the terminal emulator program has crashed and needs to be restarted.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/

**Comment by jaredbhatti** [comment]
Should work now.  I'm keeping an eye on these interactive tutorial issues since they seem to be accumulating.
