### ISSUE TITLE
Heading anchors sometimes don't consider page header when jumping

### ISSUE THREAD

**Issue by ghodss** [kubernetes/kubernetes.github.io#370]
http://kubernetes.io/docs/admin/admission-controllers/#what-are-they works correctly - you jump to what-are-they with enough padding that the header of the page doesn't cover the heading.

http://kubernetes.io/docs/admin/authorization/#abac-mode works incorrectly - you jump to the heading ABAC Mode but it's covered up by the page header. It may be because there is no table of contents on visible on the page.

**Comment by johndmulhausen** [comment]
@CreaturesInUnitards please investigate.

**Comment by CreaturesInUnitards** [comment]
I don't repro success in either case when navigating from elsewhere — inline TOC is the only success case. I'll need to look for the hash on pageload

**Comment by johndmulhausen** [comment]
Fixed elsewhere
