### ISSUE TITLE
Issue with /docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by publicitas-deployment** [kubernetes/kubernetes.github.io#3717]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The link to the xhyve driver in the OS X install instructions is broken.

**Proposed Solution:**
Replace the link with this one:

https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#xhyve-driver

**Page to Update:**
http://kubernetes.io/docs/tasks/tools/install-minikube/

**Comment by jaredbhatti** [comment]
Appears to already be fixed.
