### ISSUE TITLE
I wish /docs/getting-started-guides/logging/ would not have a broken link at the bottom that should point to the sidecar container docs

### ISSUE THREAD

**Issue by agosto-raypitmon** [kubernetes/kubernetes.github.io#374]
I wish /docs/getting-started-guides/logging/ would not have a broken link at the bottom pointing to the sidecar container docs.  It points to: http://releases.k8s.io/release-1.2/contrib/logging/fluentd-sidecar-gcp/README.md

It should probably point to something like this: https://github.com/kubernetes/contrib/tree/master/logging/fluentd-sidecar-gcp

**Comment by atbaker** [comment]
It looks like this was fixed by https://github.com/kubernetes/kubernetes.github.io/pull/372. I don't see the broken links anymore.

cc @johndmulhausen

**Comment by runseb** [comment]
confirmed fixed, this should be closed. @johndmulhausen
