### ISSUE TITLE
Issue with /docs/tasks/configure-pod-container/configmap/

### ISSUE THREAD

**Issue by knabben** [kubernetes/kubernetes.github.io#3795]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
See Consuming ConfigMaps in Pods. link is broke.

**Proposed Solution:**
Should be pointing to ??

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configmap/

**Comment by jaharkes** [comment]
Bumped into this myself yesterday as well. It looks like a ConfigMap documentation rewrite was split across two pull requests. One got merged (#3759) but the new one describing how to actually use config maps (#3780) had a formatting error and is still pending.

**Comment by chenopis** [comment]
#3780 has been merged.
