### ISSUE TITLE
new tutorial: Configuring Redis using a ConfigMap

### ISSUE THREAD

**Issue by jputrino** [kubernetes/kubernetes.github.io#3827]
**This is a...** 
- [x ] Feature Request

**Problem:**
As discussed in #3780, the 'Real World Example' section of `docs/tasks/configure-pod-container/configure-pod-configmap.md` should probably be a separate tutorial.

**Proposed Solution:**
- Create a new tutorial from the existing content (probably needs additional information).
- Remove the section from the task doc and replace with a 'What's Next' pointer to new tutorial doc.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#real-world-example-configuring-redis-using-a-configmap

**Comment by chenopis** [comment]
done
