### ISSUE TITLE
Issue with /docs/concepts/overview/components/ (typo)

### ISSUE THREAD

**Issue by ftclausen** [kubernetes/kubernetes.github.io#3841]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

Typo in Kubernetes Components page.

> supervisord is a lightweight process monitoring and control system that can be used to keeo kubelet and docker running

"keeo" should be "keep"

**Proposed Solution:**

supervisord is a lightweight process monitoring and control system that can be used to keep kubelet and docker running

**Page to Update:**

https://kubernetes.io/docs/concepts/overview/components/

**Comment by coolsvap** [comment]
This is addressed with #3845. This can be closed.
