### ISSUE TITLE
Issue with /docs/tasks/administer-cluster/declare-network-policy/

### ISSUE THREAD

**Issue by bboreham** [kubernetes/kubernetes.github.io#3844]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Page shows `networkPolicy` as a field on `namespace`, which it isn't.
This is a proposed change at https://github.com/kubernetes/kubernetes/pull/39164, but highly contentious.

**Proposed Solution:**
Revert #3721 and other similar changes

**Page to Update:**
http://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/
http://kubernetes.io/docs/tasks/administer-cluster/configure-namespace-isolation.md

**Comment by zacharysarah** [comment]
@chenopis 👋 Can you offer any perspective here?

**Comment by bboreham** [comment]
The change was reverted, and things have moved on since.  This should have been closed by #3849
