### ISSUE TITLE
Issue with /docs/concepts/workloads/pods/pod/

### ISSUE THREAD

**Issue by gamename** [kubernetes/kubernetes.github.io#3846]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
In the 7th paragraph in the "What is a Pod?" section, there is this sentence: 
"If a node dies, the pods scheduled to that node are scheduled for deletion, after a timeout period."
That does not to make sense. Nodes are where pods live. Pods cannot be created when a node does not exist. There is nothing to delete.

**Proposed Solution:**
Please clarify how scheduling pods for missing nodes are handled

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
@gamename There are 2 parts of a Pod: one is something executed on the Node, one is a record on the Kubernetes API Server. So when a node dies, Pod record will be deleted after a while from the database. 

Does this make sense?

**Comment by zacharysarah** [comment]
@gamename Feel free to re-open this issue if you have any further questions.
