### ISSUE TITLE
Issue with /docs/admin/authorization/rbac/

### ISSUE THREAD

**Issue by bobbychef64** [kubernetes/kubernetes.github.io#3871]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

while creating the roles i am getting the below error. and the document has no info how to create the normal user accounts. 

kubectl create -f role.yaml 
Error from server (Forbidden): error when creating "role.yaml": clusterroles.rbac.authorization.k8s.io "secret-reader" is forbidden: attempt to grant extra privileges: [{[get] [] [secrets] [] []} {[watch] [] [secrets] [] []} {[list] [] [secrets] [] []}] user=&{kubecfg  [system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by liggitt** [comment]
The section on privilege escalation and bootstrapping addresses this - https://kubernetes.io/docs/admin/authorization/rbac/#privilege-escalation-prevention-and-bootstrapping
