### ISSUE TITLE
Issue with /docs/setup/pick-right-solution/

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes.github.io#3892]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The Table of Solutions should mention Calico with a pointer into the Calico docs.  Probably with one pretty general row.

**Proposed Solution:**
Add one row with IaaS-Provider=any, Config-Mgmt=any, OS=any, Networking=any, docs=http://docs.projectcalico.org/v2.2/getting-started/kubernetes/installation/,  Support=Commercial and Community

**Page to Update:**
https://kubernetes.io/docs/setup/pick-right-solution

**Comment by MikeSpreitzer** [comment]
CC @caseydavenport

**Comment by ngtuna** [comment]
should we close this ?

**Comment by chenopis** [comment]
Yeah, it looks resolved.
