### ISSUE TITLE
More Room in Tables in API Docs.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes.github.io#39]
Reduce padding in tables in API Operations docs.
Reduce font sizes so more text fits on the screen.
In the Parameters tables, give the "Description" column more width.

By API documentation, I mean:
- Operations: http://kubernetes.io/v1.1/docs/api-reference/v1/operations.html
- Definitions: http://kubernetes.io/v1.1/docs/api-reference/v1/definitions.html
- and so on for other api groups and newer versions (like 1.2)

Copied from https://github.com/kubernetes/kubernetes/issues/22389

**Comment by johndmulhausen** [comment]
@erictune Significant CSS changes have taken place. What do you think?
