### ISSUE TITLE
Make more stuff on home page clickable

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes.github.io#393]
So users can dig into more details in their areas of interest. Especially in the features section.

**Comment by bgrant0607** [comment]
I like the Prometheus feature section:
https://prometheus.io/

**Comment by bgrant0607** [comment]
cc @mansoorj

**Comment by jaredbhatti** [comment]
Bob Hrdinsky now owns the front page.  (Separate from tech docs)
