### ISSUE TITLE
Update NetworkPolicy docs for v1

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubernetes.github.io#3934]
We need to update the NetworkPolicy docs for the new v1 semantics for 1.7.

#3721 is a start, although the semantics changed a bit since that was written, as discussed in https://github.com/kubernetes/kubernetes/pull/39164.

(I will do this update myself if no one else gets to it before me.)

**Comment by zacharysarah** [comment]
@danwinship Does #4003 adequately address this issue? Can we close it?

**Comment by danwinship** [comment]
@zacharysarah Yes, this is fixed... I said "Fixes #3934" in that PR, why didn't this get closed automatically? Shrug.
