### ISSUE TITLE
Reduce amount of space on homepage filled by "marketing text"

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes.github.io#394]
Planet Scale, Never Outgrow, Run Anywhere.

I'd like these to be side-by-side, smaller, and clickable.

**Comment by bgrant0607** [comment]
cc @mansoorj

**Comment by bgrant0607** [comment]
In general, I'd prefer a more dense display on the home page -- side by side. 

For comparison, I like https://prometheus.io/

cc @bryk

**Comment by jaredbhatti** [comment]
yep, totally agree with this.  I've asked Bob Hrdinsky to remove these.
