### ISSUE TITLE
Issue with /docs/concepts/cluster-administration/cluster-administration-overview/

### ISSUE THREAD

**Issue by riclava** [kubernetes/kubernetes.github.io#3953]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
spell mistake
```
Will you be using a hosted Kubernetes cluster, such as Google Container Engine (GKE), or hosting your own cluster?
```

**Proposed Solution:**
```
Google Container Engine (GCE)
```

**Page to Update:**
http://kubernetes.io/...

**Comment by coolsvap** [comment]
I think GKE is correct. Since Google Container Engine is based on Kubernetes. Google Compute Engine is often referred as GCE. I might be wrong but I am searching for a reference for this.

**Comment by riclava** [comment]
@coolsvap you're right ;-)
