### ISSUE TITLE
Copy-to-clipboard feature does not work in Chrome

### ISSUE THREAD

**Issue by ryanmcginnis** [kubernetes/kubernetes.github.io#3965]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Today, the copy-to-clipboard feature used on kubernetes.io for code samples does not work in Chrome.

Tested using:
Chrome 58.0.3029.110 under macOS 10.12.5
Chrome 58.0.3029.110 under Ubuntu 14.04
Safari 10.1.1 under macOS 10.12.5

Steps to Reproduce:
1. Open a documentation page in Chrome. For example: https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/
2. Click the copy-to-clipboard button beside a code sample.
3. Observe that the feature does not work: the sample is not copied to the clipboard.
4. Open the page in an incognito Chrome window (because, presumably, user-installed extensions aren't loaded).
5. Click the button. Observe that the issue persists.
6. Open another web browser (such as Safari) and attempt to reproduce issue. Observe that the issue does not reproduce: the feature works as expected.

**Proposed Solution:**
1. Investigate why the button no longer works in Chrome.
2. Commit necessary change to resolve the issue.

**Page to Update:**
http://kubernetes.io/

**Comment by jaredbhatti** [comment]
Ahmet, is there a clear and easy fix to this?  Otherwise, let's just remove this functionality.

**Comment by ryanmcginnis** [comment]
The copyCode function lives here: https://kubernetes.io/js/script.js

**Comment by ahmetb** [comment]
Sent a fix at #4190.
