### ISSUE TITLE
Issue with /docs/concepts/configuration/assign-pod-node/

### ISSUE THREAD

**Issue by fleeto** [kubernetes/kubernetes.github.io#3968]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
In the document, it mentiond:

In principle, the topologyKey can be any legal label value. However, for performance reasons, ***only a limited set of topology keys are allowed***. By default the allowed topology keys are:
kubernetes.io/hostname
failure-domain.beta.kubernetes.io/zone
failure-domain.beta.kubernetes.io/region

but we can still create a pod with ***unsupported topologyKey*** like this

~~~yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: In
            values:
            - S1
        topologyKey: poor-topo
  containers:
  - name: with-pod-affinity
    image: gcr.io/google_containers/pause:2.0
~~~

**Proposed Solution:**

change ***allowed*** into ***recommended*** ?

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
Please feel free to send a PR if you have time.
