### ISSUE TITLE
Issue with /docs/concepts/workloads/controllers/statefulset/

### ISSUE THREAD

**Issue by danieljcosta** [kubernetes/kubernetes.github.io#3975]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Unable to find how is it possible to associate a persitentStorage with the StatefulSet in the documentation.

**Proposed Solution:**
Add an example.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

**Comment by ahmetb** [comment]
Duplicate of #3975.
