### ISSUE TITLE
Issue with /docs/getting-started-guides/vsphere/

### ISSUE THREAD

**Issue by g1001p** [kubernetes/kubernetes.github.io#3984]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by g1001p** [comment]
Dear forum
I am trying to deploy kubernetes with vsphere provider 
Pod deployment failed on creation of VMDK:
Here is an error
0604 10:43:05.004137   26631 reconciler.go:168] Started AttachVolume for volume "kubernetes.io/vsphere-volume/[wsdc2_ds_ssd_esdata01] volumes/testdsk.vmdk" to node "wsdc2-lnx04"
E0604 10:43:05.077373   26631 attacher.go:79] Error attaching volume "[wsdc2_ds_ssd_esdata01] volumes/testdsk.vmdk": datastore '' not found
E0604 10:43:05.077453   26631 nestedpendingoperations.go:253] Operation for "\"kubernetes.io/vsphere-volume/[wsdc2_ds_ssd_esdata01] volumes/testdsk.vmdk\"" failed. No retries permitted until 2017-06-04 10:45:05.077431587 -0500 CDT (durationBeforeRetry 2m0s). Error: Failed to attach volume "vmdktest" on node "wsdc2-lnx04" with: datastore '' not found
I0604 10:43:05.077561   26631 event.go:217] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"kafka5-deployment-224282215-jpm70", UID:"326775f2-493c-11e7-ba43-005056b07980", APIVersion:"v1", ResourceVersion:"1902", FieldPath:""}): type: 'Warning' reason: 'FailedMount' Failed to attach volume "vmdktest" on node "wsdc2-lnx04" with: datastore '' not found

What do you think a problem there?
I appreciate for any recommendation to handle this issue.
Thanks in advance

**Comment by g1001p** [comment]
part of the problem fixed - datastore name was not specified correctly.
But kubernetes is still not able to mount vmdk disk
Error: failed to add disk scsi1:0.

**Comment by divyenpatel** [comment]
@g1001p 

We can help you to debug the issue. 
Do you still have issue regarding Disk is not getting attached to the node? 

Are you using photon OVA provided in the documentation? If other OS, can you provide details.

Is the Kubernetes cluster deployed using Kubernetes-Anywhere?

cc: @tusharnt

**Comment by g1001p** [comment]
Thanks you i fixed this issue via reconfiguration of datastore as results vmdk was mounted  successfully.
Maybe you know how can i manage more than one datastore value in the vsphere.conf file?

**Comment by divyenpatel** [comment]
We recommend to use shared datastore accessible on all nodes.  You can only specify one datastore name in /etc/kubernetes/vsphere.conf

But If you have multiple shared datastore, and want to use specific datastore, which is not specified in the vsphere.conf, you can use storage class parameter
as mentioned in this yaml -  https://github.com/kubernetes/kubernetes/blob/master/examples/volumes/vsphere/vsphere-volume-sc-with-datastore.yaml

PVCs created using this storageclass will provision PVs on specified datastore in the storageclass.

**Comment by g1001p** [comment]
thanks, it is great option but it's looks not meet my use case requirements.
This case is about dynamic volume creation. 
in my use case i have vmdk already created as a prerequisite.  
Also in my case several pods could be run on same minion and should be able to mount different vmdk from different datastore location. 
how can i manage through storage class or another option?

**Comment by divyenpatel** [comment]
For this requirement, you have to create PV objects manually for pre-created vmdks.
You can then create PVC objects to bind these PV objects, and can specify PVCs in your Pod Spec.
Please refer - https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/vsphere

**Comment by g1001p** [comment]
I configured storageclass according to the reference. 
 the storageclass create seems ok, but can't describe kubectl describe storageclass  reports (no description has been implemented for "StorageClass"), 
when create pvc, it's status always pending , kubectl describe pvc:

From
{persistentvolume-controller}
Type                  Reason                                              Message
Worning            ProvisioningFailed                   failed to provision volume with StorageClass "fast": A  
                                                                          pecified parameter was not correct:   

Unfortunately it is not showing which exactly parameter is it.
What do you think a problem there?
Thanks

**Comment by divyenpatel** [comment]
This issue is closed.
@g1001p Can you please create a new issue at https://github.com/vmware/kubernetes/issues
and provide following details

what kubernetes version are you using?
`kubectl version `

please provide YAML file you are using for creating storage class and pvc.

share the output of 
```
kubectl get storageclass -o json
kubectl get pvc -o json
kubectl describe storageclass
kubectl describe pvc
```

And also provide controller log from the master node.

**Comment by g1001p** [comment]
Attached is a requested outputs in one zip file.

Thanks

**Comment by g1001p** [comment]
[DescribePVC.txt](https://github.com/kubernetes/kubernetes.github.io/files/1068880/DescribePVC.txt)
[DescribeStorageClass.txt](https://github.com/kubernetes/kubernetes.github.io/files/1068879/DescribeStorageClass.txt)



[kube-controller-manager.log.txt](https://github.com/kubernetes/kubernetes.github.io/files/1068885/kube-controller-manager.log.txt)
[PVC.json.txt](https://github.com/kubernetes/kubernetes.github.io/files/1068886/PVC.json.txt)
[storageclass.json.txt](https://github.com/kubernetes/kubernetes.github.io/files/1068887/storageclass.json.txt)

**Comment by divyenpatel** [comment]
please provide kubectl client and kubernetes cluster server version detail.

kubectl version

**Comment by divyenpatel** [comment]
@g1001p 
Annotation on the claim does not look good to me, you have both alpha and beta version?

```
"annotations": {
                    "volume.alpha.kubernetes.io/storage-class": "dses01",
                    "volume.beta.kubernetes.io/storage-class": "dses01"
                }
```

you are requesting 2 TB of VMDK, are you sure about that?

```
"resources": {
                    "requests": {
                        "storage": "1999Gi"
                    }
                }
```

Let us know what version of Kubernetes you are running? We will provide you what API version you should use in the YAML spec.

also provide YAML files here.

**Comment by g1001p** [comment]
I am trying to run it over 1.4 version im considering to switch to version 1.5.6 or even 1.6.
My understanding is about purpose of StorageClass is to create storage.
I would like to emphasize my use case. 
I already have several vmdks created/existing across of several datastores.
In this case why i need a storageclass?
I need provide the launching pod ability to select dynamically the right vmdk and mount it.
How can i configure it in the yaml ? do i still need a storageclass or maybe not? 
what could be a right option here?

**Comment by divyenpatel** [comment]
@g1001p as mentioned earlier, you do not need storage class if you do not want to provision volume dynamically.

Following are the sample YAMLs. this is the right option for you.

**Create PV for existing VMDK**

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  vsphereVolume:
    volumePath: "[datastore1] volumes/myDisk"
    fsType: ext4
```

**Create PVC to bind with PV**

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc0001
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```

**Create POD and specify PVC to use.**

```
apiVersion: v1
kind: Pod
metadata:
  name: pvpod
spec:
  containers:
  - name: test-container
    image: gcr.io/google_containers/test-webserver
    volumeMounts:
    - name: test-volume
      mountPath: /test-vmdk
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: pvc0001

```

**Comment by g1001p** [comment]
Thank you very much this is exactly was i just did and it working

**Comment by g1001p** [comment]
Thanks its working now
