### ISSUE TITLE
Document DaemonSet history 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes.github.io#3991]
1. DaemonSet history and `kubectl rollout` commands 
1. Update https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/kubectl-overview.md
    * valid resource: controllerrevisions
    * kubectl rollout
1. Remove mention of templateGeneration (deprecating), and update the guide for DaemonSet orphan & adoption

/assign @janetkuo

**Comment by janetkuo** [comment]
The PR is https://github.com/kubernetes/kubernetes.github.io/pull/4098

**Comment by zacharysarah** [comment]
Closing due to #4098 merging. 🎉
