### ISSUE TITLE
Versioned Docs Discussion

### ISSUE THREAD

**Issue by zoidbergwill** [kubernetes/kubernetes.github.io#3992]
/assign @chenopis 

**This is a...** 
- [x] Feature Request

**Problem:**

We currently don't have versioned documentation, so the only docs you get are `master` because GitHub pages.

**Proposed Solution:**

Move to Netlify

<hr>

I've been playing with deploying multiple sites to Netlify from different branches, currently to:

kubernetes-docs-1-5.zoidbergwill.com
kubernetes-docs.zoidbergwill.com
kubernetes-docs-1-7.zoidbergwill.com

After discussing with @chenopis, I think I'm gonna focus on a `kubernetes-docs-1-6.zoidbergwill.com` as a example of what'll happen when 1.7 releases.

The only work I've done so far is reverting a PR of @chenopis's that had been temporarily reverted since it was just a Netlify redirect feature:

https://github.com/kubernetes/kubernetes.github.io/compare/master...zoidbergwill:master

I assume we'd want a pretty prominent dropdown in the nav or header for swapping between versions, and then in all versions pre-1.6 we'd also want a banner warning that these aren't the latest version of the docs?

I also still need to update the edit urls to point to the versions' branch.

<hr>

### To do

- [ ] Dropdown for swapping versions https://github.com/kubernetes/kubernetes.github.io/pull/4386
- [x] Updated edit URLs
- [ ] Potentially a banner for warning about beta/outdated docs

**Comment by chenopis** [comment]
@zoidbergwill After Kubernetes 1.7 has been released, let's talk in early July to get this done in 2017Q3.

**Comment by chenopis** [comment]
About to start work on this.

**Comment by chenopis** [comment]
A pilot version of v1.6 is up: https://v1-6.docs.kubernetes.io/

**Comment by zoidbergwill** [comment]
That's building the [`netlify-move`](https://github.com/kubernetes/kubernetes.github.io/tree/netlify-move) branch, right?

**Comment by zoidbergwill** [comment]
Also something  not mentioned in my original ticket. Netlify is pretty awesome because of [deploy previews](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/)

**Comment by chenopis** [comment]
@zoidbergwill https://v1-6.docs.kubernetes.io/ is using the `release-v1.6` branch.

**Comment by chenopis** [comment]
**Update:** The versioned docs are now deployed in the following subdomains:

https://v1-6.docs.kubernetes.io/
https://v1-5.docs.kubernetes.io/
https://v1-4.docs.kubernetes.io/

I added `X-Robots-Tag: noindex` to the HTTP header for these subdomains so that they are not indexed by the search bots. Also, once https://github.com/kubernetes/kubernetes.github.io/pull/4386 is done, I will add the dropdown version selector UI to each of these.

**Comment by zoidbergwill** [comment]
Are we only gonna support PRs for current release and next release? Should we add a banner to all other branches?

**Comment by steveperry-53** [comment]
@zoidbergwill, @chenopis, Yes, our plan is to support PRs only for the current release and next release. And yes, I think we should add a banner to all other branches. The banner should warn that the docs are outdated, and it should have a link to the current docs.

**Comment by zoidbergwill** [comment]
Awesome, that's what I was thinking. Great.
