### ISSUE TITLE
kube-up.sh instructions for installing on Ubuntu 14 are broken

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes.github.io#4011]
[X] Bug Report

**Problem:**
Ubuntu 14 setup instructions are broken.

https://stackoverflow.com/questions/44302071/how-to-install-latest-kubernetes-in-ubuntu-14#

**Comment by zacharysarah** [comment]
@aronchick Can you provide a specific page URL for the broken instructions?

**Comment by zacharysarah** [comment]
@aronchick Please feel free to re-open this issue with more specific information.
