### ISSUE TITLE
http://kubernetes.io/docs/admin/networking/ does not describe AWS

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes.github.io#402]
There is a lot of confusion about how k8s AWS networking works, I think possibly because this page does not describe AWS.   People seem to think you need flannel/calico/whatever.  In fact k8s on AWS supports a model very similar to GCE.

**Comment by jaredbhatti** [comment]
We rely on members of the community to create content for the third party services.  Can you create a PR with the information for AWS here: http://kubernetes.io/docs/admin/networking/

And link to it from here: http://kubernetes.io/docs/getting-started-guides/aws/
