### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/assign-pod-node/

### ISSUE THREAD

**Issue by ankitpateledu** [kubernetes/kubernetes.github.io#4021]
**This is a...bug report or feature request. i am not sure ** 

- [x] Feature Request
- [x] Bug Report

**Problem:**
While using replication factor >1; i intend to run same container on different nodes in cluster, and i also want them to be deployed on certain nodes,so i provided replication count and node selector in yaml like below..
apiVersion: extensions/v1beta1
spec:
  replicas: 3
.........
........
........
nodeSelector:
        node: node04
	node: node05
	node: node16

3 containers got deployed but all landed on node 16!!! I want one container per node and on node 04,05, and 16

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"a55267932d501b9fbd6d73e5ded47d79b5763ce5", GitTreeState:"clean", BuildDate:"2017-04-14T13:36:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"a55267932d501b9fbd6d73e5ded47d79b5763ce5", GitTreeState:"clean", BuildDate:"2017-04-14T13:36:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by zacharysarah** [comment]
@ankitpateledu This looks less like an issue with docs and more like a request for support. I encourage you to bring your question to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/). Please feel free to re-open this issue if there's a specific docs change you'd like to address here.
