### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

### ISSUE THREAD

**Issue by venkateshsampath** [kubernetes/kubernetes.github.io#4037]
**This is a bug related to create PVC yaml. ** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
As per the documentation, after creating the PVC, the Kubernetes control plane looks for a PersistentVolume that satisfies the claim’s requirements. In this case it should identify the PV, task-pv-volume and should bind the claim to the volume. But that doesn't seem to be happening. Instead, when we create the PVC using the provided yaml in the documentation, it dynamically provisions a new PV of 3Gi storage size and binds the claim to that newly dynamically created volume.

Steps:
- Initial state of the minikube cluster
$ kubectl get pv
No resources found.
$ kubectl get pvc
No resources found.

- now create a PV as per documentation.
$ ls
task-pv-claim.yaml  task-pv-volume.yaml
$ kubectl create -f task-pv-volume.yaml
persistentvolume "task-pv-volume" created
$ kubectl get pv task-pv-volume
NAME             CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS      CLAIM     STORAGECLASS   REASON    AGE
task-pv-volume   10Gi       RWO           Retain          Available                                      16s
$ kubectl get pv
NAME             CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS      CLAIM     STORAGECLASS   REASON    AGE
task-pv-volume   10Gi       RWO           Retain          Available                                      22s

- now create a new PVC to claim bind to the available volume using the yaml given in the documentation
$ ls
task-pv-claim.yaml  task-pv-volume.yaml
$ kubectl create -f task-pv-claim.yaml
persistentvolumeclaim "task-pv-claim" created
$ kubectl get pv task-pv-volume
NAME             CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS      CLAIM     STORAGECLASS   REASON    AGE
task-pv-volume   10Gi       RWO           Retain          Available                                      2m
$ kubectl get pvc task-pv-claim
NAME            STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS   AGE
task-pv-claim   Bound     pvc-763adc96-4ce4-11e7-a788-e6209f56cf32   3Gi        RWO           standard       32s
$ kubectl get pv
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS      CLAIM                   STORAGECLASS   REASON    AGE
pvc-763adc96-4ce4-11e7-a788-e6209f56cf32   3Gi        RWO           Delete          Bound       default/task-pv-claim   standard                 37s
task-pv-volume                             10Gi       RWO           Retain          Available                                                    2m

Notice that a new PV named "pvc-763adc96-4ce4-11e7-a788-e6209f56cf32" is dynamically created and is bound to the claim.

**Proposed Solution:**
In the task-pv-claim.yaml include "volumeName: task-pv-volume" and PVC now could claim bind to the "task-pv-volume".
Reference: 
https://kubernetes.io/docs/resources-reference/v1.6/#persistentvolumeclaimspec-v1-core

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T20:41:16Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-30T22:03:41Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}

Using: OS X Yosemite Version 10.10.5

**Comment by prydonius** [comment]
@venkateshsampath see #3979, this is due to the storage class being requested. The PVC is picking up the default storage class and using that instead.

Duplicate of #2803

**Comment by prydonius** [comment]
#3979 is merged so I think this can be closed

**Comment by venkateshsampath** [comment]
@prydonius, Thanks a lot. I will go ahead and close this issue.
