### ISSUE TITLE
I wish /docs/hellonode/ contained instructions that work

### ISSUE THREAD

**Issue by georgevdd** [kubernetes/kubernetes.github.io#404]
I wish /docs/hellonode/ contained instructions that work.

The line about
  curl http://localhost:8080
just gives
  curl: (7) Failed to connect to localhost port 8080: Connection refused

I'm following the instructions in OSX, so my running container is inside a virtual box.

If I first run
  docker-machine ssh
then this lands me in a shell in the virtual box from which I can successfully run the above `curl` command.

A note about this would have saved me a couple of hours of figuring it out for myself.

**Comment by timBrockman** [comment]
This describes the problem pretty well, if you read down to the examples portion:
[https://docs.docker.com/engine/installation/mac/#access-container-ports](https://docs.docker.com/engine/installation/mac/#access-container-ports)

> This didn’t work. The reason it doesn’t work is your DOCKER_HOST address is not the localhost 
> address (0.0.0.0) but is instead the address of your Docker VM.
> Get the address of the default VM.
> `$ docker-machine ip default`
> `192.168.59.103`

I ran into the same issue

**Comment by rothgar** [comment]
I didn't realize before but issue 404 is such a fitting number for this problem.

**Comment by timBrockman** [comment]
This could be closed now, right?

**Comment by jaredbhatti** [comment]
Yep, fixed.
