### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/debug-service/

### ISSUE THREAD

**Issue by levivic** [kubernetes/kubernetes.github.io#4041]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
I have been using hyperkube to create a local cluster and started a few demo pods and a service on the same host within the same namespace. And I have been using Calico v2.2.1 as my network plugin. 

However, the pods cannot ping each other before isolation is enabled. 

I have been using `https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/` for debugging. The Service, Endpoints, Pods, kube-proxy seem all work normally. I just cannot reach other pods from within one pod.

Kubernetes Version:
1.6.4
Network plugin:
Calico v2.2.1

**Comment by zacharysarah** [comment]
@levivic 👋 This issue sounds more like a request for support and less like an issue specifically for docs. I encourage you to bring your question to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/).
