### ISSUE TITLE
User-facing doc for strategic merge patch

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes.github.io#4062]
Maybe we need a user-facing doc for strategic merge patch since they are considered as part of the API as well.
Right now we only have a developer-facing doc at https://github.com/kubernetes/community/blob/master/contributors/devel/strategic-merge-patch.md.

Maybe we can try to move it to the user-facing doc or write a separate doc.
We need to figure out a good place for it.

/assign @steveperry-53

**Comment by steveperry-53** [comment]
I'm working on a new Task topic that will cover kubectl edit and kubectl patch:
PR 4519

**Comment by erictune** [comment]
Can this be closed @mengqiy or @steveperry-53

**Comment by steveperry-53** [comment]
@erictune, @mengqiy, I'm fine with closing this issue.
https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/
