### ISSUE TITLE
Include calendar stuff

### ISSUE THREAD

**Issue by johndmulhausen** [kubernetes/kubernetes.github.io#41]
Our events calendar:

Embed source:
`<iframe src="https://calendar.google.com/calendar/embed?src=nt2tcnbtbied3l6gi2h29slvc0%40group.calendar.google.com&ctz=America/Los_Angeles" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>`

Link:
https://calendar.google.com/calendar/embed?src=nt2tcnbtbied3l6gi2h29slvc0%40group.calendar.google.com

cc @CreaturesInUnitards

**Comment by johndmulhausen** [comment]
I believe a calendar icon in the Community area of the footer and menu and a link on the community page was what we discussed. No "events" page or anything fancy like that.

**Comment by CreaturesInUnitards** [comment]
yup done, excepting community page
