### ISSUE TITLE
I wish /docs/hellonode/ also documented how to setup a kubernetes cluster on my local box so I did not have to rely on Google engine.

### ISSUE THREAD

**Issue by derekbassett** [kubernetes/kubernetes.github.io#410]
I wish /docs/hellonode/ also documented how to setup a kubernetes cluster on my local box so I did not have to rely on Google engine.  Even if it couldn't support running all the processes at scale it would at least would have been less confusing.  This document appears to be more of a sales pitch to using Google Cloud Platform.

**Comment by jaredbhatti** [comment]
Yep.  Minikube fixes this issue: http://kubernetes.io/docs/getting-started-guides/minikube/
