### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-kubernetes-api/extend-api-third-party-resource/

### ISSUE THREAD

**Issue by tengqm** [kubernetes/kubernetes.github.io#4102]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
TPR is being deprecated. It is not just unstable. It is gonna disappear.
This should be clearly stated on the documentation, or else people like me may spend a lot time working on it only to find it a waste of time.

**Proposed Solution:**
Explicitly state that TPR is being deprecated in favor of CustomResourceDefinition, with a link to the latter.

**Page to Update:**
https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-third-party-resource/

**Comment by zacharysarah** [comment]
@tengqm 👋 Thanks for opening this issue. There's a deprecation notice on the page for 1.7.
