### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/run-replicated-stateful-application/

### ISSUE THREAD

**Issue by prabhakm** [kubernetes/kubernetes.github.io#4124]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**

While trying the example, consitently getting below error on pod creation in gcloud.

Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                  Messag
e
  ---------     --------        -----   ----                    -------------   --------        ------                  ------
-
  22s           18s             4       default-scheduler                       Warning         FailedScheduling        [Sched
ulerPredicates failed due to PersistentVolumeClaim is not bound: "data-mysql-0", which is unexpected., SchedulerPredicates fai
led due to PersistentVolumeClaim is not bound: "data-mysql-0", which is unexpected., SchedulerPredicates failed due to Persist
entVolumeClaim is not bound: "data-mysql-0", which is unexpected.]
  14s           6s              3       default-scheduler                       Warning         FailedScheduling        No nod
es are available that match all of the following predicates:: Insufficient cpu (3).

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

1.6.x

**Comment by zacharysarah** [comment]
@prabhakm :wave: This issue sounds more like a request for support and less like an issue specifically for docs. I encourage you to bring your question to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/).
