### ISSUE TITLE
Plan: Remove /samples and merge maintained examples into /tutorials

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes.github.io#4134]
This is a rough plan I am planning to execute this/next week with the help of the reviewers:

- [x] Stage 1. **Delete Samples section (https://kubernetes.io/docs/samples/ )**: Most of this page is just links to various random stuff, which now moved to `kubernetes/examples` repository. They do not belong to the website.
    - The only internal link on this page is the [MEAN stack](https://kubernetes.io/docs/getting-started-guides/meanstack/) tutorial. I am reluctant about keeping this tutorial around. It's overlapping with other tutorials (mentioned below) and has _a lot_ of GKE/GCE references.
- [x] Stage 2. **Move Tutorials to https://kubernetes.io/docs/tutorials/**. By tutorials I mean the (currently) three examples maintained at https://github.com/kubernetes/examples. These are:
    - [Guestbook](https://github.com/kubernetes/examples/tree/master/guestbook#guestbook-example)
    - [Cassandra](https://github.com/kubernetes/examples/tree/master/cassandra#cloud-native-deployments-of-cassandra-using-kubernetes)
    - [MySQL & WordPress](https://github.com/kubernetes/examples/tree/master/mysql-wordpress-pd#persistent-installation-of-mysql-and-wordpress-on-kubernetes)

    On the first pass, I will move the README files of these examples from GitHub to this repository and clean up obvious issues, such as broken links, find them a proper title, and fit them under a topic on the left sidebar.

    At this stage, I appreciate if we skip reviewing the actual content. This would be just a migration PR.

- [x] Stage 3. **Remove README.md files from kubernetes/examples repository:** Not entirely removing, just updating them to contain a pointer to the tutorial link on k8s.io website to follow the tutorial.
- [x] Stage 4. **Polish tutorials over time:** Cleaning unnecessary stuff from the README.md files of these tutorials. Example of Guestbook tutorial on k8s.io vs GKE site:

    > k8s: https://github.com/kubernetes/examples/tree/master/guestbook
    > GKE: https://cloud.google.com/container-engine/docs/tutorials/guestbook

    As it can be seen from links above, GKE is much concise. I intend to keep these tutorials short. At this stage I suggest we review the content more thoroughly and meet the bar for tutorial standards. This work will be mostly done by @cody-clark.

    - [x] Polish Guestbook PHP tutorial
    - [x] Polish WordPress/MySQL tutorial
    - [x] Polish Cassandra tutorial

I am hoping to execute this in JFDI fashion, can a reviewer work with me on iterating on the PRs quickly? cc: @kubernetes/sig-docs-maintainers

**Comment by ahmetb** [comment]
cc: @steveperry-53 @chenopis @jaredbhatti I'll be starting to work on this soon. Please let me know if you have any comments.

**Comment by chenopis** [comment]
@ahmetb SGTM. Please add the 3 of us as assignees to any of the k8s.io PRs. Thx!

**Comment by jaredbhatti** [comment]
A lot of this is part of Cody's internship project.  Can you coordinate with him on all the docs work?

**Comment by chenopis** [comment]
@ahmetb I'll have @cody-clark ping you.

**Comment by steveperry-53** [comment]
@ahmetb, Could we have Cody go ahead and get started, in a separate PR, on the Cassandra tutorial? I'd like him to be able to get started on his primary internship project as soon as possible. Here's what I would suggest we have Cody do now in his own PR:

* Move the Cassandra Readme content to a location under kubernetes.io/docs/tutorials.
* Test the Cassandra tutorial steps and gain an understanding of what's being taught in the tutorial.
* Edit the Cassandra tutorial to comply with our style guide and our vision of what a tutorial should look like.

cc: @cody-clark, @jaredbhatti

**Comment by ahmetb** [comment]
We checked with Cody yesterday. He’ll be working on Step 4 (for all tutorials).

I'll send a PR to address Steps 1-3 today, then we can work on Step 4 asynchronously once the content is here. I'm reopening this issue to keep track of the work.

**Comment by ahmetb** [comment]
Step 1-3 is now fixed. @cody-clark feel free to take a stab at the tutorial content now. I mostly fixed obvious issues such as broken links and titles during the migration. The tutorials content probably needs someone executing again to see if the instructions are still working and also we should probably make these tutorials more concise by eliminating unnecessary amount of detail.

**Comment by cody-clark** [comment]
@ahmetb Thanks! I'm on it.

**Comment by chenopis** [comment]
@cody-clark Let us know when this is done so we can close this issue. Thx!

**Comment by cody-clark** [comment]
@chenopis I'm giving this a soft ready. I submitted the last PR so we're almost there :)
