### ISSUE TITLE
De-dupe http://kubernetes.io/docs/whatisk8s/

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes.github.io#414]
The version in the main repo may be more up to date:

https://github.com/kubernetes/kubernetes/blob/master/docs/whatisk8s.md

At least that's the one I've always updated. 

We should choose a single home for that doc and delete the other.

cc @johndmulhausen

**Comment by bgrant0607** [comment]
I diff'ed the two docs. They appear identical other than formatting conventions. 

I suggest gutting the one in the main repo and just leave a link to the one on kubernetes.io.

**Comment by jaredbhatti** [comment]
Brian, I'm going to close this issue for issue hygiene purposes.  Please reopen if there is still work to be done here.
