### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by bluishoul** [kubernetes/kubernetes.github.io#4141]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
```
Kubernetes Bootcamp Terminal


Sorry, we hit a problem with the connection.
Your internet connection may have dropped.

Please refresh and try again.
```

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment]
We're sorry you encountered an error. If you retry do you get the same error? If so, please let us know your browser version and OS. 

Do you have any firewalls or proxies that could be blocking https/websockets?

**Comment by bluishoul** [comment]
It seems to work fine today, still don't get the fail reason. close this
