### ISSUE TITLE
Ingress static IP

### ISSUE THREAD

**Issue by wernight** [kubernetes/kubernetes.github.io#416]
*LoadBalancer* have a `loadBalancerIP` field which is a must for any public website with a domain name. However *Ingress* just barely talks about LoadBalancer without stating how to have an Ingress behing a static IP. That's IMO critical knowledge.

**Comment by wernight** [comment]
Looking more into it, it seems that Ingress are directly exposed to the internet but there is no `loadBalancerIP` field in the spec. How are people supposed to use a DNS pointing to an Ingress if the IP cannot be made static and might change? It sounds really unsafe.

**Comment by wernight** [comment]
Sorry missed the prerequisits

**Comment by eggie5** [comment]
@wernight hey, I am trying to figure out the same exact question you have. I want to use the features of an Ingress, however, If I can't tell it to use my static IP (like the loadBalancerIP field) what's the point? 

What did you discover?

**Comment by wernight** [comment]
See my [Kubernetes article](https://beroux.com/english/articles/kubernetes/) as I describe there everything in. Basically you're probably mixing Ingress, Ingress Controller, and LoadBalancer. 3 different things.
