### ISSUE TITLE
Getting Started Guide for Ubuntu Calico is outdated

### ISSUE THREAD

**Issue by castrojo** [kubernetes/kubernetes.github.io#4167]
_From @sauercrowd on October 10, 2016 17:30_

The Getting Started Guide for Ubuntu with Calico at http://kubernetes.io/docs/getting-started-guides/ubuntu-calico/  is out of date.

The used kubernetes in this document version is **1.14**, which leads to issues with up-to-date docker versions. 

Also i want to point out that the calico version used in this document is **0.14.0**, while the current version is **0.22.0**. (I'm not sure if this also leads to compatibility issues, I'm still testing.)

_Copied from original issue: kubernetes/kubernetes#34460_

**Comment by castrojo** [comment]
_From @pwittrock on October 13, 2016 21:15_

@sauercrowd This should probably be moved out of the docs repo and somewhere else

**Comment by zacharysarah** [comment]
This resource appears to have been removed from the repo. It looks like the link to Ubuntu/Calico at `/docs/getting-started-guides/ubuntu/` now redirects to itself, so the page needs to be updated and the link removed.
