### ISSUE TITLE
I wish /docs/getting-started-guides/locally/ had instructions that work

### ISSUE THREAD

**Issue by georgevdd** [kubernetes/kubernetes.github.io#417]
I wish /docs/getting-started-guides/locally/ had instructions that work

"First, you need to download Kubernetes. Then open a separate tab of your terminal and run the following (since one needs sudo access to start/stop Kubernetes daemons, it is easier to run the entire script as root):
cd kubernetes
hack/local-up-cluster.sh"

Except, if I download a binary release, there is no 'hack' directory in it and no script called 'local-up-cluster.sh' anywhere.

**Comment by mikebrow** [comment]
Can you check again?  Each release has a couple files to download on the https://github.com/kubernetes/kubernetes/releases ... the hack/ files are in the ones called source code.  I agree it's not very obvious.
