### ISSUE TITLE
Update links to k8s.io/docs/user-guide/... in autogenerated docs

### ISSUE THREAD

**Issue by chenopis** [kubernetes/kubernetes.github.io#4194]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
There are still links in the kubernetes/kubernetes autogenerated docs to the deprecated /docs/user-guide/ directory in k8s.io. This issue is the same as [kubernetes/kubernetes#48105](https://github.com/kubernetes/kubernetes/issues/48105) in that repo.

**Proposed Solution:**
Submit a PR in kubernetes/kubernetes to fix all of the links containing kubernetes.io/docs/user-guide/. See https://github.com/kubernetes/kubernetes/search?utf8=%E2%9C%93&q=%2Fuser-guide%2F&type=

**Page to Update:**
types.go files in [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) repo

**Comment by ahmetb** [comment]
Isn't this the same as #4192?

**Comment by chenopis** [comment]
Sigh. Yes. :(
