### ISSUE TITLE
Getting started guides should mention support level and link back to index

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes.github.io#420]
In the old docs system, the getting started guides (e.g. http://kubernetes.io/docs/getting-started-guides/fedora/fedora_ansible_config/) were only discoverable via the index page (which is now http://kubernetes.io/docs/getting-started-guides/). So people always saw the "support level" information before getting to the actual doc. But now the docs are accessible via the left side nav bar (as well as via the index page). We should therefore include the "support level" information _in_ each doc, so someone who gets there via the nav bar understands the support level of the solution they're looking at. We should also include a hyperlink back to the index page from each of the getting started guides.

**Comment by jaredbhatti** [comment]
Hrm.  By "support level" do you mean "Alpha" "Beta" and "Stable"?

**Comment by davidopp** [comment]
It looks like my idea was inadvertently implemented, at least here's one example of it in action: https://kubernetes.io/docs/getting-started-guides/coreos/#support-level

My suggestion was just to have such a section in every getting started guide that we host ourselves.
