### ISSUE TITLE
Issue with k8s.io/docs/admin/high-availability/

### ISSUE THREAD

**Issue by g1001p** [kubernetes/kubernetes.github.io#4221]
**This is a...** 

- [ ] Feature Request
- [X ] Bug Report

**Problem:**
I have three k8s masters configured via nginx loadbalancer  to upstream master requests.
The 8080 port is balancing ok through the loadbalancer.
But requests coming through 6443 secured port of api server failed with error:
Failed to lidt *api.Service: Get https://192.168.3.1:443/api/v1/services?resourceVersion=0 tls: oversized record received with length 28012
###

Appreciate for any help.
**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

kubernetes version 1.4.0.4

ubuntu OS 14.04

**Comment by zacharysarah** [comment]
This issue sounds more like a request for support and less like an issue specifically for docs. I encourage you to bring your question to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/).
