### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/install-kubeadm/

### ISSUE THREAD

**Issue by talkdirty** [kubernetes/kubernetes.github.io#4222]
- [ ] Feature Request
- [x] Bug Report

**Problem:**

This does not work on a fresh Ubuntu Xenial 16.04 Instance:

```bash
apt-get update && apt-get install -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
# Install docker if you don't have it already.
apt-get install -y docker-engine
apt-get install -y kubelet kubeadm kubernetes-cni
```

for the following reason:

The installation hangs on `apt-get install -y docker-engine` forever, because docker-engine hangs at the end of the installation (will not start).

This seems like a known issue:

- https://github.com/moby/moby/issues/23347

- https://unix.stackexchange.com/questions/293675/installing-docker-hangs-at-setting-up-docker-engine-on-ubuntu-xenial

- https://forums.docker.com/t/problem-installing-docker-on-ubuntu-xenial-16-04/9273

**Proposed Solution:**

Installing and running `dmsetup` is an easy fix and works for me:

```
#!/bin/sh

apt-get update && apt-get install -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF

apt-get update

apt-get install dmsetup -y
dmsetup mknodes

# Install docker if you don't have it already.
apt-get install -y docker-engine

# Weird Ubuntu 16.04 Fix for Docker Installation
mkdir -p /etc/systemd/system/docker.service.d
cat <<EOF >/etc/systemd/system/docker.service.d/overlay.conf
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// -s overlay
EOF

apt-get install -y kubelet kubeadm kubernetes-cni
```

Can anyone confirm this on `Ubuntu Xenial 16.04`?

**Page to Update:**
https://kubernetes.io/docs/setup/independent/install-kubeadm/
The first script on the site.

**Comment by ahmetb** [comment]
I would recommend asking this on kubernetes-user mailing list. It appears like the docker issue has been closed as they haven't seen the same issue reported lately.

I'm not equipped to answer whether dmsetup should be included in the instructions. Feel free to send a patch and folks will review.

**Comment by zacharysarah** [comment]
@talkdirty This issue sounds more like a request for support and less like an issue specifically for docs. I encourage you to bring your question to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/).
