### ISSUE TITLE
rendering annotation `shell` is shown in example

### ISSUE THREAD

**Issue by MHBauer** [kubernetes/kubernetes.github.io#425]
There's an extra word in one of the verbatim exercise examples. I can guess that it's some kind of rendering directive. I don't know how to fix it or I would provide a PR. Screenshot and link to place in code below.

<img width="571" alt="screen shot 2016-04-22 at 09 34 01" src="https://cloud.githubusercontent.com/assets/13337345/14748275/a3aad772-086d-11e6-91f0-16231f5e67b5.png">

https://github.com/kubernetes/kubernetes.github.io/blame/master/docs/getting-started-guides/docker.md#L148

**Comment by atbaker** [comment]
@MHBauer - I think this bug may be fixed already. Can you confirm that it's still a problem and close if it's not?

cc @johndmulhausen

**Comment by MHBauer** [comment]
@atbaker yes, looks fixed. 

for my future reference, the fix appears to be adding raw/endraw 'tags' like `{% raw %} {% endraw %}` around the contents of the verbatim text.
