### ISSUE TITLE
[proposal] Creating play.kubernetes.io - Interactive Kubernetes Playground

### ISSUE THREAD

**Issue by BenHall** [kubernetes/kubernetes.github.io#4252]
Following on from a suggestion by @asim (https://twitter.com/chuhnk/status/881405640509460480)

We (Katacoda) would love to create and host play.kubernetes.io (or kubernetes.io/play) environment, similar to how the current interactive tutorials work on kubernetes.io. The aim would be to allow users to experiment with a Kubernetes cluster directly from their browser would any signup, downloads or configuration.

Katacoda already has a Kubernetes playground setup that provides a master/node for experimenting with Kubernetes. The playground sits alongside our interactive tutorials, similar to those hosted on the main site. You can see our existing playground at https://www.katacoda.com/courses/kubernetes/playground

If you agree it would be useful, I can send a pull request with the kubernetes.io/play page.

**Comment by idvoretskyi** [comment]
cc @kubernetes/sig-docs-maintainers @kubernetes/sig-cluster-lifecycle-misc

**Comment by chenopis** [comment]
Yeah, this sounds cool. Let me loop in @jaredbhatti, @devin-donnelly, and @steveperry-53.

**Comment by xetorthio** [comment]
Hey! We just released PWK (play with kubernetes), an opensource interactive playground (similar to the Docker's one). You might find it interesting. It is here: http://play-with-k8s.com
And there are more details here: https://medium.com/@marcosnils/introducing-pwk-play-with-k8s-159fcfeb787b

**Comment by BenHall** [comment]
This is something I had in mind:

![screenshot 2017-07-07 10 25 56](https://user-images.githubusercontent.com/82614/27952061-ed95bc84-62fe-11e7-8b70-4d00a445dfbe.png)

![screenshot 2017-07-07 10 26 43](https://user-images.githubusercontent.com/82614/27952065-f16d074a-62fe-11e7-8e94-947c80d4dfc2.png)

On my fork at https://github.com/BenHall/kubernetes.github.io/tree/playground

**Comment by steveperry-53** [comment]
This looks fantastic.
Before moving forward, I'd want to better understand the security concerns raised [here](https://twitter.com/chuhnk/status/881405640509460480).

**Comment by marcosnils** [comment]
Hi everyone PWK co-author here. We'd like to show you how the PWK integration would look and feel in the official kubenetes documentation site. For that purpose we created a video as an example so you can see some of the features that our OS playground provides.  Click on the below image to see the video.
[![PWK K8s](https://img.youtube.com/vi/IcSKpdqyXiM/0.jpg)](https://www.youtube.com/watch?v=IcSKpdqyXiM)

@steveperry-53 regarding security concerns, PWK is built using the same Open Source core as PWD (play-with-docker) which has been running for a while now and because it's an OS project it has been getting all the best security practices right from Docker security experts. As an additional fact, Docker has adopted our project as the their official and default playground for tutorials (training.play-with-docker.com), workshops, conferences and the response and participation of the community by sending PR's and adding tutorials has been amazing. We're also working on some new features that will make the platform even better.

We'd love to see the same effect in the K8s community as it happened in Docker's, so if you think this is the right approach, we're willing to help you out in whatever we can. Don't hesitate to mention either @xetorthio or me if you have any other questions.

**Comment by BenHall** [comment]
@steveperry-53 It's the same platform and security approach that has been powering the introduction tutorials on the site for the past 6/9 months (https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/). The only difference is it's an environment for kubeadm instead of minikube. 

I'm happy to go into details offline if you have particular questions.

**Comment by steveperry-53** [comment]
This looks good to me.
@devin-donnelly and @jaredbhatti, Could you chime in?
@jbeda, Do the comments in this PR address the security concerns you raised [here](https://twitter.com/chuhnk/status/881405640509460480)?

**Comment by marcosnils** [comment]
@steveperry-53 PWK heavily uses LSMs strategies to mitigate the concerns listed in that twitter conversation. As I said before, we work really close with Docker Inc security team to make sure all the best practices (selinux / apparmor / seccomp and cgroups) are taken into account in our playgrounds.

**Comment by xetorthio** [comment]
@steveperry-53 would you also consider play-with-k8s?

**Comment by steveperry-53** [comment]
@devin-donnelly, @jaredbhatti, I'd like to hear your comments on including these playgrounds in the kubernetes.io site. As I understand this proposal, there are two different playgrounds we could add to kubernetes.io: Katacoda and PWK.

**Comment by BenHall** [comment]
Sorry if opening this issue has put the team in an awkward position. I had thought that with the existing Katacoda integration and our current playground, it could have been a quick nice to have. 

While the original idea still stands and the PR is ready, to remove any potential conflict I see a couple of options:
  1) Embed both. I feel this would create a lot of confusion from the user's point of view. 
  2) Don't embed, just link to the various interactive playgrounds. I'm not 100% sure where it fits in with the site, and it might be best to leave this to projects like awesome-kubernetes.
  3) Park the proposal for now. 

Personally, I think 3. This conversation isn't fun to be part of, and I don't feel it's in-line with what the community is trying to achieve. 

Thank you @steveperry-53, @chenopis and @idvoretskyi for taking the time to consider the idea, I appreciate it.

**Comment by marcosnils** [comment]
Hi there, just wanted to share two new features we've implemented in PWK this week. Drag & Drop file uploads and we've adapted @kelseyhightower kubeadm tutorial to make it extremely easy to deploy a single node cluster through kubeadm. Here's a blog post about it https://medium.com/@marcosnils/easiest-single-node-kubernetes-cluster-f1deaf229bd5

**Comment by steveperry-53** [comment]
I've discussed this with several people, and the prevailing thought is that we should link to both the Katacoda and the PWK playgrounds, but we should not embed any playgrounds in the docs.

Here's a PR that add playgroung links to the prerequisite section for Tasks and Tutorials.
https://github.com/kubernetes/kubernetes.github.io/pull/4550

**Comment by BenHall** [comment]
@steveperry-53 Thanks for the update!! :)

**Comment by chenopis** [comment]
Thanks @steveperry-53 !
