### ISSUE TITLE
Source IP tutorial uses outdated (since 1.7) annotation method 

### ISSUE THREAD

**Issue by craigbox** [kubernetes/kubernetes.github.io#4271]
**This is a...** 
- [x] Bug Report

**Problem:**
The method for specifying traffic should be kept local to the node has been promoted from an annotation to a field in 1.7.

https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#feature-availability explains this.

**Proposed Solution:**
Update this page to match.

I'm not sure what our policy is on documenting previous versions.  Do we assume everyone is running 1.7 and only document the new method?

**Page to Update:**
k8s.io/docs/tutorials/services/source-ip/

**Comment by MrHohn** [comment]
> Page to Update:
k8s.io/docs/tutorials/services/source-ip/

Thanks for noticing, I missed this page. Will send a patch soon.
