### ISSUE TITLE
Pulling images by digest not documented 

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes.github.io#4290]
**This is a...**  Bug Report

**Problem:**
https://kubernetes.io/docs/concepts/containers/images/ page does not show how users can specify Docker images with SHA256 digests, resulting in issues like https://github.com/kubernetes/kubernetes/issues/26651.

In fact we don't have any documentation about this feature on the k8s.io at all.

**Proposed Solution:**
Create a section documenting images can be specified via digest as well.

**Page to Update:**
https://kubernetes.io/docs/concepts/containers/images/

**Comment by Bradamant3** [comment]
Note that I added the request info not to the suggested topic, but to a topic that's linked from there: https://kubernetes.io/docs/concepts/configuration/overview/#container-images

Rationale: The Images topic content is mostly about pulling from a private registry. The topic I put the info in contains more relevant detail about image tags, not using :latest, etc. Can move added content if deemed better, though.

**Comment by ahmetb** [comment]
@Bradamant3 do you mind linking the PR? I can't seem to find the change.

**Comment by chrissound** [comment]
This shows up as the first result on Google. Is this documented? If so where?

I've tried:

```
    Image:          kennethreitz/httpbin:sha256:599fe5e5073102dbb0ee3dbb65f049dab44fa9fc251f6835c9990f8fb196a72b
```

Which fails with:
```
  Warning  InspectFailed  5s (x7 over 71s)  kubelet, minikube  Failed to apply default image tag "kennethreitz/httpbin:sha256:599fe5e5073102dbb0ee3dbb65f049dab44fa9fc251f6835c9990f8fb196a72b": couldn't parse image reference "kennethreitz/httpbin:sha256:599fe5e5073102dbb0ee3dbb65f049dab44fa9fc251f6835c9990f8fb196a72b": invalid reference format
```

**Comment by petetnt** [comment]
@chrissound 

Probably not documented, but the format is `<name>@sha256:digest`
