### ISSUE TITLE
StatefulSet can be autoscaled by HPA policy

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes.github.io#4310]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
In https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/ , we are claiming that only `RC, RS and Deployment` can be autoscaled, we should also mention that the `StatefulSet` can be also autoscaled by HPA policy.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by gyliu513** [comment]
Related to https://github.com/kubernetes/kubernetes/issues/44033 https://github.com/kubernetes-incubator/cluster-proportional-autoscaler/issues/29

**Comment by chezbut** [comment]
I've actually not been able to get HPA working in a StatefulSet. 
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.service.name }}
  namespace: default
spec:
  maxReplicas: 12
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: StatefulSet
    name: {{ .Values.service.name }}
  targetCPUUtilizationPercentage: 30

**Comment by gyliu513** [comment]
Yes, this is not implemented yet, close this one for now.

**Comment by iselind** [comment]
Are there any plans for adding the support for this?

**Comment by jpza** [comment]
Bumping this but I believe it's scheduled for 1.9?

**Comment by karan-kapoor90** [comment]
Hey, any update for this? 👍

**Comment by jpza** [comment]
Bump

**Comment by funlake** [comment]
+1 
Need this feature badly

**Comment by tanujs-tech** [comment]
+1
