### ISSUE TITLE
I wish /docs/admin/dns/ did not describe DNS as an Add-On when it is basically required.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes.github.io#432]
I wish /docs/admin/dns/ did not describe DNS as an Add-On when it is basically required.

@kubernetes/sig-network

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/issues/9107#issuecomment-214527039

**Comment by thockin** [comment]
Can this be closed now?
