### ISSUE TITLE
Add info about running validate-cluster.sh

### ISSUE THREAD

**Issue by ApsOps** [kubernetes/kubernetes.github.io#433]
Can someone please give some info about running validate-cluster for a custom setup?

Basically help me fix the TODO here :) - https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/getting-started-guides/scratch.md#running-validate-cluster

**Comment by jaredbhatti** [comment]
Looks like this issue is fixed.  I'm closing this issue out for bug hygine purposes.  If there's still work to do here, please reopen.
