### ISSUE TITLE
Use a crawl to fetch all the invalid herf in doc

### ISSUE THREAD

**Issue by CaoShuFeng** [kubernetes/kubernetes.github.io#4331]
I wrote a crawl to fetch all the invalid herf in website:  https://kubernetes.io/docs/home/
This is my findlinks.go: http://paste.openstack.org/show/614826/
Run this command: 
go run findlinks.go https://kubernetes.io/docs/home/
Then we can find some invalid herf.
I fixes part of them:
https://github.com/kubernetes/kubernetes.github.io/pull/4330
But I found that there are so many invalid herf.
http://paste.openstack.org/show/614827/     (part of them)
I opened this issue to trace the invalid herf.

**Comment by CaoShuFeng** [comment]
@zhangxiaoyu-zidif  @jianglingxia may have interest to this issue.

**Comment by CaoShuFeng** [comment]
@chenopis

**Comment by zhangxiaoyu-zidif** [comment]
Thanks @CaoShuFeng , We have a similar tool, right? @chenopis .
This would be a good supplement.

**Comment by chenopis** [comment]
@CaoShuFeng @zhangxiaoyu-zidif We do have a tool, but it might be good to also have a published script that anyone else can run too.
