### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/assign-pod-node/

### ISSUE THREAD

**Issue by ekeoch** [kubernetes/kubernetes.github.io#4352]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
I have different types pods and I want to add limitations based on the number of each type/category of pod that can be run on a node. E.g. assuming I can allocate 10 pods to a node and have 2 categories of pods, lets say A, and B. I would like to be able to partition that available space to 6A + 4B pods. If a 5th B pod is required, the task should be pushed to the next available node or an error should be thrown. In addition to label based partitioning there should also be resource based partitioning as well.

**Proposed Solution:**
I'll leave this portion open to ideas, and/or suggestions to achieve something similar.

**Page to Update:**
http://kubernetes.io/...

**Comment by zacharysarah** [comment]
@ekeoch This sounds like a feature request for Kubernetes itself rather than a feature request for docs. I encourage you to open a separate issue in [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes).
