### ISSUE TITLE
Issue with k8s.io/docs/concepts/architecture/nodes/

### ISSUE THREAD

**Issue by jandsu** [kubernetes/kubernetes.github.io#4357]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
Ambiguous wording:

> **MemoryPressure**  True if node has no memory pressure, otherwise False

Could be understood as _if node as a "no-memory" pressure_ (which is what I understand from context) of _if node does not have a memory pressure_ (which is what I understand without the context)

So it is not clear if this means the memory is low or not...

**Proposed Solution:**

Pick up the appropriate wording (I don't know for sure what is true).

Same for disk BTW

**Page to Update:**
https://kubernetes.io/docs/concepts/architecture/nodes/

**Comment by Bradamant3** [comment]
Looking for small fixes as a better entry point to the community -- I'll take this one
