### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by alexandreStein** [kubernetes/kubernetes.github.io#4361]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
I can't even start the tutorial.
Here is the screenshot of the initial page after clicking on **START SCENARIO:**
![Screen shot](https://preview.ibb.co/gKZCFF/Capture_d_cran_de_2017_07_13_11_07_54.png)

I tried with Chromium and Firefox but both give me the same result.

**Proposed Solution:**
I don't know what can be the problem, I have no idea.
When I use the debugger I can see the blurry area and I see:
**Problem accessing cookies. Are cookies enabled?**
![Screen shot](https://preview.ibb.co/eAbdNv/Capture_d_cran_de_2017_07_13_11_20_34.png)

I don't block cookies:
![Screen shot](https://preview.ibb.co/dG8EvF/Capture_d_cran_de_2017_07_13_11_25_40.png)

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/

**Comment by BenHall** [comment]
Thanks for the report. Are you behind any proxies that could be blocking web sockets?

**Comment by alexandreStein** [comment]
Thanks for the quick reply.

I'm not behind a "real" HTTP proxy. I use a Shadowsock tunnel with mp-TCP to get much better bandwidth.
But it's not suppose to filter anything.
This should not be the issue, and when I connect directly to the web (no transparent proxy) I have the same behavior.

Yes, it's a Linux Ubuntu 17.04 with Kernel 4.10.0-26-generic.
The Chromium version is: 59.0.3071.109
The Firefox version is: Mozilla Firefox 54.0

I just tried with a Windows 7 on the same network (and mutlipath) and it's working.

Does it can be OS related?

Thanks again.

**Comment by BenHall** [comment]
Sounds like a potential Linux issue. Let me investigate. Thanks for telling us.

**Comment by alexandreStein** [comment]
Tell me if I can help.
If yes tell me who :smile:

**Comment by BenHall** [comment]
1) Just to double check, can you try directly on https://katacoda.com/kubernetes-bootcamp please ?
2) I'm guessing there are no JavaScript errors in the console?

**Comment by alexandreStein** [comment]
Thank to you for taking care of it.
Tell me if and who could I help.

**Comment by alexandreStein** [comment]
Sorry I messed up with my different devices...
The issue is still open.

The link you gave me works correctly.
![screen shot](https://preview.ibb.co/kDenZa/Capture_d_cran_de_2017_07_13_16_44_33.png)

You are right, there is no error in the console.
![screen shot](https://preview.ibb.co/kAZnZa/Capture_d_cran_de_2017_07_13_16_41_23.png)

The error you see are just about fonts.

**Comment by BenHall** [comment]
Interesting, must be something to do with iFrames and cookies. Thanks for the additional info.

**Comment by zacharysarah** [comment]
@benhall Just to clarify, should this issue remain open?

**Comment by BenHall** [comment]
@zacharysarah Yes, working on this but haven't been able to reproduce yet. Will continue to explore.

**Comment by alexandreStein** [comment]
Hi,

Just to keep you inform.
I made a minor kernel update from **4.10.0-26-generic** to **4.10.0-28-generic**.
And I got the same behavior.

But I will reinstall my computer.
On the browser this is the only thing I noticed but my system has other problems.

Long story short, I probably won't be able to track this bug anymore.
It looks like I'm the only affected guy so this is probably not a big issue.

Thanks for the help.
Best regards

**Comment by BenHall** [comment]
Thanks for the update. It's a problem related to cookies and certain browser settings. We're working on a fix at the moment and should be live by the end of the week.

**Comment by alexandreStein** [comment]
So you are able to reproduce the problem?
Great work.

Thanks you for what your are doing.

**Comment by BenHall** [comment]
I believe we've deployed a fix to resolve this. If you get a moment, could you please retest @alexandreStein ?

Thank you

**Comment by alexandreStein** [comment]
Yes it's working. 
I changed kernel and OS last week and it was behaving the same way.

I just tried with Chromium on Arch and it looks to be working as expected.

Thank you, feel free to close the issue.
