### ISSUE TITLE
Issue with k8s.io/docs/setup/

### ISSUE THREAD

**Issue by saydulk** [kubernetes/kubernetes.github.io#4367]
i need to have installation document for setup into ubuntu 14.04 LTS 

**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by zacharysarah** [comment]
@saydulk Does this link give you the information you need? If not, please feel free to re-open this issue.

https://kubernetes.io/docs/getting-started-guides/ubuntu/

**Comment by saydulk** [comment]
yes, thanks :)
