### ISSUE TITLE
Accessing kubernetes v1.6 documentation

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes.github.io#4374]
**Problem:**

<https://kubernetes.io/docs/> has been updated to v1.7, but there is no links to old-versioned documentation, e.g v1.6. Is v1.6 documentation still published? If yes, where can we access it?

**Comment by kkirsche** [comment]
At least for the API documentation, that's at https://kubernetes.io/docs/api-reference/v1.6/ which I got from https://kubernetes.io/docs/reference/

Not sure about the more generalized documentation

**Comment by feiskyer** [comment]
@kkirsche Yep, noticed there is the api-references for different releases, but no other documentations for v1.6.

**Comment by feiskyer** [comment]
Already added at https://v1-6.docs.kubernetes.io/docs/home/, closing it.
