### ISSUE TITLE
Link to English-language page redirects to Chinese-language page

### ISSUE THREAD

**Issue by ryanmcginnis** [kubernetes/kubernetes.github.io#4389]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
This link:

https://kubernetes.io/docs/user-guide/working-with-resources

redirects to this page:

https://kubernetes.io/cn/docs/tutorials/object-management-kubectl/object-management/

The link is found here:

https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#writing-a-job-spec

**Proposed Solution:**
Fix the redirect for /docs/user-guide/working-with-resources

**Page to Update:**
Redirect for https://kubernetes.io/docs/user-guide/working-with-resources

**Comment by php-coder** [comment]
Yeah, it's confusing. Why it's P3? How hard to fix it? How I can help?

**Comment by chenopis** [comment]
I know what the problem is and will submit a PR shortly. None of the pages in the /cn directory should have the `redirect_from` directive at the top of the page. For example, currently, /cn/docs/tutorials/object-management-kubectl/object-management.md has this set at the top of the page:

```
redirect_from:
- "/docs/concepts/tools/kubectl/object-management-overview/"
- "/docs/concepts/tools/kubectl/object-management-overview.html"
- "/docs/user-guide/working-with-resources/"
- "/docs/user-guide/working-with-resources.html"
```

**Comment by php-coder** [comment]
@chenopis Wow! Thank you!!

**Comment by chenopis** [comment]
Ok, nothing should be redirected to the /cn pages anymore. Cheers
