### ISSUE TITLE
KUBERNETES DASHBOARD

### ISSUE THREAD

**Issue by nik786** [kubernetes/kubernetes.github.io#4394]
I have tried to complete kubernetes clustering program. But I have faced below mentioned error. "User "system:anonymous" cannot proxy services in the namespace "kube-system".: "No policy matched.\nUnknown user \"system:anonymous\"" 
Im using google cloud. I have used following commands
gcloud auth list
gcloud auth application-default login
gcloud compute zones list
gcloud config set compute/zone us-east1-c
gcloud container clusters create connector-dev
gcloud container clusters describe connector-dev
kubectl cluster-info

**Comment by nik786** [comment]
any help??

**Comment by minivan** [comment]
@nik786 This repository is about issues with the Kubernetes documentation, and not the Kubernetes product. We won't be able to fix it here.

You can look through the issues opened in the [kubernetes repository itself](https://github.com/kubernetes/kubernetes/issues) or [search for your error on stackoverflow](https://stackoverflow.com/questions/tagged/kubernetes). You'll be able to get much quicker help on the latter.

[Here's an issue](https://github.com/kubernetes/kubernetes/issues/39722) describing a similar problem to yours, please check if the answers there help.

Cheers!

**Comment by zacharysarah** [comment]
This issue sounds more like a request for support and less like an issue specifically for docs. I encourage you to bring your question to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/).
