### ISSUE TITLE
Update Ubuntu install guide for v1.2.x

### ISSUE THREAD

**Issue by nebirhos** [kubernetes/kubernetes.github.io#440]
I'm trying to start Kubernetes v1.2.3 on bare-metal nodes running Ubuntu 14.04.
Here's my config:

```
export KUBE_VERSION=1.2.3
export FLANNEL_VERSION=0.5.5
export ETCD_VERSION=2.2.5
export KUBERNETES_PROVIDER=ubuntu
```

Installation works fine but pods are not able to communicate across different nodes.
Error is the same reported in kubernetes/kubernetes#24002 .

K8s 1.1.8 worked flawlessly on the same machines with the same configuration, maybe guide needs to be updated for v1.2.3?

**Comment by bryk** [comment]
+1. There is no week without people reporting issues with running services (e.g., Dashboard UI) on clusters created from this guide.

**Comment by ganting** [comment]
+1
the flanneld.log
```
I0429 13:26:09.698006 07911 vxlan.go:345] L3 miss: 172.16.96.2
I0429 13:26:09.699338 07911 device.go:187] calling NeighSet: 172.16.96.2, 8e:51:a9:8a:02:16
I0429 13:26:09.699790 07911 vxlan.go:356] AddL3 succeeded
I0429 13:26:25.561750 07911 vxlan.go:340] Ignoring not a miss: 8e:51:a9:8a:02:16, 172.16.96.2
```

**Comment by nebirhos** [comment]
Any update on this?

**Comment by jaredbhatti** [comment]
I believe this issue has been fixed, and there's a much larger write of Ubuntu happening right now. 
https://github.com/kubernetes/kubernetes.github.io/pull/1932
