### ISSUE TITLE
I wish /docs/user-guide/services/ NodePort was documented more clearly

### ISSUE THREAD

**Issue by cognitiaclaeves** [kubernetes/kubernetes.github.io#441]
I wish /docs/user-guide/services/ NodePort was documented more clearly.

( Ok, I had no idea this was going to push me into an issue... I'm not prepared for that. )

I wasn't able to figure out how to set up a NodePort in this documentation. I happened to figure it out from this line:

> The service.spec.publicIPs property is deprecated and now called service.spec.deprecatedPublicIPs. This property will be removed entirely when v1beta3 is removed. The vast majority of users of this field were using it to expose services on ports on the node. Those users should specify service.spec.type: "NodePort" instead. Read External Services for more info. ...

on this page: https://github.com/kubernetes/kubernetes/blob/master/docs/api.md

( Note how that page references the path explicitly.  Also, there is no example under the section 'NodePort', and the example that follows has an element 'nodePort' ... very confusing ... )

**Comment by jaredbhatti** [comment]
It's more explicitly on the services pages. http://kubernetes.io/docs/user-guide/services/
