### ISSUE TITLE
Facing issue to setup kubernetes on CentOS 7.3(Master) and Ubuntu 16.04(Nodes)

### ISSUE THREAD

**Issue by SuryaPractise** [kubernetes/kubernetes.github.io#4432]
Hi Team,

Is kubernetes compatable with CentOS 7.3 version?

I am trying to setup Kubernetes master with Centos7.3 and nodes with ubuntu 16.04.
Please let me know is OS versions causing issues in my case?if yes let me know which OS version can be used to bring setup up as mentioned in guide.
I followed instruction as mentioned in guide https://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/#warning but some or the other component fail to work.

Please let me know anything required from my end to dig deeper.
Thanks,
Surya

**Comment by zacharysarah** [comment]
@SuryaPractise :wave: The guide you linked to has a deprecation warning at the top and links to an [updated guide](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/):

> This quickstart shows you how to easily install a Kubernetes cluster on machines running Ubuntu 16.04+, CentOS 7 or HypriotOS v1.0.1+.

If you still encounter difficulty, I encourage you to bring your question to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/).
