### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by ticstoad** [kubernetes/kubernetes.github.io#4438]
**This is an issue with the interactive tutorial for kubernetes** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
Interactive tutorial system for kubernetes encounters errors even with a refreshed page

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment]
Thanks for your bug report. Could you please let me know the error message displayed?

**Comment by BenHall** [comment]
I believe we've deployed a fix for this. Could you please retest? Thank you.

**Comment by zacharysarah** [comment]
@ticstoad :wave: The tutorial currently loads correctly. Please feel free to reopen this issue if you continue to experience difficulty.
