### ISSUE TITLE
I wish /docs/getting-started-guides/mesos/ explained high-availability kubernetes setup for kubernetes-mesos!

### ISSUE THREAD

**Issue by vincepii** [kubernetes/kubernetes.github.io#444]
This is explained in http://kubernetes.io/docs/admin/high-availability/, but how about kubernetes-mesos? Are there implications that we need to consider?

**Comment by jaredbhatti** [comment]
Mesos is documented here: http://kubernetes.io/docs/getting-started-guides/mesos/
