### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/service-access-application-cluster/

### ISSUE THREAD

**Issue by ryanmcginnis** [kubernetes/kubernetes.github.io#4440]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
- Step 7 should include instructions for GKE
- Step 8 should explain how to set up a firewall rule (bias: ideally on GKE) — this is the very first time it's mentioned in the instructions but it isn't clear how to do that

**Proposed Solution:**
See above

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/service-access-application-cluster/

**Comment by zacharysarah** [comment]
@ryanmcginnis 👋 Thanks for opening this issue. I agree that links to outside resources (GKE, firewall rules) would be helpful.
