### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/declare-network-policy/

### ISSUE THREAD

**Issue by tmjd** [kubernetes/kubernetes.github.io#4456]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The "Network Policy API" link (https://kubernetes.io/docs/user-guide/network-policies) on the page https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/
 leads to a 404.

**Proposed Solution:**
Link to either one or both of https://kubernetes.io/docs/concepts/services-networking/network-policies/ or https://kubernetes.io/docs/api-reference/v1.7/#networkpolicy-v1-networking.  The link indicates API but I would maybe be inclined to just change it to "Network Policy" and link to https://kubernetes.io/docs/concepts/services-networking/network-policies/ since it is more focused on the Network Policy and easier to read than going straight to the api and it is much easier to read.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/

**Comment by Bradamant3** [comment]
I'd like to say here what a great pleasure it is to work with a reporter who does all the legwork for the writer. Thank you @tmjd ! (Note also that the concept topic includes a link to the API reference topic -- so the concept topic link is the solution in the PR)

**Comment by tmjd** [comment]
:+1: I'm glad to help. I had thought about putting up a PR but didn't know if there was a more appropriate link so I thought this was the best course of action.
