### ISSUE TITLE
I wish /docs/user-guide/debugging-services/ http:// should prefix ip addresses of pods on "wget -qO-" commands

### ISSUE THREAD

**Issue by borg286** [kubernetes/kubernetes.github.io#447]
I wish /docs/user-guide/debugging-services/ http:// should prefix ip addresses of pods on "wget -qO-" commands

Currently the debugging instructions have 
wget -qO- <insert pod IP>
instructions. The wget command often doesn't play nice if the url you're trying to hit doesn't have an 
http:// in front of the IP address.

**Comment by jaredbhatti** [comment]
Replaced with generic "hostname" 
http://kubernetes.io/docs/user-guide/debugging-services/
