### ISSUE TITLE
Home page improvements

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes.github.io#453]
The top of kubernetes.io says "Manage an infrastructure cluster as a single system." But this point that Kubernetes aggregates/virtualizes/abstracts cloud/datacenter resources never gets mentioned again, either in the section "above the fold" or in the "Kubernetes features." Yet it's actually the enabler for all of the container management features that are described. The way it is placed on the page right now, it's almost invisible. We can leave it where it is, but in addition, we should also restate it in one of the other, more visible sections.

I'm happy to work with someone on this.

cc/ @bgrant0607

**Comment by bgrant0607** [comment]
More generally, we should think harder about our elevator pitch and sound bites.

Other problems with the home page:

* The diagram next to the synopsis of what Kubernetes does is not very understandable (what are the boxes? what is the K8s icon? only one node?). We need a better one. The [cloud diagram](https://deis.com/blog/2016/kubernetes-overview-pt-1/) is much closer but could use some tweaks (e.g., eliminate "Master"). Also, a little bit of animation would make it stand out a lot more.
* The amount of space around Planet Scale, Never Outgrow, and Run Anywhere blurbs is disruptively excessive.
* Few things on the homepage are clickable, for learning more about a topic and/or calling to action. In particular, there's no link to whatisk8s.md. In contrast, check out https://prometheus.io/.
* It's not that attractive. Why gray and white?

cc @johndmulhausen @kubernetes/docs

**Comment by jaredbhatti** [comment]
Bob Hrdinsky owns the front page of kubernetes.io.
