### ISSUE TITLE
kubernetes controller has no --apiserver flag

### ISSUE THREAD

**Issue by aabed** [kubernetes/kubernetes.github.io#4538]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

in this file
https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/tasks/run-application/horizontal-pod-autoscale.md
 it states that to enable custom metrics you should pass api aggregator to the manager using --apiserver

but

--apiserver is unknown flag to the kube-controller-manager

**Proposed Solution:**

**Page to Update:**
https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/tasks/run-application/horizontal-pod-autoscale.md

**Comment by ahmetb** [comment]
Is it called `--api-server` perhaps? The next paragraph refers to an `--api-server` flag on Heapster.

/assign @directxman12
it appears like @directxman12 added this in #2720.

**Comment by DirectXMan12** [comment]
It's now either `--master` or `--kubeconfig`, it appears

**Comment by zacharysarah** [comment]
There may be some research to do here about which flag to use, but this still looks actionable for docs purposes.

**Comment by ahmetb** [comment]
@DirectXMan12 if you have any familiarity, I appreciate if you can submit a PR.

**Comment by abiogenesis-now** [comment]
Doc fix for this was merged last week
