### ISSUE TITLE
I wish /docs/user-guide/pod-states/ had actual YAML examples

### ISSUE THREAD

**Issue by analytik** [kubernetes/kubernetes.github.io#456]
First, there's a lot of dead links everywhere still leading to github markdown-based documentation.

Second, [API reference](http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_httpgetaction) for example for `v1.Probe` and `initialDelaySeconds` says "For more information, check `/docs/user-guide/pod-states/`. But there's no explanation, nor examples for `initialDelaySeconds` on that page.

Also, it could maybe mention if it's relevant to ReplicaSets, since they seem to be the recommended thing to use now instead of RCs?

**Comment by jaredbhatti** [comment]
The doc has a set of examples now, and the broken links are fixed.
