### ISSUE TITLE
CRD page should refrence API docs

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubernetes.github.io#4573]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

**Problem:**
CRD task should link to the API definition of objects that are referenced.  In general, we should try to create cross references between task oriented pages and reference pages.  That way users can dig into the details as they start coloring outside the lines from what is described in the task.

**Proposed Solution:**

Introduce an optional "See Also" section (or use "What's next") and reference all API objects that are talked about in this (and other) task pages.

**Page to Update:**
https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/

Also: The API docs (https://kubernetes.io/docs/api-reference/v1.7/) don't have CRDs there.  That looks like it might be this issue: https://github.com/kubernetes/kubernetes/issues/49811.

**Comment by nikhita** [comment]
Update: API reference docs for 1.8 have CRDs now. :tada: 

(1.7 still shows only TPRs though)
