### ISSUE TITLE
URL can not access

### ISSUE THREAD

**Issue by rootsongjc** [kubernetes/kubernetes.github.io#4585]
The URL [example](https://github.com/kubernetes/client-go/blob/master/examples/in-cluster/main.go)  can not access at the doc https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/tasks/access-application-cluster/access-cluster.md
-  use the Go client library, and create a client using the rest.InClusterConfig() and kubernetes.NewForConfig()functions. They handle locating and authenticating to the apiserver. [example](https://github.com/kubernetes/client-go/blob/master/examples/in-cluster/main.go)

I think we should change this URL to https://github.com/kubernetes/client-go/blob/master/examples/in-cluster-client-configuration/main.go

**Comment by wackxu** [comment]
I can help fix it

**Comment by nikhita** [comment]
This is fixed now and can be closed.
