### ISSUE TITLE
Fix site 404s

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/kubernetes.github.io#4642]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The kubernetes.io site console logs 404 status results for desktop and mobile. As of August 4, 2017, there are:
- 140 desktop 404s
- 9 mobile 404s

**Proposed Solution:**

Make sure that URLs returning 404 results have valid entries in the [`/_redirects`](https://github.com/kubernetes/kubernetes.github.io/blob/master/_redirects) file and redirect correctly.

**Page to Update:**

N/A

**Additional Information:**

This issue can only be fixed by maintainers/collaborators with access to the `kubernetes.io` site console. 

/visibility: @chenopis, @jaredbhatti, @steveperry-53

**Comment by zacharysarah** [comment]
## Challenging redirects

@chenopis :wave: How do we want to resolve cases like [this 404 for font-awesome](https://kubernetes.io/docs/api-reference/v1.6/node_modules/font-awesome/)? Here are some of the challenges:
- The link results in a 404; but
- Site search on kubernetes.io for font-awesome [still returns site hits](https://kubernetes.io/docs/search/?q=font-awesome)
- Google search for Kubernetes and font-awesome [returns repo hits](https://www.google.com/search?q=kubernetes+font-awesome)
- The content is [still in the repo](https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/resources-reference/v1.5/node_modules/font-awesome/README.md) but doesn't render on the site; and
- The history for [font-awesome](https://github.com/kubernetes/kubernetes.github.io/commits/master/docs/resources-reference/v1.5/node_modules/font-awesome) doesn't reveal much.

## Possible solutions

1. Add a 404 rewrite to `/_redirects`

I don't think this is the way to go. My concern is that the site will log these to the console with no real difference.

2. Add a 301 rewrite to a custom `404.html`

This may produce a better outcome: helpfully redirecting users away from missing content while treating the missing URL as a 301 rather than a 404.

We'd have to create a custom `404.html` file and go through the process of adding a new file to the site, but that's pretty lightweight.

What do you think @chenopis?

**Comment by chenopis** [comment]
Here are the remaining ones I can find using the Screaming Frog SEO Spider:

[response_codes_client_error_(4xx).csv.zip](https://github.com/kubernetes/kubernetes.github.io/files/1206352/response_codes_client_error_.4xx.csv.zip)

**Comment by chenopis** [comment]
@zacharysarah I set a redirect for anything matching `/docs/api-reference/v1.6/node_modules/*` to go to https://v1-6.docs.kubernetes.io/docs/api-reference/v1.6/

**Comment by zacharysarah** [comment]
Three of the 404s in the CSV file look like syntax errors: 
`https://kubernetes.io//docs/admin/authorization/rbac.md`
`https://kubernetes.io//docs/admin/node-allocatable.md1`
`https://kubernetes.io//docs/tutorials/federation/set-up-cluster-federation-kubefed.md`

**Comment by chenopis** [comment]
@zacharysarah Yeah, see if you can search in the docs for these typos. I can help tomorrow.

**Comment by steveperry-53** [comment]
@zacharysarah @chenopis I think the 404s are fixed for the 1.8 doc set. Screaming Frog and [linkchecker](https://linux.die.net/man/1/linkchecker) both give me clean reports. The kubernetes.io console shows a bunch of 209s, but I can't reproduce any problems in the pages that are shown as Linked From.

We still have some 404s in old versions of the docs, especially ref pages. I'm planning to fix those soon.

OK to close this?

**Comment by zacharysarah** [comment]
@steveperry-53 Thanks for looking at this--yes, I think we can close it. @chenopis and I have a standing monthly appointment to review the site 404 log; it's beginning to stabilize and taper off.
