### ISSUE TITLE
docs/hellonode.md Is missing 'gcloud container clusters get-credentials'

### ISSUE THREAD

**Issue by jeffmendoza** [kubernetes/kubernetes.github.io#471]
Currently it has:

> It’s now time to deploy your own containerized application to the Kubernetes cluster! Please ensure that you have configured kubectl to use the cluster you just created.

With just the link out, which is easy to miss

**Comment by jeffmendoza** [comment]
@pjfitzgibbons

**Comment by timBrockman** [comment]
It is on line 139, a couple sentences above the "Create your Pod" heading.

**Comment by runseb** [comment]
@jeffmendoza this seems fixed. Can we close the ticket ?

**Comment by jeffmendoza** [comment]
Looks good!

**Comment by pjfitzgibbons** [comment]
@jeffmendoza Yep, good now.  Thanks!
