### ISSUE TITLE
AI: Create mini style guide.

### ISSUE THREAD

**Issue by chenopis** [kubernetes/kubernetes.github.io#4742]
Create a mini style guide for how we should write and implement glossary snippets.

**Comment by chenopis** [comment]
@abiogenesis-now @heidecke

**Comment by chenopis** [comment]
@Bradamant3 Where should we put this? If I create a template file that people can clone and drop in content, i.e. `_snippet-example.md`, should we maybe just put it in there so that people can refer to it without having to look at a different file?

**Comment by Bradamant3** [comment]
I've stubbed this out. Examples are the next step, but would like feedback first before I develop them.

Minimum viable snippet:
<short-description>Required. One or two lines that provide a minimum definition. Do not repeat the term. Prefer fragments. Model after tooltips.
<long-description>Optional. Longer additional text to appear after (in conjunction with) short description. Provide where the short description is not sufficient as the intro paragraph to a topic. Write complete but concise sentences.

**Comment by Bradamant3** [comment]
Woops, +100 to including in an example template, not a separate file. Hence review here :-)

**Comment by abiogenesis-now** [comment]
Seems reasonable to me!

**Comment by chenopis** [comment]
I've added the draft to `/_includes/glossary/_glossary-template.md`. Feel free to make additional changes there.

**Comment by chenopis** [comment]
@Bradamant3 Do you want to keep this open, or should I close this now that we have something committed to the repo?

**Comment by chenopis** [comment]
This was addressed by https://github.com/kubernetes/kubernetes.github.io/pull/4865 in `_includes/templates/glossary/README.md`.
