### ISSUE TITLE
https does not work for kubernetes.io

### ISSUE THREAD

**Issue by errm** [kubernetes/kubernetes.github.io#475]
I expect to be able to visit https://kubernetes.io/ but it times out.  It should be best [practice to allow access to the site over https](https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https?hl=en)

**Comment by idvoretskyi** [comment]
+1.

This feature is not mandatory, but strongly nice to have.

**Comment by jaredbhatti** [comment]
Yep. Known issue that github pages doesn't support.  Trying to figure out a workaround.
