### ISSUE TITLE
I wish /docs/user-guide/downward-api/ had more thorough documentation about the structure of the dataset that fieldPath expressions are evaluated against.

### ISSUE THREAD

**Issue by akshayl** [kubernetes/kubernetes.github.io#480]
I wish /docs/user-guide/downward-api/ had more thorough documentation about the structure of the dataset that fieldPath expressions are evaluated against.

**Comment by steveperry-53** [comment]
/docs/user-guide/downward-api/ has been updated and relocated here:
https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/

I think the link to the ref page for [DownwardApiVolumeFile](https://kubernetes.io/docs/api-reference/v1.8/#downwardapivolumefile-v1-core) addresses the concern here.
