### ISSUE TITLE
Broken code block in `docs/concepts/services-networking/connect-applications-service`

### ISSUE THREAD

**Issue by nicr9** [kubernetes/kubernetes.github.io#4806]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:** I found a broken code block in [this section](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#exposing-pods-to-the-cluster) of the docs. Instead of being interpreted as shell code it is interpreted as plaintext and ignores newlines. I believe this is because there's no empty line between the code block and the preceding paragraph.

**Proposed Solution:** Add a newline.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

**Comment by radhikapc** [comment]
@nicr9 : We are not able to view the issue you have mentioned here. Please provide a screenshot of the broken code block, so that we can take it forward.

**Comment by nicr9** [comment]
@radhikapc Ah! It seems this was already fixed in #4782 which was only merged 3 hours ago!

Guess I'll have to find some other way to make myself useful :stuck_out_tongue: 

This issue and #4807 can be closed

**Comment by radhikapc** [comment]
That's cool @nicr9
