### ISSUE TITLE
Summarize|Surface HTML ID tags so that readers may grab them to use as references

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/kubernetes.github.io#489]
Surface HTML ID tags so that readers may grab them to use as references.

E.g.
/docs/user-guide/namespaces/

Rather than "Go to this page and scroll down to 'Namespace and DNS'
Enable "Click this link to go to 'Namespace and DNS'"

The page contains multiple ID references but these aren't surfaced to the reader of the page once rendered:

/docs/user-guide/namespaces/#setting-the-namespace-for-a-request
/docs/user-guide/namespaces/#setting-the-namespace-preference
/docs/user-guide/namespaces/#namespaces-and-dns
etc.

Recommend:
1. Each page should summarize (ToC) these links (so the hyperlinks could be grabbed)
2. Each ID should be annotated with a bookmark for the reader to grab the specific anchor

**Comment by jaredbhatti** [comment]
Agreed.  We now have a travis check that requires a TOC, and TOC entries have anchors.
