### ISSUE TITLE
I wish /docs/ would make the floating footer smaller.

### ISSUE THREAD

**Issue by borg286** [kubernetes/kubernetes.github.io#50]
![footer too big](https://cloud.githubusercontent.com/assets/8532481/13548579/551323d4-e2a8-11e5-81da-60ab03cf783d.png)
I wish / make the footer smaller.  It covers half of my screen. It is worse when I shrink my browser window horizontally which causes the items "Getting Started" "Documentation" "Blog" and "Community" to pile up vertically.  I'm not interested in these links. You have a hamburger menu in the top right. Use it.

**Comment by johndmulhausen** [comment]
Fixed. Thanks!
