### ISSUE TITLE
Diagram for `kubectl drain` command

### ISSUE THREAD

**Issue by andreykurilin** [kubernetes/kubernetes.github.io#501]
Hi!
I would like to add diagram for `kubectl drain` command. It is already done (you can find it [here](http://andreykurilin.me/share/kubectl_drain.png) ). 
But I found that http://kubernetes.io/docs/user-guide/kubectl/kubectl_drain/ page is auto-generated from the code, so I have several questions:

1) What is a proper place for images for such pages and how can I insert it?
2) What is your opinion about this diagram and about similar diagrams in general?

**Comment by bgrant0607** [comment]
cc @mml

**Comment by bgrant0607** [comment]
@andreykurilin Nice diagram! In general, we would like more diagrams.

How did you create it? If someone needs to update it, how would they do that?

Yes, that page is generated from kubectl help. While we figure out something better, we could link to the diagram from the help description.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/drain.go#L112

cc @johndmulhausen @kubernetes/docs

**Comment by andreykurilin** [comment]
@bgrant0607 
> Nice diagram! In general, we would like more diagrams.

Thanks! I have one more ;) for [rolling-update](http://andreykurilin.me/share/kubectl_rollingupdate.png)

> How did you create it? If someone needs to update it, how would they do that?

I used draw.io online service. It is free and I do not see any ad there (maybe because of adblock :D ). It supports import/export mechanism via xml(an example of [compressed dump](http://andreykurilin.me/share/kubectl_drain.xml) and [uncompressed dump](http://andreykurilin.me/share/kubectl_drain_full.xml) for kubectl_drain diagram). So it is possible to put xml source file somewhere near the image.

> Yes, that page is generated from kubectl help. While we figure out something better, we could link to the diagram from the help description.

So I need to make two PR: first one to https://github.com/kubernetes/kubernetes.github.io/tree/master/images/docs and second one with description update. Am I right?

**Comment by andreykurilin** [comment]
@bgrant0607
> If someone needs to update it, how would they do that?

Also, the service I used supports export to svg, so it should be not a hard task to extend diagram with other tools.

**Comment by bgrant0607** [comment]
@pwittrock @johndmulhausen Any suggestions?
