### ISSUE TITLE
DaemonSet tolerates more taints than currently documented

### ISSUE THREAD

**Issue by tengqm** [kubernetes/kubernetes.github.io#5011]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
A DaemonSet by default tolerates not only node ready and node reachability taints. 
By design, it can tolerate memory pressure and disk pressure taints.
For critical pods, it can tolerate outOfDisk taint as well.

**Proposed Solution:**
The above mentioned features should be documented.

**Page to Update:**
http://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#how-daemon-pods-are-scheduled

**Comment by radhikapc** [comment]
@tengqm Let the doc team know if you require any assistance from SMEs. Since you have assigned the defect to yourself, we assume that you have all the necessary information to fix this issue.

**Comment by tengqm** [comment]
@radhikapc Thanks for the heads up. The source code (and comment) is already telling us what were missing.
