### ISSUE TITLE
Initializer admission control plugin not documented

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes.github.io#5019]
**Page to Update:** https://kubernetes.io/docs/admin/admission-controllers/
**This is a...**  Bug Report

**Problem:** The `Initializer` admission controller plugin is not listed as one of the plugins in the documentation.

**Proposed Solution:** Someone with a bit more authoritative knowledge than me to add a paragraph or two explaining what this plugin does. I can add too if you give me a brief explanation.

/cc @caesarxuchao @smarterclayton

**Comment by tengqm** [comment]
addressed in pr #4751

**Comment by radhikapc** [comment]
@ahmetb  Hi, let's wait for #4751 to be merged. Will ping #doc-sig to complete the doc review.

**Comment by jamiehannaford** [comment]
Now that #4751 has been merged, can we go ahead and close this?

**Comment by ahmetb** [comment]
thanks @jamiehannaford
