### ISSUE TITLE
I wish /docs/getting-started-guides/vagrant/ http://kubernetes.io/docs/getting-started-guides/vagrant/

### ISSUE THREAD

**Issue by gyula** [kubernetes/kubernetes.github.io#502]
I wish /docs/getting-started-guides/vagrant/ http://kubernetes.io/docs/getting-started-guides/vagrant/
(bad link from https://github.com/kubernetes/kubernetes/blob/release-1.2/docs/getting-started-guides/vagrant.md)

**Comment by runseb** [comment]
@johndmulhausen this seems fixed. You should close
