### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/ip-masq-agent/

### ISSUE THREAD

**Issue by wmuizelaar** [kubernetes/kubernetes.github.io#5064]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The documentation states that 'By default, in GCE/GKE starting with Kubernetes version 1.7.0, the ip-masq-agent will run in your cluster. If you are running in another environment, you can add the ip-masq-agent DaemonSet to your cluster:'

But the DaemonSet remains empty in the documentation. Also, ip-masq-agent will not always run in the GKE-cluster, as stated by the GKE documentation:
"IP masquerading in Container Engine is handled by ip-masq-agent, a tool which runs in clusters that run Kubernetes version 1.7.0 if network policy is enabled or you are using a cluster CIDR not in the 10.0.0.0/8 range ." (from https://cloud.google.com/container-engine/docs/ip-masquerade-agent)

**Proposed Solution:**
Update the documentation to reflect the text as it is stated by google

**Page to Update:**
http://kubernetes.io/...

**Comment by radhikapc** [comment]
@bowei Hi! Could you please take a look at this issue and provide necessary recommendation to take it to closure.
The documentation is at https://kubernetes.io/docs/tasks/administer-cluster/ip-masq-agent/

@wmuizelaar Would you please clarify what do you mean by `DaemonSet remains empty in the documentation` Thank you

**Comment by dnardo** [comment]
I've had pr/#4284 out for review.  It should clear up the wording.

**Comment by radhikapc** [comment]
Thanx @dnardo.
