### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by pueffl** [kubernetes/kubernetes.github.io#5119]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
kubectl proxy doesn't work (never finishes)

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/

**Comment by radhikapc** [comment]
@BenHall 👋

**Comment by BenHall** [comment]
Thank you for the feedback. This is by design on how kubectl proxy works. All the future commands launch in a separate terminal window while Kubectl Proxy is running.

We should make this clearer in the scenario text itself.

**Comment by BenHall** [comment]
Related to #5138

**Comment by heckj** [comment]
related (original) issue: #1561

**Comment by heckj** [comment]
Hi Wolfgang,

This bug matches closely other bugs reported against the use of `kubectl proxy` in the tutorial's hosted at Katacoda. I have a PR pending to resolve, and am closing this bug to focus conversation on the earliest report of this issue: https://github.com/kubernetes/kubernetes.github.io/issues/1561

Please comment at https://github.com/kubernetes/kubernetes.github.io/issues/1561, or subscribe to that bug, to get updates as we work on resolving this.
