### ISSUE TITLE
Many links that I run across show a big 404 but get redirected to the right location

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes.github.io#512]
e.g. http://kubernetes.io/v1.1/docs/getting-started-guides/docker.html 

If we can redirect, we should remove the 404

**Comment by jaredbhatti** [comment]
Yep, I totally hate this too.  Unfortunately, it's how the site is currently built.

Anything with a .html or .md extention 404s before redirecting.  I can't seem to fix it. @thockin
