### ISSUE TITLE
Document HPA custom metrics feature

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes.github.io#513]
Even though it's alpha, it would be good to document it, otherwise nobody will know about it. (Apologies if it already exists and I missed it.) I guess add it to
http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/
?

@fgrzadkowski @piosz @mwielgus

**Comment by piosz** [comment]
There is some documentation in flight #135

**Comment by jaredbhatti** [comment]
Duplication of https://github.com/kubernetes/kubernetes.github.io/issues/998
