### ISSUE TITLE
I wish /swagger-spec/ existed

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes.github.io#515]
I wish /swagger-spec/ existed

**Comment by nikhiljindal** [comment]
Example of external people referencing it: https://github.com/kubernetes/kubernetes/issues/15571

**Comment by nikhiljindal** [comment]
cc @kubernetes/docs

**Comment by nikhiljindal** [comment]
fwiw, it used to be served from https://github.com/kubernetes/kubernetes/tree/gh-pages/swagger-spec

**Comment by gnomeontherun** [comment]
You can find it at http://kubernetes.io/kubernetes/third_party/swagger-ui/

**Comment by gnomeontherun** [comment]
You could also grab them using the github cdn https://rawgit.com/kubernetes/kubernetes/tree/master/api/swagger-spec/apis.json
https://github.com/kubernetes/kubernetes/tree/master/api/swagger-spec

Need to clean it up

**Comment by nikhiljindal** [comment]
oh nice http://kubernetes.io/kubernetes/swagger-spec/ is good.

Yes the JSON headers need to be fixed: https://github.com/kubernetes/kubernetes/issues/15571

**Comment by mbohlool** [comment]
http://kubernetes.io/kubernetes/swagger-spec/ is a dead link now.

**Comment by nikhiljindal** [comment]
oh yes @thockin deleted the gh-pages branch on Friday I think so all http://kubernetes.io/kubernetes links are dead now.
We should add swagger spec to https://github.com/kubernetes/kubernetes.github.io. I did similar thing for swagger ui: https://github.com/kubernetes/kubernetes.github.io/pull/1921

**Comment by thockin** [comment]
Do we need to undelete it?

**Comment by nikhiljindal** [comment]
@thockin Yes I think it is reasonable to undelete it until we fix http://kubernetes.io/kubernetes/swagger-spec/. How easy is it to undelete? (Wondering if its easier to just fix http://kubernetes.io/kubernetes/swagger-spec/)

**Comment by thockin** [comment]
I have a relatively recent copy of that branch that I can re-push

**Comment by thockin** [comment]
OK, I pushed a copy of gh-pages back to the main repo

**Comment by jaredbhatti** [comment]
Thoughts on the new API docs: http://kubernetes.io/docs/api-reference/1_5/#replicaset-v1beta1

**Comment by thockin** [comment]
Looks nice, but there's a lot of linewrap in that middle column:

```
metadata
ObjectM
eta
```

**Comment by chenopis** [comment]
Ok, things should be cleaned up now. The Swagger UI is gone, but I left links to the spec and swagger.json in the ToC of the [Reference](https://kubernetes.io/docs/reference/) section.
