### ISSUE TITLE
I wish /docs/admin/resourcequota/walkthrough/ made it clear whether the hard cpu can be (eg) 1000m  rather than 1, or 500m

### ISSUE THREAD

**Issue by ianmiell** [kubernetes/kubernetes.github.io#522]
I wish /docs/admin/resourcequota/walkthrough/ made it clear whether the hard cpu can be (eg) 1000m  rather than 1, or 500m

**Comment by jaredbhatti** [comment]
I'm not sure what the document request is here.  I'm going to close this issue as part of our doc issue cleanup, but please feel free to reopen with more information if this issue is still relevant.
