### ISSUE TITLE
Documentation does not make clear which version of k8s is being documented

### ISSUE THREAD

**Issue by davidewatson** [kubernetes/kubernetes.github.io#5232]
**This is a request to include the relevant version of kubernetes at the top of the documentation page** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

When reading the documentation, sometimes it matters which version of kubernetes the documentation was written for. For example, the [class documentation for persistent volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class) reads

> In the past, the annotation volume.beta.kubernetes.io/storage-class was used instead of the storageClassName attribute. This annotation is still working, however it will become fully deprecated in a future Kubernetes release.

The meaning of past and future depend on the context. See #4374 for a related request.

**Proposed Solution:**

It would be helpful if the kubernetes version in question were included at the top, perhaps in a header, so that it is always clear which version of kubernetes is being documented.

**Page to Update:**

http://kubernetes.io/...

**Comment by zacharysarah** [comment]
@davidewatson :wave: There's a version selector in the top right corner. 👍
