### ISSUE TITLE
I wish /docs/hellonode/ Had videos and more example scenarios

### ISSUE THREAD

**Issue by brightbluejay** [kubernetes/kubernetes.github.io#524]
I wish /docs/hellonode/ Had videos and more example scenarios

**Comment by jaredbhatti** [comment]
We've had mixed reviews on videos, and we've generated a lot more tutorials and getting started information since this bug was filed. 

I'm going to close this issue as part of our doc issue cleanup, but please feel free to reopen with more information if this issue is still relevant.
