### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateless-application/hello-minikube/

### ISSUE THREAD

**Issue by jackymail** [kubernetes/kubernetes.github.io#5251]
can not launch "minikube dashboard"
the error message is : 
Could not find finalized endpoint being pointed to by kubernetes-dashboard: Error validating service: Error getting service kubernetes-dashboard: services "kubernetes-dashboard" not found

**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by kairen** [comment]
Just to make sure, I also tried to the last version for Minikube, but I can launch dashboard via `minikube dashboard` command.

**Comment by jackymail** [comment]
install the latest version of minikube  and kubctl, still can not get it work.

**Comment by heckj** [comment]
I removed the team/katacoda tag, since this isn't related to the browser-based tutorial sets.

@jackymail - could you verify what version of minikube you're running locally (using the command `minikube version`), the output of `minikube status`, and the output of `minikube addons list`?

I have a sneaking suspicion that the dashboard addon simply hasn't been added, but either way this will help us debug what's happening.

**Comment by jackymail** [comment]
Thanks Dude,following are the output of the commands you mentioned.
1: minikube version
minikube version: v0.22.1
2:minikube status
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.100
3:minikube addons list
- addon-manager: enabled
- registry: disabled
- registry-creds: disabled
- dashboard: enabled
- default-storageclass: enabled
- kube-dns: enabled
- heapster: disabled
- ingress: disabled
hope it helps.

**Comment by heckj** [comment]
thanks @jackymail  - so far, that's looking good. 

Can you go ahead and run a few command via `kubectl` as well please?

- `kubectl get services --namespace kube-system`
- `kubectl get pods --namespace kube-system`

This second should include the full name of the pod that's running the dashboard, once you have it:

`kubectl logs pod $(kubectl get pods --namespace kube-system | grep dashboard | cut -d' ' -f1)`

(sorry that last one is arcane - I'm sure there's a better way of doing this, but I wanted to get the log output from the pod that's running the dashboard)

**Comment by jackymail** [comment]
Thanks!!!,there is no running pod currently, following are the output:
1kubectl get services --namespace kube-system
NAME                   CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes-dashboard   10.0.0.5     <none>        80/TCP    7d
2:
kubectl get pods --namespace kube-system
NAME                                    READY     STATUS              RESTARTS   AGE
kube-addon-manager-minikube             0/1       ContainerCreating   0          7d
kubernetes-dashboard-3313488171-mtv6w   0/1       ContainerCreating   0          7d

**Comment by heckj** [comment]
The STATUS messages there lend a bit of a hint - unless you JUST started minikube in the past minute or something, they should both be well past ContainerCreating, so I'd guess Minikube is having some trouble getting those containers up and running. You can get some better details on what might be happening (or not happening) with the command:

`kubectl --namespace kube-system describe pod kubernetes-dashboard-3313488171-mtv6w`

Is you laptop running in a location where you may require a PROXY to get access to the internet to pull images? That might be one consideration here - either way, hopefully the command above will show more detail about why the dashboard container hasn't yet been fully created

**Comment by heckj** [comment]
@jackymail 👋 

Wanted to see if you were able to work through the issues with containers getting activated?

Since this isn't an issue about the documentation (or at least doesn't seem to be) I'm going to go ahead a close this issue for now, feel free to re-open if there is a specific documentation issue that we can resolve.

**Comment by jackymail** [comment]
sorry,still not working:
kubectl --namespace kube-system describe pod kubernetes-dashboard-3313488171-mtv6w
Name:		kubernetes-dashboard-3313488171-mtv6w
Namespace:	kube-system
Node:		minikube/192.168.99.101
Start Time:	Tue, 12 Sep 2017 23:16:23 +0800
Labels:		k8s-app=kubernetes-dashboard
		pod-template-hash=3313488171
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"kubernetes-dashboard-3313488171","uid":"567ae196-97cd-11e7-a...
Status:		Running
IP:		172.17.0.4
Created By:	ReplicaSet/kubernetes-dashboard-3313488171
Controlled By:	ReplicaSet/kubernetes-dashboard-3313488171
Containers:
  kubernetes-dashboard:
    Container ID:	docker://b022e1544a626458951137ea2326cb43f7e5b8c24a457541d8252b3dc4bc9950
    Image:		gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3
    Image ID:		docker://sha256:691a82db1ecd12bf573b1b9992108a48e0d1a8640564c96d4f07e18e69dd83e6
    Port:		9090/TCP
    State:		Running
      Started:		Wed, 11 Oct 2017 19:22:22 +0800
    Last State:		Terminated
      Reason:		Error
      Exit Code:	2
      Started:		Wed, 20 Sep 2017 12:55:05 +0800
      Finished:		Wed, 20 Sep 2017 14:08:37 +0800
    Ready:		True
    Restart Count:	1
    Liveness:		http-get http://:9090/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-l801k (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  kubernetes-dashboard-token-l801k:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	kubernetes-dashboard-token-l801k
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	node-role.kubernetes.io/master:NoSchedule
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  2m		2m		1	kubelet, minikube			Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "kubernetes-dashboard-token-l801k" 
  2m		2m		1	kubelet, minikube			Normal		SandboxChanged		Pod sandbox changed, it will be killed and re-created.
  2m		2m		1	kubelet, minikube	spec.containers{kubernetes-dashboard}	Normal		Pulled			Container image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3" already present on machine
  2m		2m		1	kubelet, minikube	spec.containers{kubernetes-dashboard}	Normal		Created			Created container
  2m		2m		1	kubelet, minikube	spec.containers{kubernetes-dashboard}	Normal		Started			Started container

**Comment by heckj** [comment]
hi @jackymail 
based on the extended output you just posted, it looks like the dashboard did eventually get created and appears to be running in the output above. If you invoke a `minikube dashboard` now, are you still unable to access it?

It could have taken quite a while to start up - when you start minikube, the instance of kubernetes within that VM download images from gcr.io (google's container registry), and if your bandwidth is constrained, or your machine is heavily taxed for other reasons, that can take quite a bit of time. Kubernetes will keep working until it gets where it wants it to be. 

In the output above, there's also references to multiple liveness probe failures, which hints that the dashboard wasn't available and ready for some time, but as of 11 OCT was up and running.
