### ISSUE TITLE
Please mention the file for bash autocompletion for kubectl

### ISSUE THREAD

**Issue by talon-vonneudeck** [kubernetes/kubernetes.github.io#533]
I wish the /docs/getting-started-guides would mention that there already is a file for kubectl autocompletion in bash available. If adding the kubectl-directory to PATH is explained, then the autocompletion should be mentioned as well. Maybe centralised in docs/user-guide/kubectl-overview/ ?

**Comment by arush-sal** [comment]
@talon-vonneudeck Well a little of google search landed me to `http://www.arulraj.net/2016/01/bash-completions-for-kubectl.html` and the link seems working for me(Ubuntu). Hope it was of any help.

**Comment by jingxu97** [comment]
There are some instructions on the page
[http://kubernetes.io/docs/getting-started-guides/gce/](http://kubernetes.io/docs/getting-started-guides/gce/)

$ source ./contrib/completions/bash/kubectl
$ cp ./contrib/completions/bash/kubectl /etc/bash_completion.d/

**Comment by MrHohn** [comment]
Above instructions are outdated. Updated instructions locate at https://github.com/kubernetes/kubernetes/blob/release-1.3/docs/user-guide/kubectl/kubectl_completion.md. Overview as below:

## kubectl completion

Output shell completion code for the given shell (bash or zsh)

### Synopsis


Output shell completion code for the given shell (bash or zsh).

This command prints shell code which must be evaluation to provide interactive
completion of kubectl commands.

`## kubectl completion

Output shell completion code for the given shell (bash or zsh)

### Synopsis


Output shell completion code for the given shell (bash or zsh).

This command prints shell code which must be evaluation to provide interactive
completion of kubectl commands.


```
kubectl completion SHELL
```

### Examples

```

$ source <(kubectl completion bash)

will load the kubectl completion code for bash. Note that this depends on the
bash-completion framework. It must be sourced before sourcing the kubectl
completion, e.g. on the Mac:

$ brew install bash-completion
$ source $(brew --prefix)/etc/bash_completion
$ source <(kubectl completion bash)

If you use zsh, the following will load kubectl zsh completion:

$ source <(kubectl completion zsh)`

**Comment by jaredbhatti** [comment]
http://kubernetes.io/docs/user-guide/kubectl/kubectl_completion/

**Comment by johnpetersjr** [comment]
http://kubernetes.io/docs/user-guide/kubectl/kubectl_completion/ 

Sorry, this page was not found. :(
