### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/update-intro/

### ISSUE THREAD

**Issue by KyleKR** [kubernetes/kubernetes.github.io#5375]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
when under rolling update, the new version pods changed from the old version have to take all the traffic which was separated when it was more than 2 pods. though it is short time before all the pods are changed to new version. A few pods have to endure all traffic, so I think there will should be a min number of pods that is switched to new version to ensure the application can support the load during transition.

**Proposed Solution:**
basic min num of pods before convert pods to new one for endure traffic with safe

**Page to Update:**
http://kubernetes.io/...

**Comment by chenopis** [comment]
I'm not sure I understand what this issue is asking for. Do you just want to know what the current minimum is needed for a smooth transition? Or are you saying we need to document this information  in the site, but maybe not in the tutorial itself?

**Comment by steveperry-53** [comment]
@chenopis, @heckj

**Comment by heckj** [comment]
@chenopis @steveperry-53 I think the core of this issue is a feature request for how Kubernetes works, rather than a request against the documentation directly. @KyleKR please correct me if I'm incorrect in this assessment. 

I don't know what the proper protocol is when an issue in the docs is a feature request for another component in Kubernetes. Please advise.

**Comment by KyleKR** [comment]
@chenopis Well, I didn't mean what minimum is needed for a smooth transition but I wonder there is a way to modify mininum number of pods when switching new version from old version.
as I mentioned above, I guess there might be an service failure if only a few pods have to take all traffic during update (this case might be not often situation). for example there are service running based on 6 pods and it have to urgent update for service. then with rolling update. pods are updated sequentially and when the pods numbered is 2 then new version will be shown to end-user at first before left 4 pods has changed to new version. thought it is short time but I think it occurs error because 2 pods(at first) take all the traffic. So I try to find a doc for setting min num of pods will be switched to new version.

I am not sure it is about feature req or not anyway.

**Comment by heckj** [comment]
@KyleKR Are you aware of the details in the documentation at https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-unavailable, which allows you to define the number of containers to keep available while doing a rolling update within a deployment. Does this solve what you're looking for? There's another "maxSurge" variable that can be set as well to help control how many containers are active while a rollout/update happens

**Comment by KyleKR** [comment]
@heckj I think it is right that I am looking for, Thanks. anyway it is quite hard to calculate it balancing maxunavailable and maxsurge. I understand maxunavilable = min number of pods (when pods are switched from old version to new version so when it is ready to service new version to client) am I right?

anyway Thanks for your time!!

**Comment by chenopis** [comment]
Ah, ok. So can we close this issue then?

**Comment by KyleKR** [comment]
oh sure thanks! :)
