### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/encrypt-data/

### ISSUE THREAD

**Issue by zioalex** [kubernetes/kubernetes.github.io#5388]
**This is a a Bug Report* 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Nowhere in the documentation page is stated that etcdv3 is needed to have data encryption, though it seems to be a requirement.

**Proposed Solution:**
Fix the documentation.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/

**Comment by php-coder** [comment]
> Nowhere in the documentation page is stated that etcdv3 is needed to have data encryption, though it seems to be a requirement.

Yes, it's a requirement.

@smarterclayton Let me know if you want me to update the docs.

**Comment by smarterclayton** [comment]
Please
