### ISSUE TITLE
I wish /docs/getting-started-guides/README/ I wish this page existed.

### ISSUE THREAD

**Issue by levmichael3** [kubernetes/kubernetes.github.io#54]
I wish /docs/getting-started-guides/README/ I wish this page existed.

**Comment by johndmulhausen** [comment]
I appreciate that but now that we've separated the code from the docs into separate repos, we're not going to continue to have README files in every folder. Historically that has created a situation where things are documented twice (in index.md and README.md) in each directory. The new repo is quite lightweight if you want to clone it and peruse the docs in "file mode"

**Comment by levmichael3** [comment]
sure thanks!
