### ISSUE TITLE
The new floating header shouldn't cover content for section deeplinks

### ISSUE THREAD

**Issue by ryanschwartz** [kubernetes/kubernetes.github.io#543]
For any section deeplink, the linked section title and some content is now obscured in the viewport by the floating header menu.

Example: http://kubernetes.io/docs/hellonode/#allow-external-traffic
![wide view](http://ryanschwartz.net/images/kube_doc_wide.png)

This occurs regardless of browser window width:
![narrow-ish view](http://ryanschwartz.net/images/kube_doc_narrow-ish.png)

Yay responsive design, but :cry: being able to actually read the content w/o scrolling.

**Comment by johndmulhausen** [comment]
Thanks to @atbaker for the fix!
