### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/

### ISSUE THREAD

**Issue by ericson-cepeda** [kubernetes/kubernetes.github.io#5442]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
hostAliases property is not being written to the pod description when using "kubectl apply -f hostaliases.yml".

**Proposed Solution:**
Edit resource description directly from Kubernetes dashboard.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/

Kubernetes Version:
1.7.x
Additional Information:
Tried 1.7.0 and 1.7.5

**Comment by zacharysarah** [comment]
@mengqiy :wave:

**Comment by mengqiy** [comment]
@ericson-cepeda I guess you have tried this after #5443 merged.
If you think it still doesn't work, please paste the output of the following 2 commands
```
kubectl version
kubectl apply -f hostaliases.yml -v8
```

**Comment by ericson-cepeda** [comment]
@mengqiy, right. Working as expected. Thank you very much for your promptness.
