### ISSUE TITLE
kubectl, kubelet v1.6.9 doesn't exist on kubernetes repository 

### ISSUE THREAD

**Issue by pekfi** [kubernetes/kubernetes.github.io#5456]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
doesn't find kubectl, kubelet binaries Version 1.6.9 in kubernetes repository only the folloing:

yum search kubectl
======================================================= N/S matched: kubectl =======================================================
kubectl-1.5.4-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
kubectl-1.6.0-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
kubectl-1.6.1-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
kubectl-1.6.2-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
kubectl-1.6.3-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
kubectl-1.6.4-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
kubectl-1.6.5-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
kubectl-1.6.6-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
kubectl-1.6.7-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
kubectl-1.6.7-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
kubectl-1.7.0-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
kubectl-1.7.1-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
kubectl-1.7.2-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
kubectl-1.7.3-1.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
kubectl-1.7.4-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
kubectl-1.7.5-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.

/etc/yum.repos.d/kubernetes.repo
 [kubernetes]
name=Kubernetes
baseurl=http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
This is not a documentation issue. Can you please open this at https://github.com/kubernetes/release/ ?

**Comment by pekfi** [comment]
OK, open on release
