### ISSUE TITLE
I wish the logging docs sucked less

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes.github.io#548]
http://kubernetes.io/docs/user-guide/logging/ is incredibly brief and could benefit from a little more detail, but isn't bad.
http://kubernetes.io/docs/getting-started-guides/logging/ has fallen out of date (particularly the screenshots), doesn't explain how to use cloud logging's better query functionality, and doesn't explain important features like how to use structured logs. It's also titled as just "Logging" in the table of contents despite primarily being about Stackdriver logging.
https://github.com/kubernetes/contrib/tree/master/logging/fluentd-sidecar-gcp is just terribly out of date, although the image being so old is more of an issue than the documentation.

I'll clean this stuff up for the 1.3 release after code freeze if no one else jumps in before then.

**Comment by a-robinson** [comment]
We could also really use a doc explaining how to set up your own daemonset with a custom logging agent image.

**Comment by bgrant0607** [comment]
I'd also like to organize docs around other logging-related topics, such as Elasticsearch/Kibana and vendor solutions.

See also:
https://github.com/kubernetes/kubernetes/issues/24677
https://github.com/kubernetes/kubernetes/issues/17183

**Comment by therc** [comment]
Troubleshooting the logging pipeline is really painful, too. See my latest adventures at

https://github.com/kubernetes/kubernetes/issues/22537#issuecomment-221021856

**Comment by bgrant0607** [comment]
See also https://github.com/kubernetes/kubernetes/issues/16326

**Comment by edevil** [comment]
These documentation improvements would be very welcome. At this moment I'm trying to configure the logging of an existing Kubernetes cluster to be sent to a remote ELK cluster, but all I can find in the Kube documentation about this is a flag that has to be specified at cluster initialization time.

**Comment by a-robinson** [comment]
I'm not going to be able to finish off the planned improvements before I leave Google. Sorry for not getting them all in with 1.3.

@piosz, updating and improving the documentation might be a good place to get started with logging?

**Comment by piosz** [comment]
cc @Crassirostris @aleksandra-malinowska

**Comment by Crassirostris** [comment]
Addressed by https://github.com/kubernetes/kubernetes.github.io/pull/1837

Further addressed by https://github.com/kubernetes/kubernetes.github.io/pull/2096 and https://github.com/kubernetes/kubernetes.github.io/pull/2114

After the latter two are merged, can be closed

**Comment by janetkuo** [comment]
#1837 and all other PRs should target `master` branch instead of `release-1.5`

**Comment by Crassirostris** [comment]
@janetkuo OK, thanks!

**Comment by Crassirostris** [comment]
@janetkuo Is it possible to deploy https://github.com/kubernetes/kubernetes.github.io/pull/1837 to the k8s.io before 1.6?

**Comment by janetkuo** [comment]
> Is it possible to deploy #1837 to the k8s.io before 1.6?

@Crassirostris yes. Would you open another PR which merges changes in #1837 to `master` branch (you may need to rebase)?

**Comment by Crassirostris** [comment]
@janetkuo It's merged already actually: https://github.com/kubernetes/kubernetes.github.io/pull/2128

I didn't see that it's uploaded to the k8s.io already, sorry. Thanks!

**Comment by jaredbhatti** [comment]
What additional docs are needed to help out here?

**Comment by Crassirostris** [comment]
@jaredbhatti https://github.com/kubernetes/kubernetes.github.io/pull/2141 and https://github.com/kubernetes/kubernetes.github.io/pull/2142 address the problems mentioned in this ticket

We have some plans for the additional docs, but to extend the topic and cover new functionality. As for the refactoring I think that's it.

**Comment by piosz** [comment]
All changes to logging documentation are merged now
