### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/ingress/

### ISSUE THREAD

**Issue by sahilsk** [kubernetes/kubernetes.github.io#5561]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
LInks are broken:  https://git.k8s.io/ingress/controllers/nginx#running-multiple-ingress-controllers

all `git.k8s.io` links on this page is broken.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/ingress/

**Comment by nikhita** [comment]
@sahilsk Can you check again? All the `git.k8s.io` links are working fine, including https://git.k8s.io/ingress/controllers/nginx#running-multiple-ingress-controllers.

**Comment by heckj** [comment]
Good morning @sahilsk - I double checked the links and per @nikhita they all appear to be working correctly. Since they are functional, I'm going to close this PR for now, please re-open it if there is a specific documentation issue we can help resolve
