### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by sungwookgit** [kubernetes/kubernetes.github.io#5562]
**This is a...** 

- [ ] Feature Request
- [ X] Bug Report

**Problem:**
Tutorial hangs at "we are preparing the environment for you..."

**Proposed Solution:**
Make the tutorial work.

**Page to Update:**
http://kubernetes.io/...

**Comment by heckj** [comment]
Thank you for the report @sungwookgit 

Could you verify that you can generally get access to the website `https://katacoda.com` from your local browser? I just accessed the page you indicated, and the tutorial iframe came up and was active without issue, but it is hosted separately from the documention itself. If you're unable to access content from a 3rd party website, the interactive tutorial component may not work correctly for you.

**Comment by BenHall** [comment]
Thanks @sungwookgit, as @heckj mentioned could you please try directly on the site at https://katacoda.com/kubernetes-bootcamp/scenarios/1

**Comment by sungwookgit** [comment]
Thanks for the quick responses. The linked site shows the same thing. I guess it is either my company network or some missing plugins then. I will try this at my home. FYI, I was using Chrome browser running on Windows 7 :)

**Comment by heckj** [comment]
@sungwookgit thanks for the feedback and the issue. I'm going to close this issue for now, but feel free to re-open if there's a specific documentation issue. You can also reach us on the sig-docs channel of the [Kubernetes slack](http://slack.k8s.io)
