### ISSUE TITLE
Consider automate check for the broken links

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes.github.io#5575]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

**Problem:**
Time to time, our docs have links that are broken.

**Proposed Solution:**
In order to noticed them quickly, I suggest to add automated check. There are some useful tools for that, for example: https://github.com/dkhamsing/awesome_bot and https://www.npmjs.com/package/markdown-link-check

We can run such check on each pull request or daily (see https://docs.travis-ci.com/user/cron-jobs/).

**Comment by zacharysarah** [comment]
@php-coder 👋 Thanks for the suggestion. We're in the early stages of implementing automated link checking. Unfortunately I can't give an ETA, but we're working on it!.
