### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by goldengit** [kubernetes/kubernetes.github.io#5585]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel-rbac.yml

This url is not resolving - it gives a 404 error

**Proposed Solution:**
repair link

**Page to Update:**
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

**Comment by zhangxiaoyu-zidif** [comment]
@zacharysarah 
https://github.com/kubernetes/kubernetes.github.io/pull/5584 fixed it.
So it can be closed =)
