### ISSUE TITLE
404: k8s.io/docs/concepts/workloads/controllers/deployment/

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/kubernetes.github.io#5595]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The following pages (that I tested) currently return a `404`:

* https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
* https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/

It seems like they both redirect to:

https://kubernetes.io/docs/concepts/workloads/pods/poddocs/concepts/workloads/pods/pod/

And then show a `404` warning.

Furthermore, the version drop-down menu does not work on Safari:

<img width="548" alt="screen shot 2017-09-23 at 23 17 36" src="https://user-images.githubusercontent.com/383250/30777179-683cfd1e-a0b5-11e7-8797-95034342978c.png">

**Comment by nikhita** [comment]
@JeanMertz Can you check again? They seem to be working fine now.

**Comment by zacharysarah** [comment]
@JeanMertz 👋 I validated that the links appear to be working correctly now. Please feel free to reopen this issue if you continue to see 404s for these links.
