### ISSUE TITLE
The left-nav zippies shouldn't indent title text

### ISSUE THREAD

**Issue by johndmulhausen** [kubernetes/kubernetes.github.io#56]
It's a bit difficult to scan the left nav and determine the hierarchy of topics right now because the title text does not align vertically. This is happening because topics that have sub-topics are indented inwards visually by the zippy graphics. Ideally the first letter of each title of the same hierarchy level would be on the same vertical line. 

cc @CreaturesInUnitards

**Comment by CreaturesInUnitards** [comment]
Yup fixed.

**Comment by johndmulhausen** [comment]
Thank you!
