### ISSUE TITLE
[1.7] kube-proxy flags needs to be updated

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes.github.io#5618]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Reported by https://github.com/kubernetes/kubernetes/pull/48625#issuecomment-331868843, the kube-proxy reference configuration is missing the `--metrics-bind-address` option.

See https://kubernetes.io/docs/admin/kube-proxy/.

**Proposed Solution:**
Regenerate kube-proxy flags on that page. 

**Page to Update:**
https://kubernetes.io/docs/admin/kube-proxy/

cc @alexbrand

**Comment by heckj** [comment]
@zacharysarah 👋  - This is one of the autogenerated pages with reference documentation. I'm not entirely sure how to resolve this directly. I went ahead and tagged up the bug as Actionable, but don't quite know how to resolve it...

**Comment by alexbrand** [comment]
@heckj I just verified that the `--metrics-bind-address` flag is documented in the 1.8 documentation. It is still missing from the 1.7 docs though.

**Comment by zacharysarah** [comment]
@heckj I'm not sure that any of us do--sounds like a great issue to raise in [K8s slack](https://kubernetes.slack.com/messages/C1J0BPD2M/details/).

**Comment by heckj** [comment]
PR to kubernetes source (where this generated documentation comes from) applied to resolve going-forward edits requested from editorial team in the review: https://github.com/kubernetes/kubernetes/pull/53671
