### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by gotteric** [kubernetes/kubernetes.github.io#5621]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
File used for command below seems to have been moved

`kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel-rbac.yml`

**Proposed Solution:**
Modify path

`kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml`

**Page to Update:**
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

**Comment by nikhita** [comment]
This issue has been fixed in https://github.com/kubernetes/kubernetes.github.io/pull/5588. The flannel yaml is now pinned to a specific version.
