### ISSUE TITLE
I would like documentation about how to update a daemonset

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes.github.io#563]
We need documentation on updating a daemonset, as it doesn't support normal rolling upgrade semantics (yet):

---

To update a daemonset, you have to:
1. Apply the new config
2. Delete the pods one by one
3. Let the system recreate them for you

Alternatives (if you don't care about documentation)
'kubectl delete pods -l daemonset_label=value; kubectl create -f new_daemonset_spec.yml'
'kubectl replace --force newds.yaml'

**Comment by kelseyhightower** [comment]
@aronchick Are you looking for a tutorial here?

**Comment by aronchick** [comment]
Not a tutorial - just a doc page.

**Comment by bprashanth** [comment]
Actually what you suggested isn't guaranteed to work, the daemonset controller might not have seen the updated daemonset when it sees the deleted pods, and so might end up creating the new pods with the old pod template. We should just implement a flavor of --rolling-update on daemon set that understands generationNumber. Or better yet, do it server side like deployments.

**Comment by bprashanth** [comment]
aha https://github.com/kubernetes/kubernetes/issues/22543

**Comment by jaredbhatti** [comment]
I'm not sure if there's any further action to take here from a docs standpoint.  I'm going to close this issue since it hasn't been updated in 6+ months.  Please reopen if there's still issues to work on here.
