### ISSUE TITLE
Issue with k8s.io/docs/setup/pick-right-solution/

### ISSUE THREAD

**Issue by adriancislo** [kubernetes/kubernetes.github.io#5638]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Link to kubeadm (like: _If you already have a way to configure hosting resources, use **kubeadm** to easily bring up a cluster with a single command per machine._) forwards to page https://kubernetes.io/docs/setup/ instead of https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/. Now we cannot navigate to page with kubeadm instructions.

**Proposed Solution:**
Link to proper page.

**Page to Update:**
https://kubernetes.io/docs/setup/pick-right-solution/

**Comment by nikhita** [comment]
This has been fixed in https://github.com/kubernetes/kubernetes.github.io/pull/5648 and can be closed now.
