### ISSUE TITLE
Container port limitation for Kubernetes cluster

### ISSUE THREAD

**Issue by dpatelapx** [kubernetes/kubernetes.github.io#5640]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

Bug Report

**Problem:**
Kubernetes cluster crashes when assigning certain container port numbers

**Proposed Solution:**
Find a workaround for this issue

**Page to Update:**
http://kubernetes.io/...

**Comment by heckj** [comment]
thanks for the report @dpatelapx - is this an issue that you're seeing with your cluster, or a problem in the documentation? It reads like it's a bug report for kubernetes, but filed as a documentation issue.

**Comment by dpatelapx** [comment]
This turned out to be an issue with limitation of resources on the Kubernetes cluster. We recently provisioned additional containers and that was maxing out our CPU/Memory. I upsized the VMs running the container instance and it seems be to be fine now.

[Description: Logo 1v]
Darshan Patel
Manager of QA and DevOps, APX Inc.
Application Development
2001 Gateway Place Suite 315W, San Jose, CA 95110
(408) 517-2155
dpatel@apx.com<mailto:dpatel@apx.com>

**Comment by heckj** [comment]
Thanks @dpatelapx - I went ahead and modified your reply so that your phone number and email address weren't included in the github bug report, hopefully that's acceptable to you. 

Since this isn't a documentation flaw, I'm going to go ahead and close this issue for now. Please re-open if there's a documentation issue we can help resolve.

**Comment by dpatelapx** [comment]
Thanks you!

[Description: Logo 1v]
Darshan Patel
Manager of QA and DevOps, APX Inc.
Application Development
2001 Gateway Place Suite 315W, San Jose, CA 95110
(408) 517-2155
dpatel@apx.com<mailto:dpatel@apx.com>
