### ISSUE TITLE
"UI access" doc should be removed 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes.github.io#565]
Ref. [user complaint](https://twitter.com/sjin2008/status/734974172397375488) about [UI access doc](http://kubernetes.io/docs/user-guide/ui-access/)

Problems: 
- It has no menu
- It should be deleted (and redirected to main UI docs) and parts of it should be incorporated into main UI docs
- It talks about installation and `kube-addons.sh`. This is not relevant for users and only causes confusion. Perhaps this may be useful for admins, but do we have dos for installing, e.g., heapster? 

@kubernetes/docs @bryk

**Comment by bryk** [comment]
We can work on this but with ETA 2-3 weeks from now. Is this OK?

cc @kubernetes/dashboard-maintainers

**Comment by gertipoppel** [comment]
I will continue with updating the ui.md (dashboard user guide) with regard to new/changed features.

**Comment by jaredbhatti** [comment]
Fixed.
