### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/explore-interactive/

### ISSUE THREAD

**Issue by jekstrom** [kubernetes/kubernetes.github.io#5679]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Missing an 'R' on Step 2 of Module 3 first paragraph.

**Proposed Solution:**
Add an 'R' to "ecall that Pods are running in an isolated, ... "

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/explore-interactive/

**Comment by heckj** [comment]
@nikhita thanks - content is hosted with Katacoda, including the content here - so it's not obvious to find. For the record, the content for those tutorials is hosted at https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios

**Comment by heckj** [comment]
@jekstrom thanks for the report! I'll get a fix up immediately and provide a PR link here

**Comment by heckj** [comment]
@BenHall I think we need you to look at the underlying content - the content in question is at https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/blob/master/4/step2.md - and appears to have the `R` that's missing in this report... I did verify that the `R` is missing in the deployed content.

**Comment by BenHall** [comment]
@heckj Sorry, that looks like a bad merge/update on my side. Let me double check how that happened.

It's fixed now. Thanks for the report and looking into it.

**Comment by heckj** [comment]
@BenHall awesome, thank you!
