### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/network-policies/

### ISSUE THREAD

**Issue by nferro** [kubernetes/kubernetes.github.io#5685]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The link in `See the NetworkPolicy getting started guide for further examples.` is broken

**Proposed Solution:**
Fix the link

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/network-policies/

**Comment by tengqm** [comment]
/assign @kairen 

That patch is a more complete one.
