### ISSUE TITLE
404 link on 1.8 release blog post

### ISSUE THREAD

**Issue by abitrolly** [kubernetes/kubernetes.github.io#5686]
**This is a...** 
- [x] Bug Report

**Problem:**
http://blog.kubernetes.io/2017/09/kubernetes-18-security-workloads-and.html link to architecture is 404.

**Comment by nikhita** [comment]
It should point to https://github.com/kubernetes/community/tree/master/sig-architecture (instead of https://github.com/kubernetes/community/sig-architecture)

**Comment by divyam3897** [comment]
Hi, I would like to fix this one but I was not able to find the blog post, is it being written somewhere else where it is to be fixed? As I couldn't find any .md related to the same.

**Comment by nikhita** [comment]
@divyam3897 I think SIG-PM owns the blog and has access to it.

@idvoretskyi Can PRs be sent to fix the blogpost?

**Comment by idvoretskyi** [comment]
cc @zacharysarah

**Comment by idvoretskyi** [comment]
> Can PRs be sent to fix the blogpost?

Not sure, but @zacharysarah may help us.

**Comment by zacharysarah** [comment]
@idvoretskyi 👋 Blog content is hosted and maintained elsewhere--outside of any repo, if I recall correctly. @kbarnard10 may be able to help.

**Comment by kbarnard10** [comment]
Thanks for the heads up. I've fixed the link. The blog is maintained through blogger.com. Feel free to assign any future blog issues to me, or let me know if you need access.

**Comment by abitrolly** [comment]
@kbarnard10 would be awesome to host blog contents on GitHub and publish it from here. This way more #hacktoberfest people will be motivated to help with spell and link checking.

**Comment by kbarnard10** [comment]
@arbeit +1. We have an issue open for it here: #5823
