### ISSUE TITLE
Whitespace issues

### ISSUE THREAD

**Issue by johndmulhausen** [kubernetes/kubernetes.github.io#57]
* There's quite a gap between the grey nav bar and the content
* FIXED The margin above tables is too small and the tops of tables are thus bumping up against their preceding paragraphs
* Open nodes in the left nav create large, yawning whitespaces above and below themselves (this collapses when the node is closed)

cc @CreaturesInUnitards

**Comment by johndmulhausen** [comment]
Fixed the tables issue.

**Comment by CreaturesInUnitards** [comment]
yup done
