### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by gajenderpathak** [kubernetes/kubernetes.github.io#5700]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
I tried to use the interactive tutorial of Kubernetes. But I am not able to do so. Only black screen is coming. I am using Chrome browser over Windows 7 m/c. 

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by heckj** [comment]
Thanks for your report @gajenderpathak  - are you by chance able to see the tutorial screens directly from www.katacoda.com? The content for those interactive tutorials is hosted from a site external to https://kubernetes.io.

**Comment by gajenderpathak** [comment]
Thanks it's working at katacoda.com.
