### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/centos/centos_manual_config/

### ISSUE THREAD

**Issue by davalente** [kubernetes/kubernetes.github.io#5712]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
"This version is deprecated", link shows an empty page.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by heckj** [comment]
Working on this right now with a pull request (https://github.com/kubernetes/kubernetes.github.io/pull/5594) resolving some broken links

**Comment by heckj** [comment]
PR merged, so going ahead and closing this issue.
