### ISSUE TITLE
I wish /docs/getting-started-guides/ listed both Ubuntu guides in the Bare Metal section, noting the networking for each

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes.github.io#572]
I wish /docs/getting-started-guides/ listed both Ubuntu guides in the Bare Metal section, noting the networking for each (the listed one uses Flannel, the omitted one (but it is in the navigation panel on the left) uses Calico).

**Comment by jaredbhatti** [comment]
http://kubernetes.io/docs/getting-started-guides/ubuntu/

Ubuntu is getting a big rewrite as well.  https://github.com/kubernetes/kubernetes.github.io/pull/1932
