### ISSUE TITLE
I wish /docs would allow me to download the entire guide as a PDF or MOBI, or even just show it on a single HTML page so I could read it  all in one go.

### ISSUE THREAD

**Issue by quavmo** [kubernetes/kubernetes.github.io#574]
I wish /docs would allow me to download the entire guide as a PDF or MOBI, or even just show it on a single HTML page so I could read it  all in one go.

**Comment by gtirloni** [comment]
Going on a long trip and I wish the same. I will probably download the whole repo and generate it with Jekkyl locally.

**Comment by jaredbhatti** [comment]
Yep. Sorry, we don't plan on supporting PDF or Mobi.
