### ISSUE TITLE
I wish /docs/samples/ didn't have a broken Petstore link

### ISSUE THREAD

**Issue by brandon-atkinson** [kubernetes/kubernetes.github.io#575]
I wish /docs/samples/ didn't have a broken Petstore link

**Comment by nVitius** [comment]
For the record, the broken link in question is located here:  https://github.com/kubernetes/kubernetes.github.io/blob/master/_data/samples.yml#L79  

The actual link should be to `examples/k8petstore`. At least, that's what it is in the [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/tree/release-1.2/examples/k8petstore/) project. Not sure which one we should change (`k8spetstore` makes more sense to me).
