### ISSUE TITLE
I wish /docs/search/ ingress

### ISSUE THREAD

**Issue by zfonly** [kubernetes/kubernetes.github.io#576]
I wish /docs/search/ ingress

**Comment by nVitius** [comment]
Not sure what you mean by `/docs/search`, but if you're looking for the Ingress docs, they are here: http://kubernetes.io/docs/user-guide/ingress/

**Comment by runseb** [comment]
I verified that search worked:

http://kubernetes.io/docs/search/?q=ingress

returns all relevant results.

@johndmulhausen we should close.
