### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/scratch/

### ISSUE THREAD

**Issue by atoato88** [kubernetes/kubernetes.github.io#5779]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
At "Cloud Providers" paragraph, There is a sentence following.
```
Used by aws, gce, mesos, openshift, ovirt and rackspace.
```
In this sentence,  is "openshift" correct?
It should be "openstack", I think. Because following sentence is described at same paragraph.
```
options for --cloud-provider flag are aws, azure, cloudstack, fake, gce, mesos, openstack, ovirt, photon, rackspace, vsphere, or unset.
```

Here, "openshift" isn't present, but "openstack" is present.

**Proposed Solution:**

Replace "openshift" with "openstack" in sentence at "Cloud Providers" paragraph following.
```
Used by aws, gce, mesos, openshift, ovirt and rackspace.
```

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/scratch/

**Comment by heckj** [comment]
thanks @atoato88 - I suspect you're correct and made a quick patch (https://github.com/kubernetes/kubernetes.github.io/pull/5783) to resolve. When I looked in the cloud-provider releases for 1.8, there was one for openstack, but not openshift - so I think this was just a missed typo/reference mistake
