### ISSUE TITLE
I wish /docs/getting-started-guides/binary_release/ where to start? how about some docs on the default cluster? How about not a  500 meg autorunning shell script with inadequate docs on dependencies. Terrible. Seriously. Terrible.

### ISSUE THREAD

**Issue by aaadschutz** [kubernetes/kubernetes.github.io#582]
I wish /docs/getting-started-guides/binary_release/ where to start? No docs on the default cluster. 500 meg autorunning shell script with inadequate docs on dependencies, which removes the 500 meg file at the end regardless of errors. Okay, downloaded and modified the shell script, fixed the unlisted dependencies (e.g. libvirt for vagrant. qemu support). Okay, it starts e.g. grafana. Which requires a password. Which is listed where? Oh, no docs at all. No pointers to docs on this specific build.

Really suprised there are more thumbs up than down on this page.

**Comment by jaredbhatti** [comment]
This page has been rewritten a while ago: http://kubernetes.io/docs/getting-started-guides/binary_release/

I'm going to close this bug for issue hygiene.  If there's still more work to do here, please reopen.
