### ISSUE TITLE
404 on RBAC page

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes.github.io#5868]
https://kubernetes.io/docs/admin/authorization/rbac/ returns a 404

the page is still present and linked in `_data/reference.yml`, the same as ABAC, which works correctly:
https://kubernetes.io/docs/admin/authorization/abac/

any ideas about how to correct this?

**Comment by liggitt** [comment]
Looks like a publish failed to roll out to all CDNs. Republishing fixed the issue.

**Comment by abiogenesis-now** [comment]
For future reference---kicking off a redeploy at https://app.netlify.com/sites/kubernetes-io-master-staging/deploys fixes things.
