### ISSUE TITLE
I wish /docs/getting-started-guides/docker/ What year is it? These instructions are from a snapshot months ago, missing critical refactorings

### ISSUE THREAD

**Issue by borg286** [kubernetes/kubernetes.github.io#59]
Please merge from release 1.2
https://github.com/kubernetes/kubernetes/blob/release-1.2/docs/getting-started-guides/docker.md
It includes setting a default DNS server (which I struggle to get to work), and simplifies the instructions into a single docker command.
Unless you find that these instructions get more reliably up than in version 1.2 please roll forward to 1.2

**Comment by johndmulhausen** [comment]
Done.

**Comment by johndmulhausen** [comment]
Note: Please don't file any more issues regarding the 1.2 import. See this message for details on how the 1.2 import is aligning with the repo switchover. Thanks!
https://groups.google.com/forum/#!topic/kubernetes-dev/UedwIYb-fHg
