### ISSUE TITLE
Invalid URL on k8s.io/docs/setup/independent/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by dkirrane** [kubernetes/kubernetes.github.io#5908]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The above wiki and `kubeadm init` mentions an invalid URL
Browsing to http://kubernetes.io/docs/admin/addons/ results in URL 404 Error

**Proposed Solution:**
Update url on the wiki and in `kubeadm init` output

**Page to Update:**
k8s.io/docs/setup/independent/create-cluster-kubeadm/

```
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by heckj** [comment]
thanks @dkirrane 

Looks like we need a redirect for `http://kubernetes.io/docs/admin/addons/` that gets to the right end destintation (which I think is has moved to https://kubernetes.io/docs/concepts/cluster-administration/addons/)
