### ISSUE TITLE
I wish /docs/admin/multiple-schedulers/ to mention that the example doesn't work on a local cluster

### ISSUE THREAD

**Issue by borismattijssen** [kubernetes/kubernetes.github.io#596]
I wish /docs/admin/multiple-schedulers/ to mention that the example doesn't work on a local cluster.

Please specify that this example doesn't work on a local cluster (using hack/local-cluster-up.sh). It probably works on a local cluster using [docker](http://kubernetes.io/docs/getting-started-guides/docker/), but I haven't tested this yet.

**Comment by jaredbhatti** [comment]
Not sure if this is still true.
