### ISSUE TITLE
doc bug in http://kubernetes.io/docs/user-guide/compute-resources/

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes.github.io#597]
From @krmayankk, originally in https://github.com/kubernetes/kubernetes/issues/26340

"""
At http://kubernetes.io/docs/user-guide/compute-resources/

The following line
`The following pod has two containers. Each has a request of 0.25 core of cpu and 64MiB (2^20 bytes) of memory and a limit of 0.5 core of cpu and 128MiB of memory. The pod can be said to have a request of 0.5 core and 128 MiB of memory and a limit of 1 core and 256MiB of memory.`
incorrectly mentions 64Mib as 2^20bytes.
MiB is 2^20 so 64MiB is 64*2^20 which would be 2^26
"""

**Comment by krmayankk** [comment]
Thanks i already have a PR https://github.com/kubernetes/kubernetes.github.io/pull/580

Waiting for my organization to approve the CLA before i can contribute.

**Comment by jaredbhatti** [comment]
Fixed.
