### ISSUE TITLE
Token File "Groups" Docs

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes.github.io#598]
From @nVitius, originally filed as https://github.com/kubernetes/kubernetes/issues/26659

"""
The documentation for [Authentication](http://kubernetes.io/docs/admin/authentication/) talks about "groups" when it mentions the token file. However, it doesn't talk about what they are used for nor how they are created.
"""

**Comment by jaredbhatti** [comment]
Groups: a set of strings which associate users with as set of commonly grouped users.
