### ISSUE TITLE
broken sample links on kubernetes.io

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes.github.io#599]
From @joshuacox, originally filed as https://github.com/kubernetes/kubernetes/issues/26672

"""
Lot's of the sample links are broken at the moment on kubernetes.io, perhaps there is quite a bit missing from release-1.2?

e.g.:

https://github.com/kubernetes/kubernetes/tree/release-1.2/examples/logging-demo/

https://github.com/kubernetes/kubernetes/tree/release-1.2/examples/k8spetstore/
looks like it should be:
https://github.com/kubernetes/kubernetes/tree/release-1.2/examples/k8petstore

all from this page:
http://kubernetes.io/docs/samples/
"""

**Comment by nVitius** [comment]
The Petstore issue was also recorded in #575
