### ISSUE TITLE
Search bar taking up most of page

### ISSUE THREAD

**Issue by borg286** [kubernetes/kubernetes.github.io#60]
![screenshot_20160306-103317](https://cloud.githubusercontent.com/assets/8532481/13556144/44be7d96-e387-11e5-97a9-d97e185e98d9.png)
Please fix the search bar so that it doesn't make white space below it.

**Comment by johndmulhausen** [comment]
cc @CreaturesInUnitards

**Comment by CreaturesInUnitards** [comment]
yup done.
