### ISSUE TITLE
I wish /docs/reference/ indicated what version of kubernetes the page described, and allowed me to choose a particular version (e.g. if my cluster is running an older version of k8)

### ISSUE THREAD

**Issue by ghost** [kubernetes/kubernetes.github.io#605]
I wish /docs/reference/ indicated what version of kubernetes the page described, and allowed me to choose a particular version (e.g. if my cluster is running an older version of k8 and I need to know how to format a command for that specific version)

**Comment by steveperry-53** [comment]
We have versioned docs now. Start [here](https://kubernetes.io/docs/home/). In the upper right, there is a drop-down menu where you can choose v1.8, v1.7, v1.6 etc.
