### ISSUE TITLE
header element covers scroll bar

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes.github.io#607]
On /docs/user-guide/kubectl/kubectl_run/ (and maybe other pages) the header element covers the horizontal scrollbar, preventing the user from clicking it. See screenshot below.

OS: Ubuntu 14.04.4 LTS
Browser: Chrome 51.0.2704.79 (64-bit)

Screenshot:
![2016-06-03-112417_3120x1920_scrot](https://cloud.githubusercontent.com/assets/3272040/15788920/975180f2-297e-11e6-91f9-00a3ab475635.png)

**Comment by jaredbhatti** [comment]
Fixed.
