### ISSUE TITLE
Split "community" support level for getting started guides into two categories

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes.github.io#612]
I think we should distinguish community contributions by the project responsible for the underlying platform. This is a different axis than whether there is a commercial support arrangement. For example, we are going to have three Azure getting started's, and it would be useful to distinguish the one a Microsoft employee did vs. the others. Whether any of them are commercially supported is an orthogonal dimension.

**Comment by davidopp** [comment]
An alternative would be to add a column indicating the affiliation of the creator. Then it would be easy to see whether they are affiliated with the platform in question or not.

**Comment by jaredbhatti** [comment]
Interesting suggestion, although we should take more about how to implement this (or even if it's a good idea to implement).  Want to set up a meeting with Devin Donnelly and I?

**Comment by davidopp** [comment]
I don't feel strongly enough about it to pursue discussing it right now (vs. all the other stuff on my plate). If someone else wants to run with it that's certainly fine.
