### ISSUE TITLE
Document required Docker Version in getting started guides

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes.github.io#613]
`/docs/getting-started-guides/docker/` does not mention the docker version anywhere on the page. Users running the latest docker (v1.11) will run into problems trying to run Kubernetes v1.2 (e.g. [this SO question](http://stackoverflow.com/questions/37644097/running-kubernetes-locally-via-docker-documentation-seems-not-accurate/37647208#37647208))

**Comment by jaredbhatti** [comment]
This suggests using Minikube now.
