### ISSUE TITLE
ubuntu-calico.md overlooks dependency of kubelet.service on calico-node.service

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes.github.io#617]
I tried to follow the instructions for setting up the master, but kubelet.service failed to start because it depends on calico-node.service and that is not defined yet.
I was able to get farther by doing the kubelet stuff after, rather than before, the calico stuff.

**Comment by MikeSpreitzer** [comment]
Now I find the current state to be inexplicable.  When I look at https://github.com/projectcalico/calico-cni/blob/master/samples/kubernetes/master/kubelet.service now, it does *not* reference the calico-node service.  When I look at its history, I see only the commit that created the current version.

**Comment by jaredbhatti** [comment]
Is this still an issue?  I haven't seen any more comments on this thread for a long time.  I'm going to close this out for issue hygiene, but please feel free to reopen if there's additional work to do here.
