### ISSUE TITLE
Doc about Node Condition is out of date

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes.github.io#619]
In http://kubernetes.io/docs/admin/node/#node-condition, it said:

```
Currently the only node condition is Ready.
```

However, we already have more conditions now, such as `MemoryPressure`, `OutOfDisk` and `NetworkUnavailable`.

**Comment by rata** [comment]
@Random-Liu only OutOfDisk is on k8s 1.2, right? Or those two (ready and OutOfDisk) are listed on kubectl describe node <node> on kubernetes 1.2.4.

**Comment by Random-Liu** [comment]
@rata Yeah. And the other two `MemoryPressure` and `NetworkUnavailable` will be on 1.3. :)

**Comment by rata** [comment]
On Thu, Jun 16, 2016 at 11:06:28AM -0700, Lantao Liu wrote:
> @rata Yeah. And the other two `MemoryPressure` and `NetworkUnavailable` will be on 1.3. :)

I made a PR to include what is already in 1.2 :)

**Comment by Random-Liu** [comment]
@rata Cool, thanks a lot! ;)

**Comment by jaredbhatti** [comment]
This appears to still be an issue in the docs.  Can you suggest an update?

**Comment by steveperry-53** [comment]
https://kubernetes.io/docs/concepts/architecture/nodes has been updated. Please reopen this issue if further updates are needed.
