### ISSUE TITLE
I wish /docs/user-guide/logging-demo/ existed

### ISSUE THREAD

**Issue by kichik** [kubernetes/kubernetes.github.io#629]
I wish /docs/user-guide/logging-demo/ existed. It's linked from http://kubernetes.io/docs/user-guide/getting-into-containers/

**Comment by idvoretskyi** [comment]
cc @johndmulhausen 

If the demo is still actual, it has to be moved from https://github.com/kubernetes/kubernetes/tree/release-1.1/docs/user-guide/logging-demo (and checked the v1.2-v1.3 compatibility).

**Comment by MikeSpreitzer** [comment]
I do not know anything in particular about this.

**Comment by jaredbhatti** [comment]
Link fixed.
