### ISSUE TITLE
Can't scroll left or right inside the code example boxes

### ISSUE THREAD

**Issue by eyalev** [kubernetes/kubernetes.github.io#633]
In /docs/user-guide/kubectl/kubectl_expose/ I can't scroll left or right inside the code example boxes.

Using Chrome 50.0.2661.86 (64-bit) on Ubuntu 14.04

**Comment by Lukenickerson** [comment]
I'm seeing the same thing in Chrome on Windows. It appears to be caused by the CSS for the headers.

![image](https://cloud.githubusercontent.com/assets/3942453/16992715/713b23f4-4e6e-11e6-97bf-3ebb3d1a7de3.png)

**Comment by thkoch2001** [comment]
I don't understand the purpose of this CSS in the first place. The offending two lines are here:
https://github.com/kubernetes/kubernetes.github.io/blob/master/_sass/_base.sass#L713

    margin-top: -$header-clearance
    height: $header-clearance

Please delete those and find a better solution for whatever problem they are supposed to solve. In any case they introduce new breakage.
