### ISSUE TITLE
The docs site robots.txt doesn't allow snippets to be shown in search

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/kubernetes.github.io#647]
I see this in Google after searching for basic concepts:
Pod - Kubernetes
kubernetes.io/v1.0/docs/user-guide/pods.html
A description for this result is not available because of this site's robots.txt – learn more.

cc @pwittrock

**Comment by pwittrock** [comment]
From @johndmulhausen 

Looks like this is already fixed for new URLs.  We are not planning on updating the old URLs and need to get traffic to the new ones instead.
