### ISSUE TITLE
Swagger -> YAML RFC

### ISSUE THREAD

**Issue by johndmulhausen** [kubernetes/kubernetes.github.io#650]
**For each API Object:**
- Name
- Description (Markdown)
- API Group and Version
- HTTP Request Code (determines CRUD?)
- Example Request
  - Concatenates: Host, then API group and Version, then deployment, then (optionally) name of object, then the HTTP type
  - Then, JSON object body
- Equivalent kubectl
  - Name of command
  - Example string w/usage
- Example response (YAML and JSON) generated from fields
- Return values/response codes

**For each field:**
- Example values for fields
  - Create request example
  - Update request example
  - Create response example
  - Update response example
- Type
  - Link to datatype ref
  - Specify if non-primitive
- Required
- Name
- Description (Markdown)
- Default value

**Comment by johndmulhausen** [comment]
@pwittrock @janetkuo

**Comment by jaredbhatti** [comment]
Phillip, I know  you're working on this already, and you've made a lot of progress. This bug hasn't been updated in 8+ months, so I'm going to close it out for bug hygiene purposes.
