### ISSUE TITLE
I wish /docs/editdocs/ existed

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes.github.io#66]
It is sort of referenced from http://kubernetes.github.io/docs/#contribute-to-our-docs but the thing that looks like a button does not behave like a button.

**Comment by johndmulhausen** [comment]
Should be fixed now. The correct URL was just /editdocs/ :)

**Comment by MikeSpreitzer** [comment]
yes, it is fixed.
