### ISSUE TITLE
I wish /docs/ had no broken buttons

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes.github.io#67]
At the end of the http://kubernetes.github.io/docs/#what-is-kubernetes section there is a blue button with white text --- except it does not behave like a button: it does not react when I hover over it, and nothing happens when I click on it.

**Comment by johndmulhausen** [comment]
@MikeSpreitzer I can't repro nothing happening when I click on the button. Can I ask what browser you're using?

**Comment by MikeSpreitzer** [comment]
Firefox 38.6.1 on MacOS 10.10.5
Safari 9.0.3 on same.
Problem strikes more than one apparent button.  Lower ones work, upper ones do not.

**Comment by MikeSpreitzer** [comment]
Width matters!  Change browser window width, watch changes in which of the first three buttons work!

**Comment by MikeSpreitzer** [comment]
When width allows all three buttons on one row, all work.
When width allows two sections per row, first section's button does not work.
When width puts each button on its own row, only the last works.
(Same for both firefox and safari)

**Comment by johndmulhausen** [comment]
Ah hah! Very good sleuthing, sir. @CreaturesInUnitards has a number of things to do to make responsive behavior work properly. The site doesn't launch in a few days yet, but we really appreciate the early feedback and I'll be sure we get this one fixed before launch.

**Comment by CreaturesInUnitards** [comment]
yup done
