### ISSUE TITLE
having issues when running kubectl edit deployment hello-node. I get the following response: error: there was a problem with the editor "vi"

### ISSUE THREAD

**Issue by dzuluaga** [kubernetes/kubernetes.github.io#674]
I wish /docs/hellonode/ I'm having issues when running kubectl edit deployment hello-node. I get the following response: error: there was a problem with the editor "vi". Any idea what could be wrong? Thanks!

**Comment by runseb** [comment]
Hi @dzuluaga , I assume that you manage to create the deployment properly with `kubectl` ?

If yes, what is our $EDITOR variable. Could be that it is not set properly.
Does vi works normally otherwise.

I just tested this and it works just fine.

**Comment by pselle** [comment]
I've gotten the same error, `vi` works normally otherwise. `vi` is the value of `$EDITOR` in this case

**Comment by pselle** [comment]
BTW, changing $EDITOR to nano works; not sure what the issue is with vi+kubernetes

**Comment by jaredbhatti** [comment]
Haven't seen any movement on this issue for 6 months. Closing out.

**Comment by alunarbeach** [comment]
Setting KUBE_EDITOR="vim" explicitly helped me resolving this issue.

**Comment by yehaifeng** [comment]
I got the same problem. 
Because the system don't the 'vi', only have a alias for "alias vi='vim'" but does not work. And install the vi to fix.

**Comment by soheilade** [comment]
> KUBE_EDITOR="vim"

how to set KUBE_EDITOR="vim"?

**Comment by ksripathi** [comment]
@soheilade 

> echo 'KUBE_EDITOR="vim"' >> ~/.bash_profile
> source ~/.bash_profile

**Comment by mikehuston** [comment]
> Setting KUBE_EDITOR="vim" explicitly helped me resolving this issue.

This helped me also, thanks! Perhaps because `vi` is a symlink for `vim` on my Mac laptop.
```
ls -al /usr/bin/vi
lrwxr-xr-x  1 root  wheel  3 Mar 22  2019 /usr/bin/vi -> vim
```

**Comment by lewiscowleschipuk** [comment]
I Just got this, which is weird as it was working before...

setting `KUBE_EDITOR=vim` worked a charm, even in 2022. Perhaps my vi is an alias of vim. In any case, likely not a kubernetes issue, but local environment config.

**Comment by bustopsy777** [comment]
> I Just got this, which is weird as it was working before...
> 
> setting `KUBE_EDITOR=vim` worked a charm, even in 2022. Perhaps my vi is an alias of vim. In any case, likely not a kubernetes issue, but local environment config.

Hello,
Please can you help me in detail with how you did it, step by step? I am having a problem with this. Thanks

**Comment by EricoCartmanez** [comment]
`export EDITOR=vim` worked for me.
