### ISSUE TITLE
"latest" release does not work with SkyDNS

### ISSUE THREAD

**Issue by geoffhendrey** [kubernetes/kubernetes.github.io#685]
These docs http://kubernetes.io/docs/getting-started-guides/docker/ begin by "Decide what Kubernetes version to use." and have environment variables to set for latest vs stable.

later there is a a section "deploy dns". The instructions linked from there, are these: http://kubernetes.io/docs/getting-started-guides/docker-multinode/deployDNS/

The installation of SkyDNS described above will not work successfully if you use "latest" environment variable as the latest version is totally messed up with regard to skydns. In particular the latest version includes a kube-dns-v13 replication controller, whereas the tutorial skydns installation assumes the replication controller v10 is installed by the tutorial. It's a mess.

**Comment by sarahnovotny** [comment]
@johndmulhausen can you put this on your list?

**Comment by jaredbhatti** [comment]
Minikube is the way to do this, now: http://kubernetes.io/docs/getting-started-guides/minikube/
