### ISSUE TITLE
Please make kubernetes.io available over HTTPS 

### ISSUE THREAD

**Issue by jawnsy** [kubernetes/kubernetes.github.io#691]
Hello,

Please consider making the Kubernetes documentation (http://kubernetes.io) available over HTTPS. Better yet, consider applying Strict-Transport-Security, Upgrade-Insecure-Requests, and related security headers to the web site as well.

I apologize if this is a duplicate - I did a quick search but didn't find anything else that looked relevant in this repository. The web is better with HTTPS :)

Jonathan

**Comment by johndmulhausen** [comment]
Note: GitHub just added support for this:

https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

**Comment by jaredbhatti** [comment]
It's still a "sorta" level of support.  We're working on a way to do this using Netlify.
