### ISSUE TITLE
I wish /docs/getting-started-guides/juju/ Was tested to work with Ubuntu 16.04

### ISSUE THREAD

**Issue by lodotek** [kubernetes/kubernetes.github.io#703]
I wish /docs/getting-started-guides/juju/ Was tested to work with Ubuntu 16.04

Seems that most of the steps are not working for trying to install a kuber cluster on AWS using juju on ubuntu16.04

**Comment by steveperry-53** [comment]
Consolidating with https://github.com/kubernetes/kubernetes.github.io/issues/1391
