### ISSUE TITLE
'docker run' step not working as specified in 'Hello World' walkthrough

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes.github.io#708]
One of the steps on http://kubernetes.io/docs/hellonode/ says:

> $ docker run -d -p 8080:8080 gcr.io/PROJECT_ID/hello-node:v1
> 325301e6b2bffd1d0049c621866831316d653c0b25a496d04ce0ec6854cb7998

However, when I try this, the argument `325...` specified is interpreted as the COMMAND/entry-point.

Error response from daemon: Cannot start container d78e73358830fa62a9e79c6ef027cd026c1d236670859b67e66aaff25c4f5233: [8] System error: exec: "325301e6b2bffd1d0049c621866831316d653c0b25a496d04ce0ec6854cb7998": executable file not found in $PATH.

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by janetkuo** [comment]
@foxish Did you type `325301e6b2bffd1d0049c621866831316d653c0b25a496d04ce0ec6854cb7998` as part of the command? It's the console output.

**Comment by foxish** [comment]
Oh yes. It seems like I misinterpreted that to be a continuation of that line. I removed that and proceeded with the other steps. Thanks!
