### ISSUE TITLE
'Create your cluster' missing the step for setting the compute zone.

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes.github.io#709]
On the page: http://kubernetes.io/docs/hellonode/, under the section: "Create your cluster".
`gcloud container clusters get-credentials hello-world` prompts to set compute/zone value. 

> ERROR: (gcloud.container.clusters.get-credentials) The required property [zone] is not currently set.
> It can be set on a per-command basis by re-running your command with the [--zone] flag.
> 
> You may set it for your current workspace by running:
> 
>   $ gcloud config set compute/zone VALUE

It may be more convenient to add that step to the document.

**Comment by cehsu** [comment]
Please refer to: https://github.com/rvowles/kubernetes-codelounge
