### ISSUE TITLE
Automate PR check for Orphaned .md files

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes.github.io#731]
We need a script that checks for the following on all open PRs and prevents submission until these tests come back clean: 
# Orphaned .md files

Any new .md file in a PR needs to have an accompanying TOC entry in one of the following left nav files:
- _data/guides.yml
- _data/support.yml
- _data/reference.yml
- _data/samples.yml

**Comment by jaredbhatti** [comment]
@devin-donnelly Seems like this issue has already been addressed with new travis checks?

**Comment by steveperry-53** [comment]
The Travis check now includes a TOC check. https://github.com/kubernetes/kubernetes.github.io/blob/master/verify-docs-format.sh
