### ISSUE TITLE
Automate PR check for Front matter precedent

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes.github.io#732]
We need a script that checks for the following on all open PRs and prevents submission until these tests come back clean: 
# Front matter precedent

All .md pages must start with the following two lines:

```

---

---
```

Between these two lines, we can put front-matter YAML if we ever need to, though they are empty now. More importantly, Jekyll will not process Markdown/Liquid for .md files that do not start with a front-matter section.

**Comment by Kashomon** [comment]
What can go in the front matter precedent? Anything?

**Comment by jaredbhatti** [comment]
@Kashomon : Are you still working on this? 
@devin-donnelly : Is this being handled by existing Travis checks?  Also, is what's required in the front matter documented in our templates?

**Comment by Kashomon** [comment]
Nope, sorry. Removing self.

**Comment by steveperry-53** [comment]
Travis requires the page to have a title. And the title goes in the front matter. So a page with no front matter fails the Travis CI check.
