### ISSUE TITLE
Automate PR check for Validate In-page TOC

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes.github.io#733]
We need a script that checks for the following on all open PRs and prevents submission until these tests come back clean: 
# In-page TOC, please

If a topic has more than four headings, ask users to add the following to the top of the page so users can jump around the doc.

```
* TOC
{:toc}
```

**Comment by steveperry-53** [comment]
The TOC element is in our templates, for example, https://github.com/kubernetes/kubernetes.github.io/blob/master/_includes/templates/task.md.
