### ISSUE TITLE
Improve Git files staging

### ISSUE THREAD

**Issue by wernight** [kubernetes/kubernetes.github.io#746]
I can hardly commit via the command line because my user/email and SSH keys are not set.

Using the web interface of Che I'm constantly committing without including all the files or changes.

Current:

 - Git > Add to Index... only marks for addition without adding changes
 - Git > Commit... no matter what I check there it seems to also no add new/changed files or it's weird and I've no idea what it'll actually commit.

Expected:

 - Git > Commit... shows a list of files to commit with a checkbox next to each. Should check by default all modified or deleted files. Pretty much like SmartGit or Git Extensions.

**Comment by runseb** [comment]
@wernight is that a bug for K8s docs ? does not seem related.

**Comment by wernight** [comment]
Oh my... sorry.
