### ISSUE TITLE
Symbols for Diagrams

### ISSUE THREAD

**Issue by danielromlein** [kubernetes/kubernetes.github.io#747]
## About

Kubernetes is a complex product and we would like to be able to better explain its core concepts through use of visuals. A visual language composed of symbols and icons will enable the creation of illustrative diagrams.
## Current State

Only symbols we have today are in the first five slides of this [Google Cloud Platform slide deck](https://docs.google.com/presentation/d/13klSkUQI9yPxKckP8UFLpzzKzxYwv1lit9ELWOnXJFM/edit#slide=id.p15) (if anyone has any others please share). 
## Proposal
1. **Prioritize concepts** we want to have visualizations for. 
2. **Discuss possible representations for concepts & post sketches**. Loop in Google UX researchers for feedback.
3. **Establish basic visual guidelines** for designs of different icons to adhere to as we expand the library. Symbols should be grounded in [Material Design System Icons](https://material.google.com/style/icons.html#icons-system-icons) principles (e.g. "Bold, geometric, simple, intuitive, actionable, consistent"). The Slides of the [Google Cloud Platform visual language](https://docs.google.com/presentation/d/13klSkUQI9yPxKckP8UFLpzzKzxYwv1lit9ELWOnXJFM/edit#slide=id.p15) should be referenced as inspiration, but we're also not going out of our way to align with this style.
4. **Design visually consistent vector (i.e. SVG) symbols**.

Based on @bgrant0607's [proposed concepts](https://github.com/kubernetes/kubernetes.github.io/issues/84#issuecomment-226300701), I've put together the following list of concepts to consider for visualization:
- Pod
- All types of services:
  - Cluster
  - Nodeport
  - Loadbalancer
  - Headless
  - Imported
- Ingress
- EndPoint
- Every controller:
  - Replication Controller
  - Replica Set
  - Deployment
  - DaemonSet
  - PetSet
  - Job
  - ScheduledJob
- Rolling update
- Canary deployment pattern
  - with ConfigMap
- Horizontal Pod Autoscaling
- ServiceAccount
- Secret
- Persistent Volumes and Persistent Volume Claims
- System Architecture
- Things we will need to diagram concepts and processes
  - Virtual IP
  - IP address
  - Running Container
  - Request / Response

As @pwittrock [pointed out](https://github.com/kubernetes/kubernetes.github.io/issues/84#issuecomment-228387857), we should focus first on designing visualizations for concepts, while keeping in mind how those visualizations will come together in more complex diagrams (e.g. _deployment_)
## Reference
- [Issue #84 – "We need more diagrams!"](https://github.com/kubernetes/kubernetes.github.io/issues/84)
- [Brian Grant _WSO2Con US 2015 Kubernetes_ Slides](http://www.slideshare.net/BrianGrant11/wso2con-us-2015-kubernetes-a-platform-for-automating-deployment-scaling-and-operations)
- [Microsoft's Azure, Cloud and Enterprise Symbol / Icon Set](https://www.microsoft.com/en-us/download/details.aspx?id=41937)

**Comment by bryk** [comment]
CC @kubernetes/dashboard-maintainers

**Comment by bryk** [comment]
Is this about creating simple icons that'll identify aforementioned concepts or complex diagrams that would explain how they work? I'm particularly interested whether this would fit into the navigation menu that we work on in https://github.com/kubernetes/dashboard/issues/908.

If this can fit into the menu, I'm more than happy to gather a team and help out with this. We can do some collaborative brainstorming to throw out ideas on the table. 

What do you think?

**Comment by bryk** [comment]
> Prioritize concepts we want to have visualizations for.

I'd like us to move forward with top-level menu items from: https://github.com/kubernetes/dashboard/issues/908. Then, if feasible, second level of navigation.

**Comment by jaredbhatti** [comment]
Closing this issue for issue hygine reasons.  Please reopen if it's still necessary.

**Comment by techtonik** [comment]
It is still necessary - #3584

**Comment by techtonik** [comment]
I'd like to create Inkscape symbol library and even cover it with some history to introduce people into it if there are some funds.

**Comment by techtonik** [comment]
Also would be nice to have some convention for placing such symbols in source code repositories.

**Comment by Vlaaaaaaad** [comment]
This is **very much needed**. Creating documentation and plans for Kubernetes without having any icons is a huge struggle. The end-result looks bad too. 

See [AWS Icon packs](https://aws.amazon.com/architecture/icons/) and how AWS schemas are all the same, no matter who the author is( an official drawing or a random blog post).

**Comment by Roderick-Jonsson** [comment]
@danielromlein I have done some diagrams which cover some concepts you mentioned. Here you have an example [PowerodIT - Blog - Kubernetes Patterns: Stateless Applications](https://powerodit.ch/2017/11/06/kubernetes-patterns-stateless-applications/). Is there still interest in pursuing this project from your side. Would be interested to have short chat with you about the project.

**Comment by collinmangum** [comment]
@danielromlein @Roderick-Jonsson @Vlaaaaaaad I work at Lucidchart and since there are no official Kubernetes icons we are seriously looking to create an Icon pack. If there is anyone that would be interested in chatting with us about that let me know, we would love input from the community.

**Comment by Roderick-Jonsson** [comment]
@collinmangum You guys where actually on my mind, great to hear from you. We are at the moment reviving the project. @danielromlein has his meetings on [Thursdays](https://github.com/kubernetes/community/tree/master/sig-ui), how about we meet then to further discuss this opportunity?

**Comment by Vlaaaaaaad** [comment]
@collinmangum: great initiative from Lucidchart! Not sure how much I can help, but I'm open for a chat.

I'd prefer a more... minimalistic approach with simple lines, but that's me.

I can say I really enjoyed the icons used in [this blog post](https://container-solutions.com/deployment-strategies/) by @etiennetremel. A big hexagon for a pod and smaller ones for containers seem great. The hexagon motif is used in the _Kublr Control Plane_ section on [kublr](https://kublr.com/) too where an example of a detailed container/pod view can be seen.

**Comment by etiennetremel** [comment]
Thanks @Vlaaaaaaad, Container Solutions also helped with the diagrams used in the [Kubernetes basics tutorials](https://kubernetes.io/docs/tutorials/kubernetes-basics/)

**Comment by Vlaaaaaaad** [comment]
@etiennetremel wow, those are great. Extending on them seems perfect.

BTW, are the resources available anywhere? I'd love to use them.

**Comment by etiennetremel** [comment]
There some of these resources available here: https://github.com/kubernetes/website/tree/master/docs/tutorials/kubernetes-basics/public/images

**Comment by collinmangum** [comment]
Glad to hear of some excitement behind this project! @Roderick-Jonsson can you invite me to the Thursday meeting referenced and I'll get a few members of the Lucidchart team on the line with me so we can have some initial discussions?

**Comment by Roderick-Jonsson** [comment]
@collinmangum Great! I just took a look at the [SIG meeting calendar](https://kubernetes.io/community/) @danielromlein will there be a meeting tomorrow?

**Comment by Roderick-Jonsson** [comment]
@collinmangum @danielromlein  Seems that there is no meeting slot for today.
Let's make an open meeting next Thursday where everybody interested in getting this project of the ground is encouraged to join in :)

**Comment by collinmangum** [comment]
Sounds great, @Roderick-Jonsson. I will watch for the meeting info and have some Lucidchart representation.

**Comment by collinmangum** [comment]
@Roderick-Jonsson I'm not seeing a meeting slot on the calendar for Thursday. Is there one scheduled? Trying to ensure I can have some Lucidchart members join.

**Comment by Roderick-Jonsson** [comment]
@collinmangum Sorry for the delay there seem to be changes going on. I am waiting for someone from the team opening the calendar entry. @danielromlein @maciaszczykm @floreks

**Comment by danielromlein** [comment]
@collinmangum not sure where the calendar event went for SIG UI's weekly. For now, I've created a one-off meeting this [Thursday](https://calendar.google.com/event?action=TEMPLATE&tmeid=MHRuNTV1aXFxanY5bjU3c2I4OHU0YjVzZW1fMjAxODA0MTlUMTYwMDAwWiBkcm9tbGVpbkBnb29nbGUuY29t&tmsrc=dromlein%40google.com&scp=ALL) at the typical time so we can chat then. Thanks for your interest!

**Comment by collinmangum** [comment]
Great, thanks @danielromlein! Chat with you Thursday at 9am PT.

**Comment by etiennecoutaud** [comment]
I'm not sure if it's the right place, but we worked on kubernetes symbols for diagrams.

Feel free to use: [https://github.com/octo-technology/kubernetes-icons](https://github.com/octo-technology/kubernetes-icons)

Do not hesitate to ask for help if needed.

**Comment by dankohn** [comment]
I think these are great. If you wanted to contribute them to CNCF, we would be happy to host them, which may get them additional attention. Unless, perhaps, ContribEx wanted to host them in the Kubernetes project directly.

Cc @parispittman @castrojo @Phillels @thockin

**Comment by etiennecoutaud** [comment]
It would be a pleasure to contribute them to CNCF.

I'm waiting for ContribEx feedbacks

**Comment by castrojo** [comment]
cc @kubernetes/sig-architecture-feature-requests as I know their charter mentions documenting the k8s architecture and they might have an opinion on this. We could either create a new directory for it or put it under the sig-arch/ directory.

**Comment by lucidanthony** [comment]
@etiennecoutaud these are excellent! @collinmangum and I work for a diagramming company, [Lucidchart](https://www.lucidchart.com) (see mention earlier in this thread), and we've been looking for a canonical source of Kubernetes icons. Our goal is to turn them into a shape library so that people can use them to create Kubernetes architecture diagrams. We have similar shape libraries for AWS, GCP, and Azure today. 

Would you be open to our using these icons in a Kubernetes shape library?

**Comment by etiennecoutaud** [comment]
@lucidanthony sure !

**Comment by jdumars** [comment]
+100 for a Lucidchart Kubernetes icon set.

**Comment by idvoretskyi** [comment]
+100 as well!

Great job!
