### ISSUE TITLE
user-guide/ui: PetSet = load balanced service?

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes.github.io#750]
https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/ui.md

>[Pet Sets](http://kubernetes.io/docs/user-guide/load-balancer/) (nominal Services, also known as load-balanced Services) for legacy application support.

Are Pet Sets == "load-balanced Services"? It also links to the external load balancer docs which I wasn't expecting.

**Comment by chrislovecnm** [comment]
@colemickens please explain more.

**Comment by colemickens** [comment]
I'm not sure what else I can explain. The "Pet Sets" link takes you to the generic "load balancer" documentation that presumably has nothing to do with "pet sets". Also, the description text seems confusing. Maybe I'm thinking about pet sets wrong, but it seems like there's a better description that "load-balanced Services".

**Comment by colemickens** [comment]
Ping.

**Comment by digitalfishpond** [comment]
Assuming this should link to here: http://kubernetes.io/docs/user-guide/petset/ ? If someone can confirm, I will fix.

**Comment by colemickens** [comment]
Seems like that's the right fix to me.
