### ISSUE TITLE
I wish /docs/getting-started-guides/minikube/ indicated that exposing services of type LoadBalancer is not possible with minikube, so hitting nodes and containers becomes difficult

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/kubernetes.github.io#756]
I wish /docs/getting-started-guides/minikube/ indicated that exposing services of type LoadBalancer is not possible with minikube (it's listed as a known issue in the repo), so hitting nodes and containers requires additional configuration or at least the use of a NodePort.  

Trying to replicate the hello-node application on minikube is not straightforward because the LoadBalancer service is not possible here.

**Comment by steveperry-53** [comment]
We're making progress along these lines.

\https://kubernetes.github.io/docs/tutorials/stateless-application/hello-minikube/
https://kubernetes.github.io/docs/tutorials/stateless-application/run-stateless-application-deployment/
https://kubernetes.github.io/docs/tutorials/stateless-application/expose-external-ip-address/
