### ISSUE TITLE
Invalid link in DNS doc

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes.github.io#764]
The link to federation is broken from the DNS doc : https://github.com/kubernetes/kubernetes.github.io/blob/89ea52c058029701cecc1f094cb6bae045e5e344/docs/admin/dns.md#kubernetes-federation-multiple-zone-support

**Comment by vishh** [comment]
cc @quinton-hoole

**Comment by girishkalele** [comment]
@vishh 

Works on Kubernetes.io - the review comment was that the link should be just /docks/admin/multiple-zones.

From http://kubernetes.io/docs/admin/dns/ , the federation link works correctly, but it doesn't work when browsing Github.

**Comment by girishkalele** [comment]
cc @johndmulhausen 

@vishh This was recommended here

https://github.com/kubernetes/kubernetes.github.io/pull/742#discussion_r68834882

**Comment by steveperry-53** [comment]
Not actionable at this point
