### ISSUE TITLE
I wish /docs/admin/high-availability/ ...explained if there is more than one api-server, do they need to find each other, and how?

### ISSUE THREAD

**Issue by ae6rt** [kubernetes/kubernetes.github.io#802]
I wish /docs/admin/high-availability/ ...explained if there is more than one api-server, do they need to find each other, and how?

I am cross-referencing this document with Kelsey's https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-kubernetes-controller.md and cannot discern how multiple masters find each other, or if they even need to.  

Thanks.

**Comment by steveperry-53** [comment]
@ae6rt O think this topic addresses your question: https://kubernetes.io/docs/tasks/administer-cluster/highly-available-master/.

If not please reopen.
