### ISSUE TITLE
Outdated docs for v1 API definition

### ISSUE THREAD

**Issue by rata** [kubernetes/kubernetes.github.io#803]
Hi,

I was working with the volume secret code and I realized, looking at the code, that it accept mappings just like configmaps. There are tests for that, also. Eventhough, the documentation in: http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_secretvolumesource doesn't show it.

The documentation for configmap, http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_configmapvolumesource, does show it and for secrets I even tried it and it works the same.

I tried with this example, just to be sure:

```
$ cat test-pod.yaml 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hello-node
  name: hello-node
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello-node
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: hello-node
    spec:
      containers:
      - image: nginx
        name: hello-node
        volumeMounts:
        - mountPath: "/etc/foo/"
          name: "foo"
      volumes:
      - name: "foo"
        secret:
          secretName: test
          items:
          - key: "whatisk8s.md"
            path: "ratata"
```

And then run: `kubectl create secret generic test --from-file=docs/whatisk8s.md; kubectl apply -f test-pod.yaml`

The mapping works just fine.

Can the documentation be regenerated, please? =)

**Comment by steveperry-53** [comment]
@rata It looks like the current ref docs cover this. If not, please reopen.

https://kubernetes.io/docs/api-reference/v1.8/#secretvolumesource-v1-core
