### ISSUE TITLE
I wish /docs/api-reference/extensions/v1beta1/definitions/ described NetworkPolicy

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes.github.io#804]
I wish /docs/api-reference/extensions/v1beta1/definitions/ described NetworkPolicy

**Comment by MikeSpreitzer** [comment]
I see that NetworkPolicy is defined at `docs/api-reference/extensions/v1beta1/definitions.html#_v1beta1_networkpolicy` in the current sources, but the online view at http://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/ does *not* include NetworkPolicy.  Why is that?

CC @johndmulhausen

**Comment by MikeSpreitzer** [comment]
Things just got worse.  Now https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/api-reference/extensions/v1beta1/definitions.md just contains an include statement (which I do not know how to resolve).

**Comment by MikeSpreitzer** [comment]
What's going on here?  The view at http://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/ _still_ does not show `NetworkPolicy`.

**Comment by MikeSpreitzer** [comment]
@pwittrock explained that the include can be resolved at https://github.com/kubernetes/kubernetes.github.io/tree/master/_includes and the content there labelled as 1.3 is actually 1.2

**Comment by pwittrock** [comment]
Fixed in #1023
