### ISSUE TITLE
``` escaping problems and {{

### ISSUE THREAD

**Issue by eparis** [kubernetes/kubernetes.github.io#81]
docs/getting-started-guides/cloudstack
docs/getting-started-guides/docker
docs/getting-started-guides/docker-multinode/deployDNS
docs/getting-started-guides/docker-multinode/testing
docs/getting-started-guides/mesos
docs/user-guide/compute-resources
docs/user-guide/connecting-to-applications-port-forward
docs/user-guide/deploying-applications
docs/user-guide/kubectl/kubectl_get
docs/user-guide/production-pods
docs/user-guide/walkthrough/k8s201
docs/user-guide/walkthrough/README

All appear to have liquid force like tags, aka: `{{` which likely require a `{% raw %}`

@johndmulhausen added:

$25 bounty for anyone who submits a PR that ads {% raw %}{% endraw %} in the codeblocks that have liquid-esque tags inside them, so that the text won't be hidden on the site.

Please reference issue #81 in your PR

**Comment by mikebrow** [comment]
Hate hidden text I suppose I'll do some commits for the non-generated stuff.  I presume that's docs/* where there is no `.files_generated` file in the directory....

**Comment by johndmulhausen** [comment]
@mikebrow thanks so much! And guess what? This issue was tagged with a $25 bounty, so I'll be sending a coupon code for free Google Cloud Platform hosting time. Thanks for your efforts!

**Comment by m8ryx** [comment]
I am continuing on this issue.  These looks complete:
docs/getting-started-guides/cloudstack
docs/getting-started-guides/docker
docs/getting-started-guides/docker-multinode/deployDNS
docs/getting-started-guides/docker-multinode/testing
docs/getting-started-guides/mesos
docs/user-guide/compute-resources
docs/user-guide/connecting-to-applications-port-forward
docs/user-guide/deploying-applications

Starting with 
docs/user-guide/kubectl/kubectl_get
docs/user-guide/production-pods
docs/user-guide/walkthrough/k8s201
docs/user-guide/walkthrough/README

**Comment by m8ryx** [comment]
as far as I can tell these have all been completed.  The final file docs/user-guide/walkthrough/README appears to have been deprecated.

**Comment by johndmulhausen** [comment]
Thanks for the final fixes, m8ryx!
