### ISSUE TITLE
We need better cross-page linking

### ISSUE THREAD

**Issue by johndmulhausen** [kubernetes/kubernetes.github.io#83]
Pages frequently mention common Kubernetes concepts without linking to the canonical URL for that concept. It therefore becomes very difficult to process information without the full context of the whole of Kubernetes firmly in your head at all times. 

We are offering a bounty of $25 in Google Cloud Platform credit for each merged pull request that fully processes a page and makes sure it is linking out to helpful information. 

Every PR should process a goodly amount of text - let's say 1000 words or so, and a minimum of 15 links. That might mean your PR has three small pages in it, which is okay. But at a minimum, one long one.

Automatically generated pages (like the kubectl refdocs or the API reference) are not eligible since the source of truth for those pages lives elsewhere. 

Might limit the number of these we give out if we're over-flooded to the exclusion of other bounties but this is a general docs problem that needs fixing.

Please reference this issue in your PRs.

**Comment by jaredbhatti** [comment]
Agree with the issue, but closing it while we restructure.
