### ISSUE TITLE
I wish /docs/user-guide/jobs/ had info about ScheduledJob

### ISSUE THREAD

**Issue by dirkjonker** [kubernetes/kubernetes.github.io#838]
If I recall correctly, there should now be a ScheduledJob in Kubernetes 1.3? Can't find any information about that in the documentation.

**Comment by soltysh** [comment]
@dirkjonker you're looking for https://github.com/kubernetes/kubernetes.github.io/pull/1123. This was merged against release-1.4 branch so it'll be release along with k8s 1.4

**Comment by dirkjonker** [comment]
fixed in #1123 so this can be closed
