### ISSUE TITLE
We need more diagrams!

### ISSUE THREAD

**Issue by johndmulhausen** [kubernetes/kubernetes.github.io#84]
Kubernetes has so many concepts that beg for visual aids, whether that's cluster anatomies, control loops, deployment flows, networking diagrams, etc. 

I'm paying $100 USD in Google Cloud Platform credit to every accepted diagram.
- Must be in SVG format
- Please use [this slide deck ](https://docs.google.com/presentation/d/13klSkUQI9yPxKckP8UFLpzzKzxYwv1lit9ELWOnXJFM/edit#slide=id.p15)for diagram assets: 
  https://docs.google.com/presentation/d/13klSkUQI9yPxKckP8UFLpzzKzxYwv1lit9ELWOnXJFM/edit#slide=id.p15

Suggested workflow: Make a copy of the assets slide deck, use it to arrange your diagram, then copy/paste it into a Google Drawing and send us the SVG and the page you think it should go towards. 

Please reference issue #84 in your PRs.

**Comment by martamarszal** [comment]
Hey John, I want to work on these diagrams in Illustrator, when I download a slide as svg and open it in Illustrator it turns out that the icons are just images. This means I can't edit them. 
Can you provide a complete icon set + the grid as ai, eps or svg?

**Comment by bgrant0607** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/11764

**Comment by bgrant0607** [comment]
Some things we want diagrams for:

* All types of services: cluster, nodeport, loadbalancer, headless, imported
* Ingress
* Every controller: RC, RS, Deployment, DaemonSet, PetSet, Job, ScheduledJob
  * Rolling update
  * Canary deployment pattern
  * with ConfigMap
* HPA
* ServiceAccount and Secret
* PVCs and PVs
* System architecture

cc @kubernetes/docs

**Comment by wernight** [comment]
Would be useful to provide a way to use them. One would try to copy them but that's really "using" them. For example if the expected source is using Google Draw, having them in draw or something similar. May be having them in SVG for some other SVG editor.

**Comment by romlein** [comment]
@johndmulhausen any progress on getting the SVGs publicly available somewhere? / @pwittrock

**Comment by pwittrock** [comment]
@romlein The svgs added at the top of the slide deck are all that we have been able to locate.  Both @johndmulhausen and I have done some digging, but haven't been able to find svg's for other assets.  We are unsure of the origin of the assets, and I don't know what the original format was.

Assuming the svg's do not exist what are the next steps.  What are your thoughts on a visual language for our docs and diagrams?

**Comment by romlein** [comment]
@pwittrock OK, well thank you for satisfying the due diligence of making sure there wasn't a set we should be working from. I like fresh starts! 🙌
"Symbols / Icons" seems more appropriate than "diagrams" here, since really we're looking for the building blocks of a visual language we can _create_ diagrams with, correct? Microsoft's [Azure, Cloud and Enterprise Symbol / Icon Set](https://www.microsoft.com/en-us/download/details.aspx?id=41937) seems like it could be at least good inspiration for this.

Here's a process I could see being effective:

1. Start an issue capturing _what_ we need to include; @bgrant0607's [list](https://github.com/kubernetes/kubernetes.github.io/issues/84#issuecomment-226300701) seems like it would make sense to start with. @johndmulhausen do you want to create this?
2. Discuss there different possible representations for concepts & post sketches.
3. Establish basic visual guidelines for designs of different icons to adhere to as we expand the library. The Slides of the Google Cloud Platform visual language seem like a reasonable starting point here. 
4. From there, I have bandwidth to start designing visually consistent vectors, and anyone else that would like to is of course welcome to contribute.

Thoughts?

**Comment by pwittrock** [comment]
@romlein Thanks for leading this.  Your proposal sounds good to me.  @bgrant0607 WDYT?

In addition to the MS icon set, @erictune pointed me at the [material icon set](https://design.google.com/icons/).

One thing that is been on my mind is that we will be creating diagrams at several different abstraction levels, and our language will need to be consistent across them:

- Diagraming Concepts themselves (e.g. How do Pods, Services, Ingresses work?)
  - Will need icons to represents the sub-atomic pieces of the Concepts
  - e.g. for Pod: multiple containers, environment variables, ip address, volumes
  - May also want icons to represent processes or configurations of the Concept
  - e.g. for Pod: container restart (and restartPolicy?), liveness / readiness (and livenessChecks?), cpu limits, etc

- Diagraming Interactions+Relationships between Concepts
  - e.g. for Deployment: Create, Delete Pods
  - Will need icons to represent the actual Concepts themselves
  - Should use imagery consistent with how we diagramed the Concepts themselves
- Iterations between Concepts and Tools/People/Machines Resources

@romlein What are your thoughts on using color as part of the visual language?  Is this generally discouraged or something useful?

**Comment by romlein** [comment]
@pwittrock yes! Material icons design principles definitely make sense to incorporate. We may need to increase the 24dp grid size they're based on to accommodate more complex forms, but I think the basic guidance there is great.

I'll try to do some research into systems that have to visually represent constituent elements _as well as_ concepts those elements roll up to (e.g. containers / pods / clusters). Anyone have any recommendations around that? It would be nice if they somehow related to each other. 

@pwittrock:
>how we diagramed the Concepts themselves

Where are the above mentioned diagrams? Interspersed throughout docs? Are they centralized anywhere?

@pwittrock as far as color: I think we should intentionally incorporate it, but look to craft visual representations that also stand alone independent from color.

**Comment by pwittrock** [comment]
@romlein I would also like to be able to get Google UX researchers to review and give us feedback as early as possible.  Does this make sense to do as part of step 2, or once we have a few icons post step 2?

**Comment by romlein** [comment]
@pwittrock I'd see that as valuable in the conceptualization of step 2. Once we figure out solid vizualizations for concepts with some quick accompanying sketches, creating effective symbols / icons is mostly a matter of applying sound visual design.
As far as getting that conversation started, how would you recommend going about that? I can just create a new issue with @bgrant0607's [list](https://github.com/kubernetes/kubernetes.github.io/issues/84#issuecomment-226300701)?

**Comment by pwittrock** [comment]
@romlein Creating a new issue sounds good.  As part of the issue, we probably want to figure out what things we will need symbols / icons to represent, and what things will need diagrams composed of multiple symbols.

What sort of things do we still need / want folks to give feedback on?  The list of digram topics?  How the concepts are represented in diagrams?  Main concepts we want to convey?  Diagrams for processes vs concepts?

**Comment by tsloughter** [comment]
I found this issue looking for kubernetes diagram symbols and tried following through to other linked to issues to find if there was ever a set of diagram symbols bundled together for kubernetes components but could not find them.

Has this happened? If so, where can they be found? Thanks!

**Comment by danielromlein** [comment]
@tsloughter unfortunately there is no standardized set of symbols. This specific issue's effort sort of fizzled out and no one's yet initiated another attempt. If you have any ideas of a good approach please share! I'd love to enable more visualization of concepts.

**Comment by techtonik** [comment]
@tsloughter see #747.

**Comment by scottrigby** [comment]
Outcome of #747 🎉 https://github.com/kubernetes/community/pull/2192
