### ISSUE TITLE
CoreOS Multinode cluster documentation fails on 1.3.0

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kubernetes.github.io#840]
For the life of me I can't get this working with verison 1.3.0 of Kubernetes via http://kubernetes.io/docs/getting-started-guides/coreos/coreos_multinode_cluster/

1.1.2 seems to work fine, but not 1.3.0. 

Going to investigate this a bit further and throw some debug output in here.

cc @kelseyhightower

**Comment by kelseyhightower** [comment]
@cdrage I really want to get these "getting started guides" out of this repo and yield control of these docs to the upstream provider such as CoreOS in this case. Thoughts?

**Comment by cdrage** [comment]
@kelseyhightower since a lot of these docs are outdated now in regards to documentation, I would agree for them to be remove and their respective upstream providers dedicate time / monitor them for changes :)

**Comment by cdrage** [comment]
Page has vanished. Closing.
