### ISSUE TITLE
Reference documentation is needed for new 1.3 APIs

### ISSUE THREAD

**Issue by jimmycuadra** [kubernetes/kubernetes.github.io#849]
As far as I can tell, resource definitions and APIs for the new 1.3 API groups are not available in [the reference docs](http://kubernetes.io/docs/reference/). Specifically, I am looking for the resource definitions for the RBAC API.

**Comment by jimmycuadra** [comment]
1.4 is out and this still hasn't happened. :{

**Comment by steveperry-53** [comment]
https://kubernetes.github.io/docs/api-reference/rbac.authorization.k8s.io/v1alpha1/definitions/
