### ISSUE TITLE
Refdocs need {{ }} processing

### ISSUE THREAD

**Issue by johndmulhausen** [kubernetes/kubernetes.github.io#85]
Split from #81 

But docs/user-guide/kubectl/kubectl_get is a little special since it is auto-generated. I can probably get the generated docs in kubernetes.git to include a `{% raw %}` around all ``` blocks, but those would then show on the kubernetes.git. I wonder if it would be better as part of the import process Until such point as the docs are autogenerated here instead of there, in which case the generation would need to handle it properly....

**Comment by bgrant0607** [comment]
cc @caesarxuchao @pwittrock @janetkuo

**Comment by johndmulhausen** [comment]
Hold on any action on this; @lavalamp is currently working on checking in YAML representations of the CLIs and APIs, putting the autogeneration of refdocs in Jekyll. There, it will be dead simple to add {% raw %} where needed.
