### ISSUE TITLE
Expand Docs around Kubectl config, specifically config file path

### ISSUE THREAD

**Issue by RyanHartje** [kubernetes/kubernetes.github.io#856]
/docs/user-guide/kubectl/kubectl_config/ should explain how to configure kubectl to interact with a remote kubernetes cluster. Currently it looks like help/man page. 

It would be great to know where this configuration file is saved so I can just edit with vim instead of running a myriad of commands as well.

**Comment by steveperry-53** [comment]
Otherwise, ${HOME}/.kube/config is used and no merging takes place.
