### ISSUE TITLE
Links seem to not work

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes.github.io#86]
For example in https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/whatisk8s.md neither which refers to document works for me.

**Comment by johndmulhausen** [comment]
You should be viewing our docs on the site:

https://kubernetes.github.io/docs/whatisk8s/

**Comment by piosz** [comment]
Works for me. Thanks for the explanation.

**Comment by johndmulhausen** [comment]
No prob :) 

I know in the past we had browse-by-GitHub as more of a thing but that was all enforced by munging scripts that we're getting away from.
