### ISSUE TITLE
Verify and document the default value of imagePullPolicy

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes.github.io#875]
As per the document link http://kubernetes.io/docs/user-guide/images/#updating-images above  "The default pull policy is IfNotPresent which causes the Kubelet to not pull an image if it already exists"

But when i create a deployment , the default value i see for imagePullPolicy is "Always"

**Comment by steveperry-53** [comment]
The document seems OK now. It has this about **latest** and **Always**:
If you did not specify tag of your image, it will be assumed as :latest, with pull image policy of Always correspondingly.
