### ISSUE TITLE
Add reference links to reference page.

### ISSUE THREAD

**Issue by IanEdington** [kubernetes/kubernetes.github.io#879]
I think we should add links to all the api descriptions on the API. I found them extremely useful but they are difficult to find. I would add pods, deployments ect to this page: http://kubernetes.io/docs/reference/

eg. pods: http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_pod
deployments: http://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1beta1_deployment
services: http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_service

If there is interest I'll write something up and make a pull request.

**Comment by jaredbhatti** [comment]
We took a stab at redesigning the page with more information, and creating a beta redesign of the API pages themselves. (check the left nav). http://kubernetes.io/docs/reference/

If this is still an issue, feel free to reopen.

**Comment by IanEdington** [comment]
that's awesome. ty
