### ISSUE TITLE
I wish http://kubernetes.io/third_party/swagger-ui/ still worked

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes.github.io#88]
The top Google link for "kubernetes swagger UI" is http://kubernetes.io/third_party/swagger-ui/ which now leads to a 404.

I think the bug-reporting may also be broken. I entered "still worked" in the I Wish box at the bottom of the 404 I got on the swagger-ui page, and it generated me an issue with "I wish /v1.1/docs/devel/README/ still worked"

**Comment by bgrant0607** [comment]
Closing in favor of #105
