### ISSUE TITLE
I wish /docs/user-guide/environment-guide/ had a valid target for the 'containers/' link

### ISSUE THREAD

**Issue by ahawtho** [kubernetes/kubernetes.github.io#881]
I wish /docs/user-guide/environment-guide/ had a valid target for the 'containers/' link.

The 'containers/' link on the environment-guide links to http://kubernetes.io/docs/user-guide/containers/ , which doesn't appear to be what was intended.  I'd expect to see samples of the yaml files.

**Comment by lazzarello** [comment]
agreed. Was confused when the "code for the containers" text pointed to a discussion on "How docker handles command and arguments".

**Comment by steveperry-53** [comment]
I working on a fix for this in https://github.com/kubernetes/kubernetes.github.io/pull/2204, but I'm having trouble getting the Travis test to pass.
