### ISSUE TITLE
I wish /docs/user-guide/environment-guide/ didn't return an HTML document as text when clicking on the 'pod definition' link in the "Query the Service" section

### ISSUE THREAD

**Issue by ahawtho** [kubernetes/kubernetes.github.io#882]
I wish /docs/user-guide/environment-guide/ didn't return an HTML document as text when clicking on the 'pod definition' link in the "Query the Service" section

If you search for the text 'pod definition' and click the link, it takes you to this page:

http://kubernetes.io/docs/user-guide/environment-guide/show-rc.yaml

Which appears to be interpreted as text by Chrome, but contains HTML.

**Comment by bboreham** [comment]
I think the link you refer to is at the bottom of http://kubernetes.io/docs/user-guide/environment-guide/

Same thing happens to me; the file in question is really at https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/environment-guide/show-rc.yaml

Also the `containers/` link earlier on that page goes to http://kubernetes.io/docs/user-guide/containers/ which isn't appropriate.

**Comment by steveperry-53** [comment]
Thanks for pointing this out. The page will soon be converted to a new task topic. We'll fix the strange link at that time.
