### ISSUE TITLE
I wish /v1.0/docs/getting-started-guides/logging-elasticsearch.html existed

### ISSUE THREAD

**Issue by yenemartin** [kubernetes/kubernetes.github.io#89]
I wish /v1.0/docs/getting-started-guides/logging-elasticsearch.html existed

**Comment by johndmulhausen** [comment]
Added JavaScript redirects to 404.md that fix this.

**Comment by johndmulhausen** [comment]
Try it: http://kubernetes.io/v1.0/docs/getting-started-guides/logging-elasticsearch.html
