### ISSUE TITLE
Navigation panel is missing on http://kubernetes.io/docs/user-guide/downward-api/volume/

### ISSUE THREAD

**Issue by rutsky** [kubernetes/kubernetes.github.io#890]
http://kubernetes.io/docs/user-guide/downward-api/volume/:

![2016-07-21_16 51 11_1](https://cloud.githubusercontent.com/assets/46573/17025176/d3466c9a-4f6b-11e6-992a-90fa65846ea8.png)

Compare with http://kubernetes.io/docs/user-guide/downward-api/:
![2016-07-21_16 51 31_1](https://cloud.githubusercontent.com/assets/46573/17025189/dd33effc-4f6b-11e6-94e8-747951cc9a42.png)

**Comment by steveperry-53** [comment]
Fixed
