### ISSUE TITLE
I wish /docs/hellonode/ had correct information!  Comeon people - this is supposed to be the PREMIER getting started app - and it is filled with bad/incorrect/obsolete information!!!

### ISSUE THREAD

**Issue by thelongaevi** [kubernetes/kubernetes.github.io#894]
I wish /docs/hellonode/ had correct information!  

This is supposed to be the PREMIER "getting started" app - and it is filled with bad/incorrect/obsolete information!

THIS IS A "HELLO WORLD" APP.  

IF YOU CANNOT GET THE DOCUMENTATION STRAIGHT FOR THIS, I'D HATE TO THINK OF WHAT LIES AHEAD FOR ANYONE WHO WANTS TO USE GOOGLE CONTAINER ENGINE FOR THEIR BUSINESS.

YOU ARE WASTING YOUR USERS' TIME, THE WAY MICROSOFT DID (IN THE 80s and 90s)!

**Comment by Kashomon** [comment]
Sorry that you had a frustrating time with the hello node docs. If you have any concrete suggestions, we'd be happy to take a look into fixing them.
