### ISSUE TITLE
I wish /v1.1/docs/roadmap.html existed

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes.github.io#90]
I wish /v1.1/docs/roadmap.html existed

**Comment by johndmulhausen** [comment]
That page was really always hosted here, so I pulled it: 

https://github.com/kubernetes/kubernetes/milestones/

**Comment by quinton-hoole** [comment]
@johndmulhausen I still find the original link vie Google Search, and it still gives me a 404.  

http://kubernetes.io/docs/roadmap/

Is it not better to put a redirector on the old URL for all such URL's.  I'm sure that there are tons of third party links out there (e.g. in press releases, blog posts etc) that we won't be able to update.

**Comment by quinton-hoole** [comment]
@johndmulhausen I don't seem to be able to re-open this issue (permissions problem?).  Can you fix that too?  I guess that the Kubernetes team should continue to have the same permissions as they had on the previous docs repo.

**Comment by bgrant0607** [comment]
Reopened

**Comment by bgrant0607** [comment]
We don't have a useful roadmap doc, but I agree we should have a placeholder or redirect or anything other than 404.

**Comment by johndmulhausen** [comment]
Added a redirect in https://github.com/kubernetes/kubernetes.github.io/commit/ef891efae587c35cbf81ab7f9efc05c9ee114741

**Comment by quinton-hoole** [comment]
Awesome @johndmulhausen!  Thanks!
