### ISSUE TITLE
Are sets one word or two?

### ISSUE THREAD

**Issue by Lukenickerson** [kubernetes/kubernetes.github.io#914]
Some _sets_ are commonly written as one word (see in various Kubernetes issue discussions) -- DaemonSets, [PetSets](https://github.com/kubernetes/kubernetes/issues/27430) -- whereas some -- Replica Sets -- seem to be more often written as two words. In the documentation, two words is used across the board. Is two words the standard that we should be encouraging people to converge on, or is there a reason to use a combined/on-word spelling in some cases?

**Comment by jaredbhatti** [comment]
We have a style guide where we're hashing out these issues: http://kubernetes.io/docs/contribute/style-guide/
