### ISSUE TITLE
I wish /docs/admin/federation/index/ existed

### ISSUE THREAD

**Issue by kartikshah** [kubernetes/kubernetes.github.io#933]
I wish /docs/admin/federation/index/ existed

Seems to me that the link from this page http://kubernetes.io/docs/admin/dns/ is pointing to /docs/admin/federation/index.md, but the page does not exist.

**Comment by ericchiang** [comment]
Dup of #901?

**Comment by jaredbhatti** [comment]
Link fixed: http://kubernetes.io/docs/admin/federation/
