### ISSUE TITLE
Outdated bash completion instruction on website need to be updated.

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes.github.io#934]
The instruction on http://kubernetes.io/docs/getting-started-guides/gce/#enabling-bash-completion-of-the-kubernetes-command-line-tools is outdated. There is no "completions" folder under "contrib" anymore. 

New instructions could be found here: https://github.com/kubernetes/kubernetes/blob/release-1.3/docs/user-guide/kubectl/kubectl_completion.md

**Comment by steveperry-53** [comment]
Fixed
