### ISSUE TITLE
I wish /docs/admin/networking/ included opencontrail as a networking option...seems to be missing 

### ISSUE THREAD

**Issue by jameskellynet** [kubernetes/kubernetes.github.io#942]
I wish /docs/admin/networking/ included opencontrail as a networking option...seems to be missing

**Comment by jaredbhatti** [comment]
You're welcome to file a pull request against this doc: http://kubernetes.io/docs/admin/networking/#how-to-achieve-this

I notice there's existing information here: 
http://www.opencontrail.org/opencontrail-kubernetes-integration/
