### ISSUE TITLE
Relocate locally.md to the main Kubernetes repo under local-up-cluster.md

### ISSUE THREAD

**Issue by kelseyhightower** [kubernetes/kubernetes.github.io#949]
Based on @bgrant0607 feedback on PR https://github.com/kubernetes/kubernetes.github.io/pull/454, we need to get `docs/getting-started-guides/locally.md` moved to `kubernetes/kubernetes/docs/dev/local-up-cluster.md` in the main Kubernetes repo. We should point people at minikube for local setups.

**Comment by idvoretskyi** [comment]
https://github.com/kubernetes/kubernetes.github.io/pull/454#issuecomment-237171172
