### ISSUE TITLE
I wish /gettingstarted/ Was not at the top of Googles SERP for "Getting started with kubernetes"

### ISSUE THREAD

**Issue by HolyHaddock** [kubernetes/kubernetes.github.io#96]
I wish /gettingstarted/ existed, or was not at the top of Googles SERP for "Getting started with kubernetes" - https://www.google.co.uk/?gfe_rd=cr&ei=Fp7iVrjhFpXIzAbbwJp4&gws_rd=ssl#q=Getting+started+with+kubernetes

**Comment by johndmulhausen** [comment]
Looks like this isn't happening now; the indexing probably just needed to catch up.

**Comment by HolyHaddock** [comment]
:+1:
