### ISSUE TITLE
Wishlist: Consider a means to host the docs over HTTPS.

### ISSUE THREAD

**Issue by andrewhowdencom** [kubernetes/kubernetes.github.io#961]
While I understand this does not have a trivial solution, it'd be nice if the docs were served over TLS. GitHub do not appear to have an easy solution to use pages with custom domains over TLS (See https://github.com/isaacs/github/issues/156), however the current website might redirect to https://kubernetes.github.io

Cheers! <3 the docs; thank you for all your hard work.

**Comment by jaredbhatti** [comment]
We're looking at a few options to do this, but we'd need some technical help to get it done.

**Comment by steveperry-53** [comment]
https://kubernetes.io/
