### ISSUE TITLE
I wish /docs/getting-started-guides/docker http://kubernetes.io/docs/getting-started-guides/docker does not work, link to this page is here: http://kubernetes.io/docs/getting-started-guides/

### ISSUE THREAD

**Issue by mszumilak** [kubernetes/kubernetes.github.io#963]
http://kubernetes.io/docs/getting-started-guides/docker does not work (404), link to this page is on the  http://kubernetes.io/docs/getting-started-guides/

**Comment by jaredbhatti** [comment]
Redirects to minikube.  Fixed. 
http://kubernetes.io/docs/getting-started-guides/#local-machine-solutions
