### ISSUE TITLE
Standardizing the LGTM process for docs

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes.github.io#968]
The bot is currently running on this repository, performing assignment of PRs, but we haven't turned on the submit-queue yet. We currently have two LGTM labels, Docs LGTM and Tech Review LGTM. This is different from other repositories where we just require a single LGTM label.  
- Does it make sense to have a different LGTM process for docs as opposed to other repositories?
- Can we switch to just a single LGTM label for docs as well? 
- Would mungedocs completely remove the need for a Docs LGTM, and a separate tech & docs review?

cc @bgrant0607 @lavalamp @pwittrock @jaredbhatti

**Comment by lavalamp** [comment]
IMO:

Yes, the different process makes sense here, and we should not switch to a
single LGTM. Mungedocs does not substitute for a human review for writing
quality.



On Thu, Aug 4, 2016 at 1:57 PM, Anirudh Ramanathan <notifications@github.com

**Comment by bgrant0607** [comment]
@lavalamp @foxish No, I don't want a different process than other repos, both for a consistent contributor experience and because the previous process was an impediment to progress. 

The majority of PRs aren't creating new docs. They fix bugs and update details.

Additionally, we already have 2-phase reviews, LGTM and approval, and @kelseyhightower has suggested an iterative process where we ingest technical content first and then rework it in subsequent PRs. 

We could easily create a special process for wholly new documents, where such PRs would be directed to a writer first for high-level guidance. That would be easy to automate.

**Comment by pwittrock** [comment]
@foxish +1 to what Brian said.  Stick with the same lgtm process as the main repo (from eng for technical correctness).  The process for introducing a technical editor is TBD, but the former process resulted in docs not getting looked at for 3+ months.

**Comment by jaredbhatti** [comment]
I prefer the two step process for docs.  Tech writers and reviewers should review content on the site.  I'm certainly open to modifying the existing process to improve things, but without content review we'll continue to accrue technical debt and bad organization in our docs.

**Comment by bgrant0607** [comment]
@jaredbhatti We are implementing a 2-step process for all repositories. I am saying that I don't want a 3-step process, and I don't want a 2-step process that is mechanically different from other repositories.

**Comment by Kashomon** [comment]
> I prefer the two step process for docs. Tech writers and reviewers should review content on the site. I'm certainly open to modifying the existing process to improve things, but without content review we'll continue to accrue technical debt and bad organization in our docs.

Is there any reason the docs review can't be offline? We could conceivably create a webhook (or a mungegithub hook) that marks a doc as 'dirty/needing-review' when new doc changes are submitted.

> bad organization in our docs.

If we can figure out a clear and consistent organization system for our docs, we could encode this as part of md-check. Combined with templating, we enforce invariants on our docs automatically.

**Comment by bgrant0607** [comment]
We can also automatically categorize PRs, by size (which we do already), by whether they add new files, etc.

**Comment by jaredbhatti** [comment]
I suggest we close this issue for now, and Foxish and I work on the right process to take this on.  I'm standardizing how issues and PRs are being addressed, and I'm very reluctant to automate a process that's still uncertain. 

Also, there's been no progress on this issue for over 6 months.
