### ISSUE TITLE
Docs -- horizontal scrollbars on lengthy code snippets don't work

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/kubernetes.github.io#972]
I'm unable to use the horizontal scrollbar on, 

e.g. this page, to scroll along the command synopsis:

http://kubernetes.io/docs/user-guide/kubectl/kubectl_get/

e.g. this page, to scroll on the synopsis or the example:

http://kubernetes.io/docs/user-guide/kubectl/kubectl_autoscale/

I tried on latest Chrome|Firefox.

**Comment by jaredbhatti** [comment]
Known issue.  We need to fix this.

**Comment by jaredbhatti** [comment]
Duplicate issue: https://github.com/kubernetes/kubernetes.github.io/issues/633
