### ISSUE TITLE
I wish /docs/getting-started-guides/docker-multinode/master.sh existed

### ISSUE THREAD

**Issue by lorrin** [kubernetes/kubernetes.github.io#976]
I wish /docs/getting-started-guides/docker-multinode/master.sh existed

It is linked to from http://kubernetes.io/docs/getting-started-guides/docker-multinode/

**Comment by lorrin** [comment]
Also `http://kubernetes.io/docs/getting-started-guides/docker-multinode/worker.sh`, which is also linked to from the same page.

**Comment by lorrin** [comment]
...and the diagram link to http://kubernetes.io/docs/getting-started-guides/docker-multinode/k8s-docker.png is broken.

**Comment by jaredbhatti** [comment]
Fixed.  Thanks for the issues.
