### ISSUE TITLE
Need usage help text for federation binaries

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes.github.io#977]
`/docs/admin/federation-apiserver/` and `/docs/admin/federation-controller-manager/` should display the usage help text with explanation of all the flags for the corresponding federation binaries. See [/docs/admin/kube-apiserver/](http://kubernetes.io/docs/admin/kube-apiserver/) for example.

@nikhiljindal says we used to have this but we lost it during the generated-code-checkin transition.

**Comment by nikhiljindal** [comment]
cc @jaredbhatti @kubernetes/docs  Is there a process to import docs from kubernetes main repo to this docs repo to ensure that k8s.io has latest docs?

Looks like we did not update k8s.io with 1.3 docs.
federation-apiserver doc exists in kubernetes release 1.3 but is not there on k8s.io.

**Comment by nikhiljindal** [comment]
For now I can copy the doc manually to the master branch in this repo.
But we need to come up with a process to keep it in sync.

**Comment by nikhiljindal** [comment]
Had added those files in https://github.com/kubernetes/kubernetes.github.io/pull/983.
https://github.com/kubernetes/kubernetes.github.io/pull/1222 adds a link to them on left side navigation.

**Comment by nikhiljindal** [comment]
We now have http://kubernetes.io/docs/admin/federation-apiserver/ and http://kubernetes.io/docs/admin/federation-controller-manager/
