### ISSUE TITLE
I wish /docs/getting-started-guides/docker-multinode/master.sh this page existed! i came from http://kubernetes.io/docs/getting-started-guides/docker-multinode/

### ISSUE THREAD

**Issue by apzarabi** [kubernetes/kubernetes.github.io#986]
I wish /docs/getting-started-guides/docker-multinode/master.sh this page existed! i came from http://kubernetes.io/docs/getting-started-guides/docker-multinode/

**Comment by yissachar** [comment]
Duplicate of https://github.com/kubernetes/kubernetes.github.io/issues/976

**Comment by jaredbhatti** [comment]
Fixed.
