### ISSUE TITLE
I wish /docs/getting-started-guides/locally I wish this page existed.

### ISSUE THREAD

**Issue by Estebanv** [kubernetes/kubernetes.github.io#988]
I wish /docs/getting-started-guides/locally I wish this page existed.

**Comment by yissachar** [comment]
Duplicate of https://github.com/kubernetes/kubernetes.github.io/issues/988

**Comment by jaredbhatti** [comment]
Minikube is the way to go now: http://kubernetes.io/docs/getting-started-guides/minikube/
